### PR TITLE
[Feat] Basic Math Operations

### PR DESCRIPTION
**Pull request by dunkeroni**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [x] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [x] Yes
- [ ] No

## Description
Adds floating point math nodes, conversion, and mod:
- Add
- Subtract
- Multiply
- Divide
- Round
- Round To Multiple
- Modulus
- Square Root
- Absolute Value

The "Round To Multiple" node is the general conversion for Float->Int. It offers Nearest/Floor/Ceiling options for how to round. Leaving the multiple_of field at 1 rounds to the nearest integer. Higher values will convert to integer multiples of the value.

## QA Instructions, Screenshots, Recordings
UPDATE: Math nodes consolidated per comments.
image

### CODE REVIEW

**Review by Millu — APPROVED** [review]
Looks good to me - thanks for adding these! 

Double thanks for updating the documentation as well

**Comment by blessedcoolant** [comment]
Ideally, I would have loved to have a single `Math` node that controls all kind of math operations for all kind of input values (ints, floats, vectors, colors and etc) but currently we do not support multiple types of fields in a particular socket. But as a budget approach to that, I think maybe we're better served by putting these all into one single node called `Float Math` and allowing the user to pick the type of operation that needs to be performed.

That way, a user can copy paste a single node and plug it in for different operations for and just change the type as needed.

I know a couple of output are `IntegerOutput` but maybe we can change them to `FloatOutput` to make this a single node and instead add a `FloatToInt` and `IntToFloat` nodes to allow the transform if needed.

The same way, we can do probably also unity all the Integer Math nodes.

**Comment by dunkeroni** [comment]
Oh, the can of worms blessedcoolant has opened up.
After much going around in circles, it seems we all have quite differing opinions on how to add two numbers. Arbitrary string eval math nodes aside, we have a few options for condensing the basic math to avoid bloat.

Option 1: Singular node with a dropdown list for operation. Preferred by user uselessness
image

Option 2: Globbing on a lot of outputs. Might get problematically large with more operations included.
image

Option 3: My preference at this point, maintains Int and Float math without increasing the size of the core node library. Could be a good standard output format for a lot of future nodes as well.
image

Option 4: The set currently proposed by this PR.
image

Option 5: Proposed by JPPhoto, not satisfied with the previous choices and wanting all math to be float math with conversions to get back to integer forms.
image

**Comment by blessedcoolant** [comment]
I'm leaning towards Option 1. It's just more compact, clean and in sync with how many other apps do their math stuff. But I think we should just do 1 output and not 2 which should be the same as the input type. Doing two is just feels messy coz in cases of float math many values would just have be rounded down or up. Which is not very ideal. If a user really needs to convert this, let them do that with the node proposed below.

Here's what I think we should do.

### Two math nodes (and do vector / image / colors and etc later)

- Integer Math
- Float Math

Why two? Well for starters, coz we can't do both in one

If we do not do both and keep just floats, then every int needs to converted with an extra node to floats before they are plugged in just to get the math done. Rather avoid that.

### Add 2 new nodes

- Integer to Float
- Float To Integer

I think  this is much more cleaner than having float operations output integer values which basically in many cases means rounding down or up. Just messy.

There are a couple of use cases when you might need an int input in float math, the suggestion here would be to just take in a float input and round down to get the nearest in on the backend.

---

If any when we support multi type sockets, we can merge it all into the one great powerful `Math` node.

**Comment by hipsterusername** [comment]
> I'm leaning towards Option 1. It's just more compact, clean and in sync with how many other apps do their math stuff. But I think we should just do 1 output and not 2 which should be the same as the input type. Doing two is just feels messy coz in cases of float math many values would just have be rounded down or up. Which is not very ideal. If a user really needs to convert this, let them do that with the node proposed below.
> 
> Here's what I think we should do.
> ### Two math nodes (and do vector / image / colors and etc later)
> 
>     * Integer Math
> 
>     * Float Math
> 
> 
> Why two? Well for starters, coz we can't do both in one
> 
> If we do not do both and keep just floats, then every int needs to converted with an extra node to floats before they are plugged in just to get the math done. Rather avoid that.
> ### Add 2 new nodes
> 
>     * Integer to Float
> 
>     * Float To Integer
> 
> 
> I think this is much more cleaner than having float operations output integer values which basically in many cases means rounding down or up. Just messy.
> 
> There are a couple of use cases when you might need an int input in float math, the suggestion here would be to just take in a float input and round down to get the nearest in on the backend.
> 
> If any when we support multi type sockets, we can merge it all into the one great powerful `Math` node.

I agree. While it's elegant to have Int/Float operate out of a single node, I get concerned with types changing in-node.

**Comment by dunkeroni** [comment]
In that case, I propose the following for your consideration. Validation to avoid divide by zero and complex outputs is included. 
image 
image 
image

**Comment by blessedcoolant** [comment]
I think the names don't need the mathematical operations next to it.

- We go with `Add`, `Subtract`, `Multiply`, `Divide`, `Exponent`, `Minimum`, `Maximum`.

Also a bit hesitant about `Absolute` being in this coz it's not doing anything with the second value. But the downside of removing it from here is we need to add two nodes to turn them into abs for float and int respectively.

Also move Operation to the top imo.

**Comment by psychedelicious** [comment]
Just wanna throw this out there - no nerd-snipe intended.

What if, instead of a drop-down, there was a free-text entry that was passed into a calculator function? We do a simple regex to replace the operands in the math to evaluate, then use a calculator library with eg `calc.eval(math_string)`?

We could even use a pydantic validator to check for syntactical validity by evaluating the math with dummy values.

**Comment by blessedcoolant** [comment]
> Just wanna throw this out there - no nerd-snipe intended.
> 
> What if, instead of a drop-down, there was a free-text entry that was passed into a calculator function? We do a simple regex to replace the operands in the math to evaluate, then use a calculator library with eg `calc.eval(math_string)`?
> 
> We could even use a pydantic validator to check for syntactical validity by evaluating the math with dummy values.

@hipsterusername Someone kidnapped the real @psychedelicious. This fake one is suggesting usage of regex which we know for a fact that the real @psychedelicious would never approve.

**Comment by psychedelicious** [comment]
Let me revise, so as to maintain my disguise - we can do a simple string replace :D

**Comment by dunkeroni** [comment]
> I think the names don't need the mathematical operations next to it. Think it will be presumed that it'll always be the first value to the second in reference.
> 
> * We go with `Add`, `Subtract`, `Multiply`, `Divide`, `Exponent`, `Minimum`, `Maximum`.
> 
> Also a bit hesitant about `Absolute` being in this coz it's not doing anything with the second value. But the downside of removing it from here is we need to add two nodes to turn them into abs for float and int respectively.
> 
> Also move Operation to the top imo.

Originally I had it that way, but I had abs() and sqrt() in there, so I figured it would be good to reinforce that single-input operators apply only to A. Also it's not like we're running out of space. With square root relegated to exponentiation, that does make absolute value the odd one out. We can remove the notation, but I think it only helps and does not detract, particularly for people from other cultures who might otherwise assume "Subtract A from B".

As for @psychedelicious , this is at least the third time someone has suggested using an eval() for generalized math. I'm all for it, on two conditions.
1: Guarantee that it cannot execute any functions outside of math operations.
2: Documentation will be obvious enough in UI so that anyone who has never programmed in python will know what operations and syntax are available.
Those being the case, we could strip these down to just arithmetic operators ( + - * / ) which should be the minimum math that needs to have graphical node forms without requiring equation strings for the arithmophobic.

**Comment by hipsterusername** [comment]
From a UX perspective that’s obviously better, but I am very hesitant to do anything that even remotely puts system at risk. I think we’d rather move quickly with a non-eval option than deliberate for a while on this?

**Comment by Millu** [comment]
Seconding @hipsterusername here

Path forward that makes sense to me is getting the bundled math nodes in, and then a follow-up to address eval - perhaps a separate node for free form equations

**Review by hipsterusername — APPROVED** [review]

**Comment by psychedelicious** [comment]
I've taken the liberty of making a some changes:
- Run `black`, `flake8` and `isort` (recently introduced)
- Added a new nodes UI feature for this PR - labels for enum fields.
  - Nodes may provide a `ui_choice_labels: dict[str, str]` for the enum fields.
  - The key is the actual value used in the field, and the value is the label the UI should display in the dropdown element.
- Update the new math nodes to use this. So the actual values used now are like "ADD", "MUL", "DIV", etc - while the UI displays the human-friendly values. Using strings like "Modulus A%B" for values makes me nervous, and I've been meaning to implement this anyways.

Here's the result:

https://github.com/invoke-ai/InvokeAI/assets/4822129/d113a276-b177-41e5-906f-cf4e4c34a6de

Thanks @dunkeroni !

**Pull request merged**
