### PR TITLE
feat(dev_reload): use jurigged to hot reload changes to Python source

### PR DESCRIPTION
**Pull request by keturn**
While it is not _necessary_ to change the application source to use [jurigged](https://github.com/breuleux/jurigged) for live reloading, it does help discoverability to have the option show up in our Config instead of relying on developers having that particular bit of Python know-how.

Programmatically starting jurigged like this also allows for better integration with our logging configuration, though the way I've integrated it here lacks the color-coding provided by jurigged's default.

## What type of PR is this? (check all applicable)

- (developer) Feature

## Have you discussed this change with the InvokeAI team?

See [livereload / hot reloading Python development server](https://discord.com/channels/1020123559063990373/1138647706542280785).
      
## Have you updated all relevant documentation?
- [x] Yes

## Related Tickets & Documents

- #4216

## QA Instructions, Screenshots, Recordings

Start the server with the `--dev_reload` flag.

Change a Python source file and note the behavior changes without having to shut down and restart the server.

## Added/updated tests?

- No, I'm not writing tests that modify the Python sources to check how a running server responds.

### CODE REVIEW

**Comment by lstein** [comment]
Very cool! If it's still unmerged I'll give it a thorough review when I'm back from camping in a couple of days.

**Review by psychedelicious — APPROVED** [review]
Woohoo! It works wonderfully.

One caveat - when changing a node:
- the `InvocationsUnion` doesn't change and `Graph` model isn't re-initialized
- so the OpenAPI schema is not updated
- so changes to anything other than the body of each node's `invoke()` function are not hot-reloaded

For example, changing the name, type, or fields of a node does not change trigger a reload. This is expected, but it would be very nice if that could all reload too.

I made some progress on this in #4334. Can we provide callbacks to `jurrigged` to execute on certain events? Specifically, can we make any hot reload in `invocations/*.py` trigger logic similar to #4334?

**Comment by keturn** [comment]
> Can we provide callbacks to jurrigged to execute on certain events?

Hmm, looks like yes, but let's leave that to a later PR so we can explore that whole mess of Invocation loading and introspection separately.

**Comment by damian0815** [comment]
sooo on macos, ootb jurigged is broken because of some change to whichever flavour of FSEvents system that the fruit company wants us to use in 2023. is this able to act as a workaround?

**Comment by keturn** [comment]
> sooo on macos, ootb jurigged is broken [...] is this able to act as a workaround?

This is literally just instantiating a jurigged watcher, so I expect it inherits any jurigged brokenness.

**Comment by damian0815** [comment]
ahh. oh well, thanks.

**Review by hipsterusername — APPROVED** [review]

**Review by blessedcoolant — APPROVED** [review]

**Review by lstein — APPROVED** [review]
LGTM

**Pull request merged**
