### PR TITLE
Feature: model switching in dream prompt

### PR DESCRIPTION
**Pull request by ArDiouscuros**
Add command !model [model_name] and argument --model model_name to switch model without leaving dream prompt - see #804 and #923
It is not clear to me, why just deleting / setting to None self.model in generate.py in not enough to clean the GPU memory. Looks like we have a copy of model in each generator and probably somewhere else.
I would be grateful for any feedback.

### CODE REVIEW

**Comment by lstein** [comment]
Thanks so much! 

I am not adding new features to the RC at this time, because we're just doing bug and documentation fixes. If you could rebase this into `development` that would be best. This feature was actually # 1 on my wish list, so it'll be in a point release very soon.

**Comment by ArDiouscuros** [comment]
> rebase this into development

Could you give me a hint how one could correctly rebase into development ?

**Comment by ArDiouscuros** [comment]
After changing base branch from release-candidate-2 to development and making rebase I see 9 extra commits...
Not sure that it is right - should I just delete the PR and make it again?

**Comment by lstein** [comment]
Yeah, this sometimes adds extra commits which cause confusing log entries. Sorry it happened to you. It would be best to close the PR and issue a new one against development. Sorry for the added work.

**Comment by ArDiouscuros** [comment]
Okay, I will do my best to rebase or to move it to development.
Probably will take some time as I will have limited access to internet next week...

**Comment by lstein** [comment]
It does look like some unrelated commits got included. Aside from `generate.py` are there any other files that need to change?

**Comment by ArDiouscuros** [comment]
> It does look like some unrelated commits got included. Aside from `generate.py` are there any other files that need to change?

Yes, in cb4396a76c9800a8f6769f515d2c6d9f00eae6e0 args.py for argument handling and main dream.py for invocation. So it was basically two commits - first one and e1ffce69905a4f8c862b371dccf6c9b2a163e9c1.

**Comment by lstein** [comment]
This was superseded by a series of model manipulation commands I added more recently, but I credited your work.

**Pull request closed without merging**
