### PR TITLE
Web UI: Option panel pin/unpin, bug fixes

### LINKED ISSUE #1295: [bug]: Deleting from the gallery intermittently fails
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

24

### What happened?

- Start server
- Generate image
- Immediately delete image from gallery (trash icon or delete key)
- 'Disconnected' in console
  - (Rinse, repeat for as many you like.)
- When client immediately reconnects 'Deleted' toast pops up, but image(s) remain in gallery list
- Reload client browser tab
- Image(s) have been deleted

### Client console:
```
2022-10-29T18:52:56-0400: Image generation requested: {"prompt":"test prompt","iterations":1,"steps":6,"cfg_scale":8,"threshold":0,"perlin":0,"height":512,"width":512,"sampler_name":"k_dpm_2_a","seed":1497525810,"progress_images":true,"seamless":false,"hires_fix":false,"variation_amount":0}
2022-10-29T18:52:58-0400: Image generated: outputs/000194.8863c182.1497525810.png
2022-10-29T18:53:01-0400: Disconnected from server
2022-10-29T18:53:02-0400: Loaded 0 images
2022-10-29T18:53:02-0400: Loaded 0 images
```
### Server side console:
```
* Initializing, be patient...
>> GFPGAN Initialized
>> CodeFormer Initialized
>> ESRGAN Initialized
>> Using device_type cuda
>> Loading stable-diffusion-1.4 from models/ldm/stable-diffusion-v1/model.ckpt
   | LatentDiffusion: Running in eps-prediction mode
   | DiffusionWrapper has 859.52 M params.
   | Making attention of type 'vanilla' with 512 in_channels
   | Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
   | Making attention of type 'vanilla' with 512 in_channels
   | Using faster float16 precision
>> Model loaded in 8.45s
>> Max VRAM used to load the model: 2.17G 
>> Current VRAM usage:2.17G
>> Setting Sampler to k_lms

* --web was specified, starting web server...
>> Started Invoke AI Web Server!
>> Default host address now 127.0.0.1 (localhost). Use --host 0.0.0.0 to bind any address.
>> Point your browser at http://127.0.0.1:9090
>> Image generation requested: {'prompt': 'test prompt', 'iterations': 1, 'steps': 6, 'cfg_scale': 8, 'threshold': 0, 'perlin': 0, 'height': 512, 'width': 512, 'sampler_name': 'k_dpm_2_a', 'seed': 1497525810, 'progress_images': True, 'seamless': False, 'hires_fix': False, 'variation_amount': 0}
ESRGAN parameters: False
Facetool parameters: False
>> Setting Sampler to k_dpm_2_a
>> Parsed prompt to FlattenedPrompt:[Fragment:'test prompt'@1.0]
Generating:   0%|                                                                     | 0/1 [00:00<?, ?it/s]>> Ksampler using karras noise schedule (steps <= 29)
>> Sampling with k_dpm_2_ancestral starting at step 0 of 6 (6 new sampling steps)
100%|█████████████████████████████████████████████████████████████████████████| 6/6 [00:01<00:00,  3.76it/s]
>> Image generated: "/home/fortyseven/opt/ai/invoke-ai/outputs/img-samples/000194.8863c182.1497525810.png"s]
Generating: 100%|█████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]
>> Usage stats:
>>   1 image(s) generated in 2.26s
>>   Max VRAM used for this generation: 3.40G. Current VRAM utilization: 2.25G
>>   Max VRAM used since script start:  3.40G
>> Delete requested "outputs/000194.8863c182.1497525810.png"
/home/fortyseven/opt/ai/invoke-ai/outputs/img-samples/000194.8863c182.1497525810.png
```

### Screenshots

_No response_

### Additional context

_No response_

### Contact Details

_No response_

### LINKED ISSUE #1297: [bug]: Sending Image from txt2img to inpainting causes spinning circle and image doesn't load
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12gb

### What happened?

Sending Image from txt2img/img2img to inpainting causes spinning circle and image doesn't load

no errors in cli or in web ui console

works fine from image gallery while under inpainting option

### Screenshots

image

### Additional context

Same issue On Chrome on windows/android, Microsoft edge on windows and Firefox on linux

### Contact Details

_No response_

### PR DESCRIPTION
**Pull request by psychedelicious**
- Options panel can now be unpinned and floats
- Numerous bug fixes related to edge cases when pinning/unpinning options panel and gallery
- Styling updates
- Fixes  #1297 (please test @Fortyseven and @mickr777) 
- Fixes #1295 (please test @Fortyseven and @mickr777) :
    - Optimistically remove the image from the gallery so you cannot delete an image you already deleted from gallery (previously, it only removed from gallery after a response was sent by server)
    - Still throw an error if you attempt to delete an image and it doesn't exist
    - Disable delete buttons while disconnected/processing (as during these times delete requests are either queued or don't happen)
    - The toast saying deleted was fake news. It always shows when you click delete. Removed it entirely in favor of just using errors to say when something *doesn't* work.

### CODE REVIEW

**Comment by Fortyseven** [comment]
This ended up being lower res than I intended, but should be just readable.

Pasting seems to be working, but when I try to do inpainting on it, the server pops an `images do not match` error.

The error at the end:
```
2022-10-30T02:15:50-0400: Image uploaded: outputs/init-images/image.301a381f.png

2022-10-30T02:16:07-0400: Image generation requested: {"prompt":"hot dog","iterations":1,"steps":50,"cfg_scale":7.5,"threshold":0,"perlin":0,"height":512,"width":512,"sampler_name":"k_lms","seed":1321259652,"progress_images":false,"init_img":"outputs/init-images/image.301a381f.png","strength":0.75,"fit":false,"init_mask":"iVBORw0KGgoAAAANSUhE...","bounding_box":{"x":0,"y":0,"width":479,"height":532},"variation_amount":0}

2022-10-30T02:16:10-0400: Server error: images do not match
```

https://user-images.githubusercontent.com/156409/198865435-e7bbc94d-4713-4883-b927-29bb19ffbd79.mp4

**Comment by Fortyseven** [comment]
If I reload the page, I can delete from the gallery.

If I generate images, then try to delete:
```
Uncaught TypeError: e.categories[r] is undefined
    removeImage http://localhost:9090/assets/index.57b0f348.js:478
    p http://localhost:9090/assets/index.57b0f348.js:428
    produce http://localhost:9090/assets/index.57b0f348.js:428
    p http://localhost:9090/assets/index.57b0f348.js:428
    p http://localhost:9090/assets/index.57b0f348.js:428
    reducer http://localhost:9090/assets/index.57b0f348.js:428
    i3 http://localhost:9090/assets/index.57b0f348.js:452
    NF http://localhost:9090/assets/index.57b0f348.js:428
    i3 http://localhost:9090/assets/index.57b0f348.js:452
    ...
    ```

**Comment by Fortyseven** [comment]
https://user-images.githubusercontent.com/156409/198865676-4ea4d242-48c0-4fde-a0d6-db3f29c9d0d9.mp4

**Comment by psychedelicious** [comment]
@Fortyseven Figured out the delete issue. The "category" attribute of images wasn't getting set, so attempts to delete couldn't see where to grab the image from. Fixed in the latest commit here.

The issue with "images do not match" is bc the bounding box dimensions are somehow not a multiple of 64 (they should never be). That's a WIP, I freaking hate math.

**Comment by Fortyseven** [comment]
@psychedelicious Everything I reported seems to be working great now (though there's the bounding size multiplier thing noted on Discord, but you CAN inpaint into it, so that's :+1: ). Seems like the most reasonable solution for clipboard provided imagery, I guess. :)

image

**Comment by Fortyseven** [comment]
Things were going well for a bit, having a lot of fun playing with inpainting. Seemed solid! 

But then _something_ happened and suddenly everything I did was generating *this* with subsequent inpainting requests:

```
Traceback (most recent call last):
  File "/home/fortyseven/opt/ai/invoke-ai/backend/invoke_ai_web_server.py", line 901, in parameters_to_generated_image_metadata
    rfc_dict["orig_hash"] = calculate_init_img_hash(
  File "/home/fortyseven/opt/ai/invoke-ai/ldm/invoke/args.py", line 1059, in calculate_init_img_hash
    if image_string.startswith(prefix):
AttributeError: 'NoneType' object has no attribute 'startswith'


DDIMSampler:   0%|                                  | 0/33 [00:00<?, ?it/s]
Generating:   0%|                                    | 0/1 [00:00<?, ?it/s]
object of type 'Image' has no len()


Traceback (most recent call last):
  File "/home/fortyseven/opt/ai/invoke-ai/backend/invoke_ai_web_server.py", line 796, in generate_images
    self.generate.prompt2image(
  File "/home/fortyseven/opt/ai/invoke-ai/ldm/generate.py", line 455, in prompt2image
    results = generator.generate(
  File "/home/fortyseven/opt/ai/invoke-ai/ldm/invoke/generator/base.py", line 90, in generate
    image = make_image(x_T)
  File "/home/fortyseven/opt/ai/invoke-ai/ldm/invoke/generator/omnibus.py", line 114, in make_image
    samples, _ = sampler.sample(
  File "/home/fortyseven/opt/ai/invoke-ai/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/fortyseven/opt/ai/invoke-ai/ldm/models/diffusion/sampler.py", line 188, in sample
    samples, intermediates = self.do_sampling(
  File "/home/fortyseven/opt/ai/invoke-ai/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/fortyseven/opt/ai/invoke-ai/ldm/models/diffusion/sampler.py", line 303, in do_sampling
    img_callback(img,i)
  File "/home/fortyseven/opt/ai/invoke-ai/backend/invoke_ai_web_server.py", line 613, in image_progress
    command = parameters_to_command(generation_parameters)
  File "/home/fortyseven/opt/ai/invoke-ai/backend/modules/parameters.py", line 41, in parameters_to_command
    if "init_img" in params and len(params["init_img"]) > 0:
TypeError: object of type 'Image' has no len()
```

I don't have repeatable steps yet (it happened quite randomly, but I'll watch for it). However, I did notice I was getting previously pasted (and thought to be deleted) images showing up in the generated image panel, while not appearing in the gallery. 

Considering I've been goofing off with this for an hour now and only _now_ it's crept up, unless this has made something 'click' with another issue, it's probably worth treating separately. (After it's merged and I get it to happen again, reliably, I'll throw up a ticket. Or I can do it now, knowing it's forthcoming? :thinking: Etc, etc.)

(Nuking the `output/` directory and refreshing put things working again.)

**Comment by Fortyseven** [comment]
Just noticed this -- I hadn't touched any of the mask color settings yet.

image

**Comment by psychedelicious** [comment]
@Fortyseven 
> Just noticed this -- I hadn't touched any of the mask color settings yet.

What may have happened is you updated the repo without resetting the local storage (gear icon @ top right > reset web UI is a way to do it without getting into dev tools). Does that sound like a possibility?

**Comment by psychedelicious** [comment]
@Fortyseven The other issue, `TypeError: object of type 'Image' has no len()` is related to metadata generation and inpainting using PIL images during the generation process when Display In-Progress Images is enabled. I have side-stepped the issue for now by disabling that setting for inpainting only.

**Comment by mickr777** [comment]
Interesting quirk, with this PR I how found (but not always), if the masking is out side the inpaint box it can cause the output to be very random, here i was adding a dog and forgot to change the box size
Screenshot 2022-10-31 174921

Screenshot 2022-10-31 174818

**Review by blessedcoolant — APPROVED** [review]

**Comment by psychedelicious** [comment]
@mickr777 
> Interesting quirk, with this PR I how found (but not always), if the masking is out side the inpaint box it can cause the output to be very random, here i was adding a dog and forgot to change the box size

SD needs images closer to 512x512 to have good results but it looks like you are attempting to inpaint in a region much smaller than that. What you got is more or less expected; try generating an image of that same size to see what I mean. 

We can warn if using a box smaller than 512x512, saying results may be sub-optimal.

**Comment by mickr777** [comment]
> SD needs images closer to 512x512 to have good results but it looks like you are attempting to inpaint in a region much smaller than that. What you got is more or less expected; try generating an image of that same size to see what I mean.
> 
> We can warn if using a box smaller than 512x512, saying results may be sub-optimal.

That Explains it, thanks for taking your time to explain.
just one other quirk, sometimes colours are made darker in the boxed area, even if there not in the masked off

I marked an aera where its most noticeable
image

**Comment by Kyle0654** [comment]
> > SD needs images closer to 512x512 to have good results but it looks like you are attempting to inpaint in a region much smaller than that. What you got is more or less expected; try generating an image of that same size to see what I mean.
> > 
> > We can warn if using a box smaller than 512x512, saying results may be sub-optimal.
> 
> That is it, thanks for taking your time to explain.
> just one other quirk, sometimes colours are made darker in the boxed area, even if there not in the masked off
> 
> I marked an area where its most noticeable
> image
> 
> 

What model are you using when inpainting?

**Comment by mickr777** [comment]
> What model are you using when inpainting?

Inpainting 1.5, however I am using a custom merge of 2 models to create the original image

**Comment by Kyle0654** [comment]
Ah, yah, this is happening because the inpainting model goes through a different code path currently, which doesn't do color correction or a masked repaste of the original image. If you don't use a bounding box it looks great, but it unfortunately still has very slight differences in color and detail that are noticeable in this sort of scenario.

**Comment by Kyle0654** [comment]
If you do an inpaint at low strength and steps over the seam with one of the regular SD models it might correct it.

**Comment by mickr777** [comment]
> Ah, yah, this is happening because the inpainting model goes through a different code path currently, which doesn't do color correction or a masked repaste of the original image. If you don't use a bounding box it looks great, but it unfortunately still has very slight differences in color and detail that are noticeable in this sort of scenario.

Ok, Thanks for that info

**Comment by Fortyseven** [comment]
> ...I did notice I was getting previously pasted (and thought to be deleted) images showing up in the generated image panel, while not appearing in the gallery...

Just to cut off this dangling thread: these were in the user "uploads" gallery section and I just didn't realize it. So this one was just ignorance on my part. :sweat_smile:   (It's all been pretty solid at this point. :ok_hand:)

**Comment by psychedelicious** [comment]
> > ...I did notice I was getting previously pasted (and thought to be deleted) images showing up in the generated image panel, while not appearing in the gallery...
> 
> 
> 
> Just to cut off this dangling thread: these were in the user "uploads" gallery section and I just didn't realize it. So this one was just ignorance on my part. :sweat_smile:   (It's all been pretty solid at this point. :ok_hand:)

Yeah, we will improve the gallery experience. The current gallery is the bare minimum to handle uploads, and def is not the best way to handle it. I do not like how I have to keep switching between the tabs. 

Internally we are discussing a kind of session or staging area where all images generated from a single initial image are displayed. Something to separate the concepts "everything I have made in InvokeAI" and "my current working images".

**Review by hipsterusername — APPROVED** [review]

**Pull request merged**
