### PR TITLE
fix(backend): ignore missing layers when applying LoRA

### LINKED ISSUE #5081: [bug]: LoRA + CLIP Skip fails: ModuleList has no attribute `11_mlp_fc1`
### Is there an existing issue for this?

- I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

1c7ea57492802eaf19f81ada9ed545a2e618add8

### What happened?

Using an SD 1.5 model (such as InvokeAI Fantasy and Art by Zovya):
- LoRA like `add detail` works fine
- CLIP Skip advanced option works fine on its own
- but when CLIP Skip is used ***with*** a LoRA, it is errortime:

```
  File "invokeai/backend/model_management/lora.py", line 76, in apply_lora_text_encoder
    with cls.apply_lora(text_encoder, loras, "lora_te_"):
  File "python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "invokeai/backend/model_management/lora.py", line 123, in apply_lora
    module_key, module = cls._resolve_lora_key(model, layer_key, prefix)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "invokeai/backend/model_management/lora.py", line 54, in _resolve_lora_key
    module = module.get_submodule(submodule_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.11/site-packages/torch/nn/modules/module.py", line 686, in get_submodule
    raise AttributeError(mod._get_name() + " has no "
AttributeError: ModuleList has no attribute `11_mlp_fc1`
```

not sure if this is a regression or not as I haven't been using LoRAs often.

### PR DESCRIPTION
**Pull request by psychedelicious**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Description

[fix(backend): ignore missing layers when applying LoRA](https://github.com/invoke-ai/InvokeAI/commit/1dbf05899cafc9c97659092350d3e4b6fabfaef6)

This handles LoRAs that attempt to modify layers skipped by CLIP Skip.

## Related Tickets & Documents

- Closes #5081
- Closes most of #5077 - there's another error in this issue related to tensor size mismatch which this PR does not address

## QA Instructions, Screenshots, Recordings

Use CLIP Skip > 0 and a LoRA. Shouldn't cause any issues. 

The `add_detail` LoRA was used as a test case, and it would fail with CLIP Skip of 1.

### CODE REVIEW

**Comment by psychedelicious** [comment]
@RyanJDick appreciate a review from you here

**Review by Millu — APPROVED** [review]
Works for me!

**Comment by blessedcoolant** [comment]
I think the more ideal solution to this problem is to apply the clip skip after the lora patching rather than skipping layers that might be in LoRA's but wiped from the text encoder. I just tested it the other way and it works as expected which I believe should be the intended result in this case.

**Comment by psychedelicious** [comment]
That makes sense but if I understand correctly, we would then be needlessly spending time patching layers that are gonna get skipped

**Comment by blessedcoolant** [comment]
> That makes sense but if I understand correctly, we would then be needlessly spending time patching layers that are gonna get skipped

We would be. But there is no way for us to know what needs to be patched and what should not be coz each LoRA might be different. So the ideal solution imo is to let the patching happen and then skip the `x` number of layers set by the user at the very end.

**Comment by RyanJDick** [comment]
I agree with @blessedcoolant here. The error that we are now ignoring could equally likely mean that we are applying a LoRA to an incompatible model - which we don't want to ignore.

**Comment by psychedelicious** [comment]
Thanks y'all I'll update the PR to do clip skip after applying LoRAs

**Comment by psychedelicious** [comment]
@blessedcoolant @RyanJDick 
Thanks for the feedback, I've updated this PR as you suggested.

**Review by hipsterusername — APPROVED** [review]

**Pull request merged**
