### PR TITLE
Feature to change Stable Diffusion checkpoint from the webui

### PR DESCRIPTION
**Pull request by HugoSega**

### CODE REVIEW

**Comment by blessedcoolant** [comment]
Can you please rebase this against dev? Not against main. I'll take a look then.

**Comment by blessedcoolant** [comment]
Hello, I see you've rebased against Dev but I do not see your changes in the files. Maybe something went wrong?

Please manually ping me here when this PR is ready for a review.

**Comment by psychedelicious** [comment]
@HugoSega Looks like you have rebased against `invoke-development` - please instead rebase against `development`. Thanks for working on this feature.

**Comment by lstein** [comment]
Are there really 230 commits? This doesn't look right.

**Comment by blessedcoolant** [comment]
> Are there really 230 commits? This doesn't look right.

It's not. It's a nearly made PR and I can't actually find the feature itself coz it was rebased incorrectly. The best way to actually implement this is to rework the CLI to support this and have the frontend call that instead.

**Comment by Kyle0654** [comment]
Can we reject this, or figure out the correct branch to merge into? I'd like to remove `invoke-development` and just leave the one active "node" branch.

**Pull request closed without merging**
