### PR TITLE
Explicitly call python found in system

### LINKED ISSUE #2166: [bug]: 2.2.5 - I get an error when installing
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### VRAM

_No response_

### What happened?

I get an error when installing.

### Screenshots
```
./install.sh
InvokeAI simple installer...

Some of the installation steps take a long time to run. Please be patient.
If the script appears to hang for more than 10 minutes, please interrupt with control-C and retry.
<Press any key to start the install>
Installing for osx-arm64
Python 3.10.2 found at /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10

Select your preferred location for the 'invokeai' directory [/Users/if3lc]:
./install.sh: line 124: python: command not found
```

### Additional context

In version 2.2.4 I was getting an error in the "Upscale Image" section, so I uninstalled it and did a clean reinstall and I get the above error during installation.

### Contact Details

_No response_

### PR DESCRIPTION
**Pull request by CodeZombie**
Some users are unable to run the installer because the line 124 in install.sh:
`ROOTDIR=$(python -c "from pathlib import Path; print(Path('${ROOTDIR}').expanduser().resolve())")`
expects an executable in the path named `python`, or else it will fatally crash.

Some users have python installed as `python3` on their systems and not simply `python`, thus causing the error. 
Prior sections of the installer script already find the full path to a user's python executable in a variable called `$PYTHON`, so this change simply adds that discovered python in place of the hard-coded `python` call.

This will fix #2166

### CODE REVIEW

**Review by lstein — APPROVED** [review]
Thanks for finding and fixing this.

**Comment by Paininperfection** [comment]
hi, im new to this I am getting the same issue and I don't understand what it is im suppose to do? and I suppose to copy paste something to line 124?

**Comment by N2bK** [comment]
I changed line 124 to python3, and it still doesn't work.  

line 124: python3: unbound variable

**Comment by Hutterbuff** [comment]
I changed line 124 to python3, and it still doesn't work the same as well ...

**Pull request merged**
