### PR TITLE
feat(mm): faster hashing for spinning disk HDDs

### LINKED ISSUE #5938: [enhancement]: support non-mmap BLAKE3 hashing
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

_No response_

### What should this feature add?

Add a configuration for model hashing to support non-mmap, non-threaded BLAKE3.

This vastly improves performance on spinning disks: https://discord.com/channels/1020123559063990373/1217051407543435344

I think the best way is to remove `skip_model_hash: bool` and make it `hashing: 'blake3' | 'blake3-no-mmap' | 'none'`.

### Alternatives

_No response_

### Additional Content

_No response_

### PR DESCRIPTION
**Pull request by psychedelicious**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [x] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [x] Yes
- [ ] No

## Description

BLAKE3 has poor performance on spinning disks when parallelized. See https://github.com/BLAKE3-team/BLAKE3/issues/31

- Replace `skip_model_hash` setting with `hashing_algorithm`. Any algorithm we support is accepted.
- Add `random` algorithm: hashes a UUID with BLAKE3 to create a random "hash". Equivalent to the previous skip functionality.
- Add `blake3_single` algorithm: hashes on a single thread using BLAKE3, fixes the aforementioned performance issue
- Update model probe to accept the algorithm to hash with as an optional arg, defaulting to `blake3`
- Update all calls of the probe to use the app's configured hashing algorithm
- Update an external script that probes models
- Update tests
- Move ModelHash into its own module to avoid circuclar import issues

## Related Tickets & Documents

- Closes #5938

## QA Instructions, Screenshots, Recordings

There should be no change in behaviour.

## Merge Plan

This PR can be merged when approved

## Added/updated tests?

- [x] Yes
- [ ] No : _please replace this line with details on why tests
      have not been included_

### CODE REVIEW

**Comment by psychedelicious** [comment]
@lstein In the interest of fixing a performance issue for users, I've implemented single-threaded hashing in this PR.

**Review by hipsterusername — APPROVED** [review]

**Comment by psychedelicious** [comment]
I've added the hashing algorithm as a prefix to the output hashes and added/updated tests.

**Review by brandonrising — COMMENTED** [review]
lgtm!

**Review by brandonrising — APPROVED** [review]
lgtm! Should we perhaps update model hashes as their retrieved if we don't detect the prefix?

**Pull request merged**
