### PR TITLE
Cleanup code in main

### PR DESCRIPTION
**Pull request by StAlKeR7779**
Delete `--karras-max` argument as it's no longer used.
Mark regex strings, as without it there special characters may interfere.
Fix - in some places there tuples instead of values itself.
Delete `get_learned_conditioning` and `channels` from `InvokeAIStableDiffusionPipelineOutput` as it's methods for compatibility with legacy classes.
Delete `bsgran`/`image_degradation` as it's not referenced anywhere.

Also could someone look at:
https://github.com/invoke-ai/InvokeAI/blob/main/invokeai/backend/config/model_install_backend.py#L450
This logic looks strange, IMHO)
It's works as `.startswith("/VAE/")` + it's case sensitive + if it's for internal relative path it's should not starts with / + if we check for vae it's should be not in config path

### CODE REVIEW

**Comment by hipsterusername** [comment]
@lstein @damian0815 

Any thoughts on this PR? If we are holding on making any of these changes, would like to make sure we keep track of perspectives/thoughts in this PR

**Comment by ebr** [comment]
All of the syntax improvements look great :+1: . Can't comment on `bsrgan`, etc, deletions though (makes sense to me on the surface, but I don't know enough about that)

**Comment by lstein** [comment]
I'm going to review this later today - sorry I missed seeing it!

**Comment by hipsterusername** [comment]
@lstein - Any chance you reviewed?

**Comment by lstein** [comment]
It looks good to me. I'm going to approve;  there are some conflicts that need fixing.

**Review by lstein — APPROVED** [review]
Apologies for the delay. I am happy to approve.

**Comment by lstein** [comment]
@StAlKeR7779 I've merged with main and resolved conflicts. The `image_utils.py` file was deleted in your PR but modified in `main`. Out of an excess of caution I added it back in.

**Comment by StAlKeR7779** [comment]
@lstein It's intended deletion - all folder deleted and this just one file from it.
Conflict just due to small patch with new logging in main.

**Pull request closed without merging**
