### PR TITLE
Make unit tests work again

### PR DESCRIPTION
**Pull request by lstein**
This PR is for adjusting the unit tests in the `tests` directory so that they no longer throw errors. 

I've removed two tests that were obsoleted by the shift to latent nodes, but `test_graph_execution_state.py` and `test_invoker.py` are throwing this validation error:

```
TypeError: InvocationServices.__init__() missing 2 required positional arguments: 'boards' and 'board_images'
```

### CODE REVIEW

**Comment by hipsterusername** [comment]
@psychedelicious @maryhipp looks like this is from the inclusion of boards.

**Comment by psychedelicious** [comment]
We definitely should not be removing any tests. I'll aim to fix these this weekend.

**Comment by lstein** [comment]
> We definitely should not be removing any tests. I'll aim to fix these this weekend.

Advise if the TestTextualInversion and TestNodeGraph should be added back in some form. The first was failing because it tries to load TextualInversionManager, which has been rewritten and no longer exists. The second was failing becuase TextToImage and ImageToImage invocations were removed and replaced with latent node implementations.

**Comment by psychedelicious** [comment]
Yes the tests should be added back. While they refer to nonexistent node types, the test node graph suite is testing core functionality and could use any node type. 

If we still support TI we should instead change the TI tests to properly test that functionality.

**Comment by psychedelicious** [comment]
@lstein
I've reverted (via hard reset, for a clean commit history) the deletion of the two test suites, and pushed some fixes:
- Fix all tests in `test_node_graph.py`
- Fix typing of `InvocationServices` wrt logger and model manager services
- Fix instantiation of `InvocationServices` in the tests

Not sure what to do about the TI tests - how is TI handled now? Is it entirely via diffusers?

**Comment by ebr** [comment]
I added a commit that re-enables previously skipped test suites, so that we know what's actually failing and needs fixing

**Comment by psychedelicious** [comment]
Uhh I'm a bit confused, I had fixed everything so that all tests passed except the textual inversion suite. Why are these other changes needed?

**Comment by ebr** [comment]
> Uhh I'm a bit confused, I had fixed everything so that all tests passed except the textual inversion suite. Why are these other changes needed?

Because I had skipped the failing tests in another PR that was merged to `main`, before seeing your fixes in this PR. So I'm re-enabling them here. + moving the `InvocationServices` fixture to a common location for DRY.

**Comment by psychedelicious** [comment]
Whew, that was really confusing. 

[tests(nodes): fix nodes tests](https://github.com/invoke-ai/InvokeAI/pull/3575/commits/87302c4820a773fda10daf07dc13eec19c114ac2)
[87302c4](https://github.com/invoke-ai/InvokeAI/pull/3575/commits/87302c4820a773fda10daf07dc13eec19c114ac2)

Revert extracting mock invocation services into their own file.

One part of graph validation is checking that all nodes in the graph have a valid node `type` attribute. The union of valid types is constructed dynamically, at runtime, by checking all node classes in memory.

By creating the mock invocation services in their own module, the union is constructed before the test node classes are loaded into memory. During tests, the test node types are not part of the union and so validation fails.

We need to ensure the test nodes are all imported before the union is constructed. I couldn't figure out how to make this work with the mock services being in different files, so I have reverted that change. Each test that needs mock services should create their own.

**Comment by psychedelicious** [comment]
I've manually squashed and merged the commits in this PR because rebasing a the different manual reverts was complicated.

**Review by psychedelicious — APPROVED** [review]

**Comment by ebr** [comment]
> By creating the mock invocation services in their own module, the union is constructed before the test node classes are loaded into memory. During tests, the test node types are not part of the union and so validation fails.
> 
> We need to ensure the test nodes are all imported before the union is constructed.

Thank you for figuring this out - this is great to know! And sorry for sending you on a wild goose chase by extracting the fixture (something something "paved with good intentions").

**Review by blessedcoolant — APPROVED** [review]

**Pull request merged**
