### PR TITLE
[refactor] Infill Methods + Mosaic Infill

### PR DESCRIPTION
**Pull request by blessedcoolant**
## Summary

Refactor and code cleanup for Infill Methods.

### InfillImageProcessorInvocation

A new parent node has been added similar to how we deal with ControlNet processors. This node will perform higher level operations required for Infill method nodes.

- Currently handles the loading of the input image and the building of the infilled outputs.
- Ensures that the input image has an alpha channel before being processed.
- Mandates an abstract method called `infill` that can be used by children nodes to perform the required infill operations.

### Clean Up

- Updated all existing Infill methods to make use of the new parent invocation.
- Cleaned up the `infill.py` invocations file of all infill related logic. Those now reside inside `backend/image_util/infill_methods` folder.
- Patchmatch had class methods defined while brute forcing the usage of instance variables inside these methods. This has now been fixed. Also cleaned up the patch match code a bit so it reads better coz the class is called in various files to check if patchmatch is available. This could probably be simplified to one call actually. I'll do this in another PR coz it messes with the config.
- Fixed the `INFILL_METHODS` constant having a lint error because we were dynamically setting `Literal` types. While this works, this is not how it needs to be done. Unfortunately, there's no "dynamic" solution afaik to setting literals. So instead just cleaned up the code with manual types so we get proper code completion for infill methods.

### Mosaic Infill

- Added a new type of Infill called Mosaic -- which is effectively a form of Tile Infill but allows you to control the tile shape, tile color and etc.
- Added both "mosaic" and "color" as new infill options for Unified Canvas.

I think I can refine Mosaic a bit more. If that pans out, I'll just remove Tile Infill coz this would be better in almost every use case compared to the older one.

### CODE REVIEW

**Comment by psychedelicious** [comment]
Sweet, great idea to handle this all in a parent class

**Review by psychedelicious — APPROVED** [review]
I'm not sure I understand how mosaic works. I seem to get solid colors pretty frequently. Here's an example:
image

Everything else looks great

**Comment by blessedcoolant** [comment]
> I'm not sure I understand how mosaic works. I seem to get solid colors pretty frequently. Here's an example: ![image]

That is not how that is supposed to work. My guess is that when the min value falls on the spectrum behind the max value, it resorts to a single color. Which is why we needed the double color input module in the UI to avoid this. Umm .. gotta think.

**Comment by psychedelicious** [comment]
I've updated this PR on main (`git pull --rebase` to update your local branch).

I was troubleshooting a canvas problem with the bbox and my troubleshooting kept getting interrupted by a problem with the tile infill. In the end, I don't think the error with tile was related to the bbox issue, but I ended up rewriting the tile infill method to be much simpler with no failure mode. Added it to this PR which seemed appropriate.

I added a notebook to test an infill method, and 10 test images that cover a variety of situations. The notebook duplicates each image, applying some transformations to the copies, to really cover all our bases. This test can't really be automated, so this serves as a way to smoke test the infill methods.

Here's the output from my new tile infill (identical in character to the previous, but not the same - though this doesn't really matter for canvas):
tile_output

**Comment by psychedelicious** [comment]
@blessedcoolant
Given that my tile redo is a bugfix, how do you feel about omitting the mosaic fill for now and merging this PR sooner rather than later?

I had some ideas for tile infill to make it better that I didn't get to:
- Match the tile image to a histogram. I think this could end up serving a similar purpose to mosaic but with more detail.
- Add noise to the tile image.
- Do a liquify kind of effect on the tile image. This would mitigate the relatively common straight lines that we get from this infill method.
- Add a blur to the tile image.

I think the last 3 options could help get tile infill much closer to patchmatch quality, but far more efficiently.

**Comment by blessedcoolant** [comment]
> @blessedcoolant Given that my tile redo is a bugfix, how do you feel about omitting the mosaic fill for now and merging this PR sooner rather than later?
> 
> I had some ideas for tile infill to make it better that I didn't get to (I just wanted to fix the bug for now):
> 
> * Match the tile image to a histogram. I think this could end up serving a similar purpose to mosaic but with more detail.
> * Add noise to the tile image.
> * Do a liquify kind of effect on the tile image. This would mitigate the relatively common straight lines that we get from this infill method.
> * Add a blur to the tile image.
> 
> I think the last 3 options could help get tile infill much closer to patchmatch quality, but far more efficiently.
> 
> Let's merge this before getting into the weeds on other features.

Yep. I'm good with that. Leave the mosaic infill code in but disable the node ?

**Comment by psychedelicious** [comment]
> Yep. I'm good with that. Leave the mosaic infill code in but disable the node ?

Yeah sounds good. Could just comment out the `@invocation` decorator I guess

**Comment by psychedelicious** [comment]
- Disabled mosaic
- Updated PR

Masterwork from testing
image

**Pull request merged**
