### PR TITLE
restore ability of ksamplers to process -v variation options

### PR DESCRIPTION
**Pull request by lstein**
- supersedes #977
- A limitation of this fix is that it works with txt2img only, and not with img2img. Please use plms or ddim samplers for applying minor variations to img2img until a better solution is found.

### CODE REVIEW

**Comment by Any-Winter-4079** [comment]
I'll check it out.

Also, I proposed
```
if x_T is not None:
            if S != total_steps-1:
                x = x_T + torch.randn([batch_size, *shape], device=self.device) * sigmas[0]
            else:
                x = x_T * sigmas[0]
```
in https://github.com/invoke-ai/InvokeAI/pull/977

**Comment by lstein** [comment]
Second commit gets variations working properly with both `txt2img` and `img2img`. Trick is to replace torch.randn with torch.randn_like when the init_img is present.

**Comment by Any-Winter-4079** [comment]
@lstein  It seems to work, but I've encountered something weird.
```
if x_T is not None:
            x = x_T + torch.randn([batch_size, *shape], device=self.device) * sigmas[0]
            print(x)
            if x0 is not None:
                #x = x_T + torch.randn([batch_size, *shape], device=self.device) * sigmas[0]
                x = x_T + torch.randn_like(x0, device=self.device) * sigmas[0]
                print(x)
            else:
                x = x_T * sigmas[0]
        else:
            x = torch.randn([batch_size, *shape], device=self.device) * sigmas[0]
```

**Comment by Any-Winter-4079** [comment]
`img2img` variations seem to work
image

**Comment by lstein** [comment]
Excellent news. Another bug down, and I don't know how many more to go.

Every call to `randn()` is going to advance the current seed and affect all subsequent calls to the random number generator. I've been think that we should use another method of advancing the seed that is set before generating each image, in order to avoid this source of change between one version and another.

**Pull request merged**
