### PR TITLE
Add New Web UI and Desktop Mode

### PR DESCRIPTION
**Pull request by blessedcoolant**
# All New WebUI

This PR brings in the new design for the new WebUI.

msedge_Dr19bjNDMi

msedge_A3NcO3KHDG

The new redesign presents a simple and easy to use GUI for anyone. The main options that are required for prompt generation are readily available with the more detailed settings presented to you as advanced options.

The New WebUI currently supports text to image generation, image to image generation, image upscaling, face restoration, variations, progress images and seamless tiling with more being worked on.

Currently only the Text to Image tab is populated. However you will find other tabs in the UI. These tabs will be released in future patches. These tabs will provide dedicated UI's for image to image, inpainting, outpainting , node workflow and post processing.

### Usage

New `dream.py` arguments.

- `--web` - Launches WebUI on a local server
- `--host` - To set the host of your server
- `--port` - To set the port of your server
- `--cors` - To white list your server and port if you are getting CORS errors

**Example usage:**

```python
dream.py <other arguments> --web
```

# Desktop Mode

You can now run the WebUI as a desktop app on your computer. This will launch using your systems browser as a desktop window instead of inside a regular browser.

To use desktop mode, you will need to install `pip install flaskwebgui`

### Usage

```python
dream.py <other_arguments> --gui
```

---

# Notes

- If you have tested previous version of the WebUI, it is recommend you delete your LocalStorage. Sometimes this might cause some issues with persistence. You just need to do this once. You can do this manually by deleting it from the developer tools of your browser or from Settings > Reset Web UI.

---

Rebased #879
Co-Authored-By: psychedelicious <4822129+psychedelicious@users.noreply.github.com>

### CODE REVIEW

**Comment by lstein** [comment]
It's looking good. One thing I noticed is that if you are using an image as an init image and then delete it from the gallery, the GUI will fail to generate until you push the trash can icon on the init image. Inactivating "Init Image" doesn't do it.

**Comment by blessedcoolant** [comment]
> It's looking good. One thing I noticed is that if you are using an image as an init image and then delete it from the gallery, the GUI will fail to generate until you push the trash can icon on the init image. Inactivating "Init Image" doesn't do it.

Oh we forgot to fix that. We'll fix it in one of the next patches.

@psychedelicious

**Comment by lstein** [comment]
I inadvertently tried to generate a 2048xx2048 image. It took a long time for the cancel button to take effect!

**Comment by blessedcoolant** [comment]
> I inadvertently tried to generate a 2048xx2048 image. It took a long time for the cancel button to take effect!

Yes. That's a threading issue. Unfortunately there's no easy bypass for this. I'm looking into asynchronous solutions but don't have one right now. If we fix this, then it'll also be in a future patch.

**Review by lstein — APPROVED** [review]
Really nice work. I noticed a few minor glitches, noted in the comments, but I'm going to go ahead and merge into development.

**Comment by blessedcoolant** [comment]
> Really nice work. I noticed a few minor glitches, noted in the comments, but I'm going to go ahead and merge into development.

Thank you. I'm nearly done with the img2img tab too. I should have a PR for it in a day or two. Maybe faster if I can find time.

**Pull request merged**
