### PR TITLE
Mkdocs fixes

### PR DESCRIPTION
**Pull request by mauwii**
addressing changes mentioned [here](https://github.com/invoke-ai/InvokeAI/issues/1013#issue-1403311736), and many more... Utilizing capabilities of mkdocs-material as best as I could :godmode: 

Preview available at https://mauwii.github.io/stable-diffusion/

### CODE REVIEW

**Comment by lstein** [comment]
Thank you so much for working on this. I hadn't appreciated how nice the pages look when converted. You'll take the PR out of draft state when you are ready for a review, right?

**Comment by mauwii** [comment]
Np, I guess you where busy with other stuff 🙈

**Comment by mauwii** [comment]
Is it on purpose that there is docs/CHANGELOG.md as well as docs/features/CHANGELOG.md? (I guess yes since both got updated 🤔 )

**Review by tildebyte — APPROVED** [review]
LGTM 💯

**Comment by tildebyte** [comment]
@mauwii; Drat, we seem to have GH Action issues...

**Comment by mauwii** [comment]
I thought [the 403 error](https://github.com/invoke-ai/InvokeAI/actions/runs/3222934736/jobs/5272503617#step:5:214) would be because I do neither have permissions to update the Repo nor gh-pages 🤔

**Comment by tildebyte** [comment]
> I thought [the 403 error](https://github.com/invoke-ai/InvokeAI/actions/runs/3222934736/jobs/5272503617#step:5:214) would be because I do neither have permissions to update the Repo nor gh-pages 🤔

I figured that might be it...

**Comment by mauwii** [comment]
I would guess that a PR does not have the permission to use secrets and so the GH-Token which is necesarry to run the `git push origin gh-pages` is not valid, which should be fixed when merged into main (since it is only failing when running `mauwii:mkdocs-fixes`, but not when running from `main`)

**Comment by mauwii** [comment]
I disabled the pull request part in the action now 😅

**Comment by mauwii** [comment]
This will be it, since I am going to start work now 🙈

**Review by lstein — APPROVED** [review]
I really appreciate this!

**Comment by lstein** [comment]
I'm seeing conflicts, but hopefully I can get them resolved and merged this morning before I have to start work.

**Comment by lstein** [comment]
Merged in. I used a squash commit to consolidate the 47 commits into one.

**Pull request closed without merging**
