### PR TITLE
feat(ui): protect against t2i adapters with incompatible image dimensions

### LINKED ISSUE #5370: [bug]: T2I-Adapter in tiled-upscaling-sample nodes-workflow isn't working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

3.5.1

### What happened?

While testing out if you could use the canny t2i-Adapter instead of a Controlnet in the new Tiled-Upscaling sample nodes-workflow, the following error arises at the beginning of the denoising process (note that I'm using SDXL instead of SD 1.5) : 

[2024-01-01 20:32:29,684]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "C:\Users\\source\Git\Invokeai\.venv\lib\site-packages\invokeai\app\services\invocation_processor\invocation_processor_default.py", line 104, in __process
    outputs = invocation.invoke_internal(
  File "C:\Users\\source\Git\Invokeai\.venv\lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 669, in invoke_internal
    output = self.invoke(context)
  File "C:\Users\\source\Git\Invokeai\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\\source\Git\Invokeai\.venv\lib\site-packages\invokeai\app\invocations\latent.py", line 772, in invoke
    ) = pipeline.latents_from_embeddings(
  File "C:\Users\\source\Git\Invokeai\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 381, in latents_from_embeddings
    latents, attention_map_saver = self.generate_latents_from_embeddings(
  File "C:\Users\\source\Git\Invokeai\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 454, in generate_latents_from_embeddings
    step_output = self.step(
  File "C:\Users\\source\Git\Invokeai\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\\source\Git\Invokeai\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", li    uc_noise_pred, c_noise_pred = self.invokeai_diffuser.do_unet_step(
  File "C:\Users\\source\Git\Invokeai\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusion\shared_invokeai_diffusion.py", line 267, in do_unet_step
    ) = self._apply_standard_conditioning(
  File "C:\Users\\source\Git\Invokeai\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusion\shared_invokeai_diffusion.py", line 380, in _apply_standard_conditioning
    both_results = self.model_forward_callback(
  File "C:\Users\\source\Git\Invokeai\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 664, in _unet_forward
    return self.unet(
  File "C:\Users\\source\Git\Invokeai\.venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\\source\Git\Invokeai\.venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\\source\Git\Invokeai\.venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 1087, in forward
    sample += down_intrablock_additional_residuals.pop(0)
RuntimeError: The size of tensor a (57) must match the size of tensor b (56) at non-singleton dimension 3

[2024-01-01 20:32:29,695]::[InvokeAI]::ERROR --> Error while invoking:
The size of tensor a (57) must match the size of tensor b (56) at non-singleton dimension 3

### Screenshots

_No response_

### Additional context

_No response_

### Contact Details

_No response_

### PR DESCRIPTION
**Pull request by psychedelicious**
## Summary

T2I Adapter requires images be multiples of 64. It's not clear if this is fixable or worth the effort to fix.

Pre-4.2.0, there was a little hack that set the image dimensions to the nearest multiple of 64 when selecting a T2I adapter. This was lost in the CL implementation. I don't like this solution - the user can change the image dimensions at any time and then they'll get a mysterious error when invoking.

To address the issue, an additional pre-Invoke check is added. You cannot click Invoke if you have a T2I layer and the image dimensions are not a multiple of 64.

image

Another issue apparent in the discord thread is that there is no way to differentiate between T2I adapter models and ControlNet models in the drop-down if the model names don't include "controlnet" or "t2i adapter" in them. It wasn't clear that the model in use was a T2I adapter model.

To address this, the model select now groups both by base model and model type:

image

While fixing up the pre-invoke check messages, I reworked them for Control Layers. It's a bit stricter now - you cannot invoke if an enabled RG layer has no mask, for example. The messages are more descriptive, too.

image

These changes are all CL-only - they do not apply to UC.

## Related Issues / Discussions

https://discord.com/channels/1020123559063990373/1149506274971631688/1238333845648969789

Closes #5370

## QA Instructions

Have a play with the pre-invoke checks, I believe that's the only change that may warrant some discussion. 

## Merge Plan

n/a

## Checklist

- [x] _The PR has a short but descriptive title, suitable for a changelog_
- [ ] _Tests added / updated (if applicable)_
- [x] _Documentation added / updated (if applicable)_

### CODE REVIEW

**Review by hipsterusername — APPROVED** [review]

**Comment by psychedelicious** [comment]
Also fixed pluralization on the tooltip for the generations count.

**Comment by Adreitz** [comment]
@psychedelicious In my experience, T2I-Adapters require a multiple of 32, not 64, for image resolution. I use T2I SDXL Canny for upscaling control in Nodes, and it works fine for controlling diffusion at 3840x2400 (not tiled). Am I misunderstanding the limitation?

**Comment by psychedelicious** [comment]
@Adreitz I found a note I had left myself some time ago saying that dimensions must be multiples of 64, but also I had read about it being 32. I did testing at lower resolutions then that and not all multiples of 32 worked, so I made it 64.

For example, 544 * 544 fails:

```
RuntimeError: The size of tensor a (68) must match the size of tensor b (64) at non-singleton dimension 3
```

64 works all the time. However, I realize now that I only tested on SD1.5. I just check and SDXL works with multiples of 32.

Digging deeper, we see why: https://github.com/invoke-ai/InvokeAI/blob/main/invokeai/app/invocations/latent.py#L762-L778

This confirms that SDXL works with multiples of 32 and SD1.5 works with multiples of 64. I can update the check to match these constraints.

@RyanJDick, can you advise if this is still a hard requirement for T2I Adapter?

**Comment by RyanJDick** [comment]
> @RyanJDick, can you advise if this is still a hard requirement for T2I Adapter?

It's been a while since I looked at this, so my memory is a little fuzzy on the details. I made [this PR](https://github.com/huggingface/diffusers/pull/5435) on diffusers to reduce the requirements from "64 for SD1 and 32 for SDXL" to "8 for SD1 and 16 for SDXL". It sounds like we are still running into the old limits. I'd have to dig deeper to figure out why. What would say is the priority of this?

**Comment by hipsterusername** [comment]
Probably low.

**Comment by psychedelicious** [comment]
> What would say is the priority of this?

IMO, we shouldn't spend any time on it. Nobody has complained about the constraints on image dimensions with T2I Adapter. The issue is that I've changed unwittingly changed constraints in the last release. I've addressed this #6366 by allowing images that are multiples of 32 when using SDXL T2I Adapter.

**Comment by Adreitz** [comment]
As far as I'm concerned, reduced restrictions are a nice-to-have but not necessary. Preventing a regression in the restrictions was my main point, and I think you've addressed that. Thanks.

**Pull request merged**
