### PR TITLE
[WebUI] They see me slidin .. they hatin...

### PR DESCRIPTION
**Pull request by blessedcoolant**
Porting over as many usable options to slider as possible.

- Ported Face Restoration settings to Sliders.
- Ported Upscale Settings to Sliders.
- Ported Variation Amount to Sliders.
- Ported Noise Threshold to Sliders <-- Optimized slider so the values actually make sense.
- Ported Perlin Noise to Sliders.
- Added a suboption hook for the High Res Strength Slider.
- Fixed a couple of small issues with the Slider component.
- Ported Main Options to Sliders.

### CODE REVIEW

**Review by hipsterusername — APPROVED** [review]
Approved - now required to name all PRs as 2000s hip hop songs

**Comment by psychedelicious** [comment]
I think we should have this be optional... Maybe we extend this to be a compact mode in the future? This is the kind of polarising UI change we may want user feedback on... also @netsvetaev

Also, yes, I support making a workflow to enforce a certain degree of matching PR names to hip hop songs. I have some ideas about how to calculate a similarity score.

**Comment by blessedcoolant** [comment]
> I think we should have this be optional... Maybe we extend this to be a compact mode in the future? This is the kind of polarising UI change we may want user feedback on... also @netsvetaev
> 
> Also, yes, I support making a workflow to enforce a certain degree of matching PR names to hip hop songs. I have some ideas about how to calculate a similarity score.

Yeah. I've been thinking about that too. Maybe I'll make it optional and see how that feels. If not so good, we scrap this PR.

**Comment by psychedelicious** [comment]
Even if we don't implement this now, it's a good exercise to see what it would look like

**Comment by blessedcoolant** [comment]
Yep. Was mainly doing it to see how it feels coz we did talk about an all Slider world a long time ago. If i get the chance, I'll try to make this option, if not, we can always come back and reuse some of the code if need be at a later time.

**Comment by netsvetaev** [comment]
> I think we should have this be optional... 

@psychedelicious The best slider implementation to me, is blender-like, where text input and slider are combined into one block. Click — precise edit, drag — slider. 

Also some options need to be precise. Some need quick presets on the slider itself (cfg 3-7-12-15-20-..., steps 5-20-35-50-70-100-...). The steps are more or less linked to the samplers, ideally their scale should change for each sampler.
The number of steps up to 100 seems limited (to a user), and I've seen little change at 400-500 steps ddim with sd2.1. 

I agree, as with the canvas beta UI, we can keep the original layout and propose a new one as an option (and keep working on it).

Ideally, we should make two variants: a safe one, for beginners, where there're no extreme settings, options are limited and it's impossible to «break» the result, and an advanced one, where there are no such restrictions, options are more precise and free to change in any way.

**Review by lstein — APPROVED** [review]
Tested and working well in an Ubuntu environment. I think it's intuitive enough for everyone and don't think we need to have an "expert mode" for the sliders UI.

I noticed a small UI annoyance. When I type a value directly into the number field, the slider value doesn't update until I move focus out of the field. I kept pressing <return> thinking that this would cause the slider to update, and don't see why that shouldn't work.

**Comment by psychedelicious** [comment]
@lstein 

> and don't see why that shouldn't work.

Welcome to JavaScript.

**Comment by blessedcoolant** [comment]
> Tested and working well in an Ubuntu environment. I think it's intuitive enough for everyone and don't think we need to have an "expert mode" for the sliders UI.
> 
> I noticed a small UI annoyance. When I type a value directly into the number field, the slider value doesn't update until I move focus out of the field. I kept pressing thinking that this would cause the slider to update, and don't see why that shouldn't work.

I think I did that coz something was not updating correctly. So decided to play it safe and do it on focus left. I'll look into that again.

**Comment by psychedelicious** [comment]
I think disallowing explicit, direct control of all numbers is a mistake, even if sliders are intuitive and work for most use cases. Think of eg ancestral samplers where excellent results can be had at 16 steps but 15 and 17 are wildly different.

**Comment by blessedcoolant** [comment]
> I think disallowing explicit, direct control of all numbers is a mistake, even if sliders are intuitive and work for most use cases. Think of eg ancestral samplers where excellent results can be had at 16 steps but 15 and 17 are wildly different.

Which slider doesnt allow this? (except width and height) .. I need to unlock those coz the step is now 8 with diffusers and not 64.

**Comment by psychedelicious** [comment]
I mean if we change them all to sliders. Or do they all have number inputs also? Sorry if I missed that, I haven't checked out the pr yet

**Comment by blessedcoolant** [comment]
> I mean if we change them all to sliders. Or do they all have number inputs also? Sorry if I missed that, I haven't checked out the pr yet

All have Sliders / Inputs / Reset.

**Comment by blessedcoolant** [comment]
@psychedelicious @hipsterusername @netsvetaev 

This is now an optional thing.

Default

msedge_CYRVytKEbX

Setting 

msedge_tDTYQiqsCc

They see me slidin .. they hatin ... 

msedge_WGqb2lrD95

**Comment by netsvetaev** [comment]
@blessedcoolant great work! Thank you.

**Comment by blessedcoolant** [comment]
@psychedelicious If you review and approve this can you can do another build and rebase too please? Think something else got merged in to the front end. I'm off the PC for a few hours.

**Review by psychedelicious — APPROVED** [review]
tryna catch me slidin dirty

**Pull request merged**
