### PR TITLE
Integrate New WebUI with dream.py

### PR DESCRIPTION
**Pull request by blessedcoolant**
This is the first draft of integrating the new WebUI with `dream.py`

## Major Changes

- Launching `dream.py` with `--web` now launches the new WebUI.

---

**NOTE**

This is just a first draft. At the moment, I just ported over the entire thing as it is with some changes to let dream.py handle the loading of the models and etc.

Everything should work like it has been if you launched `backend/server.py`

There's a ton of code cleanup that can be done. I will work on it through the week and have this finalized by then.

---

@psychedelicious Do a thorough test of the new `server_integrated.py` please to make sure everything is working as intended. Feel free to make updates to it. Once we know it's all set in place, I'll remove the `server.py` file and rename the integrated version to server.py.

### CODE REVIEW

**Comment by psychedelicious** [comment]
Almost everything works fine, thanks for helping improve things. Only problem is images not being served from flask. 

I have made a couple very small changes in [my branch of your branch](https://github.com/psychedelicious/stable-diffusion/tree/webui-integration):
- Manually implemented PR#826 (was breaking progress images)
- "Fix" for images 04304b26fce488247559b56e8cc9a68a63e5194e

Without the "fix" I made, flask was trying to serve paths like `outputs/img-samples/img-samples/12345.png`. The change I made fixes the issue for me, but only for the default `outdir` arg. I can't wrap my head around making it work. 

As I went through, there are some obvious refactoring candidates, suspect you've also found others:
- Wrapping each event handler with `try: except:`, emitting an 'error' with caught exceptions (see issue #817)
- Clean up everything related to socketio sending progress/status updates
- The handlers for `runESRGAN` and `runGFPGAN` share like 95% of the same code

**Comment by blessedcoolant** [comment]
> Manually implemented PR#826 (was breaking progress images)

Implemented this fix.

> Without the "fix" I made, flask was trying to serve paths like `outputs/img-samples/img-samples/12345.png`. The change I made fixes the issue for me, but only for the default `outdir` arg. I can't wrap my head around making it work.

This has not been an issue for me. In fact that fix you suggest is what is breaking it. Otherwise the files are being served from the output folder on the origin host which is what it should be doing.

> * Wrapping each event handler with `try: except:`, emitting an 'error' with caught exceptions (see issue [Web server backend crashes if a file in local storage is missing #817](https://github.com/invoke-ai/InvokeAI/issues/817))

While adding exceptions will work, the ideal way to solve this is to add the local storage entries as soon as the page loads if they don't exist. So calling them does not break the app.

But I'll go through a cleaning pass soon.

> * The handlers for `runESRGAN` and `runGFPGAN` share like 95% of the same code

Yep. Also find ways to minimize other code duplications if any. I'm also thinking of code splitting maybe because the file is pretty long.

**Comment by blessedcoolant** [comment]
@psychedelicious I am also going to work on a reskin while I am working on this. I noticed a few things that need fixing. Hope you can do them while I work on the styling.

- When I press the cancel button, I expect the progress bar at the top to reset. Instead it just stops where it is.
- Pressing the cancel button should stop the status text at stop to say 'Canceled' or something. But it stops at Generating.

Please fix these two. It's important to give the user a visual feedback when the cancellation happens.

I'll keep beeping you on this thread as I find more stuff. Hope you don't mind. :)

**Comment by psychedelicious** [comment]
Can fix those no problem. 

I'll respond in more detail a bit later, but for now, if you are reskinning, please check out the [Chakra theming system](https://chakra-ui.com/docs/styled-system/customize-theme#using-theme-extensions). It's quite nice. I'm using `extendTheme()` [here](https://github.com/blessedcoolant/stable-diffusion/blob/webui-integration/frontend/src/app/theme.ts) already to customize individual component styles.

You can add a `global` property, as described in the docs, use CSS selectors as keys with CSS rules as values and it gets compiled into the CSS. I have been hacking away at the node-based UI and styling with this, you can get a better example [here](https://github.com/psychedelicious/stable-diffusion/blob/react-flow-test/frontend/src/app/theme.ts). Dark mode is super easy with this. 

If we have some awesome color scheme, it can be defined and override the color and other theme tokens automagically when selected. I.e. you use `blue.500` and all the other theme tokens throughout `theme.ts`, then define a colorscheme that changes which actual color those tokens resolve to. So user selects the Cyberpunk theme from a dropdown and everything changes.

Sorry if you already know all this!

**Comment by blessedcoolant** [comment]
> I'll respond in more detail a bit later, but for now, if you are reskinning, please check out the [Chakra theming system](https://chakra-ui.com/docs/styled-system/customize-theme#using-theme-extensions). It's quite nice. I'm using `extendTheme()` [here](https://github.com/blessedcoolant/stable-diffusion/blob/webui-integration/frontend/src/app/theme.ts) already to customize individual component styles.
> 
> You can add a `global` property, as described in the docs, use CSS selectors as keys with CSS rules as values and it gets compiled into the CSS. I have been hacking away at the node-based UI and styling with this, you can get a better example [here](https://github.com/psychedelicious/stable-diffusion/blob/react-flow-test/frontend/src/app/theme.ts). Dark mode is super easy with this.
> 
> If we have some awesome color scheme, it can be defined and override the color and other theme tokens automagically when selected. I.e. you use `blue.500` and all the other theme tokens throughout `theme.ts`, then define a colorscheme that changes which actual color those tokens resolve to. So user selects the Cyberpunk theme from a dropdown and everything changes.
> 
> Sorry if you already know all this!

I've done some research and decided against using the extendTheme functionality to theme further. There are limitations to it beyond the API they provide. There are some cases where I would like a full override and that is not possible. Infact because Chakra uses Emotion to inject CSS after hydration, using CSS classes or any other framework on top of it becomes difficult.

So I implemented as a cache system with Emotion to prepend the Chakra classes instead of appending them. This now allows us to theme on top of the Chakra UI.

---

I'm doing a theming pass using SCSS. This styling will be purely visual as I intend to retain the functionality that ChakraUI components provide.

There are a few advantages of doing this.

1. Anyone wanting to style or theme does not have to learn Chakra UI for this. They can just use CSS.
2. While theming becomes easier, we can still continue to use Chakra to build further UI elements.
3. There will be a dedicated color scheme files. All anyone ever needs to do is alter color values or create a new file with the same values to generate a whole new theme. This is a lot easier than getting them to mess with the ChakraUI components which could be widespread across the entire app.

I'll give you a preview of how I'm doing it once I have something substantial to show. At the moment, I'm setting up the barebones to get rolling.

firefox_uHD3TYtEen

There is a LOT to do. You'll see when I'm done.

**Comment by psychedelicious** [comment]
Thanks for giving it consideration. I tried to keep styling out of the project as I went, but there are some layout-related style props on most of the components. I'm not sure if stripping them so they are bare Chakra UI components, or leaving them and building on top is better for what you are doing. 

Anyways, I look forward to the upcoming overhaul!

**Comment by blessedcoolant** [comment]
> 



> Thanks for giving it consideration. I tried to keep styling out of the project as I went, but there are some layout-related style props on most of the components. I'm not sure if stripping them so they are bare Chakra UI components, or leaving them and building on top is better for what you are doing.
> 
> Anyways, I look forward to the upcoming overhaul!

I'll take care of that as I go. I am removing styling exclusive components and retaining the functional components. This way we have a simpler JSX too.

**Comment by plucked** [comment]
@blessedcoolant I am running a setup with two GPUs, therefore running two instances. I was looking for a way to send prompts as a curl request to the web server. Do you know if that is supported by your work? I guess that would also make testing easier.

**Comment by blessedcoolant** [comment]
Styling update. Just the prompt bar done for now. But I like how its shaping up. The work will continue through the week.

https://user-images.githubusercontent.com/54517381/192588100-e8bd97ff-668f-4675-a92e-5078f282a849.mp4

**Comment by blessedcoolant** [comment]
Some more progress on the UI. Did some initial drafts for the image viewer and the gallery. Lots more to do. The options panel will have a major overhaul.

https://user-images.githubusercontent.com/54517381/192617239-8bafbdce-e978-44fd-8e8c-289260706fb9.mp4

**Comment by psychedelicious** [comment]
I dig the purple :) 

@plucked Please raise an issue with your request

**Comment by blessedcoolant** [comment]
@lstein This is good to go. I'm leaving @psychedelicious original server.py in the files for the time being. If there's any emergency porting bugs that need to be fixed, it'll be there for reference. If nothing pops up, I'll delete it in my theme update.

**Comment by blessedcoolant** [comment]
@lstein @tildebyte After many hours of fixing stupid ass bugs, @psychedelicious and I finally managed to have most of the things sorted. There are some niche issues that we know of which we will tend to in the coming days.

But for now this should be good to go.

The first integration of the new WebUI in to the main script. Big thanks and kudos to everyone who contributed to this massive undertaking.

In the coming days or week, I will make a push for a redesign of the new WebUI styling (screenshots that you can see above) and then refine it further based on user feedback.

Let's go.

**Review by psychedelicious — APPROVED** [review]
Tested pretty thoroughly and think its ready to go!

**Comment by tildebyte** [comment]
@blessedcoolant. @psychedelicious;

I don't have time to thrash this right now, so I'm trusting that the two of you are fully confident in this.

**Review by tildebyte — APPROVED** [review]

**Comment by lstein** [comment]
I am very excited to check this out.

**Comment by lstein** [comment]
I may have deleted the import line from backend.invoke_ai_web_server when I resolved a conflict with dream.py. I've readded it and am testing. Will directly commit a patch if it checks out.

**Comment by tildebyte** [comment]
Windows 11, multiple browsers

`python scripts/dream.py --web`

and then browsing to the indicated  http://127.0.0.1:9090 nets me a blank white page.

Console says

```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
```

**Comment by blessedcoolant** [comment]
> I may have deleted the import line from backend.invoke_ai_web_server when I resolved a conflict with dream.py. I've readded it and am testing. Will directly commit a patch if it checks out.
> 
> ..yep, that was me. Fortunately I caught and fixed it in minutes. The new interface is working great. The one thing I noticed is that when I first loaded, I got a bunch of broken image icons because I had cleared out my output directory earlier and none of the cached local storage images were valid. The issue was fixed by reloading the page in the browser.
> 
> Here's the message that printed out on the command line:
> 
> ```
> >> Page None of images requested (page size 50 offset None)
> Exception in thread Thread-9:
> Traceback (most recent call last):
>   File "/u/lstein/.conda/envs/ldm/lib/python3.9/threading.py", line 980, in _bootstrap_inner
>     self.run()
>   File "/u/lstein/.conda/envs/ldm/lib/python3.9/threading.py", line 917, in run
>     self._target(*self._args, **self._kwargs)
>   File "/u/lstein/.conda/envs/ldm/lib/python3.9/site-packages/socketio/server.py", line 730, in _handle_event_internal
>     r = server._trigger_event(data[0], namespace, sid, *data[1:])
>   File "/u/lstein/.conda/envs/ldm/lib/python3.9/site-packages/socketio/server.py", line 755, in _trigger_event
>     return self.handlers[namespace][event](*args)
>   File "/u/lstein/.conda/envs/ldm/lib/python3.9/site-packages/flask_socketio/__init__.py", line 282, in _handler
>     return self._handle_event(handler, message, namespace, sid,
>   File "/u/lstein/.conda/envs/ldm/lib/python3.9/site-packages/flask_socketio/__init__.py", line 826, in _handle_event
>     ret = handler(*args)
>   File "/u/lstein/projects/SD/InvokeAI/backend/invoke_ai_web_server.py", line 169, in handle_request_images
>     chunk_size * (page - 1) + offset,
> TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
> ```

Yep. This is a known issue. We'll fix this up in one of the coming bug fix patches.

@psychedelicious Maybe the solution to this is to add a check where we check if the file exists on disk. If it doesn't then we just remove it from the image gallery and push that.

**Comment by blessedcoolant** [comment]
> Windows 11, multiple browsers
> 
> `python scripts/dream.py --web`
> 
> and then browsing to the indicated http://127.0.0.1:9090 nets me a blank white page.
> 
> Console says
> 
> ```
> Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
> ```

Can you clear the older stuff and give this a fresh pull and try again?

**Comment by tildebyte** [comment]
> Can you clear the older stuff and give this a fresh pull and try again?

Same same. @psychedelicious and I ran into this once before, but I can't remember the resolution. Something about MIME types on Windows.

**Comment by blessedcoolant** [comment]
> > Can you clear the older stuff and give this a fresh pull and try again?
> 
> Same same. @psychedelicious and I ran into this once before, but I can't remember the resolution. Something about MIME types on Windows.

I'm on Windows too. Not facing this error. But let me try to look it up. Maybe @psychedelicious remembers the fix.

**Comment by hipsterusername** [comment]
Pulling down to put it through the ringer. Will report back.

**Pull request merged**
