### PR TITLE
feat(ui): FLUX in linear UI

### PR DESCRIPTION
**Pull request by maryhipp**
## Summary

Adds support in linear UI for using FLUX as a main model for text-to-image, image-to-image, inpainting, and outpainting.

**Does NOT include: LoRA support, controlnet support, IP adapter support, or upscaling**. This means the only available layers on the canvas included in this PR are inpainting and raster layers. Support for the rest will be in subsequent PRs as the back-end is built out.

## QA Instructions

Options for FLUX generation settings:
Screenshot 2024-09-16 at 1 33 19 PM

## Checklist

- [ ] _The PR has a short but descriptive title, suitable for a changelog_
- [ ] _Tests added / updated (if applicable)_
- [ ] _Documentation added / updated (if applicable)_

### CODE REVIEW

**Comment by hswlab** [comment]
The node user interface is not quite self-explanatory for basic users, it would be great if FLUX models could be used like all the other models via the basic ‘text to image’ user interface. Is this a big challenge to adapt Invoke AI to make this possible or can we expect such a functionality to be available in the future?

**Comment by maryhipp** [comment]
> The node user interface is not quite self-explanatory for basic users, it would be great if FLUX models could be used like all the other models via the basic ‘text to image’ user interface. Is this a big challenge to adapt Invoke AI to make this possible or can we expect such a functionality to be available in the future?

That is what this PR is doing 👍

**Comment by hipsterusername** [comment]
When switching to Flux from SDXL, bounding box can get put into a state that is whack/breaks - It's also strange to have the bounding box change sizes when canvas mode is selected.

**Review by psychedelicious — APPROVED** [review]
Looks great!

I changed one thing - drop the default steps from 50 to 30. Ain't nobody got time for that.

**Pull request merged**
