### PR TITLE
[docs] Provide an example of reading prompts from a script

### PR DESCRIPTION
**Pull request by lstein**
To address #1654 this PR provides a more fullsome example of how to generate a matrix of prompts via script and feed them into `invoke.py` at the command line.

### CODE REVIEW

**Review by mauwii — APPROVED** [review]

**Review by hipsterusername — APPROVED** [review]
Nice tips!

**Comment by Neosettler** [comment]
Still doesn't show how to pass the data to the script:

> To feed it to invoke.py, pass the filename of "-"
> python matrix.py | python scripts/invoke.py --from_file -

**Comment by mauwii** [comment]
[](https://invoke-ai.github.io/InvokeAI/features/PROMPTS/?h=from_file#reading-prompts-from-a-file)

**Comment by Neosettler** [comment]
@mauwii thank you, this part is well understood. The part that is missing is:

> You may also read a series of prompts from standard input by providing a filename of -. For example, here is a python script that creates a matrix of prompts, each one varying slightly:

which is confusing at best. Please, consider --from_memory <data> usable in interactive mode.

**Comment by mauwii** [comment]
> Please, consider --from_memory "prompt -s 7 -S 41 | prompt -s 7 -S 42 | prompt -s 7 -S 43", usable in interactive mode.

@Neosettler: I am not sure if I understand this Part.

The example provides a python script

```py
#!/usr/bin/env python

adjectives = ['sunny','rainy','overcast']
samplers = ['k_lms','k_euler_a','k_heun']
cfg = [7.5, 9, 11]

for adj in adjectives:
    for samp in samplers:
        for cg in cfg:
            print(f'a {adj} day -A{samp} -C{cg}')

```

which generates a output like

```
a sunny day -Aklms -C7.5
a sunny day -Aklms -C9
a sunny day -Aklms -C11
a sunny day -Ak_euler_a -C7.5
a sunny day -Ak_euler_a -C9
...
a overcast day -Ak_heun -C9
a overcast day -Ak_heun -C11
```

When the script is finished, each of the 27 combinations of adjective, sampler and CFG will be executed.

**Comment by Neosettler** [comment]
In what universe -from_file - function call fetches previous console inputs as arguments? Coming from a C++ background, It seems like a hack and should be handled in a more elegant way. 

To answer your question, as of 2.0, from_file only works when invoke.py is initialized. Maybe I'm missing something but I'm still trying to understand why would anyone use -from_file as it is currently implemented. from_file function must be use in interactive mode to be remotely useful!

Also, consider something like:
> --from_memory "-prompt "cat" -s 7 -S 41 | -prompt "dog" prompt -s 7 -S 42 | -prompt "bird" -s 7 -S 43"

I mean, the whole idea is to support several prompts in one function call!

**Pull request merged**
