### PR TITLE
feat (ui, generation): High Resolution Fix- added automatic resolution toggle and replaced latent upscale with two improved methods

### PR DESCRIPTION
**Pull request by marict**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [x] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [x] Yes
- [ ] No

## Description
This PR adds two new elements to the high resolution fix (HRF) feature in the text to image linear flow.
1. High resolution width and height will be automatically determined.
The width/height will be set to the closest dimensions multiplying to 512^2 pixels, while mantaining aspect ratio, and not having either dimension be greater than its final counterpart.
2. Removes the `Upscale Latents` method in the HRF modification to the text to image graph with an image resize node plus an optional ESRGAN upscale. The resize node alone and the ERSGAN upscale can be toggled with a new dropdown labeled: "Upscale Method". These new methods have less hallucinated detail and allow for a low denoise value with no artifacts.

The ERSGAN model will be automatically chosen based on the degree of upscaling required given the initial height and width.
image

## Related Tickets & Documents

- Related Issue #
https://github.com/invoke-ai/InvokeAI/issues/4906
https://github.com/invoke-ai/InvokeAI/issues/4907
- Closes #
https://github.com/invoke-ai/InvokeAI/issues/4906
https://github.com/invoke-ai/InvokeAI/issues/4907

## QA Instructions, Screenshots, Recordings
image
Tooltips:
image
image

Recall icons
image

## Added/updated tests?

- [ ] Yes
- [x] No: All changes are in frontend code

## [optional] Are there any post deployment tasks we need to perform?

Consideration of future work:
- Allow different image to image scheduler (SDE Kerras tends to work well for refining, DDIM/UniPC tends to work well for initial generation)
- Allow different image to image steps (smaller steps on the refiner can save computation)
- Add question mark tooltip button for quick synposis of feature use

### CODE REVIEW

**Review by Millu — COMMENTED** [review]
Functionality wise, this looks great to me! 

Would you be able to add tooltips to the different settings to help guide users who might not be as familiar?

**Comment by marict** [comment]
> Functionality wise, this looks great to me!
> 
> Would you be able to add tooltips to the different settings to help guide users who might not be as familiar?

Added some tooltips and updated the "Method" to "Upscale Method" to be more clear. Tried to make the tooltips concise so as not to crowd out the UI. What I think would work best for this feature is a little box with a question mark that users can click to get a run down on what the feature does.

**Comment by hipsterusername** [comment]
Resolving to 512 as the base res won't work with SDXL, but I don't think it's as much a concern. If we can commit to getting that updated in a follow-on, I'm good with approving.

There are conflicts that will need to get addressed

**Review by Millu — APPROVED** [review]
Looks great! 

As called out by @hipsterusername 512 base resolution won't work for SDXL, but HRO is more needed for SD.15

**Review by psychedelicious — CHANGES_REQUESTED** [review]
Thanks for adding the scaling logic. Given w/h are now dynamically calculated based on the output dimensions, there's no need for there to be app state for hrf w/h. 

That state should be removed and the logic put in the graph creation function, as opposed to a useEffect.

(As a side note, if we *did* have separate state for hrf w/h, we wouldn't want to use a useEffect to update it. That logic should be in the reducer.)

I'll aim to do a proper code review when I'm back on the computer in a few days. Sorry for the delay.

**Comment by marict** [comment]
> Resolving to 512 as the base res won't work with SDXL, but I don't think it's as much a concern. If we can commit to getting that updated in a follow-on, I'm good with approving.
> 
> There are conflicts that will need to get addressed

Is the PR author responsible for merging conflicts or is that done by the code owner merging?

**Comment by marict** [comment]
> Thanks for adding the scaling logic. Given w/h are now dynamically calculated based on the output dimensions, there's no need for there to be app state for hrf w/h.
> 
> That state should be removed and the logic put in the graph creation function, as opposed to a useEffect.
> 
> (As a side note, if we _did_ have separate state for hrf w/h, we wouldn't want to use a useEffect to update it. That logic should be in the reducer.)
> 
> I'll aim to do a proper code review when I'm back on the computer in a few days. Sorry for the delay.

Sounds good, moved the calculation out of the state and into the graph building.
Noted about the reducer, still learning Redux.

**Comment by marict** [comment]
> Resolving to 512 as the base res won't work with SDXL, but I don't think it's as much a concern. If we can commit to getting that updated in a follow-on, I'm good with approving.
> 
> There are conflicts that will need to get addressed

Added support for SDXL base res of 1024

**Comment by hipsterusername** [comment]
> > Resolving to 512 as the base res won't work with SDXL, but I don't think it's as much a concern. If we can commit to getting that updated in a follow-on, I'm good with approving.
> > There are conflicts that will need to get addressed
> 
> Is the PR author responsible for merging conflicts or is that done by the code owner merging?

Typically done by the PR author since the code functionality may have changed as a result of the conflict

**Comment by marict** [comment]
Just realized that the "Use All" parameters option isn't transfering the HRF metadata, working on that now!

**Review by psychedelicious — APPROVED** [review]
Thanks @marict !

**Comment by Millu** [comment]
Closes #5054

**Comment by zethfoxster** [comment]
where is this high res fix button even located now? i've looked everywhere in the latest version, has it been removed?

**Pull request merged**
