### PR TITLE
Web UI v2.2

### PR DESCRIPTION
**Pull request by psychedelicious**
Major new feature: outpainting on an infinite canvas

Supersedes:
#1355 (which I broke)
#1415 (included here)

### CODE REVIEW

**Comment by psychedelicious** [comment]
# Web UI v2.2 *DRAFT*

We are ready for review and testing of the Web UI's v2.2 release. 

The main update here is that our Inpainting UI is upgraded and now does Text to Image, Image to Image, Inpainting, and Outpainting, all in one place, on an "infinite" Unified Canvas.

There are a number of smaller updates as well:

- The gallery now generates thumbnail images. It should be way less laggy, especially as you start to make ginormo canvas images.
- There is a quick model switcher drop-down in the site header
- We have a new Green theme!
- A bazillion performance optimizations, bug fixes and UI/UX improvements
- The API surface has changed a bit; image uploads are now handled over HTTP so we don't run into data limits with socketio, and a lot of other small changes to work with outpainting.

## What we need from you

Feedback! Ideally constructive and critical. 

## First run of this PR

You will need to update your virtual environment, and probably will need to Reset Web UI from the app settings. It's possible your InvokeAI UI will to totally nonfunctional after updating; in that case you will need to reset your browser's local storage. 

## And then?

Read on for a run-down of the new canvas. TL;DR: You can outpaint and draw and stuff. 

Even better - try it out first!

## Unified Canvas

Our Inpainting Canvas UI is now upgraded to a Unified Canvas UI and can do Text to Image, Image to Image, Inpainting, and Outpainting - all in one place.

It may not make sense to think of Inpainting and Outpainting as different operations - they are very similar, with a single key difference. Let's briefly go over these two processing modes.

### Inpainting vs Outpainting

**Inpainting** means running Image to Image on some of an image, leaving the rest of the image untouched. To tell the system what parts of the image to change, you draw a mask over the area you want to be processed by Image to Image. This needs image data to be present (i.e. the image cannot be empty/fully transparent under the mask).

**Outpainting** means running Image to Image on a specific region or regions of an initial image *which are empty* (i.e. erased or fully transparent), leaving the rest of the image untouched. This means we need to fill in the empty areas of the image with *something* so that Image to Image has initial image data to work from.

Behind the scenes, we "infill" the empty areas with pixels generated from the existing image data. The infilled area is basically auto-masked; you do not need to draw a mask over the previously-erased-but-now-infilled area.

#### Same Same, But Different

When you have existing image data to work with, you can use that existing image data for Image to Image. Useful if you want to replace part of an existing image and want the result to be fairly close to the original. That's "inpainting".

When you *don't* have existing image data to work with (e.g. it is empty or fully transparent), you need to first infill that area with something before running Image to Image (which we do for you behind the scenes). Useful if you want to extend an image in one direction - or just want something totally new in an erased area. That's "outpainting".

### So, "Unified"?

We mean that you can do all the basic SD stuff from the Canvas:
- Bounding box area is totally empty -> Text to Image
- Bounding box area has no fully transparent regions/pixels -> Image to Image on that area
- Bounding box area has a mix of empty and non-transparent regions -> empty area(s) will be Outpainted (after being infilled)
- Bounding box area has a no fully transparent regions, but does have a mask -> masked area(s) will be Inpainted
- Bounding box area has a mix of empty and non-transparent regions, plus a mask -> masked area(s) will be Inpainted and the empty area(s) Outpainted (after being infilled)

### Using the Canvas

The UI provides you with Base and Mask Layers, along with Brush, Eraser and Move tools. Additionally, images generated on the canvas first go to a Staging Area.

#### Base Layer

Think of the Base Layer like a single layer in Photoshop. When you generate images, they are pasted onto this layer. Erasing on this layer erases the image data.

You can draw on this layer using the brush if you want - useful for simple sketches on top of an existing image to then run Image to Image on or Inpaint. It's only rudimentary and we don't plan to make this a full featured image editor - instead, we provide an easy way to copy the image to paste into a real image editor, do whatever you want, and then paste back into the canvas to continue working.

Erase parts of this layer so they can be Outpainted into. You can erase an area in the middle of the bounding box or on the edge of it - you just need to leave some image data in the box so we have something to generate from.

#### Mask Layer

Think of the Mask Layer as a layer mask in Photoshop. This layer is exclusively for masking operations. It displays on top of the Base Layer with  diagonal line kinda texture. 

Drawing on this layer with the brush adds to the mask, and erasing erases the mask only.

You can enable "Preserve Masked Area" to effectively invert the mask. With this enabled, instead of processing only the area under the mask, the area under the mask is the only area that is *not* processed.

#### Move Tool

The Move tool lets you move the canvas, move the bounding box, and resize the bounding box.

#### Staging Area

When you generate an image or some images, they will display in the canvas Staging Area, with Prev/Next/Hide/Accept/Discard buttons. While in the Staging Area you cannot do anything else on the canvas. 

You need to either Accept on image to lock it in on the canvas, or Discard all images. If you haven't accepted/discarded yet, and generate new images, they will use the same settings as before (or whatever you change them to) and be added to the staging area. We do plan to expand this feature in the future to be a bit more capable. 

#### Misc Canvas Features

- Undo/redo for all canvas actions
- Merge Visible flattens the base layer into a single image, which can be useful if you are working on a *really*, **really** big canvas. We have done a lot of optimization and have had 80+ images blended on the canvas without any issues, so you probably will never need to do this.
- Save to Gallery crops the canvas to its visible bounds and saves it to gallery
- Copy/Paste images from/to the Canvas (note that we have not yet implemented *insert* functionality - paste fully *replaces* the existing canvas)
- Snap to Grid snaps the bounding box to a 64px grid
- Plus more, have a look at the canvas toolbar

**Comment by mickr777** [comment]
Wow cant wait to test, however creating any image gives error

Traceback (most recent call last):
  File "/InvokeAI/backend/invoke_ai_web_server.py", line 660, in generate_images
    actual_generation_mode = generation_parameters["generation_mode"]
KeyError: 'generation_mode'

**Comment by mickr777** [comment]
I see lots of work has gone in to this, so far bugs I have found

- Text at top of webui page:
<<<<<<< refs/remotes/upstream/development <<<<<<< refs/remotes/upstream/development <<<<<<< refs/remotes/upstream/development <<<<<<< refs/remotes/upstream/development <<<<<<< refs/remotes/upstream/development <<<<<<< refs/remotes/upstream/development ======= ======= >>>>>>> Builds fresh bundle ======= >>>>>>> Fixes inpainting + code cleanup >>>>>>> Builds fresh bundle ======= ======= >>>>>>> Outpainting tab loads to empty canvas instead of upload ======= >>>>>>> Fixes wonky canvas layer ordering & compositing >>>>>>> Builds fresh bundle

- inpainting - you cannot resize or move the mask box with mouse
- inpainting - invert mask display doesn't appear to do anything
- inpainting - "AssertionError: >> outputs/000001.b2e51759.3507861853.png: File not found" when pressing invoke image is in output/img-samples but looking for it in output
- outpainting - pressing invoke give the image base64 then : File not found

**Comment by psychedelicious** [comment]
@mickr777 

Sorry, I forgot to push the updated bundle to the PR 😅 whoops!

If you pull again, you should get the updated UI (and none of the issues you mentioned).

**Comment by mickr777** [comment]
> @mickr777
> 
> Sorry, I forgot to push the updated bundle to the PR 😅 whoops!
> 
> If you pull again, you should get the updated UI (and none of the issues you mentioned).

Thank yes that was it, looks great btw

**Comment by mickr777** [comment]
Image info is not available when refreshing the webpage, so image have prompt seed etc are greyed out
image

**Comment by psychedelicious** [comment]
@mickr777 

> - Image info is not available when refreshing the webpage, so image have prompt seed etc greyed out

This is expected for images generated on the canvas, it's not really feasible to save metadata for them bc they can be a bazillion small images melded together... no way to manage that. Or is this on a non-canvas image?

> - also things go a bit strange from image to image strength  0.65 and below and just goes to boxes from 0.55

Yeah so this is the infill method. You need to use a high strength if you are outpainting. Like .9 seems to be best. We'll have a guide on release.

**Comment by mickr777** [comment]
> This is expected for images generated on the canvas, it's not really feasible to save metadata for them bc they can be a bazillion small images melded together... no way to manage that. Or is this on a non-canvas image?
>

This was a non canvas image, just created with txt2inage, it all accessable till web browser is refreshed

**Comment by psychedelicious** [comment]
@mickr777 

Fixed that metadata bug, thanks for catching it. Also added the dream-style prompt to metadata, plus a few other additions and fixes.

**Comment by mickr777** [comment]
Looks good metadata working fine now, just a few things:

- Copy dream prompt or json, I assume are meant to copy them to the clipboard? as doesn't copy anything
- not sure it this is intentional, but upscaling, face restore doesn't copy metadata to new image

Edit this one may be related to this - #1527 
- face restore and upscale on image without metadata causes "Server error: 'NoneType' object is not subscriptable"

**Comment by psychedelicious** [comment]
@mickr777 
> Copy dream prompt or json, I assume are meant to copy them to the clipboard? as doesn't copy anything

Maybe your browser disallowed access to clipboard? This works fine for me

> not sure if it is intentional, but upscaling, face restore doesn't copy metadata to new image

Fixed, the metadata was on the image but not passed tot he UI correctly when the face restore/upscale completed.

> face restore and upscale on image without metadata causes "Server error: 'NoneType' object is not subscriptable"

Hmm... Cannot recreate this one either

**Comment by mickr777** [comment]
@psychedelicious 
face restore and upscale on image without metadata causes "Server error: 'NoneType' object is not subscriptable"
Seems to be working now for me too

>> Copy dream prompt or json, I assume are meant to copy them to the clipboard? as doesn't copy anything`
> 
> Maybe your browser disallowed access to clipboard? This works fine for me

Might be my install, I have tried on edge/chrome on windows, Firefox on ubuntu and chrome on android

**Review by blessedcoolant — APPROVED** [review]

**Comment by blessedcoolant** [comment]
@lstein This is good to go. Entire 2.2 WebUI.

**Review by Kyle0654 — APPROVED** [review]
Python looks good to me.

**Review by hipsterusername — APPROVED** [review]

**Pull request merged**
