### PR TITLE
Update communityNodes.md

### PR DESCRIPTION
**Pull request by skunkworxdark**
Adding Prompt Tools and XY grid nodes

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [x] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [ ] Yes
- [x] No, because:

      
## Have you updated all relevant documentation?
- [x] Yes
- [ ] No

## Description
 Adding my custom  Prompt Tool and image to grid nodes

## Related Tickets & Documents

- Related Issue #
- Closes #

## Added/updated tests?

- [ ] Yes
- [ ] No : _please replace this line with details on why tests
      have not been included_

### CODE REVIEW

**Comment by Millu** [comment]
@psychedelicious thoughts on including these as core nodes vs Community Nodes?

**Comment by skunkworxdark** [comment]
I am happy for any of my nodes to be added to core or changed to fit a particular style or naming convention.  If I can do anything to help just let me know. 
 
There are two new nodes just added to my Prompt Tools nodes package.  But I am unsure how to update an already started PR.

8. PromptStrength - This take a string and float and outputs another string in the format of (string)strength like the weighted format of compel. 
9. PromptStrengthCombine - This takes a collection of prompt strength strings and outputs a string in the .and() or .blend() format that can be fed into a proper prompt node.

**Comment by skunkworxdark** [comment]
Worked out how to update it :)

**Review by Millu — APPROVED** [review]
Let's get this in!

**Pull request merged**
