### PR TITLE
Add mask argument to server and fix undefined error in js

### PR DESCRIPTION
**Pull request by nielo**
Added the initmask argument for use in a gimp plugin I'm working on and came across an undefined error in the js

### CODE REVIEW

**Comment by lstein** [comment]
Is this for the web server on the main branch? The web server there is being retired and replaced by a completely new one imminently. Please have a look at the new GUI - it's quite good. To get it, checkout the branch named `release-candidate-2`

I appreciate the work you put into finding and fixing this problem.

**Comment by nielo** [comment]
I would like to attempt adding the mask feature if I can.

As mentioned I am developing a Gimp 3 plugin using your project as a
back-end and the masking feature is a requirement.

Any advice on how to go about assisting in implementing the masking feature
would be greatly appreciated, thanks!

**Comment by nielo** [comment]
Hi, sorry, after just starting my investigation it looks like that feature
is already there, thanks.

**Comment by nielo** [comment]
Hi Lincoln,

I've been playing around with the socket communication, but it would bloat
the plugin requirements significantly.

I was wondering if the legacy web interface couldn't be promoted to an API
interface, as the only thing I was really still trying to get working in
the gimp plugin was a combo box.

Kind regards,
Nielo

**Pull request closed without merging**
