### PR TITLE
fix .swap() by reverting improperly merged @classmethod change

### PR DESCRIPTION
**Pull request by damian0815**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

brings back `.swap()` (will not work with inpainting, sequential guidance, or xformers. untested with SDXL)

### CODE REVIEW

**Review by JPPhoto — APPROVED** [review]
Tested with 1.5 models, works again!

**Comment by keturn** [comment]
## SD 1.x results

**Prompt:** `("a cat in the forest", "a fantasy forest").and() `
**Result:** ❌ operation completes without error, but only "a cat in the forest" is logged and the result looks equivalent to that part alone; the second term "a fantasy forest" seemingly having no impact at all.

**Prompt:** `silhouette of a dancing (Elvis).swap(frog)`
**Result:** ✅ behaving appropriately. Both terms logged, output is as expected.

**Prompt:** `(pineapple, cogwheel).blend()`
**Result:** ✅ behaving appropriately. Both terms logged, output is as expected (probably? I should have picked a blend I had a prior result for.)

## SD 2.x results

Same as SD 1.x.

**Comment by keturn** [comment]
## SDXL results
Exceptions all the way. Is that in scope here or should we consider it separately?

**Comment by damian0815** [comment]
thanks @keturn.

`.and()` support is being looked at by @StAlKeR7779 (there's not PR), so it's a known issue that that doesn't work.

i don't know what SDXL support should look like. i cannot run SDXL on my machine which makes me a poor candidate for looking into it.

**Comment by psychedelicious** [comment]
Merging as the missing pieces (`.and()` and SDXL) are both known WIP items.

**Pull request merged**
