### PR TITLE
Generalize facetool strength argument

### PR DESCRIPTION
**Pull request by db3000**
Take strength for face restoration in the `facetool_strength` parameter everywhere, instead of `gfpgan_strength`. This makes usage of non-GFPGAN face restoration much more straightforward, it never made sense to me that I had to pass `--ft codeformer --gfpgan_strength 0.5` to run CodeFormer. The change also makes it easier to add more face restoration algorithms and to expose CodeFormer in the web UI.

Mostly just a search and replace, but I left support in for `--gfpgan_strength` as well on the command line and when loading metadata for backwards compatibility.

### CODE REVIEW

**Comment by blessedcoolant** [comment]
I see the parameter name change but is there any functional change made? Because right now it works exactly like that. the gfpgan_strength is basically a face restoration trigger that works with both gfpgan and codeformer. We just didn't rename it when we added codeformer. The changes seem to be just that. Or am I missing something else here?

**Comment by db3000** [comment]
> If it's just the rename, then I'll test everything works in order and approve it.

It's just the rename for now, which improves clarity in the invoke command line UI. I was thinking to use it to add support for CodeFormer in the web UI in a later PR.

**Comment by blessedcoolant** [comment]
Okay. Seems good. Please rebase to match the latest changes on dev. Approving this.

@lstein Please do a quick check once before you merge.

**Review by blessedcoolant — APPROVED** [review]

**Comment by db3000** [comment]
Rebased then rebuilt frontend using `npm run build`.

**Review by lstein — APPROVED** [review]
Looks fine. I'll merge.

**Pull request merged**
