### PR TITLE
feat: organise services

### PR DESCRIPTION
**Pull request by psychedelicious**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Description

[feat(backend): organise service dependencies](https://github.com/invoke-ai/InvokeAI/commit/81a6c0a1000ba6c2ebdb8c0a05e252e8115b0d3f)

**Service Dependencies**

Services that depend on other services now access those services via the `Invoker` object. This object is provided to the service as a kwarg to its `start()` method.

Until now, most services did not utilize this feature, and several services required their dependencies to be initialized and passed in on init.

Additionally, _all_ services are now registered as invocation services - including the low-level services. This obviates issues with inter-dependent services we would otherwise experience as we add workflow storage.

**Database Access**

Previously, we were passing in a separate sqlite connection and corresponding lock as args to services in their init. A good amount of posturing was done in each service that uses the db.

These objects, along with the sqlite startup and cleanup logic, is now abstracted into a simple `SqliteDatabase` class. This creates the shared connection and lock objects, enables foreign keys, and provides a `clean()` method to do startup db maintenance.

This is not a service as it's only used by sqlite services.

[feat(backend): move pagination models to own file](https://github.com/invoke-ai/InvokeAI/commit/136c43a56266c0989a16cfb946a74c60e3582591)

[feat(backend): rename db.py to sqlite.py](https://github.com/invoke-ai/InvokeAI/commit/03a9d85dd48ae252afc6a86e447de97cfba0b8b4)

[feat: refactor services folder/module structure](https://github.com/invoke-ai/InvokeAI/commit/b8b302ebc1a6a726f42c5a028eb61a7b61876292)

Refactor services folder/module structure.

**Motivation**

While working on our services I've repeatedly encountered circular imports and a general lack of clarity regarding where to put things. The structure introduced goes a long way towards resolving those issues, setting us up for a clean structure going forward.

**Services**

Services are now in their own folder with a few files:

- `services/{service_name}/__init__.py`: init as needed, mostly empty now
- `services/{service_name}/{service_name}_base.py`: the base class for the service
- `services/{service_name}/{service_name}_{impl_type}.py`: the default concrete implementation of the service - typically one of `sqlite`, `default`, or `memory`
- `services/{service_name}/{service_name}_common.py`: any common items - models, exceptions, utilities, etc

Though it's a bit verbose to have the service name both as the folder name and the prefix for files, I found it is _extremely_ confusing to have all of the base classes just be named `base.py`. So, at the cost of some verbosity when importing things, I've included the service name in the filename.

There are some minor logic changes. For example, in `InvocationProcessor`, instead of assigning the model manager service to a variable to be used later in the file, the service is used directly via the `Invoker`.

**Shared**

Things that are used across disparate services are in `services/shared/`:

- `default_graphs.py`: previously in `services/`
- `graphs.py`: previously in `services/`
- `paginatation`: generic pagination models used in a few services
- `sqlite`: the `SqliteDatabase` class, other sqlite-specific things

## QA Instructions, Screenshots, Recordings

Run the app. Everything should work.

Because the majority of changes are changing file structure, you'd get errors on startup if something was wrong.

The bits that involve logic changes would also cause the app to fail if they weren't done correctly.

## Added/updated tests?

- [x] Yes
- [ ] No : _please replace this line with details on why tests
      have not been included_

### CODE REVIEW

**Review by maryhipp — APPROVED** [review]
I skimmed the changes and ran it locally - LGTM!

**Review by ebr — APPROVED** [review]
Tested - LGTM!

**Comment by psychedelicious** [comment]
We will hold off on merging this until the next release (early next week)

**Review by lstein — APPROVED** [review]
The reorganization is much more sensible! LGTM.

**Review by brandonrising — APPROVED** [review]

**Pull request merged**
