### PR TITLE
Allow bfloat16 to be configurable in invoke.yaml

### PR DESCRIPTION
**Pull request by Millu**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [ ] Yes
- [X] No, because: simple change

      
## Have you updated all relevant documentation?
- [ ] Yes
- [X] No

## Description
Allow bfloat16 to be configured in invoke.yaml

Need help testing as I cannot on my machine. 

## QA Instructions, Screenshots, Recordings
Set `precision: bfloat16` and test generations. Then set `precision: auto` and test generations. 

## Merge Plan
Can be merged once tested.

## Added/updated tests?

- [ ] Yes
- [X] No : _please replace this line with details on why tests
      have not been included_

## [optional] Are there any post deployment tasks we need to perform?
N/A

### CODE REVIEW

**Review by psychedelicious — APPROVED** [review]
LGTM

**Comment by Millu** [comment]
@lstein would love your eyes on this one before we merge

**Review by psychedelicious — CHANGES_REQUESTED** [review]
Actually, this doesn't work.

**Comment by Millu** [comment]
🤦‍♂️ thanks @psychedelicious!

**Comment by lstein** [comment]
I'll look through this as soon as I can. Two grant applications are due tomorrow, and I can't miss the deadlines. Probably can do tomorrow after submission.

**Review by hipsterusername — APPROVED** [review]

**Pull request merged**
