### PR TITLE
Update communityNodes.md with Stereogram nodes

### PR DESCRIPTION
**Pull request by simonfuhrmann**
## Summary

Adds a community node to the InvokeAI documentation.

### CODE REVIEW

**Review by hipsterusername — APPROVED** [review]
Very cool nodes - Good add!

**Comment by simonfuhrmann** [comment]
Is there anything required from my end to move this forward?

**Comment by hipsterusername** [comment]
Nope - Just requires me to push the right sequence of buttons, sacrifice the right chickens, etc.

**Comment by hipsterusername** [comment]
Will have to forgive us - Has been a hectic few weeks with the installer, and I’m increasingly reliant on notifications. If you’d like to reopen PR, I’d be happy to get it through.

**Comment by simonfuhrmann** [comment]
Oh haha, I didn't even realize this was still open. I will create a new PR with this.

**Comment by simonfuhrmann** [comment]
https://github.com/invoke-ai/InvokeAI/pull/7493

**Pull request closed without merging**
