### PR TITLE
refactor(events): use pydantic schemas for events 

### LINKED ISSUE #5459: [enhancement]: Use pydantic models for events
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

_No response_

### What should this feature add?

[fastapi-events](https://github.com/melvinkcx/fastapi-events) has some nice pydantic integration and it just leveled up. You can now dispatch pydantic models directly. We should use this as it is very ergonomic and clear approach.

### Alternatives

_No response_

### Additional Content

_No response_

### LINKED ISSUE #6442: [enhancement]: Simplify session events
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

_No response_

### What should this feature add?

While working on #5748, I noticed that we have some holdovers from the days early days when we have multiple processors and before the session queue. 

In short, we have some events that bounce around between the processor and queue to cancel or complete a session.

At best, it's confusing, but at worst, it creates race conditions.

For example, I've invoked 3 generations. Here are the socket events, filtered to show session events only:
image

Looks fine. But if we look at queue item status events, things are out of order:
image

This occurs because we complete a queue item by emitting an event saying its session is complete, then handle that event in the queue and complete the queue item. By the time that event is handled, the next item has already been dequeued, causing the out-of-order events.

The session queue should have an explicit `complete_queue_item` method, alongside the `cancel_queue_item` and `fail_queue_item`. 

There's similar wonkiness when a queue item is canceled. The queue gets this event, then emits a queue item status changed event _and_ session canceled event. It's the session canceled event that the processor handles.

Maybe we should remove the session-scoped events altogether - they are essentially a holdover from before we had queue items. 

### Alternatives

_No response_

### Additional Content

_No response_

### PR DESCRIPTION
**Pull request by psychedelicious**
## What type of PR is this? (check all applicable)

- [x] Refactor

## Have you discussed this change with the InvokeAI team?
- [ ] Yes
- [x] No, because: Nerd sniped myself

## Description

[refactor(events): use pydantic schemas for events](https://github.com/invoke-ai/InvokeAI/pull/5748/commits/262b97a06825d599894ab478a2ab54490f7da621)

Our events handling and implementation has a couple pain points:
- Adding or removing data from event payloads requires changes wherever the events are dispatched from.
- We have no type safety for events and need to rely on string matching and dict access when interacting with events.
- Frontend types for socket events must be manually typed. This has caused several bugs.

`fastapi-events` has a neat feature where you can create a pydantic model as an event payload, give it an `__event_name__` attr, and then dispatch the model directly.

This allows us to eliminate a layer of indirection and some unpleasant complexity:
- Event handler callbacks get type hints for their event payloads, and can use `isinstance` on them if needed.
- Event payload construction is now the responsibility of the event itself (a pydantic model), not the service. Every event model has a `build` class method, encapsulating this logic. The build methods are provided as few args as possible. For example, `InvocationStartedEvent.build()` gets the invocation instance and queue item, and can choose the data it wants to include in the event payload.
- Frontend event types may be autogenerated from the OpenAPI schema. We use the payload registry feature of `fastapi-events` to collect all payload models into one place, making it trivial to keep our schema and frontend types in sync.

Note: Over half the lines in this PR are from the new autogenerated types. This PR is otherwise a net reduction in LOC.

## Related Tickets & Documents

- Closes #5459
- Closes #6442

## QA Instructions, Screenshots, Recordings

Give the app a spin. Things that use events:
- Graph execution (session- and invocation-scoped events)
- Enqueuing
- Clearing the queue
- Model loading
- Model download and install
- Bulk downloads

## Merge Plan

This PR can be merged when approved

## Added/updated tests?

- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by psychedelicious** [comment]
I've updated this PR against current `main` and tested it.

**Review by hipsterusername — APPROVED** [review]

**Comment by psychedelicious** [comment]
I've updated this PR.
- Resolved conflicts
- Fixed all type issues
- Reviewed and updated `model_install_common.py`. This file is new to this PR, and its contents were cut and pasted from `model_install_base.py`. There was a change in `model_install_base.py` that needed to be copied over.
- Smoke-tested the app

**Review by maryhipp — APPROVED** [review]
Looks good. Lets wait to merge until we are confident with the most recent changes.

**Comment by psychedelicious** [comment]
Converted to draft to prevent premature merge

**Comment by psychedelicious** [comment]
This PR is updated and smoke-tested.

**Comment by psychedelicious** [comment]
While working on this PR, I noticed a race condition and general wonkiness with how the queue and processor communicate. It's possible this is causing occasional user-facing queue weirdness. I created #6442 to improve this.

**Comment by psychedelicious** [comment]
I've updated this PR to resolve the issues described in #6442.

Closes #6442

**Pull request merged**
