### PR TITLE
feat: model events

### PR DESCRIPTION
**Pull request by psychedelicious**
[feat(nodes): emit model loading events](https://github.com/invoke-ai/InvokeAI/commit/7b6159f8d65a3876ef7ecc8e8a31dacf9a50d213)

- remove dependency on having access to a `node` during emits, would need a bit of additional args passed through the system and I don't think its necessary at this point. this also allowed us to drop an extraneous fetching/parsing of the session from db.
- provide the invocation context to all `get_model()` calls, so the events are able to be emitted
- test all model loading events in the app and confirm socket events are received

[feat(ui): add listeners for model load events](https://github.com/invoke-ai/InvokeAI/commit/c487166d9ca0b868ee39125a53e010aa62ed7777)

- currently only exposed as DEBUG-level logs

---

One change I missed in the commit messages is the `ModelInfo` class is not serializable, so I split out the pieces of information we didn't already have (hash, location, precision) and added them to the event payload directly.

### CODE REVIEW

**Comment by psychedelicious** [comment]
Once we decide how to expose these events to the user I'll add them. There's the little status indicator dot at top right that shows status text on hover.

One idea is to set a timer on any of the "started" type events, then if it's been 3 seconds and no further events received, force-show that little status text until the next event is received.

**Review by lstein — APPROVED** [review]
Code looks good and running is not generating any errors. Where do the model loading log messages get sent to? I don't see them in either the browser nor the command-line consoles?

**Comment by psychedelicious** [comment]
Logs to the browser console, you'd need to rebuild the ui to see the messages

**Comment by lstein** [comment]
> Logs to the browser console, you'd need to rebuild the ui to see the messages

`yarn dev` should be sufficient, shouldn't it? Im still not seeing the model load events in the browser console.

**Comment by psychedelicious** [comment]
@lstein 
Ahh, I missed about half of the `get_model()` calls, specifically compel & inpaint.

Fixed that and made the socket event timestamps display millisecond precision. You should see something like this in the browser console (I've filtered the log with "model load"):
image

**Review by blessedcoolant — APPROVED** [review]

**Pull request merged**
