### PR TITLE
feat(mm): hide missing models from API response

### LINKED ISSUE #6117: [bug]: Model database remains stale
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 4090

### GPU VRAM

24GB

### Version number

main

### Browser

Chrome / Firefox

### Python dependencies

_No response_

### What happened

When a user moves model files to another folder, the model database continues to remain stale.

Here's the example scenario:

1. Let's say I add a bunch of LoRA's in a folder `C:/models/loras` which has a bunch of `safetensors` files.
2. I boot up Invoke and the client recognizes these new models and registers them to the database and the client.
3. Now let's say I do some local file management and now instead moved these LoRA's to `C:/models/loras/styles`
4. When I boot up Invoke next, the `ModelInstallerService` as expected, reports that the LoRA's registered are now missing from their location.

Here's where the problems begin:

5. The Model Manager UI does not reflect these missing models in anyway. So it is not possible to tell at a glance from the UI which of the models files are not there. This needs to be referred to from the console. The Model Manager should mark this.
6. There doesn't seem to be a way from the Model Manager UI to update these paths to a new path. So it basically becomes a dead entry.
7. If you notice, the new path of these LoRA files are also in the same folder hierarchy where they should be recognized automatically by Invoke. But they do not register the new paths because the files share the same names as those existing in the database already. If the file names are same, then maybe we should update these paths automatically? This could be a problem for Diffusers sub models which have the same names but should not be an issue for checkpoint paths maybe? Because Diffusers are detected by the folder name in most cases.

### What you expected to happen

- The Model Manager UI should visually indicate the missing model files somehow
- The Model Manager UI should have an option to update these paths either manually or automatically.
- The ModelInstallerService should probably override the database entry with the new path if the model with the same name is detected under the same folder hierarchy.

### How to reproduce the problem

_No response_

### Additional context

_No response_

### Discord username

_No response_

### PR DESCRIPTION
**Pull request by psychedelicious**
## Summary

Check if the model file exists. If not, omit it from the list of models.

## Related Issues / Discussions

Closes #6117

## QA Instructions

Delete/rename/move an installed model. Refresh the UI and it should not appear in the list of models.

## Merge Plan

n/a

## Checklist

- [x] _The PR has a short but descriptive title, suitable for a changelog_
- [ ] _Tests added / updated (if applicable)_ n/a
- [ ] _Documentation added / updated (if applicable)_ n/a

### CODE REVIEW

**Comment by hipsterusername** [comment]
Does this really solve the problem? 

How does a user fix the missing model? Re-add?

**Comment by blessedcoolant** [comment]
Not a solution imo. Coz if they no longer show up in the list, then the user cannot even remove the models from the database for them to be detected fresh.

They need to show up and ideally be also marked as not found. So the user at least knows to delete the entries and let the auto importer do its job next boot. Even better, providing a route to update the path from the UI itself.

**Comment by psychedelicious** [comment]
I don't support this change (or any change related to the "missing models" edge case). We should never end up with models missing unless the user sticks their fingers in the pie. We can't both fully manage the model files _and_ let users manage them.

There is no auto importer. We cannot remove missing models automatically anyways. For example if you disconnect your external drive, all your models are now missing and they get removed.

Tbh the current behaviour makes the most sense to me - fail loudly when a model is missing and log a warning in the terminal on startup. 

In response to the issue vic made, I started looking into what would be involved with indicating/handling throughout the app when a models file are missing and it's a lot of work with fiddly UI.

This PR was a 5 min change, I don't think we should spend more time on this edge case

**Review by maryhipp — APPROVED** [review]

**Comment by psychedelicious** [comment]
marking draft pending more discussion, good points raised

**Comment by lstein** [comment]
Mistakes happen and some users will end up with a model config in the database but missing model files. The system will complain at startup. What is the user to do to remedy the problem? 

I would suggest either: 1) adding a UI button "Remove orphan models" or 2) a "Remove orphan models" command line script (accessible through the launcher), which removes the dangling model configs.

**Comment by psychedelicious** [comment]
I like @lstein's suggestion. Closing this in favor of implementing it like that.

**Pull request closed without merging**
