### PR TITLE
Improve visibility into Model Cache memory issues

### PR DESCRIPTION
**Pull request by RyanJDick**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [ ] Yes
- [x] No, because:

      
## Have you updated all relevant documentation?
- [x] Yes
- [ ] No

## Description

This PR adds logging to expose issues in self-reported model sizes in the model cache.

I'm going to leave this as a draft for now until we address some of the issues. I'm afraid it would be too noisy right now. 

## Added/updated tests?

- [ ] Yes
- [x] No : _please replace this line with details on why tests
      have not been included_

### CODE REVIEW

**Comment by lstein** [comment]
From your code, there actually seem to be two problems. The first is that the model predicted size, which is calculated by reading the model metadata, doesn't match its size in RAM. How often does this happen, and do you understand the cause?

The second is that the model is changing size in RAM after loading. I don't understand why this should be. Are they growing because of LoRA or Controlnet patches? They are supposed to be unpatched when generation completes, which should free up the memory again.

We could fix the second problem by traversing the RAM cache's contents each time a new model needs to be loaded, and calculating the size of the whole thing. We don't actually need to have each model track how much memory it needs if we don't mind the overhead of traversing the whole data structure each time.

The first problem will need some work to understand why the disk-based prediction is unreliable.

**Comment by RyanJDick** [comment]
> From your code, there actually seem to be two problems. The first is that the model predicted size, which is calculated by reading the model metadata, doesn't match its size in RAM. How often does this happen, and do you understand the cause?

The cause that I've seen is a model that is stored in fp32 on disk and loaded as fp16. In the case of an SDXL UNet, this can cause us to over-report the size by ~5GB.


> The second is that the model is changing size in RAM after loading. I don't understand why this should be. Are they growing because of LoRA or Controlnet patches? They are supposed to be unpatched when generation completes, which should free up the memory again.

One cause is a VAE being initially loaded in fp16 and later converted to fp32, doubling its size.

I've also noticed LoRAs growing after initial load, but haven't investigated what's causing that yet.

I haven't tested ControlNets or TIs yet.

> We could fix the second problem by traversing the RAM cache's contents each time a new model needs to be loaded, and calculating the size of the whole thing. We don't actually need to have each model track how much memory it needs if we don't mind the overhead of traversing the whole data structure each time.

I like this option if it's not too slow.

**Comment by lstein** [comment]
@RyanJDick I've pushed in a disk-based stash of model sizes that may help with the size change issues you've identiifed. The logic is as follows:

1) Before load, the inaccurate disk-based file size estimation runs. (I am working on a fast way to determine whether the model is fp16 or fp32, but this is not implemented yet.)
2) After load, the precise model size is calculated and written to a stash file.
3) The cached size is also updated each time the model is requested from memory, handling the case of the model growing or shrinking after use.
4) The next time the model needs to be loaded from disk, the updated size is read from the stash file, making the predicted size more accurate.

**Review by lstein — APPROVED** [review]
Great detective work. Hopefully the workarounds I made will mitigate the issues somewhat.

**Comment by lstein** [comment]
This has been in draft form for a long time. Is it still being worked on?

**Comment by RyanJDick** [comment]
My apologies, the priority of this dropped after the fixes in https://github.com/invoke-ai/InvokeAI/pull/4784 . I'm going to cancel for now. May re-open if this climbs higher up my priority list.

**Pull request closed without merging**
