### PR TITLE
Mkdocs updates

### PR DESCRIPTION
**Pull request by mauwii**
- separate toc by disabling the toc.integrate feature (just [take a look](https://mauwii.github.io/stable-diffusion/) how much this improves the navigation 🙈)
- remove protobuf from brew install (corresponding to #596 )
- change printWidth for markdown files to 80, since this is the default setting and it also helps a lot when looking at a a split diff 🤓
- fixed many markdown violations in mac_install.md
- added codeblock anotations : 
image
- shorten lines with long commands - this way it looks much better in MkDocs Codeblocks (and ofc still works)

### CODE REVIEW

**Comment by mauwii** [comment]
@lstein: some hours ago the question came up when you are going to activate gh-pages (by @Any-Winter-4079 and @tildebyte), so I don't want to hurry you in any way, but I wanted to ask if I should leave this a draft PR until you will do the next release and publish gh-pages (since I am sure I will do some more changes / updates), or if it would be better to just merge them as soon as I do a PR?

**Comment by tildebyte** [comment]
@mauwii; I'm not familiar with `!!! note` in Markdown - what's it for?

**Comment by mauwii** [comment]
@tildebyte it is not common markdown language, but mkdocs-material:

image

**Review by lstein — APPROVED** [review]
Thank you. Looks nice!

**Pull request merged**
