### PR TITLE
Update prompt on connected viewers during invoke

### PR DESCRIPTION
**Pull request by gfosco**
When there are multiple viewers, it would be nice to update the prompt being used to generate images.

If this is acceptable I can add the yarn built assets, felt it was best to provide a clean push of the changes first.

### CODE REVIEW

**Comment by Kyle0654** [comment]
I don't imagine this would be desired behavior in some cases (e.g. I want to have two people on my network generating different things). Maybe make this an option at startup? Something like `--collaborative`?

**Comment by gfosco** [comment]
Ok, sounds good, will gate it behind a startup flag.

**Comment by Kyle0654** [comment]
You might check out the `development-invoke` branch or write an issue for it as well. We're going to move to a node-based backend at some point, which has different API/events. I think this might be possible there as well (and in a more powerful way), but will need a lot of events added to enable collaboration on a node graph.

**Comment by gfosco** [comment]
Gated it behind `--collaborative` and tested with/without successfully.

**Comment by gfosco** [comment]
@hipsterusername I suppose I started down this path because I didn't realize multiple people could use it, led down that path since #976 wasn't in there, and that it locks the button when someone generates.  I was just watching my wife generate things and not seeing the prompts.

Will close this, you're absolutely right.. using the gallery to grab the information is sufficient.

**Pull request closed without merging**
