### PR TITLE
Option to directly invert the grayscale heatmap

### PR DESCRIPTION
**Pull request by spezialspezial**
Theoretically less work inverting the image while it's small but I can't measure a significant difference. Though, handy option to have in some cases.

### CODE REVIEW

**Comment by spezialspezial** [comment]
Should read: gs = self.to_grayscale(not invert)

**Review by lstein — APPROVED** [review]
Looks cleaner and probably will come in handy somewhere.

**Comment by lstein** [comment]
Sorry, I had to back the change out. The !mask operation prints out two images with partial transparency showing the selected and deselected areas, and the greyscale fix was interfering with this.

**Comment by spezialspezial** [comment]
Is it because of my initial logic error: self.to_grayscale(invert) instead of the correct self.to_grayscale(not invert)? I fixed the patch but I don't know when you pulled it in.

**Comment by spezialspezial** [comment]
While you're here, is there a reason you decided against the refined model?

**Comment by lstein** [comment]
I pulled in two commits. I'm afraid I'm working on the release and didn't have time to track down what the problem was, but I suspect that you're losing the alpha channel at some point. What you need to do is to get the !mask command working such that you get two partially transparent images as described here on slide 10: https://docs.google.com/presentation/d/1pWoY510hCVjz0M6X9CBbTznZgW2W5BYNKrmZm7B45q8/edit#slide=id.g14e1695382b_0_116

With respect to the refined model, could you remind me?

**Comment by spezialspezial** [comment]
There is a refined model rd64-uni-refined.pth which seems to be slightly nicer. Could be interesting if there is some time after the release.
refined

**Comment by spezialspezial** [comment]
Fixed.

selected
000026 000025 2634654006 hair selected

deselected
000026 000025 2634654006 hair deselected

masked
000026 000025 2634654006 hair masked

**Pull request merged**
