### PR TITLE
[WebUI] Fix 'Use All' Params not Respecting Hi-Res Fix

### PR DESCRIPTION
**Pull request by blhook**
## What was the problem/requirement? (What/Why)
As part of a [change in 2.3.0](https://github.com/invoke-ai/InvokeAI/commit/d74c4009cb671dd69768bfc0c6376a7ea74e358e), the high resolution fix was no longer being applied when 'Use all' was selected. This effectively meant that users had to manually analyze images to ensure that the parameters were set to match. 
~~Additionally, and never actually working, Upscaling and Face Restoration parameters were also not pulling through with the action, causing a similar usability issue.~~

## What was the solution? (How)
This change adds a new reducer to the `postprocessingSlice` file, mimicking the `generationSlice` reducer to assign all parameters appropriate for the post processing options. This reducer assigns:
* Hi-res's toggle button only if the type is `txt2img`, since `img2img` hi-res was removed previously
* ~~Upscaling's toggle button, scale, denoising strength, and upscale strength~~
* ~~Face Restoration's toggle button, type, strength, and fidelity (if present/applicable)~~

### Minor
* Added `endOfLine: 'crlf'` to prettier's config to prevent all files from being checked out on Windows due to difference of line endings (and git not picking up those changes as modifications, causing ghost modified files from Git)

### Revision 2:
* Removed out upscaling and face restoration pulling of parameters

### Out of Scope
* Hi-res strength (applied as img2img strength in the initial image that is generated) is not in the metadata of the final image and can't be reconstructed easily
* Upscaling and face restoration have some peculiarities for multi-post processing outside of the UI, which complicates it enough to scope out of this PR. 

## How were these changes tested?
* `yarn dev` => Server started successfully
* Manual testing on the development server to ensure parameters pulled correctly
* `yarn build` => Success

## Notes
As with `generationSlice`, this code assumes `action.payload.image` is valid and doesn't do a formal check on it to ensure it is valid.

### CODE REVIEW

**Comment by psychedelicious** [comment]
Thanks for the PR!

Not including the postprocessing parameters is intentional. An image may be postprocessed multiple times, and each postprocessing action is stored in the metadata. The UI can only postprocess once. Instead of recalling in a potentially misleading way, we recall only generation parameters. 

As a compromise, in the metadata viewer, there are buttons to recall postprocessing parameters individually.

Updating the hires strength is something we should do.

All that said, we have just begun to migrate to a new execution engine and API, in which metadata handling will be totally revamped. As part of the change, we are freezing the UI (after I finish #2814 ). 

Part of the new engine is that generation and post are represented by graphs. Metadata will likely be the JSON representation of the graph. So this can, in theory, handle arbitrary processing steps.

I think we can accept the hires fix part of this, but maybe it's more respectful of your time to put this PR on hold until we have stabilised and how to integrate it is clear.

**Comment by blhook** [comment]
Interesting. While the metadata changes are expected with the node system, I would have expected the reducers to abstracted out the that enough to where this wouldn't be an issue for migration. 

If we are okay with the hi-res fix, let's scope this PR down to that, as it is something I've felt the pain of missing since its removal every time I boot up. It'd probably save me more time than clinging onto the commit locally and trying to handle the rebases. 

For the other items, I think there could be an argument to recall this information if the post processing only has one of the categories or was generated from the UI and then informing the user if not, but is a much lesser of a concern for me personally.

**Comment by psychedelicious** [comment]
The reducers should be abstract enough, yes. The theming PR doesn't change any of that, and hopefully doesn't change any component level logic. 

---

Let's call the current UI the linear UI. The `parameterTranslation.ts` file should handle formatting internal state into a graph for the linear UI. 

On the node UI (currently theoretical, with a working prototype made some months back), all parameter state is exactly the graph. It will probably be it's own separate slice. 

We will support sending linear UI state to the node UI state but of course that won't work the other way around. 

---

I'll get some contributing guidelines for the feature freeze added. We really need to improve those guidelines (I suppose they are nonexistent currently). We've been operating as a team for a while now and a lot of this is discussed "internally" on discord but its not like we are a closed project!

**Comment by psychedelicious** [comment]
Sorry, I didn't exactly address your message. The redux store may change drastically during migration due to a change in API surface. We want to freeze the UI entirely so we can focus on migration without needing to review PRs against a changing code base, and to not waste the PR contributors' time.

**Comment by blhook** [comment]
To clarify, is the code-base already at the point of not taking new PRs for the Web UI or are PRs still being accepted/reviewed until the [aforementioned PR](https://github.com/invoke-ai/InvokeAI/pull/2814) is pushed? I don't mind closing this if it is already frozen or working to push it through if there is intent to freeze in the near future. I just want to ensure I understand your intent with what the next action is for it is.

**Comment by psychedelicious** [comment]
Happy to accept your changes here, the reduced scope is fine. `v2.3` is the public-facing branch right now, if you want these changes to be released sooner the PR will need to be against that branch. Then we will merge changes from `v2.3` back into main as we freeze.

Else if you don't mind waiting for this PR to make it into a release, please rebase onto main and I'll review/approve. Thanks again for your work!

**Review by lstein — COMMENTED** [review]
@psychedelicious  I think this can go in; it doesn't affect the refactoring. What do you think?

**Comment by blhook** [comment]
As I don't quite trust Git for a base change with how the assets are being handled in this particular repo, I've created a new branch/PR for the pushing into 2.3. I think it makes slightly more sense there, as it solves a bug with (hopefully) little other impact. 
https://github.com/invoke-ai/InvokeAI/pull/2840

Closing out this PR.

**Pull request closed without merging**
