### PR TITLE
hotfix(unified install): last minute changes missing from PR #1506

### PR DESCRIPTION
**Pull request by tildebyte**
Fixes:
- 'requirements.in':
   - add picklescan
   - finally find a good compromise for torch and torchvision pinning for all platforms
- 'invoke.sh: hotfix for MacOS - add `export PYTORCH_ENABLE_MPS_FALLBACK=1`

Late additions:

- invoke scripts:
   - more meaningful messaging
   - 'load_models' **must** run absolutely last
- setup.py: Set "name" field to the *product* (InvokeAI), not the project (invoke-ai)

Signed-off-by: Ben Alkov <ben.alkov@gmail.com>

### CODE REVIEW

**Comment by tildebyte** [comment]
Testing:
- Grab the 'installer/install' .sh|.bat from dev
- Drop it in an EMPTY folder
- Edit the 'install' script according to this diff

```diff
-[RELEASE_URL=https://github.com/invoke-ai/InvokeAI]
-[RELEASE_SOURCEBALL=/archive/refs/heads/main.tar.gz]
+[RELEASE_URL=https://github.com/tildebyte/InvokeAI]
+[RELEASE_SOURCEBALL=/archive/refs/heads/hotfix-unified-installer-last-minute.tar.gz]
```

Run it :)

**Comment by damian0815** [comment]
YESS

**Review by damian0815 — APPROVED** [review]

**Comment by damian0815** [comment]
was able to download, launch, generate, restore faces - all seems good

**Comment by damian0815** [comment]
still looks good

**Review by lstein — APPROVED** [review]

**Pull request merged**
