### PR TITLE
feat: increase random seed space from 32 to 53 bits

### PR DESCRIPTION
**Pull request by dfl**
this should help somewhat to replicate creations from other UIs;  inspired by waffletower's PR #2843

## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [ ] Yes
- [x] No, because: it was already discussed on PR #2843

      
## Have you updated all relevant documentation?
- [ ] Yes
- [x] No (don't think there is any) 

## Description
This is a refactor/feature to increase the random seed to 53 bits (maximum possible integer according to javascript frontend)

## Related Tickets & Documents

- Related Issue PR #2843
- Closes

## QA Instructions, Screenshots, Recordings

n/a

## Added/updated tests?

- [ ] Yes
- [x] No : only a change in parameters, not essential code

## [optional] Are there any post deployment tasks we need to perform?
no

### CODE REVIEW

**Comment by lstein** [comment]
Is it confirmed that expanding the seed space actually does help reproduce images generated on other platforms? There are so many other variables that affect generations that I'm curious.

**Comment by dfl** [comment]
@lstein short answer, no. But it’s part of the picture. You’re right, the pipeline weighting/parsing is also a big piece of the pie. Conversely, is there a good reason for limiting the seed space?

**Comment by psychedelicious** [comment]
@dfl We've approached seed space a few times and I have some hazy memory of reading about how numpy does some modulus of seeds over the limit... Is that something we should concern ourselves with?

**Comment by dfl** [comment]
hmm, seed is uint32 here so if that’s what is being used then you are correct it is 32 bit mod 🙊 https://github.com/numpy/numpy/blob/34d6693b6e763c42ffa09ad050cce7f429e15ec0/numpy/random/src/mt19937/mt19937.c

**Comment by psychedelicious** [comment]
Hmm, ok. This is a bit beyond me, technically, so I'll just say that if increasing the seed space means the application is more capable, then I'm all for it. 

That said, I think 32 bits is *plenty* for the purposes of seeding RNG, for generation in 2023 at least... uint32 max is over 4 billion, which I submit provides the same degree of variation as infinite seeds - that is to say, 4 billion images is approximately 4 billion more images than any individual will ever generate.

**Comment by dfl** [comment]
on further investigation, it looks like numpy [defaults to PCG64](https://numpy.org/doc/stable/reference/random/generator.html) (not 32-bit mt19937 Mersenne Twister). This is further supported by the fact that [pytorch uses 64-bit seeds]( https://pytorch.org/docs/stable/generated/torch.manual_seed.html), so perhaps it is making the application more capable.

However one thing I am unclear about is the flipping of bits for conditioning_data (c.f. 6eddbd58). Unfortunately I don't understand the pipeline enough to know what this is doing and why. It seems it should be a 64-bit flip with a 64-bit seed, but I found that breaks backwards-compatibility/reproducibility with images previously generated by InvokeAI.
One solution to this could be to have a user-configuration variable for this bitmask. Perhaps a less messy way could be to dynamically create a bitmask that ignoring leading zeros in the seed.

**Comment by Millu** [comment]
Catching up here - @dfl given this would break backwards compatibility and does not guarantee reproducibility with other UIs, I'm a little hesitant about it. 

Do we see any other major use cases for it?

**Comment by Millu** [comment]
@dfl thank you for efforts on this! 

Going to go ahead and close this for now - can revisit if increased random seed space is still required in the future.

**Pull request closed without merging**
