### PR TITLE
feat: core metadata & graph in viewer

### PR DESCRIPTION
**Pull request by psychedelicious**
# Core Metadata Parameters

Previously we used a convoluted graph traversal to pick out the relevant bits of metadata for an image. While objectively very cool, it was a bad idea.

## Metadata Accumulation

A `MetadataAccumulator` node is added to handle metadata for the linear UI. It has fields for the core metadata parameters and its output is a `CoreMetadata` object. During graph creation for the linear UI, this node is added and populated.

`LatentsToImage` optionally accepts a `CoreMetadata` object in its `core_metadata` input. If the object is present, it is saved to db and the image file.

## Saving `CoreMetadata`

When the image is created using the `images` service, if there is a `CoreMetadata` object, it is stringified and stored in the `metadata` column of the `images` table. It is also written to the PNG info field under `metadata`. 

❗ Should we put both of these under more unique fields?

## Saving the Graph

Additionally, during saving, the image's parent `session` is retrieved from the db using a new `ItemStorage` method `get_raw()`. This gets the item (in this case, the `session`) without serializing it - just gets it as stringified JSON.

The `session` is loaded into a dict, the `graph` property extracted, and the `MetadataAccumulator` node and its edges are removed from the graph. Then this graph is stringified again before being written to the PNG info as `graph`.

## Retrieving `ImageDTO`s

The `ImageDTO` object no longer includes the `metadata` column. The route to retrieve it is now `GET images/{image_name}`.

## Retrieving metadata

The previous route for the DTO, `GET images/{image_name}/metadata`, now returns both the `CoreMetadata` and `Graph`. 

`CoreMetadata` is read from the `metadata` column and loaded to `dict`. It is not parsed by pydantic.

The graph is retrieved same as earlier - `get_raw()` the session, extract `graph` and purge refs to `MetadataAccumulator`.

## Recalling Graphs (TODO)

Now that the unexpanded graph is directly accessible in the UI, we can recall it.

### Recall the Graph into Linear UI

We can do this, but need to handle fail cases related to potentially transient resources like models, embeddings and init/control images. 

This will replace the current "recall all parameters" functionality.

### Recall the Graph into Node Editor

We will provide two options:
- Recall as template: "structurally" loads the nodes and edges; i.e. parameters would just use defaults
- Recall with data: attempts to fully recreate the graph in the node editor

We will need to work out an auto-placement algorithm for graph recall.

❗ I propose graph sharing be done primarily via images, but a JSON export is also useful. This would follow the same pattern as above. Recalling these would then use the same code as above too.
- "Save as template"
- "Save with data"

## Importing images (TODO)

Dropping an image on the UI currently uploads it. With the graphs now stored in the image, we can provide the functionality described above for images generated on other invoke installs. So on drop, you could upload or recall the graph.

### Uploaded images

Uploading an image currently strips out the PNG info. 

There are a couple options if we don't like this behaviour:
- Preserve the PNG info exactly as it is on the uploaded image
- Preserve only `metadata` and `graph` (if they exist)
- Parse `metadata` and `graph`

If we preserve some or all of info, do we also write it to the database? No, I'm vetoing this right now.

I also don't think it is a good idea to preserve the PNG info in the file. When I upload an image to a service, I expect only the pixel data to remain. This is a local application, but since we are truly *ingesting* the image - not just organizing it - I don't think we should preserve PNG info.

❗ Do we preserve PNG info on the file? 

### Reading PNG info in the browser

There are pure JS libraries to extract PNG iTXT chunks (where the info is stored) from PNGs. I have tested one successfully. 

While parsing binary PNG data in the browser gives me the heebie-jeebies, I think this is the best approach for accessing metadata from external images. Keep the DB out of the picture.

## Thanks

Thanks for attending my ~~TED~~ NODE talk.

### CODE REVIEW

**Comment by psychedelicious** [comment]
https://github.com/invoke-ai/InvokeAI/assets/4822129/fcbb25c1-d118-455c-86d9-23d93b0293e8

MVP UI

**Comment by psychedelicious** [comment]
This is ready for a review, with a couple TODO/Discussion items.

**Recall Functionality changes**
1. The current image buttons to recall `prompt`, `seed`, and `all` do not work. They do not have access to the metadata object because:
- Metadata is no longer retrieved in the DTO
- The metadata query is only initiated when the `ImageMetadataViewer` component is mounted

I've *not* moved the metadata query higher up so the current image buttons have access to it so that when you scroll through images, it's not constantly requesting metadata. We could try it out, but every time you view an image it will make a network request...

2. The image context menu buttons for recall also do not work for the same reason. They will need to be removed, sorry.

These changes are needed because metadata is becoming a larger object and we don't want to send that along with the bazillions of image loads.

**Questions from the PR description**
1. The metadata embedded into the images is currently just under "metadata" and "graph". Probably these should be something else.

2. Graph sharing via images or JSON - this is an active discussion w/ @blessedcoolant but I'm slowly coming around to using the `reactflow` serialization functionality for graph sharing via JSON. We'll also need to support dropping an image, but unless we also pass the `reactflow` state in with the accumulator node, that's not possible (also I really don't like that idea).

3. What do we do for uploaded images' metadata? See the `Importing images` section in the PR description.

**Comment by maryhipp** [comment]
regarding Recall Functionality changes - could we make a network request when a user clicks the recall buttons to get the metadata for that image and use it? I feel like losing those buttons will be a blow

**Comment by psychedelicious** [comment]
@maryhipp just updated that section - we can debounce the metadata query and allow it to be initiated anywhere

**Comment by maryhipp** [comment]
I agree that it may be a good idea to not call the metadata field `metadata`. I know in postgres, for example, that is a reserved column name that I have had to work around. 

I think this all sounds good. I am a bit overwhelmed by the simultaneous conversations around metadata and importing. I know they are tightly coupled so its good that they are being designed together but I do think of them as distinct features.  

Will this be backwards compatible with existing images that have the "old" metadata schema? I'm guessing yes since we are not validating the shape anymore but want to make sure.

**Review by blessedcoolant — APPROVED** [review]

**Comment by psychedelicious** [comment]
[feat(ui): restore recall functionality](https://github.com/invoke-ai/InvokeAI/pull/3728/commits/946125efbeebbd82ec9c34462b1acc87cdb9b696)
[946125e](https://github.com/invoke-ai/InvokeAI/pull/3728/commits/946125efbeebbd82ec9c34462b1acc87cdb9b696)

- Restore recall functionality to `CurrentImageButtons` and `ImageContextMenu`.
- Debounce metadata requests for `ImageMetadataViewer` and `CurrentImageButtons` by 500ms. It's possible to scroll through these really fast, so we want to debounce the network requests.
- `ImageContextMenu` is lazy-mounted so it does not need to be debounced; it makes the metadata request as soon as you click it.
- Move next/prev image selection logic into hook and add the hotkeys for this to `CurrentImageButtons`. The hotkeys now work when metadata viewer is open.

I will follow up with improved loading state during the debounced calls in the future

[feat(app): embed PNG info in invokeai_metadata and invokeai_graph](https://github.com/invoke-ai/InvokeAI/pull/3728/commits/4d936c30c21f538c6f8986fde0ed0c7f18091159)
[4d936c3](https://github.com/invoke-ai/InvokeAI/pull/3728/commits/4d936c30c21f538c6f8986fde0ed0c7f18091159)

Using just `metadata` and `graph` feel a bit too generic.

@maryhipp 

The old metadata format is slightly different, but the old metadata just doesn't expose itself in the recall actions so nothing breaks. However, the old metadata is available for copy-paste in the JSON viewer.

There's no backcompat, BUT the old format is just ignored on the client bc the shape is different, and users can copy/paste from the metadata for prompt. See video comparing old and new format:

https://github.com/invoke-ai/InvokeAI/assets/4822129/48540e9c-2500-4fe8-bc85-17739c6d75f3

**Pull request merged**
