### PR TITLE
Sync dev with main

### PR DESCRIPTION
**Pull request by lstein**
This pull request will synchronize the `development` branch with `main` version 2.1.3, without undoing any more recent changes to `development.`

### CODE REVIEW

**Comment by hipsterusername** [comment]
@lstein - This method of merging into Dev is somewhat foreign to me, although I get the general gist. If you're confident that the merge commit path is the right way to go, I can provide an approving review for the merge.

How confident are we that there won't be conflicting changes?

**Comment by hipsterusername** [comment]
At the very least, we should make the _assumption_ that this will break dev and we will need to either cherry pick some commits or fix unintended side effects

**Comment by lstein** [comment]
I've tested the merge on my local repo and there weren't any conflicts. All systems remained functional.

**Comment by mauwii** [comment]
`python scripts/invoke.py --from_file tests/preflight_prompts.txt` did all checks succesful, only one came out a bit strange:

```bash
#banana sushi -Ak_lms -W640 -H480 -S42
>> Provided width and height must be multiples of 64. Auto-resizing to 640x448
>> Setting Sampler to k_lms
Generating:   0%|                                                                                                                                             | 0/1 [00:00<?, ?it/s]>> Ksampler using model noise schedule (steps >= 30)
>> Sampling with k_lms starting at step 0 of 50 (50 new sampling steps)
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [02:52<00:00,  3.44s/it]
Generating: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [02:59<00:00, 179.62s/it]
>> Usage stats:
>>   1 image(s) generated in 179.96s
Outputs:
[9] outputs/img-samples/000270.42.png: banana sushi -s 50 -S 42 -W 640 -H 480 -C 7.5 -A k_lms
```



Besides this one everything looked good! Also tested the Webinterface which was working as well.

**Review by mauwii — APPROVED** [review]

**Comment by lstein** [comment]
Let's hope the weird sushi image is not a symptom of something bad going on. I'm inclined to think it is just one of those random bad images we get from time to time.

**Comment by lstein** [comment]
Thanks for the review! It is now merged.

**Pull request merged**
