### PR TITLE
Add Discord Bot based on discord.py

### PR DESCRIPTION
**Pull request by Zallist**
I've created a Discord bot that implements most of the functionality of the prompt2png code, except img2img variations.
The documentation on getting the bot running is in /docs/features/DISCORD_BOT.md.

The bot is relatively simple and not meant for being invited to many servers. Simply put, first come, first served, for generation of images.

This was originally based on https://github.com/Desm0nt/stable-diffusion-Discord-bot but had to be rewritten so that it was just a layer **on top** of the T2I interface.

It supports the following prompt2png arguments in the /dream command:
* per-prompt width/height
* `seed`
* `steps`
* number (`iterations`)
* strength (`cfg_scale`)
* img2img (`init_img`)
* img2img_mask (`init_mask`)
* img2img_fit (`fit`) (defaulted to True)
* img2img_noise (`strength`)
* `seamless`

### CODE REVIEW

**Comment by ausbitbank** [comment]
I too have a discord bot, based on eris js and using this repos unmodified web api at https://github.com/ausbitbank/stable-diffusion-discord-bot

It supports everything the web api does. I feel like a dick pointing this out in your issue but I'm not sure where else it would be more relevant to make people aware in case we can reduce redundant work..

**Comment by Zallist** [comment]
That works out pretty much perfect for choice. @lstein can now choose to include a discord bot directly in the source, or add to the README an endorsement for a standalone one. Or neither, I guess.

**Comment by tildebyte** [comment]
pinging @lstein for his opinion

I think Discord (well, any) bots are out-of-scope for this repo, but as I suggested to the person working on dockerizing, you could create a "sibling" project (NOT a fork, I don't mean that you need to **maintain an entire fork** of this project; simply depend on it) which would use the source from this repo as the back end.

I think as well that we could have a section in the readme for "Interesting projects using this repo as a base" or whatever.

**Comment by lstein** [comment]
I'll be honest about this. If @Zallist (or some else) will volunteer to take long term responsibility for maintaining the Discord bot, I would be happy for this to be part of the repository. Due to the restrictions on the hardware I work on, I cannot myself test the bot or respond to bug reports, and I feel responsibility for the quality and stability of this repository's products.

This project has moved at lightning pace over the past few weeks, and unfortunately a few people who were active contributors in the early days have since dropped off, leaving me maintaining code that I'm not 100% comfortable with. If someone can make the commitment, then I'll make you a collaborator and hand the maintenace of the parts of the code that run the bot over to you. Otherwise,  @tildebyte 's suggestion to create a friendly, but independent, peer of this repository is the best way to go, and you might prefer to be maintaining a self-contained and independent project in any case!

**Comment by Zallist** [comment]
The bot will never touch the underlying code, so I'd be perfectly comfortable maintaining **specifically** this code. Or acting as gatekeeper for anyone else who wanted to add/refactor to it, so long as I see relevant issues/pull requests.

I'm not even sure that people will opt to use it, since a wrapper like @ausbitbank has might end up being more versatile. A single running api of Stable Diffusion that can accept requests from N sources, vs a simpler to setup, but **only** Discord, solution. It's more aimed at the person who is self-hosting for fun & games, rather than using a network disconnected cluster for hardcore image generation.

**Comment by tildebyte** [comment]
@Zallist; I just realized that you're targeting 'main'; please switch branches to 'development'

**Comment by Zallist** [comment]
> @Zallist; I just realized that you're targeting 'main'; please switch branches to 'development'

Done

**Review by lstein — APPROVED** [review]
I've reviewed and don't see any obvious issues. However, I can't actually run this code because my development environment is an HPCC node on which I am absolutely not allowed to run a discord server!

I am adding a few reviewers to the request list in the hopes of finding someone who can independently verify that the Discord bot works as advertised.

**Comment by lstein** [comment]
I still need reviewers for the discord bot. I cannot independently verify because I don't have a system on which I can install a discord server.

**Comment by bakkot** [comment]
The bot looks cool, but I'm not sure it should live inside of this repository? It's a much more niche use case than the web UI - I would guess at least half of people are using the web UI, and probably less than 1% of people will want to run the discord bot. And it's more dependencies and maintenance burden we'd be taking on.

**Comment by tildebyte** [comment]
> The bot looks cool, but I'm not sure it should live inside of this repository? It's a much more niche use case than the web UI - I would guess at least half of people are using the web UI, and probably less than 1% of people will want to run the discord bot. And it's more dependencies and maintenance burden we'd be taking on.

[Yep](https://github.com/invoke-ai/InvokeAI/pull/592#issuecomment-1248665901) (previous post in this PR). /invoke @blessedcoolant... 😂

**Comment by blessedcoolant** [comment]
I've been thinking about this and here are my thoughts on this.

 We named this repo as a 'Stable Diffusion Toolkit` which means we provide access to any tool that implements SD. By that definition, this code should be a part of this repo. But this brings up a set of issues that weigh in heavily against that idea. Let me outline a few.

1. This is a feature that will see very little general public use. The biggest use case for this is for people who are looking to host SD a discord service and the number who want to do that is relatively low.
2. This is not an easy to test feature. It requires the elaborate setup of a Discord server to make sure the code is fully functional and not every dev has access to that. Which means the number of people that can code and debug this becomes very low.
3. If @Zallist at any point of time moves on from this project, then incorporating it into InvokeAI will put the responsibility on us to take care of it or scrap the feature entirely. Which I am not a fan of. And because devs interested and capable of developing and testing this feature is limited, it might become a hard one to maintain.

I would really love for this to be a part of this repo but I am leaning against the idea at the current time.

----

Maybe I can suggest an alternative to @Zallist.

- You can make this project under the repo of `InvokeAIDiscordBot` and we can add this repo to the organization. That way anyone who has particular need for this can go to that repo rather than the primary one. The responsibility of keeping that repo up to date will be on you.
- We can add the link to that repo in our docs for anyone looking at this feature.

This way we keep it a part of this project while still maintaining independency in terms of code and dvelopment.

Thoughts @lstein @tildebyte .. ?

**Comment by manzke** [comment]
We have invoke-ai now. Why not opening a repo next to it?
Personally not a fan of mono-repos and it could be the beginning of a real structure.
The project is evolving in such a high speed right now, that it will be necessary long-term anyway.

Question is where it will / should / wants to go.

**Comment by tildebyte** [comment]
@blessedcoolant;

> Now that we have an org, might as well use it eh?

🤯 I WISH I'D THOUGHT OF THAT

@Zallist; This really is the best of all solutions - your bot can be "official", but you won't end up getting lost in all of the chaos going on in *this* repo :grin: . Given that you'll be part of the org, you can feel free to ping maintainers in here for reviews, advice, discussions, etc.

**Pull request closed without merging**
