### PR TITLE
feat(ui): Add "Hide Preview" Button to WebUI

### PR DESCRIPTION
**Pull request by SammCheese**
Occasionally you may find yourself wanting to use the WebUI in public (remotely?) but not showing everyone what you last generated, or generating something without wanting others to see it. 
While you could disable "Display In-Progress Images" it will still show you the final image, which might not be something a user wants.

This PR attempts to solve that problem by adding a button to toggle visibility of the Preview.
For the Image2Image tab, it hides both the uploaded image and the preview

image
image

### CODE REVIEW

**Comment by blessedcoolant** [comment]
Rest of it seems fine. Thanks for the PR. I'll let @psychedelicious also give a quick glance before we build and merge.

**Review by psychedelicious — CHANGES_REQUESTED** [review]
Good idea! I've got a small nitpick: `hidden` is not super descriptive of the variable. I'd prefer something like `shouldHidePreviews`.

Can you please choose a more descriptive name, and add a `chore(ui): build` commit after running `yarn build` (we have to bundle the build in the repo, long story)?

Thanks for your contribution!

**Comment by SammCheese** [comment]
This should do ^^

**Comment by blessedcoolant** [comment]
> This should do ^^

You didn't update the setter function's name yet. Also can you check why your build has changes to other localization stuff?

**Comment by SammCheese** [comment]
> > This should do ^^
> 
> You didn't update the setter function's name yet. Also can you check why your build has changes to other localization stuff? Seems to be removing and adding a ton of other strings.

That's odd. I didn't change anything regarding localization. I just run `yarn build` as requested by psychedelicious.

**Comment by blessedcoolant** [comment]
> That's odd. I didn't change anything regarding localization. I just ran `yarn build` as requested by psychedelicious.

Just checked again. Seems like those might be left overs from earlier PR's that weren't built yet. Don't worry about it. Change the setter function's name to match the new variable name and build again. Should be good to go after that.

**Review by blessedcoolant — APPROVED** [review]

**Review by psychedelicious — APPROVED** [review]

**Pull request merged**
