### PR TITLE
[WebUI] Add Image Gallery Drawer

### PR DESCRIPTION
**Pull request by blessedcoolant**
The PR converts the Image Gallery to a resizable drawer type layout. This is done for many reasons.

1. The gallery doesn't always need to show and it was taking up space on the UI that can be used for the canvas -- especially handy with upcoming features like Outpainting.
2. Gallery Size is no longer fixed. Which means people with different screens and resolutions and adjust it as they want. (Option to remember the resized gallery size will be added in the next patch).
3. The expandable gallery now opens up avenues for many features in the future. Once we had filter options and a bunch of other stuff for gallery management, they can all go in the Gallery Drawer now without any issues.

https://user-images.githubusercontent.com/54517381/194688743-7bd0176b-36ee-422e-b4d9-d469310a1c4e.mp4

### CODE REVIEW

**Comment by 19wolf** [comment]
I like this idea as a separate tab for full screen gallery, and make the gallery on the side resizable such that it doesn't overlay the rest of the ui

**Review by lstein — APPROVED** [review]
LGTM

**Comment by lstein** [comment]
The drawer is now folded into both `development` and `release-candidate-2`. However, I'm seeing a phenomenon in which there is a lot of extra space between the left-hand panel and the main image, and the image drawer overlaps the right side of the main image. 

See the two screenshots. In the second, the drawer is covering part of the woman's left cheek.
Screenshot from 2022-10-08 11-55-09
Screenshot from 2022-10-08 11-55-29


Further I worry that the user won't know to click on the image icon to open up the drawer!

**Comment by blessedcoolant** [comment]
The idea is to leave enough space for the canvas. In a single image, you'd see the empty space but in images that are wide aspect ratio, it'll take up that space.

I'd say let people try the app first. I think knowing there's a gallery feature will be an immediate go to. But if for some reason they don't click on the button, it is still listed as a top hotkey. But even then if people don't somehow open it, then I'll make the button glow lol.

As I develop the inpainting and outpainting UI, I might take changes to the canvas area that affect the other panels retrospectively. So let's see how it develops.

At the moment, I am primarily focusing on making it feature rich. Once we have all the features in place, I will focus on doing a UX pass where I refine the usability and experience as much as possible.

**Pull request merged**
