### PR TITLE
Auto-format frontend

### PR DESCRIPTION
**Pull request by kasbah**
Auto-format the frontend using prettier and add a check for it to lint-frontend Github Actions workflow.

### CODE REVIEW

**Comment by lstein** [comment]
@kasbah apologies for reaching out to you via the PR, but I and the others would like you to join the team on GitHub. Let me know and I'll send you an invite. Do you have a discord name where I can reach you?

**Review by blessedcoolant — CHANGES_REQUESTED** [review]
Can we use yarn here instead?

**Comment by mauwii** [comment]
@kasbah somehow this workflow was running in some of the PRs already, any Idea why this happened?

**Comment by kasbah** [comment]
You mean here?


https://github.com/invoke-ai/InvokeAI/blob/df4679b31054340465a64232e9885b87459eb8a9/frontend/package.json#L14

The reason I use `npm` there is because `npm` is always installed, even when you use `yarn`. The readme in the frontend still says you can do everything with just `npm` so `yarn` might not be installed.  Also, I migrated a codebase from `yarn` to `pnpm` recently and realized if I had just used `npm` in the scripts in package.json it would have been one place less to worry about for the migration.

**Comment by blessedcoolant** [comment]
> > Can we use yarn here instead?
> 
> You mean here?
> 
> https://github.com/invoke-ai/InvokeAI/blob/df4679b31054340465a64232e9885b87459eb8a9/frontend/package.json#L14
> 
> The reason I use `npm` there is because `npm` is always installed, even when you use `yarn`. The readme in the frontend still says you can do everything with just `npm` so `yarn` might not be installed. Also, I migrated a codebase from `yarn` to `pnpm` recently and realized if I had just used `npm` in the scripts in package.json it would have been one place less to worry about for the migration.

Wont this generate lock or dependency files that clash with the lock files from yarn?

**Comment by kasbah** [comment]
No, it doesn't install anything. Just runs the script.

**Comment by mauwii** [comment]
> @kasbah somehow this workflow was running in some of the PRs already, any Idea why this happened?

nevermind, I think I found the reason why this was happening.

**Review by blessedcoolant — APPROVED** [review]

**Comment by blessedcoolant** [comment]
> No, it doesn't install anything. Just runs the script.

Ok. Rest seems good.

**Comment by blessedcoolant** [comment]
We're not doing our own prettier config? Just go with defaults?

**Comment by kasbah** [comment]
> @kasbah somehow this workflow was running in some of the PRs already, any Idea why this happened?

It's running the workflow `on: push` that's on the main branch already. I think when the PR branch is on this repo then it shows up on the PR like I thought it would.  Adding `on: pull_request` also makes it show up on external pull_requests.

**Comment by kasbah** [comment]
> We're not doing our own prettier config? Just go with defaults?

Yeah, most of the code is already conforming to prettier defaults it seems.

**Comment by blessedcoolant** [comment]
Okay. Guess its handy for people who haven't setup prettier on their editor. And will let us enforce any styling requirements we need later through the config file if need be.

**Comment by psychedelicious** [comment]
Yeah I use the default prettier config so most of it should be consistent. Thanks for the pr.

**Pull request merged**
