### PR TITLE
add --no-interactive to preload_models step

### PR DESCRIPTION
**Pull request by mauwii**

### CODE REVIEW

**Comment by mauwii** [comment]
@lstein thought it would be helpful to have this with the script :godmode:

**Comment by mauwii** [comment]
should have directly mentioned the PR itself #1290

**Comment by lstein** [comment]
I'm confused. Didn't I already add  `--no-interactive` to PR #1290 ?

**Review by lstein — APPROVED** [review]

**Comment by lstein** [comment]
I'll delete the previous comment. I see that you are applying the flat to the github action.- thought you were adding to the script itself.

**Pull request merged**
