### PR TITLE
cut over from karras to model noise schedule for higher steps

### PR DESCRIPTION
**Pull request by lstein**
The k_samplers come with a "karras" noise schedule which performs very well at low step counts but becomes noisy at higher ones.

This commit introduces a threshold (currently 30 steps) at which the k samplers will switch over from using karras to the older model noise schedule.

### CODE REVIEW

**Comment by psychedelicious** [comment]
Sounds like a good option to exposed for advanced users.

**Comment by db3000** [comment]
Is there a discontinuity there though, i.e. does 31 steps actually make it noisier than 30 steps because of the cutover?

**Comment by lstein** [comment]
> Sounds like a good option to exposed for advanced users.

I've added a "sticky" `--karras_max` option that allows you to adjust the switchover point. Can set to zero to use the LD noise model exclusively, or some high number (1000) to use the Karras schedule exclusively.

**Comment by jjoshua2** [comment]
Does newer, faster samplers like k_dpmpp_2 affect this 30 cutover? Because this one is so good that 10 is OK, 15 is normal, and 20 is high and 30 is never needed.

**Pull request merged**
