### PR TITLE
Configure and model install TUI tweaks

### PR DESCRIPTION
**Pull request by lstein**
The installer TUI requires a minimum window width and height to provide a satisfactory user experience. If, after trying and exhausting all means of enlarging the window (on Linux, Mac and Windows) the window is still too small, this PR generates a message telling the user to enlarge the window and pausing until they do so. If the user fails to enlarge the window the program will proceed, and either issue an error message that it can't continue (on Windows), or show a clipped display that the user can remedy by enlarging the window.

### CODE REVIEW

**Review by hipsterusername — APPROVED** [review]

**Comment by hipsterusername** [comment]
A most elegant solution.

**Comment by ebr** [comment]
Should this be rolled into #3547 , or merged separately following that?

**Comment by lstein** [comment]
> Should this be rolled into #3547 , or merged separately following that?

This should be merged separately. Either one can be merged first and I will resolve any conflicts before merging the second.

**Review by ebr — APPROVED** [review]
Tested by merging with #3547 locally (to work around 'model type "main"' errors)

```
[2023-06-26 16:00:49,153]::[InvokeAI]::ERROR --> Insufficient horizontal space for the interface. Please make your window wider and try again.
```

- works :+1:  as expected on Gnome terminal.
- still line wrapping (also as expected) on 3rd party terminals that do not respond to being resized programmatically. 
- *But* , this PR fixes the crash when 3rd party terminals (e.g. Terminator) are resized to fixe the line wrapping - the above message is printed instead.

All works great from my perspective!

**Pull request merged**
