### PR TITLE
feat: Add High Resolution Fix to SDXL Linear Flow

### PR DESCRIPTION
**Pull request by marict**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [x] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [x] Yes
- [ ] No

## Description
Adds the high resolution fix feature to the SDXL linear flow.

## Related Tickets & Documents

- Related Issue #
- Closes #

## QA Instructions, Screenshots, Recordings
image

## Added/updated tests?

- [ ] Yes
- [x] No : Front end change

## [optional] Are there any post deployment tasks we need to perform?
I'm having difficulty getting this to work on my development machine (m2 macbook). I'm getting a black image when I run sdxl with the VAE fix at fp32. Can someone try this on a more capable machine to verify it works correctly?

### CODE REVIEW

**Comment by Millu** [comment]
Works great for me! The print looks like it comes from the REALESRGAN library: 

https://github.com/xinntao/Real-ESRGAN/blob/master/realesrgan/utils.py#L163

Not sure how to suppress this

**Comment by Millu** [comment]
I agree it's probably out of scope for this PR, and double checked - the same behavior appears when doing a normal upscale as well

**Comment by psychedelicious** [comment]
@lstein I've addressed the print statements in #5177

**Review by lstein — APPROVED** [review]
LGTM

**Review by hipsterusername — APPROVED** [review]

**Review by psychedelicious — CHANGES_REQUESTED** [review]
I noticed two issues:

1) It seems there is a problem related to VAE precision. If I select the base SDXL model and VAE @ FP32, and generate an image normally, it works. When I enable HRF, the initial gen decodes to black, suggesting the precision is from the original l2i isn't copied correctly. It looks correct in the code, though.

2) The original l2i is left in the graph, as are connections to it. This results in 3x VAE decodes happening. The original l2i and its connections should be removed from so we aren't doing this extra work. I wonder if this might be related to 1). Note this issue was not introduced in this PR.

**Comment by hipsterusername** [comment]
@marict - Checking in here! We're getting ready for an RC - do you want to include this in it?

**Pull request closed without merging**
