### PR TITLE
Make model key assignment deterministic

### PR DESCRIPTION
**Pull request by lstein**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [X] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [X] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [X] Yes
- [ ] No

## Description

Previously, when a model was installed, it was assigned a random database key. This caused issues because if the model was reinstalled, its key would change. It also makes metadata irreproducible. This PR changes the behavior so that keys are assigned determinstically based on the model contents

- .safetensors, .ckpt and other single file models are hashed with sha1. This is compatible with A1111's model hashes.
- The contents of diffusers directories are hashed using imohash (faster, but nonstandard)

## Related Tickets & Documents

See discord: https://discord.com/channels/1020123559063990373/1149513647022948483/1210441942249377792

- Related Issue #
- Closes #

## QA Instructions, Screenshots, Recordings

Try installing and uninstalling a model, using the command line `invokeai-model-install --add <url or repoid>`, followed by `invokeai-mode-install --delete <name of model>`. Both safetensors URLs and HF diffusers should get the same key each time.

## Merge Plan

Can merge when approved.

## Added/updated tests?

- [X] Yes - changed length of expected hash for embedding files.
- [ ] No

### CODE REVIEW

**Review by hipsterusername — APPROVED** [review]

**Review by psychedelicious — CHANGES_REQUESTED** [review]
There's a problem with the SHA1 implementation. It uses a block size when reading the file, causing the hash to be incorrect.

I was curious so I whipped up a benchmark of file hashing in python: https://github.com/psychedelicious/hash_bench

`SHA1` with block size is by far the fastest, but `BLAKE3` is still way faster than any other _correct_ algorithm. I think we should use this for single-file models. 

CivitAI provides `BLAKE3` hashes, and you can query for a model on their API using it: https://civitai.com/api/v1/model-versions/by-hash/39d4e86885924311d47475838b8e10edb7a33c780934e9fc9d38b80c27cb658e

(that's DreamShaper XL something or other - used in my tests)

There are a few ways to implement `BLAKE3`, see my benchmark repo for the fastest method, which parallelizes hashing and uses memory mapping (I don't really understand what this means but it makes it super fast).

**Comment by RyanJDick** [comment]
From a general DB design perspective, I'd be inclined to keep the random primary key and add the hash as another column on the table. (Which I think is what we had discussed when we originally decided to use a random key.)

This would be better if we think there's _any_ chance that the definition of the hash key will change in the future, or it's uniqueness constraint will be dropped. Example situations:
- If we ever decide to change the hashing function that we use (e.g. for performance, we discover a bug, to map very similar models to the same 'hash', etc.), the migration will be simpler.
- If we ever decide that we want to track deleted models, having a unique primary key is more practical.
- If, in the future, we want to run optimizations on models (e.g. TensorRT) and store the optimized artifacts, having a single primary hash key probably won't map well to what we are trying to represent.
- And probably many more situations that are hard to anticipate...

Up to you if you think the added effort now is worth it for the future-proofing.

**Comment by psychedelicious** [comment]
The PK can be anything but we need to be able to reference models using a stable, deterministic identifier.

There's no point in having model metadata if it isn't a stable reference to the same model.

Using a cryptographic hash also means metadata is useful between users. 

Also, I think we should consider dropping imohash and instead use b3 to hash the diffusers weights. Iterate over all files and update the hash as you go. No need to rely on the imohash library.

**Comment by lstein** [comment]
Huh. I didn't realize that I was hashing incorrectly. The web is filled with misleading info, I guess.

The `memoryview()` method applied to sha256 gives the same answer as `sha256sum` on the command line and is twice as fast as the linux command-line tool:

```
def sha256sum(filename):
    h  = hashlib.sha256()
    b  = bytearray(128*1024)
    mv = memoryview(b)
    with open(filename, 'rb', buffering=0) as f:
        for n in iter(lambda : f.readinto(mv), 0):
            h.update(mv[:n])
    return h.hexdigest()
```

Python:

```
time python hash.py ais-stcks-sdxl.safetensors
cf729c0896c2bd69d2a9e5687f5ebe0b44d29879529e2271f8f2d64550485608

real	0m0.591s
user	0m0.554s
sys	0m0.037s
```

Command line tool:
```
time sha256sum ais-stcks-sdxl.safetensors 
cf729c0896c2bd69d2a9e5687f5ebe0b44d29879529e2271f8f2d64550485608  ais-stcks-sdxl.safetensors

real	0m1.080s
user	0m1.040s
sys	0m0.041s
```
The only reason I chose `sha1` in the first place is that it produces shorter hashes. Civitai supports `sha256` as well as other algorithms that are part of the standard `hashlib` library. Can't we use one of those rather than trying to 

With respect to doing full hashes of the whole directory, `imohash` gives you a deterministic signature very fast, but doesn't provide file integrity checking. I think we need to discuss what our use cases are.

**Comment by lstein** [comment]
Here's timing on a 7 GB SDXL file, including information on memory consumption during the process:

sha256 implementation in python:
```
/usr/bin/time --verbose ~/bin/hash.py juggernautXL_version5.safetensors
70229e1d563a36fdf9f006368611dd34a176e2bb9dbe9f29696ecaaba3969521
        Command being timed: "/home/lstein/bin/hash.py juggernautXL_version5.safetensors"
        User time (seconds): 3.05
        System time (seconds): 1.59
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:04.65
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 10432
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 1176
        Voluntary context switches: 10
        Involuntary context switches: 10
        Swaps: 0
        File system inputs: 26976260
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

Command-line tool:

```
/usr/bin/time --verbose sha256sum juggernautXL_version5.safetensors
70229e1d563a36fdf9f006368611dd34a176e2bb9dbe9f29696ecaaba3969521  juggernautXL_version5.safetensors
        Command being timed: "sha256sum juggernautXL_version5.safetensors"
        User time (seconds): 14.71
        System time (seconds): 1.22
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:15.93
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 1476
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 107
        Voluntary context switches: 3
        Involuntary context switches: 60
        Swaps: 0
        File system inputs: 16861116
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

For the python version, wallclock time is a reproducible 3-4s. Acceptable?

**Comment by lstein** [comment]
Oh, just saw the blake3 benchmark results. That is *very* fast. Why don't we just go with that and stick with it?

**Comment by psychedelicious** [comment]
I've been moving back and forth between this PR and #5846, in which `key` will be a UUID. I've retained the improvements to the model hash class in this PR, but just made the key to be a UUID. 

My recent commits thus change this PR from "Make model key assignment deterministic" to "Improved model hashing".

**Review by psychedelicious — APPROVED** [review]

**Pull request merged**
