### PR TITLE
Update Russian localization

### PR DESCRIPTION
**Pull request by Vasyanator**
## What type of PR is this? (check all applicable)

- [x] ? Refactor
- [x] ? Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [ ] Yes
- [x] No, because: This change does not affect the code, and I only learned about the desirability of discussion now (during the execution of a pull request).

      
## Have you updated all relevant documentation?
- [ ] Yes
- [x] No

## Description

Completed all Russian localization with the exception of nodes.

## Related Tickets & Documents

- Related Issue # none
- Closes # none

## QA Instructions, Screenshots, Recordings

image

## Added/updated tests?

- [x] ? Yes
- [ ] No :

## [optional] Are there any post deployment tasks we need to perform?
- none

### CODE REVIEW

**Comment by hipsterusername** [comment]
@Vasyanator - Very much appreciate your translation support.

Unfortunately (!) - this is an auto-generated file that is produced by the translation service **Weblate**. You can learn more about how to get these translations into Weblate here https://invoke-ai.github.io/InvokeAI/contributing/contribution_guides/translation/?h=tran

**Comment by Vasyanator** [comment]
> Unfortunately (!) - this is an auto-generated file that is produced by the translation service **Weblate**. You can learn more about how to get these translations into Weblate here https://invoke-ai.github.io/InvokeAI/contributing/contribution_guides/translation/?h=tran

It may be convenient, but in some cases the translator needs to see where a particular inscription is located in order to translate it correctly.

**Comment by hipsterusername** [comment]
@Vasyanator - I'm simply calling out that this PR will be overwritten by Weblate when it auto-updates translations from that site. This file gets generated automatically based on what is input on the translation language input on that site.

The only way for translations to make it into the app are through Weblate's UI

**Comment by psychedelicious** [comment]
@Vasyanator I reviewed weblate's capabilities and found we can upload the JSON directly to weblate: https://hosted.weblate.org/projects/invokeai/web-ui/ru/#upload

It will merge the translation in, with option to overwrite the existing strings. @Millu Can you please give this a go?

**Pull request closed without merging**
