### PR TITLE
Export more for header

### PR DESCRIPTION
**Pull request by maryhipp**
* export more items needed for dynamic header
* remove build mode that is no longer needed

### CODE REVIEW

**Review by psychedelicious — COMMENTED** [review]
Why are the components exported as classes extending `React.Component`? Wouldn't it be `React.FunctionComponent` given these are function components?

**Review by psychedelicious — COMMENTED** [review]
Why are the components exported as classes extending `React.Component`? Wouldn't it be `React.FunctionComponent` given these are function components?

**Comment by maryhipp** [comment]
Probably because whatever stackoverflow I copied that from used `React.Component` and it worked 😂 I can update to `FunctionComponent`

**Comment by maryhipp** [comment]
I tried changing this to both React.FunctionComponent and JSX.Element and they both presented a slew of type errors in my React app that is rendering this - are you ok to leave as React.Component for now since that seems to play nicely for whatever reason?

**Review by psychedelicious — APPROVED** [review]

**Comment by psychedelicious** [comment]
Haha, yep gotcha. Maybe `ReactNode` is the correct typing for a component - I know that's what you'd use if you want a component to have `children`, but I'm not sure if that is correct here either. If this works, no worries.

I've approved, feel free to rebase and merge at your leisure, or change it if you want.

**Comment by maryhipp** [comment]
@blessedcoolant will you take a look when you have a chance please?

**Pull request merged**
