### PR TITLE
Add control_mode parameter to ControlNet 

### PR DESCRIPTION
**Pull request by GreggHelt2**
This PR adds the "control_mode" option to ControlNet implementation. 
Possible control_mode options are: 

- balanced -- this is the default, same as previous implementation without control_mode
- more_prompt -- pays more attention to the prompt
- more _control -- pays more attention to the ControlNet (in earlier implementations this was called "guess_mode")
- unbalanced -- pays even more attention to the ControlNet 

balanced, more_prompt, and more_control should be nearly identical to the equivalent options in the [auto1111 sd-webui-controlnet extension](https://github.com/Mikubill/sd-webui-controlnet#more-control-modes-previously-called-guess-mode)

The changes to enable balanced, more_prompt, and more_control are managed deeper in the code by two booleans, "soft_injection" and "cfg_injection".  The three control mode options in sd-webui-controlnet map to these booleans like:
 
!soft_injection && !cfg_injection ⇒  BALANCED            
 soft_injection &&  cfg_injection ⇒  MORE_CONTROL 
 soft_injection && !cfg_injection ⇒  MORE_PROMPT   
 
The "unbalanced" option simply exposes the fourth possible combination of these two booleans:
!soft_injection &&  cfg_injection ⇒ UNBALANCED

With "unbalanced" mode it is very easy to overdrive the controlnet inputs. It's recommended to use a cfg_scale between 2 and 4 to mitigate this, along with lowering controlnet weight and possibly lowering "end step percent". With those caveats, "unbalanced" can yield interesting results.

Example of all four modes using Canny edge detection ControlNet with prompt "old man", identical params except for control_mode:

Screenshot from 2023-06-11 23-53-00
Top middle:       BALANCED
Top right:          MORE_CONTROL
Bottom middle: MORE_PROMPT
Bottom right :    UNBALANCED

I kind of chose this seed because it shows pretty rough results with BALANCED (the default), but in my opinion better results with both MORE_CONTROL and MORE_PROMPT. And you can definitely see how MORE_PROMPT pays more attention to the prompt, and MORE_CONTROL pays more attention to the control image. And shows that UNBALANCED with default cfg_scale etc is unusable.

But here are four examples from same series (same seed etc), all have control_mode = UNBALANCED but now cfg_scale is set to 3. 
Screenshot from 2023-06-11 23-48-44
And param differences are:
Top middle:          prompt="old man", control_weight=0.3, end_step_percent=0.5
Top right:             prompt="old man",  control_weight=0.4, end_step_percent=1.0
Bottom middle:    prompt=None,        control_weight=0.3, end_step_percent=0.5 
Bottom right:       prompt=None,         control_weight=0.4, end_step_percent=1.0

So with the right settings UNBALANCED seems useful.

### CODE REVIEW

**Comment by blessedcoolant** [comment]
Are we able to control the strength of the cfg and soft injections?

**Review by psychedelicious — CHANGES_REQUESTED** [review]
Two issues: 
- There is no default control mode
- The UI placement of the control mode selector doesn't feel correct, this should probably be in the expanded view only

image

**Comment by blessedcoolant** [comment]
> Two issues:
> 
> * There is no default control mode
> * The UI placement of the control mode selector doesn't feel correct, this should probably be in the expanded view only
> 
> image

There is .. but your Cnet must have been added prior to this PR so it doesnt pick it. Delete it and readd it. The default will show up.

**Comment by psychedelicious** [comment]
Yep I needed to create a new cnet. 

The mode makes the mini view a lot less mini, and it's a big ui element for a single setting. Reluctant to make the mini view any taller, every extra item in param panel makes it less usable :/ just not an easy thing to design.

**Comment by blessedcoolant** [comment]
@psychedelicious  It's a primary setting though. If you wanna push it down, feel free. I don't mind. But the bottom part was all processor stuff. And this one isn't. So it needs a new category along with any other future options that might be added.

**Comment by psychedelicious** [comment]
I attempted to resolve conflicts but rebasing isn't doing what I expected. I'll defer to @GreggHelt2 to resolve the python side, maybe it should wait until the model manager stuff is in...

**Comment by GreggHelt2** [comment]
> 

Okay I've got current main merged into this branch, and control_mode is working in both node UI and linear UI.
Couldn't pull off a rebase, so setting up for a squash and merge once PR is approved.

**Review by blessedcoolant — APPROVED** [review]

**Review by psychedelicious — APPROVED** [review]
Fixed a couple bits post-api change, looks good to go!

**Pull request merged**
