### PR TITLE
[enhancement] import .safetensors ckpt files directly

### PR DESCRIPTION
**Pull request by lstein**
This small fix makes it possible to import and run safetensors ckpt files directly without doing a conversion step first.

### CODE REVIEW

**Comment by SnakePin** [comment]
VAE files that are in .safetensors format still can't be loaded with these changes

**Comment by lstein** [comment]
> VAE files that are in .safetensors format still can't be loaded with these changes

Thanks for the heads up. I’ll fix that.

**Comment by lstein** [comment]
> > VAE files that are in .safetensors format still can't be loaded with these changes
> 
> Thanks for the heads up. I’ll fix that.

@SnakePin Loading safetensors VAE files should be working now, but I don't have any to test with. Could you give it a try?

**Comment by SnakePin** [comment]
The code appears to fail when trying to load a model with safetensors VAE here: https://github.com/invoke-ai/InvokeAI/blob/4a9e93463d8af7f33fbab4d0f79bf8657ead191f/ldm/generate.py#L846 The output is this: `** model stable-diffusion-1.5 could not be loaded: 'state_dict'`
The same VAE file converted to ckpt seems to work.
Also, you can use this one for testing: https://huggingface.co/stabilityai/sd-vae-ft-mse-original/blob/main/vae-ft-mse-840000-ema-pruned.safetensors

**Comment by lstein** [comment]
> The code appears to fail when trying to load a model with safetensors VAE here:
> 
> https://github.com/invoke-ai/InvokeAI/blob/4a9e93463d8af7f33fbab4d0f79bf8657ead191f/ldm/generate.py#L846
> 
> The output is this: `** model stable-diffusion-1.5 could not be loaded: 'state_dict'`
> The same VAE file converted to ckpt seems to work.
> Also, you can use this one for testing: https://huggingface.co/stabilityai/sd-vae-ft-mse-original/blob/main/vae-ft-mse-840000-ema-pruned.safetensors

Thanks! I have converted this to a draft while the VAE issue is being hammered out.

**Comment by lstein** [comment]
> > The code appears to fail when trying to load a model with safetensors VAE here:
> > https://github.com/invoke-ai/InvokeAI/blob/4a9e93463d8af7f33fbab4d0f79bf8657ead191f/ldm/generate.py#L846
> > 
> > The output is this: `** model stable-diffusion-1.5 could not be loaded: 'state_dict'`
> > The same VAE file converted to ckpt seems to work.
> > Also, you can use this one for testing: https://huggingface.co/stabilityai/sd-vae-ft-mse-original/blob/main/vae-ft-mse-840000-ema-pruned.safetensors
> 
> Thanks! I have converted this to a draft while the VAE issue is being hammered out.

I believe it will work now. Give it a try.

**Comment by SnakePin** [comment]
> I believe it will work now. Give it a try.

It works fine now.

**Review by hipsterusername — APPROVED** [review]

**Pull request merged**
