### PR TITLE
Onnx Pipeline: Inference for text to image conversion

### PR DESCRIPTION
**Pull request by saikrishna2893**
Initial version of ONNX based inference pipeline for Text to image conversion based on Stable-diffusion models.
Performance related information: Tested on Raphael (AMD 7600X) and Raptor Lake (I5-13000K)
[Onnx based inference performance - InvokeAI-pipelines.pdf](https://github.com/Multicoreware-Inc/InvokeAI/files/11439783/Onnx.based.inference.performance.-.InvokeAI-pipelines.pdf)

Sample output from execution of Onnx Pipeline tested on Raptor-Lake (I5-13000k) on CPU:
image

Sample output from execution of Pytorch Pipeline tested on Raptor-Lake (I5-13000k) on CPU:
image

### CODE REVIEW

**Comment by hipsterusername** [comment]
@saikrishna2893 - Thanks for the contribution!

To confirm, is this integrated into the new `Nodes` pipelines that are being worked on in Main?

**Review by lstein — CHANGES_REQUESTED** [review]
I really appreciate the work that went into this.

I'm sad to say that this will have to be modified in order to work with nodes. In particular, CLI.py is going to disappear from the repository soon. Please take a look at the `invokeai/app` tree, in particular `invokeai/app/invocation/latents.py`, to understand how the new text to image inference system works.

**Comment by lstein** [comment]
> Initial version of ONNX based inference pipeline for Text to image conversion based on Stable-diffusion models. Performance related information: Tested on Raphael (AMD 7600X) and Raptor Lake (I5-13000K) [Onnx based inference performance - InvokeAI-pipelines.pdf](https://github.com/Multicoreware-Inc/InvokeAI/files/11439783/Onnx.based.inference.performance.-.InvokeAI-pipelines.pdf)
> 
> Sample output from execution of Onnx Pipeline tested on Raptor-Lake (I5-13000k): image
> 
> Sample output from execution of Pytorch Pipeline tested on Raptor-Lake (I5-13000k): image

Does the ONNYX pipeline take advantage of CUDA, and if so, how does it perform?

**Comment by lstein** [comment]
Also note the CI failures.

**Comment by saikrishna2893** [comment]
> > Initial version of ONNX based inference pipeline for Text to image conversion based on Stable-diffusion models. Performance related information: Tested on Raphael (AMD 7600X) and Raptor Lake (I5-13000K) [Onnx based inference performance - InvokeAI-pipelines.pdf](https://github.com/Multicoreware-Inc/InvokeAI/files/11439783/Onnx.based.inference.performance.-.InvokeAI-pipelines.pdf)
> > Sample output from execution of Onnx Pipeline tested on Raptor-Lake (I5-13000k): image
> > Sample output from execution of Pytorch Pipeline tested on Raptor-Lake (I5-13000k): image
> 
> Does the ONNYX pipeline take advantage of CUDA, and if so, how does it perform?

The Onnx Pipeline currently uses CPU as its device. Pipeline makes use of OpenVINO execution provider for enhanced optimized inferencing.

**Comment by saikrishna2893** [comment]
> I really appreciate the work that went into this.
> 
> I'm sad to say that this will have to be modified in order to work with nodes. In particular, CLI.py is going to disappear from the repository soon. Please take a look at the `invokeai/app` tree, in particular `invokeai/app/invocation/latents.py`, to understand how the new text to image inference system works.

@lstein can you point out any documentation related to use of app and node structure. Example commands to run and test. We have done code through of the invokeai/app. Quite unclear on some of the working. We have checked [PR#3180](https://github.com/invoke-ai/InvokeAI/pull/3180) and other PR's. Have seen some commands using pipe to create multiple sessions of inference. Any further information on this would be helpful. Thanks.

**Comment by hipsterusername** [comment]
Hello! Following up on the request from discussions with @lalith-mcw here - CCing @lstein and @StAlKeR7779 for visibility.

To confirm, is there a reason you're looking for CLI documentation? I ask because 3.0 supports a graph-based API, that can be accessed via OpenAPI documentation. 

It may be easier to get direct implementation support if you join Discord. That is where we offer live Dev feedback and Q&A, and where a number of folks find implementation guidance.

In any case, I believe that you'll need the following guidance, which I believe @lstein and/or @StAlKeR7779 can provide more details on:
- Using the new Model Manager (#3335) to incorporate the ONNX model configuration.
- Updating node logic in Latents.py or in the Diffuser pipeline to support the new model format

If you reach out to me on Discord, I can create a channel for us to discuss this project. Thanks again for you and the team's support

**Comment by lalith-mcw** [comment]
> To confirm, is there a reason you're looking for CLI documentation? I ask because 3.0 supports a graph-based API, that can be accessed via OpenAPI documentation.

Currently in this PR we do provide an option for the user to select their own model type between `torch/onnx`. These were updated within `args.py` and `cli.py` with previous format. We do try to integrate the same with the graph based node invocations. I'll try to start a chat in discord, thanks.

**Comment by psychedelicious** [comment]
Hi @saikrishna2893 , we have implemented Onnx support in #3562. It is integrated in the nodes backend, but support is limited to text to image only for now.

**Pull request closed without merging**
