### PR TITLE
Translation update

### PR DESCRIPTION
**Pull request by mickr777**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [X] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [ ] Yes
- [ ] No

## Description
update the Translations
Ready for reviews 

## Related Tickets & Documents

- Related Issue #
- Closes #

## Added/updated tests?

- [ ] Yes
- [ ] No : _please replace this line with details on why tests
      have not been included_

### CODE REVIEW

**Comment by mickr777** [comment]
Opening for review to see what I have missed or did wrong

**Comment by blessedcoolant** [comment]
Thanks @mickr777 for going through these and getting them updated. Once you're done, I'll take a look and merge it up.

Tagging @Harvester62 in this. So he can stay in the loop for the translation process.

@hipsterusername @psychedelicious When merging this, please squash.

**Comment by mickr777** [comment]
> Thanks @mickr777 for going through these and getting them updated. Once you're done, I'll take a look and merge it up.
> 
> Tagging @Harvester62 in this. So he can stay in the loop for the translation process.
> 
> @hipsterusername @psychedelicious When merging this, please squash.

No Problem,
Yeah I was going to squash once everyone was happy, only keeping history to keep track of what files I have done

**Comment by mickr777** [comment]
@blessedcoolant ready for review, im sure I missed something

**Review by psychedelicious — APPROVED** [review]
Thanks for putting in the legwork on this one!

**Comment by mickr777** [comment]
> Thanks for putting in the legwork on this one!
I was happy I could help, I did have to use i18n in a few files as the strings to translate where in a function

**Pull request merged**
