### PR TITLE
wip: Add LCMScheduler

### PR DESCRIPTION
**Pull request by blessedcoolant**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [ ] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [ ] Yes
- [ ] No

## Description

~~**DOES NOT WORK** -- Need to fix the incorrect shapes and then we probably need to isolate the type for LCM Models so we can control the schedulers for them. But the Scheduler is implemented.~~

UPDATE 2023-11-10
With the latest changes to diffusers package, this PR works for the LCMScheduler / LCM-LoRA combo.

## Related Tickets & Documents

- Related Issue #
- Closes #

## Added/updated tests?

- [ ] Yes
- [ ] No : _please replace this line with details on why tests
      have not been included_

### CODE REVIEW

**Comment by hipsterusername** [comment]
Not sure if this helps as reference, but Gregg got the LCM node working here - https://github.com/GreggHelt2/invoke_lcm_test_node

**Review by lstein — APPROVED** [review]
Looks fine to me. What more needs to be done?

**Comment by lstein** [comment]
I approved before I saw the note regarding the need to isolate the scheduler. I think this is the first time that we've had a scheduler that only works with certain models. Do we need to add a `required_scheduler` field to the model configs?

**Comment by hipsterusername** [comment]
> I approved before I saw the note regarding the need to isolate the scheduler. I think this is the first time that we've had a scheduler that only works with certain models. Do we need to add a `required_scheduler` field to the model configs?

I think this is a broader question of how we anticipate people using LCM models, and where we want this type of validation to live. 

My read on LCMs is that the flow will likely be some form of "Ideate/explore rapidly in LCM space, then push to the "Full" variant of the model for the final asset". In that world, I think the UI/UX might be more like each full model has an LCM variant that only generates using LCM schedulers when LCM mode is activated. 

This is probably less "modular" than people might like, though, and opinionated

**Comment by hipsterusername** [comment]
As mentioned in discord, think the answer here is moving towards "Default Settings" that can be configured on a per model basis (optionally). I don't think we want to too tightly couple "requirements"

**Comment by blessedcoolant** [comment]
This is not functional yet though. The LCM Scheduler fully fails. My understanding is that the LCM models do not take negative conditioning. So the shapes end up being mismatched. I think we need to set a bypass for that in our own conditioning. Something I haven't done before. If someone who is more familiar with that part of the code could take a look, I think that would be better.

**Comment by GreggHelt2** [comment]
With the latest changes to diffusers package, this PR works for the LCMScheduler / LCM-LoRA combo!
(I had just got a similar branch working, then saw this draft PR)
I've been testing LCMScheduler/LCM-LoRA with diffusers StableDiffusionXLPipeline as well. The outputs aren't identical, but are similar. 

Example:
Left picture is with InvokeAI, right picture is with diffusers StableDiffusionXLPipeline. Both using base SDXL 1.0 model, LCMScheduler and SDXL LCM-LoRA, steps = 4, CFG scale = 1.1, seed=0, prompt="old man".

Screenshot from 2023-11-10 03-11-28

I've found that using a very low CFG Scale is crucial -- this was also the case for the earlier "SimianLuo/LCM_Dreamshaper_v7" distilled LCM model. Results in InvokeAI are also very sensitive to LoRA scale. In the example above, for StableDiffusionXLPipeline I didn't specify a LoRA scale, which I thought would default to 1.0. But for InvokeAI the results with LoRA scale = 1.0 were terrible. For the left image above the LoRA scale = 0.45.

Here's InvokeAI, holding everything fixed as above except changing CFG scale -- top row left to right 0.3, 0.4, 0.5, bottom row left to right 0.6, 0.75, 1.0:

Screenshot from 2023-11-10 04-51-08

I don't have an explanation for the differences between resulsts with InvokeAI and StableDIffusionXLPipeline, but I think the results are good enough at this point to merge the PR.

**Review by GreggHelt2 — APPROVED** [review]

**Review by hipsterusername — APPROVED** [review]

**Pull request merged**
