### PR TITLE
Added arabic locale files

### PR DESCRIPTION
**Pull request by ParisNeo**
I have added the arabic locale files. There need to be some modifications to the code in order to detect the language direction and add it to the current document body properties.

For example we can use this:

import { appWithTranslation, useTranslation } from "next-i18next";
import React, { useEffect } from "react";

  const { t, i18n } = useTranslation();
  const direction = i18n.dir();
  useEffect(() => {
    document.body.dir = direction;
  }, [direction]);

This should be added to the app file. It uses next-i18next to automatically get the current language and sets the body text direction (ltr or rtl) depending on the selected language.

### CODE REVIEW

**Comment by blessedcoolant** [comment]
@psychedelicious Tagging you here.

The issue with this PR is that Arabic UI's are generally flipped because the language reads from right to left. Flipping the UI is extremely easy because i18n provides a direction value that we can use to flip the window entirely.

But this leads to a bunch of issues with our UI.

1. Any element that is absolutely placed does not get flipped over. We have quite a few of these.
2. Elements which have directional styles look weird. For example, some buttons tat have rounded corners on side and not the other end up looking weird.
3. In most cases the flex and grid boxes adjust well but some of the flips just look odd. I don't know if this is because I am not used to seeing them that way or they are actually seem oddly placed.

I cannot think of an obvious solution to this.

1. We do not flip the UI. Let the translation occur and the language reads right to left anyway but we do not flip the UI at all.
2. We flip the UI and ignore these UI anomalies. This would lead to some bad UI experience for the users on the language.
3. We manually design alternate styles for these items or symmetrize all their designs so they look the same even when flipped. This is a lot of work and something we'll need to be mindful of in the future design work too. Not to mention, I don't know how this'll work with the node tree.

I think we go with #1. Add the language but do not flip the UI. What are your thoughts on that experience @ParisNeo?

**Comment by ParisNeo** [comment]
Hi, sorry for being late, yesterday I was hard on myself at work so when I got home I slept for 10 hours strait :)

It is OK for me to keep the layout direction for now. But I will have to change all the sentences that contain mixes of arabic and english words to do the english part phonetically. That will at least keep the sentences consistant. 

The third option is what should be done in the future. We just build a custom style for right to left. Use the same code that flips the page to select the right to left style and that should be ok. This will allow supporting more unconventional languages like urdu and others.

But I don't think the localization of the ui is the most important part of this work. I think there are quite a few Ideas way more important to implement than localization. Actually most arab people use english language. So let's keep it that way, provide the arabic translation in phonetic manner for english names like Stable diffusion and that should be ok.

I want to know though, is there any prompt translation tool? In my personal ui for stable diffusion, I have added a translation step so that if you say want to write your prompt in french, you can select the language and when the query is sent, the backend verifies the selected language. If it is not english, it first translates it to english, then continue. I think we can bring this to your ui as I didn't see a language selection in your ui. That would be a more useful tool.


I use open ai's whisper to do the translation. It works really well and supports multiple languages. But we can go with a different tranlator like the ones provided by meta.

What do you think about this?

**Comment by psychedelicious** [comment]
I would love to provide an equally approachable UX for LTR and RTL languages, but yeah, styling the UI in such a way that is can be flipped will be a very complex task. This is the first I've thought about it, to be honest!

What if we do 1, but offer 3 as an option in settings, tagged as experimental?

Maybe that would require two different Arabic translations, but it sounds like you @ParisNeo have already RTL properly, are willing to do a LTR version.

**Comment by ParisNeo** [comment]
Ok, I can do another translation this weekend to resolve the ltr problem and use the solution 1. 
There is a possible way in between though. Which is switching only the text and not the entire UI.

I google it really fast so I'm not sure this will work, but i found this blog post that can be helpful:
https://medium.com/@p.nasirimehr/adding-rtl-support-to-an-existing-react-native-app-in-2020-3264d035cb49

I'll see what I can do this weekend as I have no time during this week to work on this project.

**Comment by psychedelicious** [comment]
Great, thank you. Please do not delete the original translation - we can use it if we provide the option to switch the UI to RTL. I just tried it with the translation and it doesn't look *too* bad:

image

In this image, I have increased the font size a bit. The Arabic script looks kinda small to me, compared to the Latin script used by English. Maybe I just lack familiarity with it, so it looks small. 

Also, please let us know how to write "Arabic" in Arabic :)

**Comment by ParisNeo** [comment]
Arabic in arabic is :
العربية
I see that some parts are simple assets anyway, so if we translate, they are not translated. In the screenshot you sent we can see: connected in glowing green. This is another challenge if we want 100% localization :).

OK, I'll keep a copy of the current translation

**Comment by psychedelicious** [comment]
Oh, good catch. There are a few things that are not in the translations at all - that is one of them.

**Comment by ParisNeo** [comment]
Lool. I have to translate some model names like GFPGAN or code former. Some sounds do not exist in arabic so I have to go with the nearest. For Invoke  AI, I have simply translated its meaning, so the people understand that yo uare invoking artificial intelligence. I don't know if this is the best cuz there is no V sound in arabic and the pholetic translation seemed odd.

**Comment by ParisNeo** [comment]
I have finished removing all Latin text. I have translated translatable stuff and use phonetic approximation for the rest.

**Comment by ParisNeo** [comment]
Hi, Can someone review my PR?

**Comment by psychedelicious** [comment]
Thanks @ParisNeo . I've fixed a couple technical things.

@blessedcoolant Need your review

I've made a change to the language picker. Previously, the picker showed all languages in the currently selected language. This seems unhelpful, for finding your language, which you expect to be listed in your own language.

I've removed all language strings except for languages in their own language, and added these to `en`. So now the picker always displays all languages in their own language.

**Comment by blessedcoolant** [comment]
Seems good.

**Review by blessedcoolant — APPROVED** [review]

**Comment by blessedcoolant** [comment]
Will merge this now. We can figure out the direction flip for RTL languages in a later patch. Instead of doing a hackjob, we do a proper UI fix. Currently not at the top on our list of todo things but if @ParisNeo wants to give a shot at it, will be more than happy to take a look.

**Comment by blessedcoolant** [comment]
@lstein can you merge this manually please? Same issue with the frontend build again. There's another PR that address this. But until then ..

**Review by psychedelicious — APPROVED** [review]

**Pull request merged**
