### PR TITLE
[WebUI] Model Merging

### PR DESCRIPTION
**Pull request by blessedcoolant**
This PR brings Model Merging to the WebUI.

Inside the Model Manager, you can now find a new button called Merge Models. Rest of it is self explanatory.

firefox_BYCM4YNHEa

### CODE REVIEW

**Review by hipsterusername — APPROVED** [review]
LGTM. Ran into some model merge issues but think those are backend related.

**Review by netsvetaev — APPROVED** [review]

**Review by psychedelicious — APPROVED** [review]
Looks great!

**Comment by psychedelicious** [comment]
Also thanks for cleaning up the exception handling.

**Comment by blessedcoolant** [comment]
> Also thanks for cleaning up the exception handling.

No issues. Just a result of me being lazy. :P

**Pull request merged**
