### PR TITLE
feat: add UniPC scheduler

### PR DESCRIPTION
**Pull request by keturn**
This enables the UniPC scheduler added to diffusers 0.13: https://huggingface.co/docs/diffusers/api/schedulers/unipc

### CODE REVIEW

**Comment by keturn** [comment]
…except it doesn't work. It quickly collapses to zero, within the first few steps.

I also tried running with diffusers `main` to make sure it wasn't https://github.com/huggingface/diffusers/pull/2595 but that didn't seem to make a difference.

the first hunch that's come to mind is something to do with `scale_model_input`, since that's one way to drive something to zero, but I don't know yet.

**Comment by keturn** [comment]
UniPC does work with the stock diffusers pipeline.

The `scale_model_input` hunch wasn't it, as this scheduler doesn't scale there.

scheduler.config looks the same, scheduler.timestamps looks the same...

**Comment by patrickvonplaten** [comment]
Hmm weird, the do the following schedulers work:
- https://huggingface.co/docs/diffusers/v0.14.0/en/api/schedulers/deis#diffusers.DEISMultistepScheduler
- https://huggingface.co/docs/diffusers/v0.14.0/en/api/schedulers/multistep_dpm_solver
? Because UniPC is in exactly the same format as these ones.

**Comment by keturn** [comment]
Correction: it doesn't collapse to 0, it collapses to NaN. Running at float32 instead of float16 does not prevent it.

As for the other models:

Yep, we've had DPMSolverMultistepScheduler in use for a bit now.

DEIS seems to work more or less fine.

**Comment by lstein** [comment]
Any progress on this?

**Comment by keturn** [comment]
superseded by #3388.

(in theory. in practice I'm getting `422: Unprocessable Entity` errors with that, but that's a story for another bug report.)

**Pull request closed without merging**
