### PR TITLE
Fix inpaint node to new manager

### PR DESCRIPTION
**Pull request by StAlKeR7779**
Inpaint node still used by canvas, so fixed it to new model manager api.
Other old generation code deleted.

### CODE REVIEW

**Comment by psychedelicious** [comment]
The old txt2img and img2img are still used by canvas, pls do not delete

**Review by psychedelicious — APPROVED** [review]

**Comment by psychedelicious** [comment]
@blessedcoolant 
Can you please test this all tabs?

Everything should be working, including controlnet on canvas txt2img and img2img modes. 

Controlnet does not work on canvas inpaint/outpaint, but since we don't have real-time generation mode detection yet, we can't disable the controlnet UI when the mode is inpaint/outpaint.

This will supersede the changes you made to add the model loader to the linear graph builders.

**Comment by blessedcoolant** [comment]
> @blessedcoolant Can you please test this all tabs?
> 
> Everything should be working, including controlnet on canvas txt2img and img2img modes.
> 
> Controlnet does not work on canvas inpaint/outpaint, but since we don't have real-time generation mode detection yet, we can't disable the controlnet UI when the mode is inpaint/outpaint.
> 
> This will supersede the changes you made to add the model loader to the linear graph builders.

Will give it a test run in a few. And I'll sync up the changes on the MM pr later.

**Comment by psychedelicious** [comment]
Tests need to be updated now that the `TextToImageInvocation` and `ImageToImageInvocation` nodes no longer exist

**Comment by blessedcoolant** [comment]
- Text To Image - Works
- Text To Image w/ ControlNet - Works
- Image To Image - Works
- Image To Image w/ ControlNet - Works
- Canvas Text To Image - Works
- Canvas Image To Image - Works
- Canvas Inpainting - Works
- Canvas Outpainting - Works
- Canvas Text To Image w/ ControlNet - Works
- Canvas Image To Image w/ ControlNet - Works
- Canvas Inpainting w/ ControlNet - Shouldnt work and doesn't. Works as expected.
- Canvas Outpainting w/ ControlNet - Shouldnt work and doesn't. Works as expected.

Everything seems to be in order. @psychedelicious

**Review by blessedcoolant — APPROVED** [review]

**Pull request merged**
