### PR TITLE
feat: ControlNet Model Search, Setting & API Route

### PR DESCRIPTION
**Pull request by blessedcoolant**
This PR adds a few things.

### Model Manager

A new function: `get_controlnet_models` that takes in a folder path and recursively searches for Diffuser based ControlNet models.

The search looks for two files: 

- `config.json` with a `_classname` of `ControlNetModel`
- An accompanying `diffusion_pytorch_model.[safetensors/bin]` weight file. 

Returns a dict: `folder_name: folder_path`.

Usage in Nodes: `list[get_controlnet_models(path).keys()]` can be used for type hints for the model dropdown for ControlNet and the same key can be used to retrieve the path in the `invoke` function to pass the model path to the backend.

### Config

A new key `controlnet_dir` has been add to the `InvokeAIAppConfig` config. Users can set their controlnet models folder in the config file and we can access it directly via the API dependency services: `ApiDependencies.invoker.services.configuration.controlnet_dir`

#### Fix

I also noticed that the service types for the configuration were not correctly updated to the config object `InvokeAIAppConfig` but were pointing to the parent class of `InvokeAISettings`. So made that change too.

### API

A new API route has been added: `/api/v1/models/controlnetmodels`.

firefox_fpsH3KSa1a

You can set a `controlnet_dir`  in your `invoke.yaml` file pointing to where your Diffusers ControlNet models are and run the route to get the object. Tested and working as intended.

### CODE REVIEW

**Comment by hipsterusername** [comment]
@blessedcoolant - How does this work w/ @GreggHelt2's current open PR?

What overlap does this have w/ what @StAlKeR7779 and @lstein have been working on w.r.t. model management service?

**Comment by blessedcoolant** [comment]
> @blessedcoolant - How does this work w/ @GreggHelt2's current open PR?
> 
> What overlap does this have w/ what @StAlKeR7779 and @lstein have been working on w.r.t. model management service?

It doesn't touch Gregg's PR at all. At a later stage, we will use this route to get the the models rather than retrieving from HF.

As for the model manager changes, it just adds one extra function to the model manager. I haven't seen that PR but it should be a simple port over.

**Review by lstein — APPROVED** [review]
This looks fine. The `get_controlnet_models` function may need to be moved from `model_management.py` to `model_cache.py` when @StAlKeR7779 has finished his work there.

**Comment by blessedcoolant** [comment]
> This looks fine. The `get_controlnet_models` function may need to be moved from `model_management.py` to `model_cache.py` when @StAlKeR7779 has finished his work there.

Could you have a look at why the tests are failing?

**Review by psychedelicious — APPROVED** [review]

**Pull request closed without merging**
