### PR TITLE
Add support for diff/full lora layers

### PR DESCRIPTION
**Pull request by StAlKeR7779**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [x] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [ ] Yes
- [x] No

## Description
Add support for "diff" layer, which includes full layer weight.
Fixes - #4091 

## Added/updated tests?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by psychedelicious — APPROVED** [review]
Tested with https://civitai.com/models/121345/jodie-foster (which was a lycoris model the bug report said broke)
I get (something approximating) Jodie Foster - and no explosions

**Review by lstein — COMMENTED** [review]
I also tested with the Jodie Foster model that @psychedelicious cited, and it didn’t blow up, but I’m also not convinced the LoRA is working.

Here is the prompt “Jodie Foster” without the LoRA:
image
Here it is with the LoRA, weight 1.0, same seed and prompt. It’s doing something, but very subtly:
image

And here is weight 1.0 with the prompt “actress”:
image

**Comment by psychedelicious** [comment]
@lstein According to the model page on civitai, the LoRAs have trigger words. In this case, `sks woman`. Using that as my prompt, I got random stuff without the LoRA, and ~Jodie Foster with it

**Comment by lstein** [comment]
> @lstein According to the model page on civitai, the LoRAs have trigger words. In this case, `sks woman`. Using that as my prompt, I got random stuff without the LoRA, and ~Jodie Foster with it

"sks woman" is the trigger for Jodie Foster? I wouldn't have guessed.

**Review by lstein — APPROVED** [review]
Thanks.

**Pull request merged**
