### PR TITLE
Fix macOS `pyenv` instructions, add code block highlight

### PR DESCRIPTION
**Pull request by Niek**
Fix: `anaconda3-latest` does not work, specify the correct virtualenv, add missing init.

### CODE REVIEW

**Review by lstein — APPROVED** [review]
Thanks for finding and fixing this. I'd llike @magnusviri to take a look as well, since I've not got a Mac to test on.

**Comment by magnusviri** [comment]
I'll try to get to this after I've finished work today.

**Comment by lstein** [comment]
Much obliged!

**Comment by magnusviri** [comment]
I looked at it, but honestly I'm new to using python environments, so I don't know what effect this change has. I didn't have time to test it today.

**Comment by lstein** [comment]
Thanks. I think I'll go ahead and merge. If you have time to test let me know. Easy enough to back out if there are unexpected problems.

**Pull request merged**
