### PR TITLE
Remove circular dependencies from frontend

### LINKED ISSUE #1982: [bug]: HMR is not working for frontend dev
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cpu

### VRAM

_No response_

### What happened?

I'm trying to set up a dev environment for the frontend. I've got it all working with `yarn dev`, it compiles, loads the web ui on `127.0.0.1:5173` and generating images :sunglasses:  

However when I want to use hot-module-reloading and make a valid change to a `.tsx` file, after first loading the page, it's not reloading and endlessly repeating this error in the browser console:

```
ReferenceError: can't access lexical declaration 'App' before initialization
```

I tried in Firefox and Chrome, with profiles loaded that don't have any extensions installed. Is HMR supposed to be working?

Edit: Have tried editing with Neovim and VS Code with the same result.

### PR DESCRIPTION
**Pull request by kasbah**
Investigating #1982 revealed the frontend codebase has a lot of circular dependencies. I've not really dealt with this issue before but some research suggests that circular dependencies, while allowed in ES, should be avoided. Vite seems to be especially bad at handling them and not giving good errors when it has issues with them. 

I used a tool called `madge` to show me the circular dependencies. Initially it included some dependencies from d.ts files and other type-only imports, which should be less problematic as they get completely removed when compiled. 

- I auto-formatted frontend so I can easier use `--fix` with eslint (`--fix` without auto-formatting after gave some weird formatting)
- I enabled `@typescript-eslint/consistent-type-imports` and used the `--fix` option with it so that type-only imports are consistently marked as such
- I added a Github Actions workflow to lint the frontend, it also runs madge, so this workflow is currently expected to fail because `madge` is still showing 143 circular dependencies

Before I venture further I wanted to get some input from @blessedcoolant  and @psychedelicious about how they feel about addressing these circular dependencies. Seems like a lot of work in re-structuring the code-base would be required.

fixes #1982

### CODE REVIEW

**Comment by blessedcoolant** [comment]
I've never really faced this issue before either.

> ✖ Found 131 circular dependencies!

What exactly is happening here? And what is the suggested solution?

**Comment by kasbah** [comment]
If you run `yarn madge` on this branch you get for instance:

```
app/store.ts > app/socketio/middleware.ts > app/socketio/listeners.ts > features/options/store/optionsSlice.ts > features/tabs/components/InvokeTabs.tsx
```

So `store.ts` is importing `middleware.ts` etc.. and `InvokeTabs.tsx` is importing things from `store.ts`... hence a circular dependency. 

https://github.com/vitejs/vite/issues/3033#issuecomment-973247243 suggests that the circular deps are the problem with vite HMR, yes. Everything I've found so far about circular deps jumps right into suggesting how you might go about removing them, so... they seem bad? :slightly_smiling_face:

**Comment by blessedcoolant** [comment]
> If you run `yarn madge` on this branch you get for instance:
> 
> ```
> app/store.ts > app/socketio/middleware.ts > app/socketio/listeners.ts > features/options/store/optionsSlice.ts > features/tabs/components/InvokeTabs.tsx
> ```
> 
> So `store.ts` is importing `middleware.ts` etc.. and `InvokeTabs.tsx` is importing things from `store.ts`... hence a circular dependency.
> 
> [vitejs/vite#3033 (comment)](https://github.com/vitejs/vite/issues/3033#issuecomment-973247243) suggests that the circular deps are the problem with vite HMR, yes. Everything I've found so far about circular deps jumps right into suggesting how you might go about removing them, so... they seem bad? 🙂

Yeah in general programming, circular dependencies are always frowned upon. But I never realized this would be an issue here.

In this particular case ...

> > app/store.ts > app/socketio/middleware.ts > app/socketio/listeners.ts > features/options/store/optionsSlice.ts > features/tabs/components/InvokeTabs.tsx

What is the recommended solution? Coz in terms of app flow, it seems to be right but I see InvokeTabs needing the store data which inevitably has to pass through the middleware and the socketio setup in between.

I would very much love to see this addressed but wondering what needs doing exactly. Because like you said, this'll need some major overhaul.

**Comment by kasbah** [comment]
One solution people suggest, though I think this is more for libraries is to have an `internal.ts` next to `main.ts` and all imports are handled through that. [Here's an article that outlines this approach](https://medium.com/visual-development/how-to-fix-nasty-circular-dependency-issues-once-and-for-all-in-javascript-typescript-a04c987cf0de). Personally, I don't really like this very much because then everything ever is imported as "internal" and that makes everything much less clear in my view. 

More concretely, the way I would address this specific circularity, because these imports are only really about type checking, is something like this commit I just pushed: https://github.com/invoke-ai/InvokeAI/pull/1995/commits/40bad84c98caf55ea16ce428b4dba6619e10a1c1 (of course I'd also remove them from store.ts and update the rest of the code). 

Like I said, this is a bit new to me, I've not really ever seemed to need to build an application that needs circular dependencies, it just never came up for me. So I'm open to suggestions on how to move forward. 

Sharing types seems to be a large part of why it's done in this code-base which is why I reached for the eslint fix, but obviously it can't rewrite examples like this hooks one, even though that's just about types as well.

**Comment by blessedcoolant** [comment]
Yeah. Sounds like a plan. I think we should resolve this. Thanks for picking it up. I'd also like to hear what @psychedelicious says and how he feels about this.

**Comment by psychedelicious** [comment]
Riiight. You've reminded me that had encountered this and had run madge ages ago. I fixed the one issue that caused the HMR issue and moved on. 
**
Besides the infinite reload loops, occasionally there is a console error about optionsReducer being used before it was created - I suspect this is also related to circular dependencies. 

I'm very happy to see all type imports corrected, I guess it never clicked that they were not being specified as types - would have hoped the ide takes care of that.

I'll run madge again and try to resolve the remaining issues (hopefully this weekend) unless you want to address it. 

Thanks for the pr; I'll approve this with the assumption you have tested a built bundle, which I may not get to for a couple days.

**Comment by psychedelicious** [comment]
Oh, I see, we need to fix the Madge issues before this passes - good!

Do you have any opinions about building and committing the bundle via GitHub actions (on PR)? I tried to do it a while back - you can see my attempts on a "GitHub-actions" (or similar name) branch on my fork - but screwed it up. 

If such a CI/CD build step is advisable, maybe we can get that working in a subsequent PR.

**Comment by psychedelicious** [comment]
One more note - the HMR issue seems to occur not at first load of the dev server but after editing certain files (I assume those that are implicated in the circularity). This makes sense to me in a vague intuitive way but i don't understand the HMR process anywhere near enough to grok it technically.

**Comment by blessedcoolant** [comment]
Let me know when this PR is good for a test run. I'll have a go at it and see if all holds up. Thank you for the work on this.

**Comment by kasbah** [comment]
This was actually less work than I thought. Splitting the `app/store.ts` hooks into another file reduced it down to 26 circular dependencies already. I've done all the rest now and madge is reporting 0. I've undone the auto-formatting and eslint stuff because it wasn't needed for this in the end (will send another PR for auto-formatting though). 

When I do a fresh clone of this branch HMR works for me so it does seem to fix it. It's ready to review and try out now.

**Comment by blessedcoolant** [comment]
Everything seems to be working as intended. Madge does report circular dependencies as zero. Excellent job @kasbah. I'll let @psychedelicious do a code review and then merge this.

**Review by blessedcoolant — APPROVED** [review]

**Comment by mauwii** [comment]
For the linting workflow it looks like it does only do the linting job but would not prevent merges or anything, right?

@kasbah do the jobs error out with f.E. circular dependencies, or would they still have a exit code of 0?

**Comment by kasbah** [comment]
I'm not sure how it would prevent merges. Can you explain what you mean or provide an example of a CI job that would prevent merges?

Madge exits non-zero when there are circular deps. I've just double checked on another branch that the CI job will fail with circular deps present: https://github.com/kasbah/InvokeAI/actions/runs/3704613517

**Comment by mauwii** [comment]
If it is exiting with another exit code than zero, the action would fail. If the Action is set to be required, this would prevent merges. sorry, my last comment was maybe formulated a bit irritating 🙈

**Comment by kasbah** [comment]
Ah yes, that probably depends on this this repo's or org's merge policy. Not too familiar with the settings there, I generally just leave them at their default. By default a failing CI run won't block merges, just tell you that it failed.

**Comment by mauwii** [comment]
Well, in the end this would only be possible if it is also set to trigger on pull requests, otherwise it would be required but not run 🙈

**Comment by blessedcoolant** [comment]
> It gets run on "push" for all branches though so it will get run on pull request branches as well. I believe Github is clever enough to associate the push to a pull-request and show the info there. No idea how the "required" settings behave though.
> 
> Do you want me to change anything to get this merged?

From the front end part, I think its good to go. @mauwii already approved it. But I'll just wait on him for another CI related check. If it is good to go, then I'll merge it.

**Comment by mauwii** [comment]
> Do you want me to change anything to get this merged?

No, would have required changes via review, but thx for asking ☺️

**Comment by blessedcoolant** [comment]
@kasbah Bring this update to date with main please. I'll merge it after.

**Comment by psychedelicious** [comment]
Thanks again for this @kasbah

**Pull request merged**
