### PR TITLE
[Feat] reimport model config records after schema migration

### PR DESCRIPTION
**Pull request by lstein**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [X] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [X] Yes
- [ ] No

## Description

Version 3.5.0 (and higher) introduces a schema change to the `model_config` table, which holds registered model configuration records. Because the table is not used in production, the migration system simply drops and redefines the table. This PR adds an additional step of (re)importing configuration records from the user's `models.yaml` file into the new table. When the new model manager actually goes into production, this will avoid headaches from users who edited their `models.yaml` to add  descriptions or change the prediction type.

This code will also run the first time the user upgrades to version 3.5 and will populate the sql database from their existing `models.yaml`. 

## Related Tickets & Documents

- Related Issue #
- Closes #

## Added/updated tests?

- [ ] Yes
- [X] No : the code in question already has unit tests
-

### CODE REVIEW

**Comment by psychedelicious** [comment]
This won't work for in-memory databases, it must use the same connection. When this logic is called, it creates a new connection, which means a totally new memory DB.

If this logic is intended to be run while the app is running (and/or on memory databases), it needs to be refactored to accept an instance of `SqliteDatabase` on init, instead of creating it in its `get_db()` method. Then, this should be passed in as a dependency to the migration builder function, along with `image_files`.

I think/hope that would be a fairly minimal change

**Comment by lstein** [comment]
> This won't work for in-memory databases, it must use the same connection. When this logic is called, it creates a new connection, which means a totally new memory DB.
> 
> If this logic is intended to be run while the app is running (and/or on memory databases), it needs to be refactored to accept an instance of `SqliteDatabase` on init, instead of creating it in its `get_db()` method. Then, this should be passed in as a dependency to the migration builder function, along with `image_files`.
> 
> I think/hope that would be a fairly minimal change

Passing the ModelRecordService object in parallel with `image_files` involves making modifications to `init_db()` in `dependencies.py`, and then making changes to the `register_migration()` call in `sqlite_util.py`, and `__init__` in `migration_2.py`. Is this truly the right way to do it? If there is a similar content migration task in `migration_3.py`, would we need to add yet another service to the chain?

For my purposes, everything would be much easier if `run_migrations()` were to pass the db object rather than a cursor. I'd use the db object to create a transient ModelRecordService to do the content migration and there'd be no issues with an in-memory db.

How is schema migration useful in an in-memory database anyway? Doesn't the database schema get reinitialized every time the app starts up?

**Comment by lstein** [comment]
> This won't work for in-memory databases, it must use the same connection. When this logic is called, it creates a new connection, which means a totally new memory DB.
> 
> If this logic is intended to be run while the app is running (and/or on memory databases), it needs to be refactored to accept an instance of `SqliteDatabase` on init, instead of creating it in its `get_db()` method. Then, this should be passed in as a dependency to the migration builder function, along with `image_files`.
> 
> I think/hope that would be a fairly minimal change

I am trying to figure out how to do this. The problem is that the code to write a modified config into the database resides in `ModelRecordServiceSQL`, which is initialized with a `SqliteDatabase` object. However, the migrate function only passes a `sqlite3.cursor`, not the database object.

**Comment by lstein** [comment]
@psychedelicious I rewrote the model config migration code to use the provided cursor. There is some duplication of SQL now between `invokeai/backend/model_manager/migrate_to_db.py` and `invokeai/app/services/model_records/model_records_sql.py`, but I couldn't come up with a more elegant way to handle it, given that the latter requires access to the database object in order to do its locking, and the database object is not available to the migration classes.

**Review by psychedelicious — COMMENTED** [review]
I think it's fine to duplicate those few queries here, but realized there's another issue.

Say we change the `model_config` table schema in v3.6.0, and update `MigrateModelYamlToDb` accordingly. If a user upgrades from v3.4.0 to v3.6.0, this yaml migration will fail when attempting to interact with the updated `model_config` table. The migration logic must be frozen to prevent issues like this.

In hindsight, the way I'm migrating the workflows using the image service has the same problem. If we change the implementation of the `image_files` service, this migration logic could fail.

**Comment by lstein** [comment]
> I think it's fine to duplicate those few queries here, but realized there's another issue.
> 
> Say we change the `model_config` table schema in v3.6.0, and update `MigrateModelYamlToDb` accordingly. If a user upgrades from v3.4.0 to v3.6.0, this yaml migration will fail when attempting to interact with the updated `model_config` table. The migration logic must be frozen to prevent issues like this.
> 
> In hindsight, the way I'm migrating the workflows using the image files service has the same problem. If we change the implementation of the `image_files` service, this migration logic could fail. My initial implementation actually did not use the image_files service - it just directly crawled the images. Maybe that's a better way to do it. @RyanJDick @lstein any thoughts?
> 
> That said, I'm not concerned about the `model_config` table. We can just plan to drop it entirely when we roll out the MM rework, renaming it to e.g. `model_configs` or `models`. In the future, when we have WIP features in the database, we should prefix the table names with `test_` or something just to make it clear.

Easiest solution is to freeze the `MigrateModelYamlToDb` code. I'll stick it into `migrations`.

**Comment by lstein** [comment]
@psychedelicious I have moved the model config content migration code to `migration_3`.

**Review by psychedelicious — APPROVED** [review]
Looks good. Can we please squash merge?

**Review by hipsterusername — APPROVED** [review]

**Pull request merged**
