### PR TITLE
Fix Sliders unable to take typed input

### PR DESCRIPTION
**Pull request by blessedcoolant**
So far the slider component was unable to take typed input due to a bunch of issues that were a pain to solve. This PR fixes it. 

Things to test:

- Moving the slider also updates the value in the input text box.
- Input text box next to slider can be changed in two ways: If you type a manual value, the slider will be updated when you lose focus from the input box. If you use the stepper icons to update the values, the slider should update immediately.
- Make sure the reset buttons next to the slider are updating correctly and make sure this updates both the slider and the input box values.
- Brush Size slider -> make sure the hotkeys are updating the input box too.

### CODE REVIEW

**Review by lstein — CHANGES_REQUESTED** [review]
By and large looks great, but I found a couple of anomaliels:

1. In the Unified Canvas, can't type in the text fields for the bounding box width and  height.
2. Similar problem for "Scaled W" and "Scaled H" in "Infill and Scaling"
3. There's no textbox next to the slider for "Inpaint Replace". Also the reset button sets this to 1, rather than the value of 0.1 which is what you get when you first reset the web UI.

**Comment by blessedcoolant** [comment]
> 1. In the Unified Canvas, can't type in the text fields for the bounding box width and  height.
> 2. Similar problem for "Scaled W" and "Scaled H" in "Infill and Scaling"

These two are intentional. Because it is crucial that the width and height are in multiples of 64, having the user enter arbitrary numbers means we have to constantly calculate the closest resolutions. This can be relatively painful so I disabled manual entry for width and height and let the stepper handle it.

> 3. There's no textbox next to the slider for "Inpaint Replace". Also the reset button sets this to 1, rather than the value of 0.1 which is what you get when you first reset the web UI.

Inpaint replace never had a text box coz of design issues. But those are gone now. I added it and fixed up the default value.

**Comment by blessedcoolant** [comment]
@lstein Please review this when you get a chance. Thanks. Would like to merge it coz it has a multiple PR build on it.

**Comment by hipsterusername** [comment]
I can put this through the ringer and test when I get home today. Sorry for delays - Been a bit busy! 🙃 

@keturn - Did we end up removing inpaint replace in diffusers? Should that input just go away, and have the frontend support 1 for img2img strength?

**Review by lstein — APPROVED** [review]
LGTM

**Pull request merged**
