### PR TITLE
Fix typo and Hi-Res Bug

### PR DESCRIPTION
**Pull request by hipsterusername**
There was a typo on the Img2img tab of "inital image"

I (believe) I've also fixed and cleaned up the code regarding the hires fix feature being turned off when navigating to the img2img tab.

### CODE REVIEW

**Comment by blessedcoolant** [comment]
Code wise seems good. Haven't tested it.

**Review by blessedcoolant — APPROVED** [review]

**Review by psychedelicious — APPROVED** [review]
Took 'er for a run around the block. All good, thanks for fixing this.

**Comment by hipsterusername** [comment]
@psychedelicious I pressed the wrong button and rebased instead of doing auto merge :)

Mind giving it another poke?

**Comment by hipsterusername** [comment]
Nvm! Seems to have said it’s good to go.

**Comment by hipsterusername** [comment]
Nvm! Seems to have said it’s good to go.

**Comment by JPPhoto** [comment]
Not sure if this was part of the PR, but "Load All" of a CLI-generated image into the GUI that had `--hires_fix` but no strength doesn't reset strength to the default of 0.75. It may not be a big deal if things are going away with nodes, but I wanted to leave a note anyway.

**Pull request merged**
