### PR TITLE
fix(ModelManager): fix overridden VAE with relative path

### LINKED ISSUE #4128: [bug]: fails to load overridden VAE when path is relative
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

4599575e65db2081886b6782f961ddf68359aecb

### What happened?

```yaml
sdxl/main/SDXL base 1_0:
  path: sdxl/main/SDXL base 1_0
  description: SDXL base v1.0
  vae: sdxl/vae/sdxl-vae-fp16-fix/
  variant: normal
  format: diffusers
```
Note the presence of a `vae` override and the use of a relative path there.

<details>
<summary>Traceback: ModelNotFoundException</summary>

```
[2023-08-01 16:43:47,222]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "src/InvokeAI/invokeai/app/services/processor.py", line 86, in __process
    outputs = invocation.invoke(
              ^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)   
           ^^^^^^^^^^^^^^^^^^^^^
  File "src/InvokeAI/invokeai/app/invocations/latent.py", line 515, in invoke
    vae_info = context.services.model_manager.get_model(     
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/InvokeAI/invokeai/app/services/model_manager_service.py", line 364, in get_model
    model_info = self.mgr.get_model(
                 ^^^^^^^^^^^^^^^^^^^
  File "src/InvokeAI/invokeai/backend/model_management/model_manager.py", line 484, in get_model
    model_path = model_class.convert_if_required(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/InvokeAI/invokeai/backend/model_management/models/vae.py", line 103, in convert_if_required
    if cls.detect_format(model_path) == VaeModelFormat.Checkpoint:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/InvokeAI/invokeai/backend/model_management/models/vae.py", line 83, in detect_format
    raise ModelNotFoundException()                                                              
invokeai.backend.model_management.models.base.ModelNotFoundException        
                                                                                                
[2023-08-01 16:43:47,226]::[InvokeAI]::ERROR --> Error while invoking:     
```

</details>

### PR DESCRIPTION
**Pull request by keturn**
The motivation here went something like this:

- I want to add a new field to the model manager listing.
- It looked like the right place to do that is in invokeai.backend.model_management.models.base.ModelBase, because that's where `get_size` is. It also seems to be the class that has access to `path` where the model is stored instead of just its run-time data.
- It should be accessible _without_ loading the full model weights in memory and locking it with ModelLocker.

I got [stumped](https://discord.com/channels/1020123559063990373/1049495067846524939/1134668785475924090) trying to figure out how to get the ModelManager to give me a ModelBase instance for a model it's managing.

This PR includes some refactoring to make that more accessible, and sketches a new ModelManager method to make those instances — but we could also revert that last bit, leaving this PR to be pure refactoring and then work out the details of the new method separately.

Usage looks something like:

```py
from invokeai.app.services.config import InvokeAIAppConfig
from invokeai.backend.model_management import ModelManager

config = InvokeAIAppConfig.get_config()
manager= ModelManager(config.model_conf_path)
m = manager._instantiate('aZovyaPhotoreal_v2', 'sd-1', 'main')
print(m.get_size())
```

## What type of PR is this? (check all applicable)

- [x] Refactor
  + except for the last commit, which demonstrates the motivating factor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- you're looking at it. See also [discord #Refactor Model Management](https://discord.com/channels/1020123559063990373/1135001512456757328/1135286563622895626).

      
## Have you updated all relevant documentation?
- [x] Yes

## Related Tickets & Documents

- Fixes #4128
- #4071 - that effort is much larger in scope

## Added/updated tests?

- [x] Yes
- [ ] No, not yet but geez I hope there are tests for this class

### CODE REVIEW

**Comment by keturn** [comment]
Something else I stumbled over while working on this was the necessity to call `create_key` everywhere, and sometimes `parse_key` would even do string parsing on that to try to restore information from it.

Is there still an API requirement for the key of `ModelManager.models` to be a string, or may we revert to using a (name: str, BaseModelType, ModelType) tuple for they key, skipping the stringificiation?

That doesn't need to be in the scope of this PR, but it would allow streamlining these functions while refactoring them.

**Comment by keturn** [comment]
Now it turns out this **does** fix a bug: the changes by #4061 missed the case of a relative path being used in the VAE override.

**Comment by lstein** [comment]
> Now it turns out this **does** fix a bug: the changes by #4061 missed the case of a relative path being used in the VAE override.

Thanks for catching that.

**Review by lstein — COMMENTED** [review]
This seems to clean up some of the awkwardness nicely. I’ll look at it in greater detail later today and do my review.

**Review by lstein — APPROVED** [review]
LGTM - thank you

**Pull request merged**
