### PR TITLE
Fix Gradient Mask (Canvas) Inpaint Model Support

### LINKED ISSUE #5972: [bug]:  outpainting and inpainting  It gives a very bad result v4.0rc2
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

_No response_

### GPU VRAM

15

### Version number

4.0rc2

### Browser

Opera GX Browser

### Python dependencies

[2024-03-15 20:54:08,268]::[uvicorn.access]::INFO --> 23.150.248.50:0 - "POST /api/v1/images/upload?image_category=general&is_intermediate=true HTTP/1.1" 201
[2024-03-15 20:54:09,284]::[uvicorn.access]::INFO --> 23.150.248.50:0 - "POST /api/v1/images/upload?image_category=mask&is_intermediate=true HTTP/1.1" 201
[2024-03-15 20:54:10,093]::[uvicorn.access]::INFO --> 23.150.248.50:0 - "POST /api/v1/queue/default/enqueue_batch HTTP/1.1" 200
[2024-03-15 20:54:10,725]::[uvicorn.access]::INFO --> 23.150.248.50:0 - "GET /api/v1/queue/default/status HTTP/1.1" 200
  4% 1/26 [00:00<00:08,  2.86it/s][2024-03-15 20:54:11,502]::[uvicorn.access]::INFO --> 23.150.248.50:0 - "GET /api/v1/images/i/16fbb6b5-b922-4f97-80ab-1b175806c7da.png HTTP/1.1" 200
  8% 2/26 [00:00<00:08,  2.86it/s][2024-03-15 20:54:12,124]::[uvicorn.access]::INFO --> 23.150.248.50:0 - "GET /api/v1/images/i/1e1c99bd-6529-4ff0-a59b-748f5ba15645.png HTTP/1.1" 200
 23% 6/26 [00:02<00:07,  2.79it/s][2024-03-15 20:54:13,557]::[uvicorn.access]::INFO --> 23.150.248.50:0 - "GET /api/v1/images/i/baa295c7-cfe0-4f71-b5ce-26bbaf194bab.png HTTP/1.1" 200
100% 26/26 [00:09<00:00,  2.79it/s]
[2024-03-15 20:54:22,196]::[InvokeAI]::INFO --> Graph stats: a4850d08-3a3a-48df-ae2c-873a053e51d5
                          Node   Calls   Seconds  VRAM Used
             main_model_loader       1    0.001s     3.201G
                     clip_skip       1    0.000s     3.201G
                        compel       2    0.001s     3.201G
                         noise       1    0.001s     3.201G
                    img_resize       4    0.423s     3.201G
          create_gradient_mask       1    0.028s     3.201G
                    vae_loader       1    0.000s     3.201G
                           i2l       1    0.582s     4.476G
               denoise_latents       1    9.441s     3.462G
                           l2i       1    1.285s     5.217G
             canvas_paste_back       1    0.280s     3.181G
TOTAL GRAPH EXECUTION TIME:  12.041s
TOTAL GRAPH WALL TIME:  12.054s
RAM used by InvokeAI process: 8.24G (+0.000G)
RAM used to load models: 1.76G
VRAM in use: 3.181G
RAM cache statistics:
   Model cache hits: 4
   Model cache misses: 0
   Models cached: 6
   Models cleared from cache: 0
   Cache high water mark: 2.74/4.00G

[2024-03-15 20:54:23,498]::[uvicorn.access]::INFO --> 23.150.248.50:0 - "GET /api/v1/images/i/3f7e56a5-630d-4dda-a9bd-c2711cebd012.png HTTP/1.1" 200
[2024-03-15 20:54:23,508]::[uvicorn.access]::INFO --> 23.150.248.50:0 - "GET /api/v1/images/i/fbe9f47f-8e97-4119-a006-3746f9d0a090.png HTTP/1.1" 200
[2024-03-15 20:54:24,859]::[uvicorn.access]::INFO --> 23.150.248.50:0 - "GET /api/v1/images/i/fa109ee5-5dd0-4c5a-8e5a-61779c9bfa63.png HTTP/1.1" 200
[2024-03-15 20:54:27,965]::[uvicorn.access]::INFO --> 23.150.248.50:0 - "GET /api/v1/images/i/fbe9f47f-8e97-4119-a006-3746f9d0a090.png/full HTTP/1.1" 200
[2024-03-15 20:54:53,100]::[uvicorn.access]::INFO --> 23.150.248.50:0 - "PUT /api/v1/queue/default/cancel_by_batch_ids HTTP/1.1" 200
[2024-03-15 20:54:55,770]::[uvicorn.access]::INFO --> 23.150.248.50:0 - "GET /api/v1/queue/default/status HTTP/1.1" 200

### What happened

outpainting
opera_ZCBTFRbdpr
 inpainting
opera_S8w5pGPbxW

and this my setting and abort
opera_7s3Dh9pSNX
opera_c5U9ecmmTO
opera_vGHznNrBLM

### What you expected to happen

.

### How to reproduce the problem

_No response_

### Additional context

_No response_

### Discord username

_No response_

### PR DESCRIPTION
**Pull request by dunkeroni**
## Summary

Adds VAE and Image fields to the Create Gradient Mask node so that it can make a masked_latents tensor for inpaint models. Canvas inpaint/outpaint graphs are updated to include the new connections.

This behavior matches what the older Create Denoise Mask node did as well.

## Related Issues / Discussions

Closes #5972 

We've had some back and forth on using the UnetField to check for inpainting type and skip this encode process when it is not needed, but we need a reliable way to test for that on all model formats without loading the model itself (currently it is done by checking the in_channels number). If we come up with a standardized way to query this quality of the model, then we can add that and shave off a bit of time for canvas operations.

## QA Instructions

Please test in Canvas interface, inpainting and outpainting. The inpaint models I have tried work, but we have seen in the past that some don't always behave like the others. Sometimes having a bit of edge_size on the coherence settings helps remove edge line artifacts, sometimes it creates different edge artifacts depending on the mask shape. For best results, start at zero and increase to 16 if necessary.

image

image

image

## Checklist

- [x] _The PR has a short but descriptive title, suitable for a changelog_
- [ ] _Tests added / updated (if applicable)_
- [ ] _Documentation added / updated (if applicable)_

### CODE REVIEW

**Comment by hipsterusername** [comment]
Think it's the right decision to not overinvest in making inpainting optimized for speed, given these models are rarely used. The extra time seems worthwhile

**Comment by dunkeroni** [comment]
> Think it's the right decision to not overinvest in making inpainting optimized for speed, given these models are rarely used. The extra time seems worthwhile

The optimization is not for inpainting models. It's for all other models. Because inpaint models require the extra VAE encode, we are performing that encode on all other models that *don't* require it. But right now we do not have a clean way of distinguishing between the two without an extra unet model load anyway.

So with this we lose a little bit of speed on all masked canvas operations, but we enable inpaint models to work again like they did before.

**Comment by psychedelicious** [comment]
In a discord conversation we discovered that during the MM2 refactor I had inadvertently removed the model variant enum from the diffusers model configs. The values were Normal (4 in-channels), Depth (5 in-channels, SD2.x only), Inpaint (9 in-channels).

To fix this:
- In `invokeai/backend/model_manager/config.py`, move `variant: ModelVariantType = ModelVariantType.Normal` from `MainCheckpointConfig` to `MainConfigBase`, from which both `MainCheckpointConfig` and `MainDiffusersConfig` inherit.
- In `invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelPanel/ModelEdit.tsx`, move the UI for variant select into a different conditional that only checks if the type is `main`, so that it is rendered for all `main` models.
- Update the model probe to correctly set the variant for diffusers models. I think this is already correct, but the variant field is getting stripped out. Fixing the classes as described above _should_ automatically fix this.

Then I believe the changes int his PR could be much simpler.

Users with diffusers inpainting models installed before this fix is rolled out will have incorrectly-configured models. Here are a few ideas to fix existing models:
1. Advise users who encounter mushy inpainting to double check the setting in the model manager tab.
2. When loading a model for inference, if the number of in-channels is not correct for its variant setting, log a warning.
3. Write a migration that loads every main model, double-checks the in-channels and updates the db.

**Comment by dunkeroni** [comment]
Even with that, we would still need the changes in this PR (as they currently are) which allow the gradient mask node to produce a masked_latents. 

If we add support for a quick Unet variant check, then we can add a unet field and only encode when necessary. Right now this PR matches how we previously supported inpaint models prior to 4.0 but now with gradient mask node.

**Comment by psychedelicious** [comment]
@dunkeroni Gotcha, thanks for clarifying that. I've updated this PR:

- Add the model variant to `MainConfigBase`, which makes both ckpt and diffusers models have this field
- Add a small test for the model probe to check that it detects properly (already did)
- Add a the variant field to the UI for diffusers models (cleaned up some UI components while I was there)
- Restore the UNet check in `CreateGradientMaskInvocation`
- Update the graphs to connect the UNet to the node
- Test all combinations of Canvas Inpainting/Outpainting, SD1.5/SDXL models, Inpainting/Normal model variants

Think we are good to go!

**Review by psychedelicious — APPROVED** [review]

**Review by hipsterusername — APPROVED** [review]

**Pull request merged**
