### PR TITLE
Refactor prompting code paths to use the `compel` library

### PR DESCRIPTION
**Pull request by damian0815**
motivation: i want to be doing future prompting development work in the `compel` lib (https://github.com/damian0815/compel) - which is currently pip installable with `pip install compel`.

### CODE REVIEW

**Review by mauwii — APPROVED** [review]
LGTM!

**Comment by psychedelicious** [comment]
The readme dot compel says cross attention is not implemented, is that out of date?

**Comment by damian0815** [comment]
> The readme dot compel says cross attention is not implemented, is that out of date?

sort of. compel doesn't support cross attention control because diffusers doesn't support it, but it will happily parse it.

**Comment by psychedelicious** [comment]
Huh. What does `swap` end up doing then? It seems to work for me.

**Comment by damian0815** [comment]
> Huh. What does `swap` end up doing then? It seems to work for me.

right, so compel is actually designed as a plug-in module for huggingface stuff, means you can do this:

```
from diffusers import StableDiffusionPipeline
from compel import Compel

pipeline = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")
compel = Compel(tokenizer=pipeline.tokenizer, text_encoder=pipeline.text_encoder)

# upweight "ball"
prompt = "a cat playing with a ball++ in the forest"
conditioning = compel.build_conditioning_tensor(prompt)

# generate image
images = pipeline(prompt_embeds=conditioning, num_inference_steps=20).images
images[0].save("image.jpg")
```

and get InvokeAI prompting syntax in your generic diffusers codepath. it'll happily parse .swap() but only Invoke actually konws how to dig into the parsed tree and do something with it. hopefully that makes sense :)

**Comment by keturn** [comment]
There are some dubious parts of our current embedding-weighting implementation, like the handling of [0 < weight < +1.0](https://discord.com/channels/1020123559063990373/1050122220728483940/1057380369105690724).

If I wanted to change how that works, would I still be able to do that within InvokeAI code, or would it require modifying compel?

**Review by keturn — DISMISSED** [review]
Good catch from @hipsterusername on the license: InvokeAI is an MIT-licensed project and cannot depend on anything licensed as AGPL.

**Comment by damian0815** [comment]
> There are some dubious parts of our current embedding-weighting implementation, like the handling of [0 < weight < +1.0](https://discord.com/channels/1020123559063990373/1050122220728483940/1057380369105690724).
> 
> If I wanted to change how that works, would I still be able to do that within InvokeAI code, or would it require modifying compel?

it would require modifying or forking compel, and i don't have plans to change that, but i do want to address that dubiousness, eg with some sort of global flags that determine how weights are calculated, and maybe with a pluggable architecture.

**Review by psychedelicious — CHANGES_REQUESTED** [review]
Two issues:

1. L1258-L1261 `invoke_ai_web_server.py` needs the calls of `compel` functions to be updated to match the new API e.g.

```python
parsed_prompt, _ = get_prompt_structure(
    generation_parameters["prompt"], self.generate.model)
tokens = None if type(parsed_prompt) is Blend else \
    get_tokens_for_prompt(self.generate.model.tokenizer, parsed_prompt)
```

2. Unable to generate when using `swap()` syntax:
```
{'prompt': 'cat.swap(dog)', 'iterations': 1, 'steps': 20, 'cfg_scale': 7.5, 'threshold': 0, 'perlin': 0, 'height': 512, 'width': 512, 'sampler_name': 'k_lms', 'seed': 2364531753, 'progress_images': False, 'progress_latents': False, 'save_intermediates': 5, 'generation_mode': 'txt2img', 'init_mask': '...', 'hires_fix': False, 'seamless': False, 'variation_amount': 0}

>> ESRGAN Parameters: False
>> Facetool Parameters: False
'builtin_function_or_method' object is not subscriptable


Traceback (most recent call last):
  File "/home/bat/Documents/Code/InvokeAI/invokeai/backend/invoke_ai_web_server.py", line 1292, in generate_images
    self.generate.prompt2image(
  File "/home/bat/Documents/Code/InvokeAI/ldm/generate.py", line 510, in prompt2image
    uc, c, extra_conditioning_info = get_uc_and_c_and_ec(
  File "/home/bat/Documents/Code/InvokeAI/ldm/invoke/conditioning.py", line 36, in get_uc_and_c_and_ec
    c, options = compel.build_conditioning_tensor_for_prompt_object(positive_prompt)
  File "/home/bat/invokeai/.venv/lib/python3.10/site-packages/compel/compel.py", line 74, in build_conditioning_tensor_for_prompt_object
    cac_args = self._get_conditioning_for_cross_attention_control(prompt)
  File "/home/bat/invokeai/.venv/lib/python3.10/site-packages/compel/compel.py", line 126, in _get_conditioning_for_cross_attention_control
    to_replace_token_count = self._get_tokens_length([x.text for x in fragment.original])
  File "/home/bat/invokeai/.venv/lib/python3.10/site-packages/compel/compel.py", line 176, in _get_tokens_length
    return sum([len[x] for x in tokens])
  File "/home/bat/invokeai/.venv/lib/python3.10/site-packages/compel/compel.py", line 176, in <listcomp>
    return sum([len[x] for x in tokens])
TypeError: 'builtin_function_or_method' object is not subscriptable
```

Not sure about this one.

**Comment by damian0815** [comment]
@psychedelicious those should both be fixed now, thanks for taking a look

**Comment by psychedelicious** [comment]
Np

Issue 1 is resolved, ty. 

Have a different error with `swap` now (compel==0.1.5): 
```
vokeai_diffusion.py", line 248, in apply_cross_attention_controlled_conditioning__diffusers
    conditioned_next_x = self.model_forward_callback(x, sigma, conditioning,
  File "/home/bat/Documents/Code/InvokeAI/ldm/invoke/generator/diffusers_pipeline.py", line 558, in _unet_forward
    return self.unet(latents, t, text_embeddings,
  File "/home/bat/invokeai/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/bat/invokeai/.venv/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 481, in forward
    sample, res_samples = downsample_block(
  File "/home/bat/invokeai/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/bat/invokeai/.venv/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 789, in forward
    hidden_states = attn(
  File "/home/bat/invokeai/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/bat/invokeai/.venv/lib/python3.10/site-packages/diffusers/models/transformer_2d.py", line 265, in forward
    hidden_states = block(
  File "/home/bat/invokeai/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/bat/invokeai/.venv/lib/python3.10/site-packages/diffusers/models/attention.py", line 307, in forward
    attn_output = self.attn2(
  File "/home/bat/invokeai/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/bat/invokeai/.venv/lib/python3.10/site-packages/diffusers/models/cross_attention.py", line 160, in forward
    return self.processor(
  File "/home/bat/Documents/Code/InvokeAI/ldm/models/diffusion/cross_attention_control.py", line 569, in __call__
    attention_mask = attn.prepare_attention_mask(
TypeError: CrossAttention.prepare_attention_mask() got an unexpected keyword argument 'batch_size'
```

`batch_size` added as a kwarg to `prepare_attention_mask()` in b21bd6f428673448309bf3f096cf884fa713c37f

if I remove that as a kwarg, it works.

**Comment by damian0815** [comment]
> `batch_size` added as a kwarg to `prepare_attention_mask()` in [b21bd6f](https://github.com/invoke-ai/InvokeAI/commit/b21bd6f428673448309bf3f096cf884fa713c37f)

urgh yeah. this is a diffusers 0.13 change that got rolled into invoke main - if you upgrade diffusers to 0.13 it should go away, but i don't know if this is intended or not

**Comment by psychedelicious** [comment]
Yep, diffusers 12.1 was installed. reinstalled it, got 13.1, and this error went away. 

To test that nothing else was affect by recent changes to `main`, I locally rebased `refactor_use_compel` onto `main` (minor manual conflict resolution needed in `args.py`) and reinstalled python packages - all good everything still works.

**Review by psychedelicious — APPROVED** [review]

**Comment by lstein** [comment]
Do we require `diffusers 0.13` to support swap()? This can be done by updating `pyproject.toml`

**Comment by psychedelicious** [comment]
@lstein we require diffusers 13 for this commit anyways https://github.com/invoke-ai/InvokeAI/commit/b21bd6f428673448309bf3f096cf884fa713c37f

13 also includes a fix for dpm samplers on mps 

So the requirements should be updated to req diffusers 13.1.

**Review by lstein — APPROVED** [review]
LGTM

**Comment by lstein** [comment]
> @lstein we require diffusers 13 for this commit anyways [b21bd6f](https://github.com/invoke-ai/InvokeAI/commit/b21bd6f428673448309bf3f096cf884fa713c37f)
> 
> 13 also includes a fix for dpm samplers on mps
> 
> So the requirements should be updated to req diffusers 13.1.

Done. In this PR.

**Comment by blessedcoolant** [comment]
Blend is broken.  `AttributeError: 'Blend' object has no attribute 'children'`

**Comment by damian0815** [comment]
> Blend is broken. `AttributeError: 'Blend' object has no attribute 'children'`

should be fixed now. also legacy ckpt support has been unbroken.

**Review by psychedelicious — APPROVED** [review]
Blend is working and ckpt is working. :+1:

**Review by blessedcoolant — APPROVED** [review]

**Pull request merged**
