### PR TITLE
apply black isort and pyupgrade to all files in v2.3(!) source tree

### PR DESCRIPTION
**Pull request by lstein**
# Enforce `black` style on the `v2.3` branch

- order of application:
   1. pyupgrade --py39-plus **/*.py
   2. isort ldm invokeai
   3. black ldm invokeai

- black default parameters have a short line length; reconsider this

This does the same thing as #2538 , so putting @dsully as coauthor of this PR.

### CODE REVIEW

**Comment by mauwii** [comment]
should we maybe think about including #2687, or move it to v2.3 branch then instead?

**Comment by lstein** [comment]
> should we maybe think about including #2687, or move it to v2.3 branch then instead?

Let's see what pushback comes in on the PR, first.

**Comment by keturn** [comment]
+1 on isort and pyupgrade, but 

**👎 -1** on formatting with `black`. As I raised in discord, `black` produces [results](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AGUAPRdAD2IimZxl1N_WlbvK5V9KEd03r0mK1OKMLFJsqPGy7meyfrF9p2qB1TH5nqEPV0bLtUqPzwL2APm6zbQKJ_orU01eIcPEEB-P1V75I255yr9VVPLZx1to_Era6b8DSXA7JAvAWiytMU0edGDuIfHADVd3pudS63UaDPPWQQLtqNcn8G2GGu750dlB7XTSiicI10w1z0xa_0p1QY2MtgJxAyccCy_oAIDwAHY5WsYPdJoszs9hHS9_1W99CjTw2n4tmGZmfdPtOYZGZHHD689L9_kHE05R_ody1wAJleuQJSAAXjIB8TIlktfINZTS0KzOE1lDwAAvwraKkRmAAgAAZAClQMAADE-KyyxxGf7AgAAAAAEWVo=) that are not a good interpretation of any reasonable coding standard.

**Comment by lstein** [comment]
> +1 on isort and pyupgrade, but
> 
> **👎 -1** on formatting with `black`. As I raised in discord, `black` produces [results](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AGUAPRdAD2IimZxl1N_WlbvK5V9KEd03r0mK1OKMLFJsqPGy7meyfrF9p2qB1TH5nqEPV0bLtUqPzwL2APm6zbQKJ_orU01eIcPEEB-P1V75I255yr9VVPLZx1to_Era6b8DSXA7JAvAWiytMU0edGDuIfHADVd3pudS63UaDPPWQQLtqNcn8G2GGu750dlB7XTSiicI10w1z0xa_0p1QY2MtgJxAyccCy_oAIDwAHY5WsYPdJoszs9hHS9_1W99CjTw2n4tmGZmfdPtOYZGZHHD689L9_kHE05R_ody1wAJleuQJSAAXjIB8TIlktfINZTS0KzOE1lDwAAvwraKkRmAAgAAZAClQMAADE-KyyxxGf7AgAAAAAEWVo=) that are not a good interpretation of any reasonable coding standard.

This type of atrocity can be fixed by increasing the black line length:
```
embedding_info["num_vectors_per_token"] = embedding_info[
                    "embedding"
                ].shape[0]
```
Let me try 128 characters and let me know if the situation has improved.

**Comment by dsully** [comment]
Agreed - we use 120 chars at my workplace. Somewhere between 120 and 140 works best from what I've seen.

**Comment by lstein** [comment]
Tried 128 characters and this fixed up at least some of the crazy word-wraps you were seeing.

**Comment by keturn** [comment]
Sure, if you increase the line length enough, then the formatter never has to reformat anything! That doesn't make it a _good_ formatter.

And now you've just opened the "what is the right line length" can of worms which is a whole thing in itself.

**Comment by lstein** [comment]
@mauwii notes that every reformatted line is going to have me as the author, making `git blame` pretty useless. There's a workaround for this, and I'll mark this PR as draft so that folks can look at the styling and decide if they're comfortable with it. (@keturn 's -1 noted)

**Comment by dsully** [comment]
@keturn That's quite unfair and pessimistic. While line length is part of what `black` does, there are many other benefits it has from parsing the AST. https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html

**Comment by psychedelicious** [comment]
Besides the direct changes a code formatter makes, it makes it easier to navigate the code. A consistent, automatically enforced code style across a project makes it so much easier to grok and so much simpler to contribute.

**Comment by keturn** [comment]
> For me that far outweighs the relatively few instances of unreadable output from the formatter.

Okay but why compromise?

If you describe its output as "unreadable", that should be an auto-fail when evaluating a formatter.

**Comment by ebr** [comment]
for an opinionated formatter, `black` does quite a good job; I wouldn't go as far as calling its output unreadable. With max line length set to 120 characters, the improvement in code style consistency is worthwhile IMO. Besides, `black` supports  the `# fmt: off` directive, so desired formatting can be preserved in those gnarly edge cases.

That said, @keturn: do e.g. `yapf` or `autopep8` do a better job in your experience? `black` is the only one I've used extensively, so can't really compare.

**Comment by psychedelicious** [comment]
Is there a formatter that does it perfectly every time? If so, great. If we can't find it, we make a compromise and choose a formatter that almost always formats well. That's better than the existing compromise of however many different code styles used across the project (often in a single file).

Regarding `black` specifically, we can adjust the line length to avoid the specific instances of unreadable code you pointed out, and as @dsully pointed out, formatters do much more than wrapping lines for you, so even if we set line length to `infinity`, it is still advantageous to use a code formatter.

**Comment by lstein** [comment]
I'll circle back to this later.

**Pull request closed without merging**
