### PR TITLE
Add 'update' action to launcher script

### PR DESCRIPTION
**Pull request by lstein**
- Adds an update action to launcher script
- This action calls new python script `invokeai-update`, which prompts user to update to latest release version, main development version, or an arbitrary git tag or branch name.
- It then uses `pip` to update to whatever tag was specified.

The user interface (such as it is) looks like this:
updater-screenshot

### CODE REVIEW

**Comment by lstein** [comment]
@ebr I cribbed the rich commands from your messages.py script, but I didn't take the time to understand how everything works. Is there a way to put the output messages from pip into a black box the way the welcome text is?

**Comment by ebr** [comment]
I haven't done it with streaming output of a subprocess, but off the top of my head it should be possible using an instance of `rich.Live`, which updates a renderable in realtime. If you don't mind a short delay, I can take a stab at it when I'm back at the computer tomorrow afternoon.

**Comment by lstein** [comment]
> I haven't done it with streaming output of a subprocess, but off the top of my head it should be possible using an instance of `rich.Live`, which updates a renderable in realtime. If you don't mind a short delay, I can take a stab at it when I'm back at the computer tomorrow afternoon.

That would be awesome.

**Comment by ebr** [comment]
@lstein This seems pretty close: 
image

I'm not sure how to get the "Choice: " and the manual entry prompts to fill the line. This might be just  a limitation of terminals with a light background. But it could be a future improvement.

(love the ":crossed_fingers:" by the way ;) )

just pushed a commit implementing this - let me know what you think.

**Review by ebr — APPROVED** [review]
@lstein i'm approving this, pending your acceptance of my changes (the prompt lines are still not styled)

**Comment by lstein** [comment]
> @lstein i'm approving this, pending your acceptance of my changes (the prompt lines are still not styled)

This looks fine. Can @blessedcoolant or @tildebyte have a look?

**Review by blessedcoolant — APPROVED** [review]

**Pull request merged**
