### PR TITLE
Run: pyupgrade --py39-plus **/*.py

### PR DESCRIPTION
**Pull request by dsully**
Remove old Python constructs in the code base.

### CODE REVIEW

**Comment by ebr** [comment]
Love the stylistic improvements! Thanks for this. Breadth of these changes may require pretty extensive testing... @lstein should we do this now, or as part of the big refactor planned for the `nodes` epic?

**Comment by lstein** [comment]
> Love the stylistic improvements! Thanks for this. Breadth of these changes may require pretty extensive testing... @lstein should we do this now, or as part of the big refactor planned for the `nodes` epic?

I'm scared of merging all these changes on the eve of a release, so would prefer to do this after 2.3.0 goes out. Accordingly I'm marking this as a draft.

I would also like to implement `black` and `isort` processing on all PRs in order to clean up formatting and make it consistent.

**Comment by lstein** [comment]
> No problem. I'll rebase after the release is out.

Following up on this. We currently have a bunch of conflicts so it would be good to resolve and get this merged ASAP. How do you want to split the chore?

**Comment by dsully** [comment]
It's easy enough to just re-run `pyupgrade`. I'll have time shortly.

**Comment by lstein** [comment]
Indeed! We'll likely have to do this on several of the PRs that are waiting in the wings. Let me try to get them reviewed and merged into main so that we can reduce the number of conflicts that occur.

**Comment by dsully** [comment]
@lstein This is ready to go.

**Comment by lstein** [comment]
Thanks! It's going to go in just before the 2.3.1 release candidate so that it doesn't create a whole bunch of conflicts with other pending PRs.

**Review by lstein — APPROVED** [review]
Approved - but do NOT merge until just before the 2.3.1 release candidate. I'll hit the merge button.

**Comment by lstein** [comment]
@dsully I made you coauthor of #2819 , which this PR inspired.

**Comment by dsully** [comment]
Thanks @lstein - hope to have more time to contribute soon.

**Pull request closed without merging**
