### PR TITLE
I18n es

### PR DESCRIPTION
**Pull request by dreglad**
Adding Spanish translations to Web UI

### CODE REVIEW

**Comment by dreglad** [comment]
I'm not sure if I should have included the bundle in `/dist` as well. I guess you may not trust  external collaborators' transpiled code blindly as being safe/correct even if best intention assumed.  Maybe moving bundle build and commit into CI (and even .gitignoring the whole `/dist` afterwards is a good idea

**Comment by blessedcoolant** [comment]
Thank you for this PR. I'm getting done with the model manager. There's some new strings in there. Once that is up, I'll ping you here so you could update the new strings and we can merge the whole Spanish localization all together.

**Comment by blessedcoolant** [comment]
@dreglad Model Manager has been merged. It has some updated strings for that part. If you update the PR an rebase, I'll be happy to review and merge it. Thank you for your work on this.

**Comment by dreglad** [comment]
@blessedcoolant   All right, rebased master into my branch and updated Spanish translations accordingly

**Comment by blessedcoolant** [comment]
> @blessedcoolant All right, rebased master into my branch and updated Spanish translations accordingly

Hey thank you. The tooltips have also been localized. The file is missing from your translations. If you do not wish to translate those, you can just create an empty es file. Coz once a language is added, we need the file as a place holder with empty brackets.

I think after the tooltip localization is done, we are good to go to merge this. Rest of it seems fine.

**Review by blessedcoolant — APPROVED** [review]

**Comment by blessedcoolant** [comment]
This is good to go. Thanks for your work @dreglad .. I rebased it and made a small fix that was needed. It'll get merged when the checks are through.

@lstein I packed thet 2.2.5 WebUI Frontend Build in this PR. Please merge it with your 2.2.5 PR after this is merged.

**Comment by dreglad** [comment]
> Hey thank you. The tooltips have also been localized. The file is missing from your translations. If you do not wish to translate those, you can just create an empty es file. Coz once a language is added, we need the file as a place holder with empty brackets.

You are right, I didn't notice tooltips. I just added those translations now.

**Pull request merged**
