### PR TITLE
docs/features/NODES.md - Fix image links

### PR DESCRIPTION
**Pull request by ymgenesis**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [x] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [x] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [x] Yes
- [ ] No

## Description

Updated broken image links in NODES.md

### CODE REVIEW

**Comment by Millu** [comment]
Thanks for updating these! 

For the future, you can link images in the docs with the relative path like this: `image` (assuming the images have been added to the assets/sub_folder folder)

**Review by lstein — CHANGES_REQUESTED** [review]
I don't think it's a great idea for us to rely on a third party image-serving service for this. Could you move the images into the repo under `./docs/assets/nodes/` and refer to them using markdown following this format:

```
![groupsnoise](../assets/nodes/groupsnoise.png"){width=654px }
```

It looks like the original author of NODES.md didn't realize that the docs would be passed through mkdocs before publication, and I didn't notice all the broken image icons till just now.

**Comment by ymgenesis** [comment]
@lstein Done. I had written the documentation originally, and wasn't aware of the process the assets would go through after being committed. Should be all good now!

**Review by hipsterusername — APPROVED** [review]
Thanks for the updates!

**Pull request merged**
