### PR TITLE
Support the PyTorch extra-index-url in updater

### PR DESCRIPTION
**Pull request by ebr**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [x] Bug Fix
- [ ] Optimization
- [x] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [x] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [x] Yes
- [ ] No

## Description

Adds support for `--extra-index-url` CLI flag when updating Invoke, which should fix PyTorch update issues, especially on Windows.

We try to infer whether the system supports CUDA by looking for installed Nvidia runtime libraries in the current virtual environment. We check for both CUDA 11.8 and 12.1 versions, because either might be installed depending on the virtual environment's age. If any are found, we install the CUDA version of Torch. If none are found, we ask the user for input.

Also this PR adds an option to pass the `--force-reinstall` flag at update time - this may help fix broken installs.

Also, it updates the Torch ROCm version to 5.6 (this only applies to Linux). 5.6 has already been tested in the Docker setup, and we haven't heard of any issues.

## Related Tickets & Documents

- Partially addresses #5507 

## QA Instructions, Screenshots, Recordings

- Tested on: Linux+CPU, Linux+CUDA, but could use more pairs of eyes.
- Needs testing on: Windows+CUDA... maybe macOS? I do not have access to a Windows box to test with at the moment.

A way to test this might be:

### "CUDA happy path":
- check out a `v3.5.x` tag and install on Windows in editable mode in a *new* virtual environment (`pip install -e ".[dev,xformers]" --use-pep517 --extra-index-url https://download.pytorch.org/whl/cu121`. This should install Torch with CUDA support.
- *replace* the update script with a copy from this branch (`git checkout ebr/updater-extra-index-urls invokeai/frontend/install/invokeai_update.py`)
- activate the virtual env
- run `invokeai-update` and update to latest release (`v3.6.2` as of this writing). The script should *not* ask for the GPU type - it should infer this from the installed `nvidia` runtime libs. The upgrade should proceed, and Torch should still have CUDA support after the upgrade.

### "CPU > CUDA happy path":
- delete the virtual env created above
- repeat the test without specifying the `--extra-index-url` when first installing the 3.5 release
- the update script *should* now ask for the GPU type, because it won't be able to infer it. Select Nvidia and proceed.
- this should now result in a CUDA-enabled Torch install.

### Additional tests:
- repeat the above over an environment created by the packaged installer
- validate that updating on Linux+ROCm + MacOS doesn't break

## Merge Plan

- "This PR can be merged when approved"

## Added/updated tests?

- [ ] Yes
- [x] No : there are no current tests for the updater and I did not contribute any here.

### CODE REVIEW

**Review by Millu — COMMENTED** [review]
Works great on macOS! Unfortunately cannot test on Windows

**Comment by psychedelicious** [comment]
Just raising this again - the function to get pypi versions has a problem where it classifies alpha/dev releases official. This will eventually cause problems. Something like this fixes it https://gist.github.com/psychedelicious/d589c53284f88cad3ea57f320b21687c

**Comment by ebr** [comment]
> Just raising this again - the function to get pypi versions has a problem where it classifies alpha/dev releases official. 

That's right - this PR does not address that - aiming to get the index url stuff sorted first.

For versioning, we might be able to just use the `pip install --pre` [flag](https://pip.pypa.io/en/stable/cli/pip_install/#pre-release-versions), without doing any parsing, because our versions already follow the [PEP440 versioning spec](https://packaging.python.org/en/latest/specifications/version-specifiers/#public-version-identifiers). I'll test that out separately

**Comment by hipsterusername** [comment]
> Traceback (most recent call last):
>   File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Python310\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\kentr\Invoke\testvenv\Scripts\invokeai-update.exe\__main__.py", line 7, in <module>
>   File "C:\Users\kentr\InvokeAI\invokeai\frontend\install\invokeai_update.py", line 194, in main
>     if (index_url := get_torch_extra_index_url()) is not None:
>   File "C:\Users\kentr\InvokeAI\invokeai\frontend\install\invokeai_update.py", line 118, in get_torch_extra_index_url
>     resolved_url = torch_package_urls[f"linux_{device}"]
> KeyError: 'linux_cuda'

On windows

**Comment by hipsterusername** [comment]
Looks like this line has linux hardcoded 

>         if device == "cuda":
>             resolved_url = torch_package_urls[f"linux_{device}"]

**Comment by ebr** [comment]
copypasta strikes again! sorry about that - fixed

**Review by hipsterusername — APPROVED** [review]

**Comment by ebr** [comment]
Ok, that makes sense. we need the installer to be able to update. I think we should merge this for the sake of `--extra-index-url`, and I'll continue iterating

**Pull request merged**
