### PR TITLE
Bug Fix: Model import fixes

### PR DESCRIPTION
**Pull request by lstein**
These bug fixes address issues #1546 and #1547 .

### CODE REVIEW

**Comment by lstein** [comment]
Some of the CI tests are crashing. Will not merge until fixed.

**Comment by lstein** [comment]
@damian0815 Can I get your review on this PR? You reported the bugs originally.

**Review by damian0815 — CHANGES_REQUESTED** [review]
this doesn't fix #1546, which is about autocomplete not working and models subsequently not loading using `!import_model` with a `--root` folder. i just checked out this branch and the problem described in #1546 persists.

**Comment by lstein** [comment]
@damian0815 Do you prefer the autocomplete to root itself in the ROOTDIR or in ROOTDIR/models/ldm/stable-diffusion-v1/ ?

I've tried it both ways and find it more natural feeling if it starts in the ROOTDIR and then you navigate your way through models, etc, rather than starting in stable-diffusion-v1 and possibly wanting to navigate up.

**Comment by damian0815** [comment]
> @damian0815 Do you prefer the autocomplete to root itself in the ROOTDIR or in ROOTDIR/models/ldm/stable-diffusion-v1/ ?

definitely ROOTDIR. the bug actually appeared when i had SD2.0 models in `ROOTDIR/models/ldm/stable-diffusion-v2/`, and on runpod i'll often just drop model files in `ROOTDIR/..`

**Review by damian0815 — APPROVED** [review]
this works exactly as required, thank you. approved.

**Pull request merged**
