### PR TITLE
add statement of values

### PR DESCRIPTION
**Pull request by lstein**
This PR adds the statement of values from https://docs.google.com/document/d/1-PrUKDJcxy8OyNGc8CyiHhv2VgLvjt7LRGlEpbg1nmQ/edit?usp=sharing that we've been working on for some time now. Feel free to add your name to this file.

### CODE REVIEW

**Review by netsvetaev — APPROVED** [review]

**Comment by damian0815** [comment]
there's something of a disorienting tonal lurch between the gravity of the ethics statement and then the list of roles that is has terms like "wizard" and "gameplay engineer" in it - these should be separate documents i think

**Review by mauwii — APPROVED** [review]
LGTM

**Comment by psychedelicious** [comment]
I agree with @damian0815 that the vibe is a kinda weird with the fun roles vs the more serious statement. Let's just have our names/usernames there as signatories - the statement doesn't really care what our roles are anyways, more that we are the core contributors and all agreed to the statement.

**Comment by blessedcoolant** [comment]
Maybe the entire Who's Who thing has no place in the Ethics statement. We should just have a different members doc for that.

The ethics statement should be from the overall team no matter who joins or leaves it. So I feel its overall better to not have individual names mentioned on this particular doc.

**Comment by hipsterusername** [comment]
> Maybe the entire Who's Who thing has no place in the Ethics statement. We should just have a different members doc for that.
> 
> The ethics statement should be from the overall team no matter who joins or leaves it. So I feel its better to not have individual names mentioned on this particular doc.

I think makes the most sense - “who’s who” can be in a readme or other team.md doc

**Comment by damian0815** [comment]
I'm making what seems to be the collectively-agreed changes, will push to the branch soon.

**Comment by damian0815** [comment]
[d6d9a3a](https://github.com/invoke-ai/InvokeAI/pull/1584/commits/d6d9a3ae6a4044b592e4512cf0724d07319c44a9) breaks up the text
[9901de3](https://github.com/invoke-ai/InvokeAI/pull/1584/commits/9901de3058305fb43aa196d693ca82475261f285) is a small copy edit that removes a repeated word and reduces the claim of "many artists" on the team to "several artists" - i think it's important not to overstate our credentials here.

**Review by lstein — COMMENTED** [review]
The changes look good to me.

**Comment by hipsterusername** [comment]
Also LGTM! Good adds @damian0815

**Comment by blessedcoolant** [comment]
LGTM

**Review by blessedcoolant — APPROVED** [review]

**Review by hipsterusername — APPROVED** [review]

**Pull request merged**
