### PR TITLE
[WebUI] Add Hotkey Support

### PR DESCRIPTION
**Pull request by blessedcoolant**
Addresses: #921

Added Hotkey support for the WebUI.

Here are the initial set of hotkeys. Test them out and see how they feel. If they feel good, I'll finalize them and convert this PR to finished. Leaving it on draft at the moment.

Ctrl + Enter = Invoke
Shift + X = Cancel
S = Set Seed
A = Set Parameters
R = Restore Faces
U = Upscale Image
I = Show Metadata
Shift + I = Set Init Image
Del = Delete
Alt + A = Prompt Focus

There is a modal in the UI now that can help you with all the set hotkeys.

firefox_0Hr2NVh1PA

### CODE REVIEW

**Comment by blessedcoolant** [comment]
@lstein Please merge this before #947.

**Comment by griffwill** [comment]
This is working great. I have found one oddity with a Mac keyboard: the "delete" function seems to be mapped to forward-space delete, requiring the use of fn+delete natively on Mac keyboards.

**Comment by blessedcoolant** [comment]
> This is working great. I have found one oddity with a Mac keyboard: the "delete" function seems to be mapped to forward-space delete, requiring the use of fn+delete natively on Mac keyboards.

I'm unfamiliar with the workings of a Mac keyboard. Maybe @psychedelicious can suggest a fix for this.

**Review by lstein — APPROVED** [review]
Looks good.

**Pull request merged**
