### PR TITLE
Give user option to disable the configure TUI during installation

### PR DESCRIPTION
**Pull request by lstein**
## What type of PR is this? (check all applicable)

- [X] Feature

## Have you discussed this change with the InvokeAI team?
- [X] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [X] No - this should go into release notes.

## Description

During installation, the installer will now ask the user whether they wish to perform a manual or automatic configuration of invokeai. If they choose automatic (the default), then the install is performed without running the TUI of the `invokeai-configure` script. Otherwise the console-based interface is activated as usual.

This script also bumps up the default model RAM cache size to 7.5, which improves performance on SDXL models.

### CODE REVIEW

**Comment by lillekemiker** [comment]
https://github.com/invoke-ai/InvokeAI/pull/4675
to fix style checks

**Comment by hipsterusername** [comment]
I fear configuring a static cache amount / should we not be basing this off the amount of RAM the user has in some fashion?

**Comment by psychedelicious** [comment]
Hmm yeah maybe we should default to no cache at all? It may be easier to handle the initial install automatically, but then direct users to consider updating their cache sizes in the yaml.

**Comment by lstein** [comment]
I’d rather select the RAM cache based off of total RAM than disable the cache completely. Without cache users will have miserable performance; every model will be loaded from disk before each generation. Currently, the code makes the RAM cache 7.5 GB, which is large enough to hold a single SDXL model. Typical RAM is 16-32 GB, but I suppose there could be some users with only 8. How about the following table of defaults?

```
RAM  (GB)       CACHE SIZE
——————         —————
8                 0
16                4
32               7.5
64               15

**Comment by psychedelicious** [comment]
Yeah, that makes sense.

Regarding the default values - I think it's fairly safe to assume that if a user is loading up invokeai to generate, they likely want to use their system to the fullest. 

I'd be inclined to bump the RAM cache defaults to half the system RAM.

**Comment by lstein** [comment]
> Yeah, that makes sense.
> 
> Regarding the default values - I think it's fairly safe to assume that if a user is loading up invokeai to generate, they likely want to use their system to the fullest.
> 
> I'd be inclined to bump the RAM cache defaults to half the system RAM.

I think that's too aggressive. Without any models loaded the web server uses nearly 2GB of RAM. So add 4 GB of RAM cache to that and you've only got 2 GB of free memory left on a 8G machine. On the other end, I've got a 64 GB machine. Do I really want 32 GB going to Invoke?

**Comment by lstein** [comment]
Latest commit uses this logic:
```
    return (
        15.0 if MAX_RAM >= 60 else 7.5 if MAX_RAM >= 30 else 4.0 if MAX_RAM >= 14 else 2.1
    )
```

On my system, at least, `psutil.virtual_memory().total` is not returning slightly lower numbers than expected for the installed RAM in the system, so I have chosen slightly lower threshold values. The lowest value, 2.1, is enough to hold SD-1.5 without reloading.

**Comment by hipsterusername** [comment]
This seems fair

**Review by psychedelicious — APPROVED** [review]

**Review by hipsterusername — APPROVED** [review]

**Pull request merged**
