### PR TITLE
replace legacy setup.py with pyproject.toml

### PR DESCRIPTION
**Pull request by mauwii**
other changes which where required:
- move configure_invokeai.py into ldm.invoke
  - update files which imported configure_invokeai to use new location:
    - ldm/invoke/CLI.py
    - scripts/load_models.py
    - scripts/preload_models.py
- update test-invoke-pip.yml:
  - remove pr type "converted_to_draft"
  - remove reference to dev/diffusers
  - remove no more needed requirements from matrix
  - add pytorch to matrix
  - install via `pip3 install --use-pep517 .`
  - use the created executables
  - this should also fix configure_invoke not executed in windows

To install use `pip install --use-pep517 -e .` where `-e` is optional

### CODE REVIEW

**Comment by mickr777** [comment]
not sure if you wanted testing but installs fine on ubuntu 22.04, I used `pip install --use-pep517 -e .`

**Comment by lstein** [comment]
> not sure if you wanted testing but installs fine on ubuntu 22.04, I used `pip install --use-pep517 -e .`

Yes, your testing is greatly appreciated!!

**Comment by ebr** [comment]
`pyproject.toml` changes look good

can I ask to please not modify `configure_invokeai.py` and related changes from your first point in the description, because I'm already making similar changes (and more) to all of that in #2292? Is it possible to keep the changes here limited to `pyproject.toml` and the CI workflows?

**Comment by mauwii** [comment]
> `pyproject.toml` changes look good
> 
> can I ask to please not modify `configure_invokeai.py` and related changes from your first point in the description, because I'm already making similar changes (and more) to all of that in #2292? Is it possible to keep the changes here limited to `pyproject.toml` and the CI workflows?

Since I do not want to include the scripts folder in the package I need to move configure_invokeai.py, but that's all I do with it, I do not change anything in it.

After looking at your PR, I could mimic the file structure and put it to `ldm/invoke/config/configure_invokeai.py` if that would help you?

**Review by ebr — APPROVED** [review]

**Review by lstein — APPROVED** [review]
I think we should merge this now. After the merge there will be a few more things to fix with respect to new scripts that have been added recently (merge and textual inversion script).

**Pull request merged**
