### PR TITLE
Add arguments to use SSL with webserver

### PR DESCRIPTION
**Pull request by javl**
This adds two optional arguments to start the web server with SSL enabled; `--certfile` and `--keyfile`.
For example:
`.venv/bin/python scripts/invoke.py --web --host 192.168.1.10 --port 8080 --certfile keys/cert.pem --keyfile keys/privkey.pem`

--

Note: I think the message

    Default host address now 127.0.0.1 (localhost). Use --host 0.0.0.0 to bind any address.

needs to be moved, as it is now shown when using a custom `--host` which doesn't seem to fit with the message, but I left it in to not clutter this PR's code change.

### CODE REVIEW

**Comment by Kyle0654** [comment]
Seems straightforward enough to me. I think the backend for the webui has diverged some though - @psychedelicious for your awareness.

Also https://github.com/invoke-ai/InvokeAI/pull/1047 will move to a FastAPI backend. You may want to submit a PR against that too.

**Review by Kyle0654 — APPROVED** [review]
LGTM

**Review by psychedelicious — APPROVED** [review]
I've generated a self-signed cert and tested - works fine. Thanks @javl !

**Comment by javl** [comment]
@psychedelicious Thanks for the merge!
Those failed checks seem to be unrelated to my change, right?

**Comment by psychedelicious** [comment]
>  Those failed checks seem to be unrelated to my change, right?

Yeah, not related to your changes. All good.

**Comment by lstein** [comment]
Note to self: Waiting on completion of CI checks before merging.

**Comment by lstein** [comment]
CI checks are failing, but I think this is because it has old version of `configure_invokeai.py`.

**Review by lstein — APPROVED** [review]

**Comment by lstein** [comment]
It looks like ssl support was added in merge from PR #1576 and there are no more diffs with `development`. So I'm closing this. If this was closed in error please reopen and/or let me know.

**Comment by psychedelicious** [comment]
That correct, this PR was cherry picked into a different PR which was merged to dev during our final prep for v2.2

**Pull request closed without merging**
