### PR TITLE
Fix(backend): Denoise Masks being applied at the wrong time

### LINKED ISSUE #5966: [bug]: gradient denoising causes artifacts in combination with LCM
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

macOS

### GPU vendor

Apple Silicon (MPS)

### GPU model

_No response_

### GPU VRAM

24

### Version number

4.0.0rc2

### Browser

Chrome

### Python dependencies

_No response_

### What happened

In the release candidates for v4.0.0 gradient denoising was introduced for the canvas:

> The canvas uses a new method for compositing called gradient denoising. This eliminates the need for multiple “passes”, greatly reducing generation time on the canvas. This method also provides substantially improved visual coherence between the masked regions and the rest of the image.
The compositing settings on canvas allow for control over the gradient denoising process.

However in combination with the LCM Scheduler this causes heavy artifacts (probably due to the low amount of steps used with LCM)

### What you expected to happen

Either gradient denoising should work seamlessly in combination with LCM or the option to fall back to the old inpainting methods with a coherence pass should be available.

### How to reproduce the problem

Use inpainting on the unified canvas with the LCM Scheduler, an LCM-Model (or Lora) and 6-8 steps

### Additional context

An example of the artifacts that are produced by inpainting with 4.0.0:

image
image
image

The same setup produces "normal" inpainting results in Invoke v3.x.x 

### Discord username

_No response_

### PR DESCRIPTION
**Pull request by dunkeroni**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [x] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [x] Yes
- [ ] No

## Description
Denoise Mask was being applied at the wrong time in the step loop, creating an off-by-one error. Each step during masked denoise was computing based on an unmasked region that was 1 step more noised than it should have been. 

## Related Tickets & Documents
- Closes #5966 

## QA Instructions, Screenshots, Recordings
This effect has been seen regularly in SDXL inpainting, since those models are better at matching the surrounding textures during denoising. It was most prevalent on smooth or otherwise featureless backgrounds. In anime models, it tends to present as sparkles or polkadots.
image
  
image

With very low step counts (8-step LCM) there was a fringe effect noticed on the edges of expanded masks.

image

### Results after fix

image

image

Inpainting LCM still has some color drift, possibly affected by the VAE round trip. That can be investigated later on. The noise artifacting at least is gone.

image

## Merge Plan
This PR can be merged when approved

## Added/updated tests?

- [ ] Yes
- [x] No : does not affect API for the diffusion pipeline

### CODE REVIEW

**Comment by blessedcoolant** [comment]
The results seem fine but the progress images not show that the entire image is being denoised rather than just the area. Is that intended?

**Comment by dunkeroni** [comment]
> The results seem fine but the progress images not show that the entire image is being denoised rather than just the area. Is that intended?

It's expected, not intended. Previously the code was acting on all tensors in step_output with a special case to detect and replace the values in the "predicted original sample". The result of this process converges to the initial image, but the callback gets a preview that is updated each step.

We can add some extra code to capture this again if we want previews to be more stable.

Incidentally, it looks like some samplers call that output "denoised" so we weren't applying that logic to all samplers anyway.

**Comment by hipsterusername** [comment]
Think it’s a nice to have if we can get the preview back, but I think it should be a follow on. This is solving a big pain point on inpainting that I think worth getting in ASAP

**Review by hipsterusername — APPROVED** [review]

**Comment by psychedelicious** [comment]
> Incidentally, it looks like some samplers call that output "denoised" so we weren't applying that logic to all samplers anyway.

I've noticed this at some point and was wondering what was happening! Good to know.

@dunkeroni Barring a fix for the progress images, is there any reason to not merge this?

**Comment by dunkeroni** [comment]
> @dunkeroni Barring a fix for the progress images, is there any reason to not merge this?

I was going to explain a framework for how I want to hijack the denoise_mask input on the node and generalize it into a denoise_guidance type that allows code injection into multiple points from other nodes... but for now here's a patch that makes the inpaint preview work again.

Also I was wrong. It's just LCM sampler that uses "denoised". A lot of the others have no field at all. This patch just takes whatever is there if there is something and otherwise uses the current latents to create a "pred_original_sample" that the progress callback can use.

**Review by blessedcoolant — APPROVED** [review]

**Comment by blessedcoolant** [comment]
Tested. Seems good. Works as advertised. Great job.

**Comment by psychedelicious** [comment]
Thanks dunkeroni

**Pull request merged**
