### PR TITLE
add --version to invoke.py arguments

### PR DESCRIPTION
**Pull request by lstein**
This commit allows invoke.py to print out its name and version number when given the --version argument. I had to move some status messages around in order to make the output clean.

There is still an early message about initializing patchmatch that interferes with a clean print of the version, and in fact the --no-patchmatch argument is not doing anything. This will be the subject of a subsequent PR.

### CODE REVIEW

**Comment by lstein** [comment]
Not ready go to. Withdrawing.

**Comment by lstein** [comment]
This is ready for review.

**Comment by ebr** [comment]
I'll try to test this later tonight, but noticed that an empty [create_installer.sh](https://github.com/invoke-ai/InvokeAI/pull/2038/files#diff-4b95465c252225665f0eb0715cf526818c2f78ac544ec900ec6485f3565371a1) file was added - is this intentional?

**Review by mauwii — APPROVED** [review]

**Review by ebr — APPROVED** [review]
LGTM! I tried to take a stab at avoiding the patchmatch messages, but quickly folded :)

(question about the empty `installer/create_installer.sh` still remains though)

**Comment by mauwii** [comment]
> (question about the empty `installer/create_installer.sh` still remains though)

This is really strange, since it is only empty when viewed in this PR, but when I check out the PR it is not empty, also not empty when I [view the File in the Commit](https://github.com/invoke-ai/InvokeAI/blob/cd64c5c7464df4d211d426c2d6c2395aeb1b34da/installer/create_installer.sh) itself.

So let's knock on wood that this is only a bug in GitHub's WebUI 🙈

**Comment by ebr** [comment]
ok, I see what happened - the permissions were adjusted from 0755 to 0644, i.e. `create_installer.sh` was made non-executable. @lstein , was that intentional?

**Pull request merged**
