### PR TITLE
feat: :sparkles: "Remix Image" option on images

### LINKED ISSUE #5552: [enhancement]: "Remix Image" option in context menu
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

_No response_

### What should this feature add?

Add an option to context menus to recall all parameters of an image **_without_** the seed.

### Alternatives

_No response_

### Additional Content

_No response_

### PR DESCRIPTION
**Pull request by joshistoast**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [x] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [ ] Yes
- [x] No

## Description
Adds a new "remix image" option where applicable, recalls all metadata except the seed. This is useful because I frequently find myself clicking "Use All" on an image but I don't want the seed.

## Related Tickets & Documents

- Closes #5552 

## Added/updated tests?

- [ ] Yes
- [x] No : I don't wanna

### CODE REVIEW

**Review by hipsterusername — APPROVED** [review]

**Comment by hipsterusername** [comment]
This is a great addition. Thanks 🙌

**Comment by hipsterusername** [comment]
@psychedelicious - Please take a peek and see if need to incorporate anything into tests or address anything else before merging, then I'll get it in.

**Review by psychedelicious — CHANGES_REQUESTED** [review]
Can you pls add the hotkey to the hotkeys modal? It's in here `invokeai/frontend/web/src/features/system/components/HotkeysModal`

I noticed the canvas already uses the 'r' hot key, but it shouldn't conflict bc this hotkey is only on t2i/i2i tabs.

**Review by psychedelicious — APPROVED** [review]
Thanks!

**Pull request merged**
