### PR TITLE
3.0 Pre-Release Polish -- Bug Fixes / Style Fixes / Misc

### LINKED ISSUE #3780: [bug]: Canvas editor cuts off while gallery is pinned and using G hotkey to toggle gallery pane
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

16gb

### What version did you experience this issue on?

13.4.1

### What happened?

The Canvas ui cuts off while gallery is pinned and using G hotkey to toggle gallery pane. It is fine while gallery is unpinned. Also noticed when you use the shift+G hotkey to unpin the gallery the ui cuts off.

### Screenshots

https://github.com/invoke-ai/InvokeAI/assets/25252829/e5ce86d8-fa64-4c44-9be3-7c3ebe57df13

### Additional context

Currently using main.

### Contact Details

_No response_

### PR DESCRIPTION
**Pull request by blessedcoolant**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Have you discussed this change with the InvokeAI team?
- [x] Yes
- [ ] No, because:

      
## Description

Making some final style fixes before we push the next 3.0 version tomorrow.

- Fixed light mode colors in Settings Modal.
- Double checked other light mode colors. Nothing seems off.
- Added Base Model badge to the model list item. Makes it visually better and also serves as a quick glance feature for the user.
- Some minor styling updates to the Node Editor.
- Fixed hotkeys 'G' and 'O', 'Shift+G' and 'Shift+O' used to toggle the panels not resizing canvas. #3780
- Fixed hotkey 'N' not working for Snap To Grid on Canvas.
- Fixed brush opacity hotkeys not working.
- Cleaned up hotkeys modal of hotkeys that are no longer used.
- Updated compel requirement to `2.0.0`

## Related Tickets & Documents

- Related Issue #
- Closes #3780

## Added/updated tests?

- [ ] Yes
- [x] No : _please replace this line with details on why tests
      have not been included_

### CODE REVIEW

**Comment by blessedcoolant** [comment]
@lstein Leaving a note here too in case it gets lost on Discord. Merge this in before you release the next beta please. Thank you.

**Comment by mickr777** [comment]
not sure if you want to look at this, but the load more arrow on the t2i has stopped working (does not load more images)

this button: (not sure when it stopped working)
image

**Comment by blessedcoolant** [comment]
> not sure if you want to look at this, but the load more arrow on the t2i has stopped working (does not load more images)
> 
> this button: (no idea when it stopped working) image

I saw the icon earlier today and it vanished on refresh. I presumed it was a bug. Didn't realize it was for load more. I'll take a look. But might be a while. If you spot it in the meanwhile, feel free to make a PR. I can merge that in here.

**Review by lstein — APPROVED** [review]
LGTM

**Review by psychedelicious — APPROVED** [review]

**Pull request merged**
