### PR TITLE
feat(nodes): WIP restricted invocation context

### LINKED ISSUE #4887: [enhancement]: Invocation Context is too powerful and should have a restricted API
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

_No response_

### What should this feature add?

The Invocation Context provided in an invocation's `invoke()` method is too powerful. An invocation can totally wreck and install, delete images/models/etc through this interface. A restricted wrapper should be created that exposes a limited API.

### Alternatives

_No response_

### Additional Content

_No response_

### PR DESCRIPTION
**Pull request by psychedelicious**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Description

**Note: this PR is based on the #4758 branch**

feat(nodes): WIP restricted invocation context

This is a first draft of a restricted `InvocationContext`, which is provided to all nodes.

### Motivation

The existing`InvocationContext` class has two issues.

#### 1. Too powerful

It's entirely possible that a node could wreck an installation by accidentally calling a destructive method or something like that. 

Also, the application relies on nodes to be well-behaved and never do certain things (like delete images), so we should just enforce this explicitly.

It's probably not possible to prevent a node from doing something naughty if it wants to, but we can reduce the chance of unintentional footgunning to almost zero by providing a restricted API.

#### 2. Too low-level/complicated

Many of the service methods are low-level and present an awkward API.

Consider the method to save an image:
```py
image_dto = context.services.images.create(
    image=image,
    image_origin=ResourceOrigin.INTERNAL,
    image_category=ImageCategory.GENERAL,
    node_id=self.id,
    session_id=context.graph_execution_state_id,
    is_intermediate=self.is_intermediate,
    metadata=self.metadata.model_dump() if self.metadata else Non
    workflow=self.workflow,
)
```

There's a crapload of fluff here that nodes shouldn't need to worry about. It's mostly boilerplate.

### Draft API

The full-fat context is now called `AppInvocationContext`, and the restricted one is `InvocationContext`. These names can be changed, I just did this so I didn't have to change a bazillion imports in all nodes while testing.

See `base_invocation.py` for the full implementation - it's a simple wrapper.

Example improved method:

The above `create()` method is reduced to this:
```py
image_name = context.save_image(image)
```

The other methods don't have as drastic an improvement but they are all improved.

### Discussion points

In addition to the design and implementation, there are a few points that probably warrant discussion.

1. Core vs community nodes

This restricted API is currently set up to apply to all nodes - core, InvokeAI-managed nodes and future community nodes.

Do we want to maybe let core nodes get access to the original, full-fat context, and only give the restricted context to community nodes?

2. Power creep

So far, I've implemented most of what our core nodes use. What if community nodes want more access - say, to star images? How do we decide what makes the cut?

3. Exposing extra stuff in the context

There are some constants/enums/things that we want to provide to nodes. We can do that via the context, as opposed to via imports.

Example:
Images have categories, which are selected via the `ImageCategory` enum - see the `create()` method above for how it works in the current release.

In this PR, I've exposed that enum as `context.categories` and made this an optional arg:
```py
context.save_image(image, category=context.categories.GENERAL)
```

This feels neat and tidy but I'm unsure if it's a good idea. Maybe the context should be methods and context attributes only?

## Related Tickets & Documents

- Related Issue #
- Closes #4887

## QA Instructions, Screenshots, Recordings

You can test this now, using a simple txt2img workflow with sd1.5 (other nodes are not migrated). You'll first need to run `pip install -e ".[dev,test]"` to get pydantic v2 installed.

[simple t2i.json](https://github.com/invoke-ai/InvokeAI/files/12915130/simple.t2i.json)

## Added/updated tests?

- [ ] Yes
- [ ] No : _please replace this line with details on why tests
      have not been included_

### CODE REVIEW

**Comment by maryhipp** [comment]
Has this been updated with pydantic changes?

**Comment by RyanJDick** [comment]
Overall, I love this initiative! Thanks for putting together a draft.

It's a little hard to review right now because the diff is polluted with pydantic changes. I'll just leave a few high-level comments for now.

**Comment by RyanJDick** [comment]
>Do we want to maybe let core nodes get access to the original, full-fat context, and only give the restricted context to community nodes?

In my opinion, we should aim to have all nodes (core and community) interface with the same API. It's nice to have a clear boundary between nodes and the app backend. I think there are a few downsides to allowing special cases for core nodes:
- If we allow it once, there will be temptation to do it again and again.
- It adds new considerations for any general node handling (e.g. adds complexity to node versioning, automatic node migration, etc.)
- It will become harder to write good node tests. If the node API is fixed, we can easily write a mock context implementation that is shared across all tests.

Put another way, before adding a method to the context we should ask ourselves: "Are we willing to support this method for both core and community nodes indefinitely?"

Of course, my mind could be changed if there was a compelling use case.

**Comment by JPPhoto** [comment]
As somebody interested in color spaces and wider gamuts and how those could be used in the future, I'd like to see `load_image` and `save_image` methods become `load_PIL_image` and `save_PIL_image` methods. This would allow us to support other image formats and APIs going forward that utilized 16 bits/LAB/etc.

**Comment by psychedelicious** [comment]
Superseded by #5491

**Pull request closed without merging**
