### PR TITLE
Relax Huggingface login requirement during setup

### PR DESCRIPTION
**Pull request by ebr**
- Fixes links to the Stable Diffusion weights license agreement. Prints a message about implicit agreement if the user used the `--yes` flag. Shortens/simplifies messaging and makes the licensing blurb more visible.
- The configuration script will no longer exit if the Huggingface token is not provided. Instead, we show a message about the purpose of the token, with a link to updated documentation, and offer to proceed with the download.
- Always caches the HF token if one is found or provided
- Prints more detailed messaging about where the token was found (or not)
- Validates the token, if exists, by logging in to HuggingFace. Offers an option to re-enter it on failure. This will prevent caching of invalid tokens which are hard for the user to reset.
- Deprecates the `--interactive[True]` flag and replaces it with `--skip-sd-weights[False]`, because: 1) its real purpose was to avoid token input when downloading the SD weights, which is no longer a blocker, and 2) avoidance of interaction is already achieved with `--yes`.

### CODE REVIEW

**Review by hipsterusername — APPROVED** [review]
LGTM!

**Comment by ebr** [comment]
> LGTM!

TY, just need to figure out why Windows checks are failing :thinking:

**Comment by mauwii** [comment]
When I try to launch the container without mounting my volume to /data, it is crashing:

```python
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
   You appear to have a missing or misconfigured model file(s).                   
   The script will now exit and run configure_invokeai.py to help fix the problem.
   After reconfiguration is done, please relaunch invoke.py.                      
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
configure_invokeai is launching....

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /usr/src/app/ldm/invoke/CLI.py:98 in main                                                        │
│                                                                                                  │
│    95 │                                                                                          │
│    96 │   # creating a Generate object:                                                          │
│    97 │   try:                                                                                   │
│ ❱  98 │   │   gen = Generate(                                                                    │
│    99 │   │   │   conf = opt.conf,                                                               │
│   100 │   │   │   model = opt.model,                                                             │
│   101 │   │   │   sampler_name = opt.sampler_name,                                               │
│                                                                                                  │
│ /usr/src/app/ldm/generate.py:159 in __init__                                                     │
│                                                                                                  │
│    156 │   │   │   weights = None,                                                               │
│    157 │   │   │   config = None,                                                                │
│    158 │   ):                                                                                    │
│ ❱  159 │   │   mconfig             = OmegaConf.load(conf)                                        │
│    160 │   │   self.height         = None                                                        │
│    161 │   │   self.width          = None                                                        │
│    162 │   │   self.model_cache    = None                                                        │
│                                                                                                  │
│ /usr/src/app/.venv/lib/python3.10/site-packages/omegaconf/omegaconf.py:189 in load               │
│                                                                                                  │
│    186 │   │   from ._utils import get_yaml_loader                                               │
│    187 │   │                                                                                     │
│    188 │   │   if isinstance(file_, (str, pathlib.Path)):                                        │
│ ❱  189 │   │   │   with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:             │
│    190 │   │   │   │   obj = yaml.load(f, Loader=get_yaml_loader())                              │
│    191 │   │   elif getattr(file_, "read", None):                                                │
│    192 │   │   │   obj = yaml.load(file_, Loader=get_yaml_loader())                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: [Errno 2] No such file or directory: '/data/configs/models.yaml'

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /usr/src/app/scripts/invoke.py:4 in <module>                                                     │
│                                                                                                  │
│   1 #!/usr/bin/env python                                                                        │
│   2                                                                                              │
│   3 import ldm.invoke.CLI                                                                        │
│ ❱ 4 ldm.invoke.CLI.main()                                                                        │
│   5                                                                                              │
│   6                                                                                              │
│                                                                                                  │
│ /usr/src/app/ldm/invoke/CLI.py:113 in main                                                       │
│                                                                                                  │
│   110 │   │   │   max_loaded_models=opt.max_loaded_models,                                       │
│   111 │   │   │   )                                                                              │
│   112 │   except (FileNotFoundError, TypeError, AssertionError):                                 │
│ ❱ 113 │   │   emergency_model_reconfigure(opt)                                                   │
│   114 │   │   sys.exit(-1)                                                                       │
│   115 │   except (IOError, KeyError) as e:                                                       │
│   116 │   │   print(f'{e}. Aborting.')                                                           │
│                                                                                                  │
│ /usr/src/app/ldm/invoke/CLI.py:953 in emergency_model_reconfigure                                │
│                                                                                                  │
│   950 │                                                                                          │
│   951 │   # try to match what the user has set on the CLI                                        │
│   952 │   root_dir = f"--root_dir {opt.root_dir}" if opt.root_dir is not None else None          │
│ ❱ 953 │   config = f"--config {opt.config}" if opt.config is not None else None                  │
│   954 │   yes_to_all = os.environ.get('INVOKE_MODEL_RECONFIGURE')                                │
│   955 │                                                                                          │
│   956 │   sys.argv = [ 'configure_invokeai', root_dir, config, yes_to_all ]                      │
│                                                                                                  │
│ /usr/src/app/ldm/invoke/args.py:343 in __getattribute__                                          │
│                                                                                                  │
│    340 │   │   │   pass                                                                          │
│    341 │   │                                                                                     │
│    342 │   │   if not hasattr(cmd_switches,name) and not hasattr(arg_switches,name):             │
│ ❱  343 │   │   │   raise AttributeError                                                          │
│    344 │   │                                                                                     │
│    345 │   │   value_arg,value_cmd = (None,None)                                                 │
│    346 │   │   try:                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError
```

when I do the same in main it is not crashing. Maybe a routine to create the INVOKEAI_ROOT if it is not existing yet would fix this, but since my lack of python skillz I can't say for sure 😅

**Comment by ebr** [comment]
good catch, fixed!

**Comment by ebr** [comment]
@mauwii any idea why Windows pip test is failing? i disabled as a test, and both Mac and Linux ones are fine. I'll reenable it now.

**Comment by ebr** [comment]
> @mauwii any idea why Windows pip test is failing in CI? i disabled it as a test, and both Mac and Linux ones are fine. I'll reenable it now.

NVM - fixed it.

**Comment by mauwii** [comment]
So for me it is still not working. 

In current main Branch i can use `INVOKE_MODEL_RECONFIGURE="--yes" python scripts/invoke.py`, which previously

1. accepted all default options for prompts like `Select the default directory for image outputs [/Users/mauwii/invokeai/outputs]` or `Download <r>ecommended models, <a>ll models, <c>ustomized list, or <s>kip this step? [r]:`
2. creates the necesarry files/directorys if not existing yet
3. if a huggingface token is available, also downloads the recommended models (if not found in invokeai_root and AGBs where accepted).

While in current branch I cannot get the SD-Models non-interactive while launching invoke.py (tried `INVOKE_MODEL_RECONFIGURE="--yes"`, `INVOKE_MODEL_RECONFIGURE="-y"`, `INVOKE_MODEL_RECONFIGURE="--no-interactive"` which all crash if the models.yaml cannot be found. Even `INVOKE_MODEL_RECONFIGURE="--interactive"` fails:

```py
INVOKE_MODEL_RECONFIGURE="--interactive" python scripts/invoke.py
>> patchmatch.patch_match: INFO - Compiling and loading c extensions from "/Users/mauwii/git/invoke-ai/InvokeAI/.venv/lib/python3.10/site-packages/patchmatch".
>> patchmatch.patch_match: ERROR - patchmatch failed to load or compile (Command 'make clean && make' returned non-zero exit status 2.).
>> patchmatch.patch_match: INFO - Refer to https://github.com/invoke-ai/InvokeAI/blob/main/docs/installation/INSTALL_PATCHMATCH.md for installation instructions.
>> Patchmatch not loaded (nonfatal)
* Initializing, be patient...
>> InvokeAI runtime directory is "/Users/mauwii/invokeai"
## NOT FOUND: GFPGAN model not found at /Users/mauwii/invokeai/models/gfpgan/GFPGANv1.4.pth
>> GFPGAN Disabled
## NOT FOUND: CodeFormer model not found at /Users/mauwii/invokeai/models/codeformer/codeformer.pth
>> CodeFormer Disabled
>> ESRGAN Initialized

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
   You appear to have a missing or misconfigured model file(s).                   
   The script will now exit and run configure_invokeai.py to help fix the problem.
   After reconfiguration is done, please relaunch invoke.py.                      
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
configure_invokeai is launching....

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/mauwii/git/invoke-ai/InvokeAI/ldm/invoke/CLI.py:98 in main                                │
│                                                                                                  │
│    95 │                                                                                          │
│    96 │   # creating a Generate object:                                                          │
│    97 │   try:                                                                                   │
│ ❱  98 │   │   gen = Generate(                                                                    │
│    99 │   │   │   conf = opt.conf,                                                               │
│   100 │   │   │   model = opt.model,                                                             │
│   101 │   │   │   sampler_name = opt.sampler_name,                                               │
│                                                                                                  │
│ /Users/mauwii/git/invoke-ai/InvokeAI/ldm/generate.py:159 in __init__                             │
│                                                                                                  │
│    156 │   │   │   weights = None,                                                               │
│    157 │   │   │   config = None,                                                                │
│    158 │   ):                                                                                    │
│ ❱  159 │   │   mconfig             = OmegaConf.load(conf)                                        │
│    160 │   │   self.height         = None                                                        │
│    161 │   │   self.width          = None                                                        │
│    162 │   │   self.model_cache    = None                                                        │
│                                                                                                  │
│ /Users/mauwii/git/invoke-ai/InvokeAI/.venv/lib/python3.10/site-packages/omegaconf/omegaconf.py:1 │
│ 89 in load                                                                                       │
│                                                                                                  │
│    186 │   │   from ._utils import get_yaml_loader                                               │
│    187 │   │                                                                                     │
│    188 │   │   if isinstance(file_, (str, pathlib.Path)):                                        │
│ ❱  189 │   │   │   with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:             │
│    190 │   │   │   │   obj = yaml.load(f, Loader=get_yaml_loader())                              │
│    191 │   │   elif getattr(file_, "read", None):                                                │
│    192 │   │   │   obj = yaml.load(file_, Loader=get_yaml_loader())                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: [Errno 2] No such file or directory: '/Users/mauwii/invokeai/configs/models.yaml'

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/mauwii/git/invoke-ai/InvokeAI/scripts/invoke.py:4 in <module>                             │
│                                                                                                  │
│   1 #!/usr/bin/env python                                                                        │
│   2                                                                                              │
│   3 import ldm.invoke.CLI                                                                        │
│ ❱ 4 ldm.invoke.CLI.main()                                                                        │
│   5                                                                                              │
│   6                                                                                              │
│                                                                                                  │
│ /Users/mauwii/git/invoke-ai/InvokeAI/ldm/invoke/CLI.py:113 in main                               │
│                                                                                                  │
│   110 │   │   │   max_loaded_models=opt.max_loaded_models,                                       │
│   111 │   │   │   )                                                                              │
│   112 │   except (FileNotFoundError, TypeError, AssertionError):                                 │
│ ❱ 113 │   │   emergency_model_reconfigure(opt)                                                   │
│   114 │   │   sys.exit(-1)                                                                       │
│   115 │   except (IOError, KeyError) as e:                                                       │
│   116 │   │   print(f'{e}. Aborting.')                                                           │
│                                                                                                  │
│ /Users/mauwii/git/invoke-ai/InvokeAI/ldm/invoke/CLI.py:953 in emergency_model_reconfigure        │
│                                                                                                  │
│   950 │                                                                                          │
│   951 │   # try to match what the user has set on the CLI                                        │
│   952 │   root_dir = f"--root_dir {opt.root_dir}" if opt.root_dir is not None else None          │
│ ❱ 953 │   config = f"--config {opt.config}" if opt.config is not None else None                  │
│   954 │   yes_to_all = os.environ.get('INVOKE_MODEL_RECONFIGURE')                                │
│   955 │                                                                                          │
│   956 │   sys.argv = [ 'configure_invokeai', root_dir, config, yes_to_all ]                      │
│                                                                                                  │
│ /Users/mauwii/git/invoke-ai/InvokeAI/ldm/invoke/args.py:343 in __getattribute__                  │
│                                                                                                  │
│    340 │   │   │   pass                                                                          │
│    341 │   │                                                                                     │
│    342 │   │   if not hasattr(cmd_switches,name) and not hasattr(arg_switches,name):             │
│ ❱  343 │   │   │   raise AttributeError                                                          │
│    344 │   │                                                                                     │
│    345 │   │   value_arg,value_cmd = (None,None)                                                 │
│    346 │   │   try:                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError
```

while `python scripts/configure_invokeai.py -y` is working fine:

```py                          
Loading Python libraries...

Welcome to InvokeAI. This script will help download the Stable Diffusion weight files
and other large models that are needed for text to image generation. At any point you may interrupt
this program and resume later.

** INITIALIZING INVOKEAI RUNTIME DIRECTORY **

InvokeAI image outputs will be placed into "/Users/mauwii/invokeai/outputs".

You may change the chosen output directory at any time by editing the --outdir options in "invokeai.init",
You may also change the runtime directory by setting the environment variable INVOKEAI_ROOT.

Creating the initialization file at "/Users/mauwii/invokeai/invokeai.init".

** DOWNLOADING DIFFUSION WEIGHTS **
** LICENSE AGREEMENT FOR WEIGHT FILES **
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

By downloading the Stable Diffusion weight files from the official Hugging Face
repository, you agree to have read and accepted the CreativeML Responsible AI License.
The license terms are located here:

   https://huggingface.co/spaces/CompVis/stable-diffusion-license


═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
The program was started with a '--yes' flag, which indicates user's acceptance of the above License terms.
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Authenticating to Huggingface
Huggingface token found in cache.
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
* v1-5-pruned-emaonly.ckpt: Downloading...
v1-5-pruned-emaonly.ckpt:   0%|▏                                                                                                       | 9.50M/4.27G [00:01<09:57, 7.12MiB/s]
```

**Comment by ebr** [comment]
> `956 │   sys.argv = [ 'configure_invokeai', root_dir, config, yes_to_all ]`

This looks like the old version of the code... That's the part I fixed. Can you try to pull again?

**Comment by ebr** [comment]
Oh, I know, @mauwii ... You need to reinstall the local module  with `pip install -e .` because when kicked into the emergency model reconfigure, the configure script is imported from venv, not from `./scripts`

**Comment by mauwii** [comment]
> > `956 │   sys.argv = [ 'configure_invokeai', root_dir, config, yes_to_all ]`
> 
> This looks like the old version of the code... That's the part I fixed. Can you try to pull again?

somehow I needed to delete the local branch and check it out again, but looks more like a "me-problem" 🙈 And yes, now it was working, will quickly rebuilt container as well to verify

**Review by mauwii — APPROVED** [review]

**Pull request merged**
