### PR TITLE
Merge-main-into-development

### PR DESCRIPTION
**Pull request by mauwii**
To get the rid of the difference between main and development.

Since otherwise it will be a pain to start fixing the documentatino (when the state between main and development is not the same ...)

Also this should fix the problem of all tests failing since environment yamls get updated.

### CODE REVIEW

**Comment by mauwii** [comment]
I would recommend to only merge this PR (not squash and not rebase)

**Review by lstein — APPROVED** [review]
Thanks again.

**Comment by lstein** [comment]
I will merge later this morning.

**Comment by mauwii** [comment]
5 PM here 🙈

**Comment by lstein** [comment]
I have to disable “Enforce linear history” to make a merge commit. Should this be a one time thing, or a permanent change in policy?

**Comment by mauwii** [comment]
> I have to disable “Enforce linear history” to make a merge commit. Should this be a one time thing, or a permanent change in policy?

Depending on future-hotfixes

Since hotfixes needs to be applied to main and development, so therefore needs to be generated from main rather than from development

**Comment by lstein** [comment]
> > I have to disable “Enforce linear history” to make a merge commit. Should this be a one time thing, or a permanent change in policy?
> 
> Depending on future-hotfixes
> 
> Since hotfixes needs to be applied to main and development, so therefore needs to be generated from main rather than from development

I’m installing VSCode today so that I can view and edit the docs without breaking the formatting. I’ll have to change my work paradigm so that I’m working locally on my desktop rather than ssh’ing into a HPC head node that doesn’t allow X forwarding.

**Comment by mauwii** [comment]
Good news for you: VSCode has a SSH-Extension, so you can run it locally while working via SSH without X-Forwarding ;)

**Comment by mauwii** [comment]
@lstein I would now create a branch from main to begin fixing docs and afterwards PR those changes to main and development, so that changes are available immediately

**Pull request merged**
