### PR TITLE
Protect-secrets-on-pr

### PR DESCRIPTION
**Pull request by mauwii**
- in this way the action is used from the base repository
- also use new secret HUGGINGFACE_TOKEN (username:token)
  - f.e. `noreply@github.com:hf_lkaugfklagwrjglaslzfgkjzzf`
- change pr prompt file to validate_pr_prompt.txt

@lstein: you need to create the new secret as mentioned above

### CODE REVIEW

**Comment by mauwii** [comment]
@lstein to add the secret, while in the repository, click on:

1. settings 
2. secrets
3. actions
4. New Repository Secret
5. name it `HUGGINGFACE_TOKEN` with content of `username:huggingface_token`
   (for me `mauwii@provider.de:hf_blablabla`)

**Comment by lstein** [comment]
> 

I've done this using my HuggingFace account and access token. Should I remove the SD URL as well?

**Review by lstein — APPROVED** [review]

**Comment by mauwii** [comment]
> I've done this using my HuggingFace account and access token. Should I remove the SD URL as well?

since secrets.SD_V1_4_URL shouldn't be reffered from the actions anymore it should be safe to remove it 👍🏻

**Comment by mauwii** [comment]
@lstein only `name:token` as the secret, no line break in the end!

**Pull request merged**
