### PR TITLE
Documentation for the Jupyter Notebooks/Colab notebook

### PR DESCRIPTION
**Pull request by lstein**
# The documentation in docs/installation/INSTALL_JUPYTER.md is incomplete

This PR fixes the link to the  Jupyter/Colab notebook, but the page needs loving attention from someone knowledgeable with Jupyter and Colab. Please use this PR to contribute the documentation.

### CODE REVIEW

**Review by blessedcoolant — APPROVED** [review]

**Comment by tildebyte** [comment]
The link is now pointing to the *wrong* notebook.

I deleted the **install** notebook as part of the work on the binary installer - I don't think that many people use/used it, and we have far too many install methods even without it.

The remaining notebook is a contribution, which is strictly for running Invoke in Colab

**Comment by lstein** [comment]
Got it.  We will have to rename this doc then to "Running InvokeAI in Google Colab." We still need the walk thru for using the notebook, though.

**Comment by Lycantant** [comment]
> Got it. We will have to rename this doc then to "Running InvokeAI in Google Colab." We still need the walk thru for using the notebook, though.

Google Colab is very helpful, especially for me who doesn't have enough hardware to run AI software. Please keep it updated for the Google Colab version. Thanks very much 🙂

**Comment by NazarYermolenko** [comment]
https://github.com/camenduru/stable-diffusion-webui-colab
Here we have a stable diffusion examples, it's nice to have full web ui installed

**Comment by lstein** [comment]
There's nothing wrong with this PR, but the Google colab doc that it points to is woefully out of date and will no longer work. This fix needs to wait until we've got a functional noteback up on colab and good documentation to go along with it.

**Pull request closed without merging**
