### PR TITLE
Update stale issues action

### PR DESCRIPTION
**Pull request by Millu**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [X] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [ ] Yes
- [X] No

## Description
Updated script to close stale issues with the newest version of the actions/stale

## Related Tickets & Documents

- Related Issue #
- Closes #

## Added/updated tests?

- [ ] Yes
- [X] No : _please replace this line with details on why tests
      have not been included_

## [optional] Are there any post deployment tasks we need to perform?
Not sure how this script gets kicked off

### CODE REVIEW

**Comment by psychedelicious** [comment]
[StaleBot](https://github.com/probot/stale) was deprecated and GH now directs you to [`actions/stale@v8`](https://github.com/actions/stale). Did you try the latest version (v8)? Probably best to use that

**Comment by Millu** [comment]
Docs are little confusing - https://github.com/marketplace/actions/close-stale-issues. Clicking latest version brings you to 4.1.1 but I updated to use `actions/stale@v8`

**Review by lstein — APPROVED** [review]
LGTM

**Comment by psychedelicious** [comment]
Oh, that is really weird about the docs pointing you to 4.1.1

**Pull request merged**
