### PR TITLE
update test-tube version requirements to match yaml files, partitally…

### PR DESCRIPTION
**Pull request by Vargol**
… fixes pip install build on macOS
Fixed version of PR #1476

### CODE REVIEW

**Review by tildebyte — APPROVED** [review]

**Comment by tildebyte** [comment]
@Vargol; Thanks for going to the trouble! I know it can be a PITA sometimes :)

**Comment by Any-Winter-4079** [comment]
I'm catching up now after a busy week but didn't we change test-tube for csvlogger a while back?

**Comment by Vargol** [comment]
> I'm catching up now after a busy week but didn't we change test-tube for csvlogger a while back?

It may be but I think this is a smaller safer change, more designed to be 'cherry picked' for going into main as a straight forward pip install is broken there.
I planning on raising another PR after this to make a number of changes to the requirements / enrolments, but they'll need testing on all  the different platforms and install methods, If successful it'll lift the version restrictions on transformers, tokenizer and protobuf and avoid the need to install rust on macOS as we can use a binary version of tokenizers without having to use the prefer binary option.

**Review by lstein — APPROVED** [review]
LGTM - fix for basicsr problems is on its way

**Pull request merged**
