### PR TITLE
Feat/Nodes: Change Input to Textbox

### PR DESCRIPTION
**Pull request by mickr777**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [ ] Yes
- [X] No, because:
not yet, making pr to show
      
## Have you updated relevant documentation?
- [ ] Yes
- [ ] No

## Description
Temp Change Node String input to a textbox, to allow easier input of prompts and larger strings, it works for me but please tell me if I did it wrong and if the size is ok

## Related Tickets & Documents

- Related Issue #
- Closes #

## Added/updated tests?

- [ ] Yes
- [ ] No : _please replace this line with details on why tests
      have not been included_

### CODE REVIEW

**Review by lstein — CHANGES_REQUESTED** [review]
It's an improvement over the current string input because it handles multiple lines, but it takes up a lot of space! Is there a way for the textbox to resize with the node panel? When I try to resize, I can only do it horizontally and the textbox inside stays the same fixed size (see video).
[cinnamon-2023-07-20T094429-0400.webm](https://github.com/invoke-ai/InvokeAI/assets/111189/468ee2c3-2589-4921-918d-7f369cc7c4ee)

**Comment by mickr777** [comment]
> It's an improvement over the current string input because it handles multiple lines, but it takes up a lot of space! Is there a way for the textbox to resize along with the node panel? When I try to resize, I can only do it horizontally and the textbox inside stays the same fixed size (see video). [cinnamon-2023-07-20T094429-0400.webm](https://github.com/invoke-ai/InvokeAI/assets/111189/468ee2c3-2589-4921-918d-7f369cc7c4ee)

@lstein I made height smaller and and changed width to resize with node width
(Since only width can be resized on most nodes)

Animation4

**Review by lstein — APPROVED** [review]
Thank you!

**Comment by psychedelicious** [comment]
I'll defer to @blessedcoolant for approving this as an interim QOL improvement. We did just merge in some code quality changes so you may need to do a bit of fiddling with the PR to make it happy. (the `lint frontend` action needs to pass before merge)

**Comment by blessedcoolant** [comment]
I'll give this a run later today and see how it feels.

**Comment by mickr777** [comment]
@blessedcoolant I made the code much more simple, if you feels its a good temp fix please use, if not worth while I can just close the pr

**Comment by blessedcoolant** [comment]
@mickr777 Sorry I didn't get to this earlier. Been so busy. Just went through it. Seems good. Thanks for the PR.

While this is not how we might do it in the long run, it works for now as a QoL feature. I made a few chanages.

- I updated even the `Style` slot of the Refiner to take a text area.
- I added a new `Prompt` node which is basically a duplicate of the String node but instead is named prompt so the frontend can display a text area rather than a input box. We can remove this node once we add proper support for conditional rendering of a node in the future.

Seems good. I'll merge in when checks pass.

**Review by blessedcoolant — APPROVED** [review]

**Pull request merged**
