### PR TITLE
enhance support for model switching and editing

### PR DESCRIPTION
**Pull request by lstein**
- Error checks for invalid model
- Add !del_model command to invoke.py
- Add del_model() method to model_cache
- Autocompleter kept in sync with model addition/subtraction.

### CODE REVIEW

**Comment by Any-Winter-4079** [comment]
Currently testing.

**Comment by Any-Winter-4079** [comment]
More feedback.
The comment on `models.yaml`
```
# This file describes the alternative machine learning models
#  available to the dream script.
#
# To add a new model, follow the examples below. Each
# model requires a model config file, a weights file,
# and the width and height of the images it
# was trained on.
```
is deleted when you delete a model. It'd be good to leave it as is.

**Comment by Any-Winter-4079** [comment]
Also, although the main of point of interaction to add / edit / delete a model will likely be the console, it might be good to consider people may manually add / edit / remove a model from `models.yaml` using an editor with the invoke> prompt open.

I haven't looked much at the code, but reading the content of the file every time may be better than storing the (supposed) state of the file in variables (because if `models.yaml` is manually edited mid session there will be inconsistency).

**Comment by Any-Winter-4079** [comment]
Also (maybe intentionally) `!models` is not a part of the invoke> history.
So I have to type it out every time vs. using up key.

**Comment by Any-Winter-4079** [comment]
@lstein other than that, the PR looks good.

**Comment by Any-Winter-4079** [comment]
Oh, also.
This was an interesting case.
Tried to `!edit_model`, but intentionally entered some wrong information, which eventually made it fail.
What happened was the model disappeared from `!models` (but not from the file).
The problem is we can't edit the info anymore (to correct our mistake) unless we exit invoke> prompt.
```
invoke> !edit_model fd1

>> Editing model fd1 from configuration file ./configs/models.yaml
description: e
weights: models/ldm/waifu-diffusion/inference/wd-v1-3-full.sha25
config: configs/stable-diffusion/v1-inference.yaml
width: 512
height: 512

>> New configuration:
fd1:
  config: configs/stable-diffusion/v1-inference.yaml
  description: e
  height: 512
  weights: models/ldm/waifu-diffusion/inference/wd-v1-3-full.sha25
  width: 512

OK to modify [n]? y
>> Verifying that new model loads...
>> Caching model stable-diffusion-1.4 in system RAM
>> Loading fd1 from models/ldm/waifu-diffusion/inference/wd-v1-3-full.sha25
** model fd1 could not be loaded: [Errno 2] No such file or directory: 'models/ldm/waifu-diffusion/inference/wd-v1-3-full.sha25'
** restoring stable-diffusion-1.4
>> Retrieving model stable-diffusion-1.4 from system RAM cache
** aborting **
invoke> !edit_model fd1
** Unknown model fd1
```

**Comment by Any-Winter-4079** [comment]
Also, when you edit the current model, it's a bit of an odd behavior. I can set a wrong model path, but it uses the model correctly anyway.
Note there is no `models/ldm/waifu-diffusion/inference/wd-v1-3-float3` but `models/ldm/waifu-diffusion/inference/wd-v1-3-float32.ckpt`
```
invoke> !edit_model fd

>> Editing model fd from configuration file ./configs/models.yaml
description: fd
weights: models/ldm/waifu-diffusion/inference/wd-v1-3-float3
config: configs/stable-diffusion/v1-inference.yaml
width: 512
height: 512

>> New configuration:
fd:
  config: configs/stable-diffusion/v1-inference.yaml
  description: fd
  height: 512
  weights: models/ldm/waifu-diffusion/inference/wd-v1-3-float3
  width: 512

OK to modify [n]? y
>> Verifying that new model loads...
Keep model loaded? [y]
invoke> !models
laion400m                 not loaded  Latent Diffusion LAION400M model
stable-diffusion-1.4          cached  Stable Diffusion inference model version 1.4
stable-diffusion-1.4-full not loaded  Stable Diffusion inference model version 1.4 (full)
stable-diffusion-1.3      not loaded  Stable Diffusion inference model version 1.3
waifu-1.3                 not loaded  Waifu Diffusion inference model version 1.3
fd                            active  fd
fd1                       not loaded  w
invoke> "anime"  -S 282367804 -W 512 -H 512 -C 7.5 -A k_lms -ft gfpgan -cf 0.75 -s10
Generating:   0%|                                                                                                                                                                                      | 0/1 [00:00<?, ?it/s]>> Sampling with k_lms starting at step 0 of 10 (10 new sampling steps)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:05<00:00,  1.81it/s]
Generating: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.99s/it]
>> Usage stats:
>>   1 image(s) generated in 6.16s
Outputs:
[256] outputs/new/000152.282367804.png: "anime" -s 10 -S 282367804 -W 512 -H 512 -C 7.5 -A k_lms -ft gfpgan -cf 0.75
```

**Comment by lstein** [comment]
Thanks for the additional feedback. I'll make the requested changes. I'd love to be able to open up a text editor to directly edit the file, but I don't see how to do this on Windows, Linux and Mac consistently.

**Comment by Any-Winter-4079** [comment]
> Thanks for the additional feedback. I'll make the requested changes. I'd love to be able to open up a text editor to directly edit the file, but I don't see how to do this on Windows, Linux and Mac consistently.

You mean the user opening the file on their own editor? Visual Studio Code for example allows for `code file` which opens a new window with the file. It obviously requires people to install Visual Studio Code, although the tool is most likely compatible with all 3 operating systems.

**Comment by lstein** [comment]
Last round of revisions. I added the preamble back to the config file, fixed the issue of changed but incorrect stanzas still working, and added a new "default" configuration option that lets `invoke.py` select the user's preferred model at startup time. I also made various internal improvements.

**Pull request closed without merging**
