### PR TITLE
Release 2.1.3

### PR DESCRIPTION
**Pull request by lstein**
# Release 2.1.3

This is a combination of commits from `release-candidate-2-1-3` and a number of recent hotfixes applied to `development`. Has gone through preflight checks and several installs successfully.

### CODE REVIEW

**Comment by blessedcoolant** [comment]
Should this include #1439 because the gfpgan_dir is now redundant.

**Comment by mickr777** [comment]
fyi this branch is missing  the index.js for the webui

**Comment by psychedelicious** [comment]
> fyi this PR removes all frontend/dist/assets/index.*.js for the webui

Good catch. This needs a `yarn build`.

**Comment by lstein** [comment]
> > fyi this PR removes all frontend/dist/assets/index.*.js for the webui
> 
> Good catch. This needs a `yarn build`.

I just did a yarn build and the asset files are appearing in a `dist` subdirectory. Is it supposed to do that?

**Review by psychedelicious — CHANGES_REQUESTED** [review]
Edit: nevermind, I see the PR *removes* `package-lock.json` so no worries.

This needs a `yarn build`. Changes look fine to me though. 

Side-question: Are you using `yarn` or `npm`? I see a `package-lock.json` which indicates `npm` has been used by somebody. These are frozen dependency lists and we need to stick to the one package manager.

- yarn uses `yarn.lock`
- npm uses `package-lock.json`

Our project uses [`yarn` v1 "classic"](https://classic.yarnpkg.com/en/docs/install#mac-stable).

**Comment by psychedelicious** [comment]
> I just did a yarn build and the asset files are appearing in a dist subdirectory. Is it supposed to do that?

Yep - that's where the build javascript bundle is output to.

**Comment by lstein** [comment]
> Edit: nevermind, I see the PR _removes_ `package-lock.json` so no worries.
> 
> This needs a `yarn build`. Changes look fine to me though.
> 
> Side-question: Are you using `yarn` or `npm`? I see a `package-lock.json` which indicates `npm` has been used by somebody. These are frozen dependency lists and we need to stick to the one package manager.
> 
> * yarn uses `yarn.lock`
> * npm uses `package-lock.json`
> 
> Our project uses [`yarn` v1 "classic"](https://classic.yarnpkg.com/en/docs/install#mac-stable).

I just use yarn. I've seen package-lock.json in the development branch, but I don't see it in this PR and don't use npm Where are you seeing it?.

**Comment by lstein** [comment]
> fyi this PR removes all frontend/dist/assets/index.*.js for the webui

Now fixed.

**Comment by lstein** [comment]
> Should this include #1439 because the `gfpgan_dir` is now obsolete.

Now included.

**Comment by lstein** [comment]
I think we're good to go, but another once-over wouldn't hurt.

**Comment by lstein** [comment]
> Edit: nevermind, I see the PR removes package-lock.json so no worries.

I recall I found this in the repo and removed it. Didn't check where it had come from.

**Comment by psychedelicious** [comment]
> > Edit: nevermind, I see the PR removes package-lock.json so no worries.
> 
> 
> 
> I recall I found this in the repo and removed it. Didn't check where it had come from.

Must have been a remnant from another contributor. At some point we will make a contribution guide for the ui.

**Review by psychedelicious — APPROVED** [review]
Looks good to me, did a run through of UI features and new env creation.

**Pull request merged**
