### PR TITLE
fix: Update SDXL Refiner graphs to use Gradient Mask

### PR DESCRIPTION
**Pull request by blessedcoolant**
## Summary

SDXL Refiner Graphs were using the old Denoise Mask. They have now been updated to use the new Gradient Mask instead.

However, the results are absolutely horrendous. This needs some backend work which @dunkeroni said he will look into. I'll make the necessary changes after.

### CODE REVIEW

**Comment by dunkeroni** [comment]
Why are we creating a new mask in the first place? I get fine results (or as fine as Refiner model gets) in workflows by just connecting the same gradient mask to the primary denoise and the refiner denoise. No glitches then, and since the gradient is timestep based, the refiner will just continue the mask expansion where the primary left off.

I made some example images, but then I tried to checkout your branch and test things, and it permanently deleted all of my models and output images. Oops.

**Comment by blessedcoolant** [comment]
> I made some example images, but then I tried to checkout your branch and test things, and it permanently deleted all of my models and output images. Oops.

Err.. why would it do that? This is based off main and the only thing different is the refiner graph. Unless something borked in main. But seems fine on my end.

I'll take a look at the mask.

**Comment by dunkeroni** [comment]
The day is saved! It made a backup of my db first. Turns out my dev installs models weren't being saved to the dev install location for some reason. Oh well. I have them back now.

Original Image of Old Man Grumbles making bread for his famous Grumblecakes
image

Inpainted with Old Man Grumbles petting a kitten (existing canvas on main)
image

Workflow result when using the same gradient mask as the primary denoise.
image

**Comment by blessedcoolant** [comment]
So you're saying I should draw the inpaint mask from the original rather than create a new node even if its with the same mask?

**Comment by dunkeroni** [comment]
Because it's the same mask, you should be able to use the same Denoise Mask output from the first gradient mask node. Alternatively you could create a second node and just make sure that all the same coherence pass settings are connected into it. If the mask expansion settings are different though, then they won't match up and the refiner stage will be denoising the area differently than the primary, which results in the fringe.

**Comment by blessedcoolant** [comment]
opera_Wzk88RBmJo

I'm still getting these even if I plug the SDXL inpaint gradient mask directly into the refiner too.

**Comment by dunkeroni** [comment]
Perhaps I'm making a few incorrect assumptions about how we handle the refiner pass. I'll take a deeper look this week when I'm near a computer again.

**Pull request merged**
