### PR TITLE
Update communityNodes.md with a few more nodes

### PR DESCRIPTION
**Pull request by dwringer**
Adds my (@dwringer's) released nodes to the community nodes page.

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [X] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [X] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [X] Yes
- [ ] No

## Description
Adds my released nodes -
Depth Map from Wavefront OBJ
Enhance Image
Generative Grammar-Based Prompt Nodes
Ideal Size Stepper
Image Compositor
Final Size & Orientation / Random Switch (Integers)
Text Mask (Simple 2D)

### CODE REVIEW

**Comment by Millu** [comment]
Thanks for getting these added @dwringer! Any chance you're able to share images to go along with them? Makes them slightly more approachable

**Comment by dwringer** [comment]
@Millu Sure! I was discussing this in Discord with @hipsterusername and I'm going to reorganize this a bit, condensing the number, pulling things into their own repos and providing the repo links instead of the .py links. I'll throw images up for all of them as well! I should be able to have this revised by this evening.

**Comment by dwringer** [comment]
@Millu @hipsterusername I've completed the changes we discussed, adding images for each repo and using links to the repos directly, as well as working on fleshing out the repo-specific documentation.

**Review by Millu — APPROVED** [review]
Thank you so much @dwringer! Looks great to me

**Pull request merged**
