### PR TITLE
Change Reset Workflow icon

### PR DESCRIPTION
**Pull request by mickr777**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [ ] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [ ] Yes
- [ ] No

## Description
Just a Suggestion to change the reset workflow button style, to be more as a reset style icon, then a trash icon, as it can be confusing to the user
image

## Related Tickets & Documents

- Related Issue #
- Closes #

## Added/updated tests?

- [ ] Yes
- [ ] No : _please replace this line with details on why tests
      have not been included_

### CODE REVIEW

**Review by hipsterusername — APPROVED** [review]

**Review by psychedelicious — CHANGES_REQUESTED** [review]
I don't think we should change the icon. We have a convention that "red trash can means destructive delete action".

I'd rather provide some feedback to the user via eg a modal. How does that sound?

**Comment by hipsterusername** [comment]
> I don't think we should change the icon. We have a convention that "red trash can means destructive delete action".
> 
> I'd rather provide some feedback to the user via eg a modal. How does that sound?

Icons need to change. The UX pattern is not contextually similar, and multiple users have expressed confusion.

**Comment by hipsterusername** [comment]
@psychedelicious -- UX Rationale:

Queue - Now has a "halt & burn the queue" icon. Not really a 'trash' icon function.
Workflow - Has a "clear work area" icon - I've copied this to canvas as that is also probably an inappropriate trash can.
Images - Trash can. Images go to the recycling bin.

Open to different icons, but these three are distinct enough to merit not sharing one.

**Comment by Millu** [comment]
+1 for changing it, the ControlNet UI already uses this icon in the same way for a reset functionality

**Comment by psychedelicious** [comment]
I understand the need to clarify actions and icons' meanings.

In this PR, on canvas, the same icon is used for both undo and reset - that's confusing:
image

---

If we can clarify actions by using icons, great, but first let's look at all the destructive actions you can take in the app and the icons that go with them (possible I'm missing some):

- Clear canvas -> destructive -> trashcan
- Clear canvas mask -> destructive -> trashcan
- Clear workflow -> destructive & (currently) irreversible action -> trashcan
- Clear queue -> including canceling the current item, destructive & irreversible -> trashcan
- Cancel current queue item -> destructive & irreversible -> `x`, because there's already a trashcan just next to it
- Delete image -> destructive & (currently) irreversible -> trashcan
- Delete board -> destructive & (currently) irreversible -> trashcan
- Reset *any* set-able image (control adapters, init image) -> resets the image, which you can trivially drag back on to the image area, non-destructive -> undo icon
- Delete controlnet itself -> destructive -> trashcan
- Delete lora -> destructive -> trashcan
- Delete linear UI field -> destructive -> trashcan
- Discard staging area -> destructive -> `x`

If we are going to change the icon used for each action, we should consider all of these actions and choose appropriate representations for each. The icons shouldn't be changing regularly, let's take the time to choose the right symbols once. They *are* pretty consistent right now.

(The reset image icon should be changed to *not* be the undo icon. That's undo/redo everywhere and there shouldn't be anything else that uses the same icon. Probably that should be an `x` instead.)

**Comment by mickr777** [comment]
> (The reset image icon should be changed to _not_ be the undo icon. That's undo/redo everywhere and there shouldn't be anything else that uses the same icon. Probably that should be an `x` instead.)

I forgot about the canvas undo redo, was just suggesting it as the clear node and controlnet image used it

maybe
image

**Comment by blessedcoolant** [comment]
Another limitation I often bump into is with FA5. Sometimes the set just doesn't have an icons we need. Eventually as we keep adding new stuff, think we will need to design our own icon packs and maintain them. But that's a future future problem.

**Comment by psychedelicious** [comment]
Glancing over that list, I count 5 kinds of actions in 3 groups:

Reversible destructive
- Destructive, reversible, single entity
- Destructive, reversible, multiple entities

Irreversible destructive 
- Destructive, irreversible, single entity
- Destructive, irreversible, multiple entities

Reset
- Reset, single entity

That implies 3 or 5 icons, depending on if we want to split up single vs multiple entities.

Also, some actions are unique enough that maybe they should have their own icon, but until we pay somebody to an icon set for us, it may be hard to fine icons that feel cohesive for all these different things.

**Comment by psychedelicious** [comment]
@mickr777 That icon has inherent meaning though - recycle, use this entity for something new.

Similarly, the undo icon means "go back one step". That's why it's used for the set-able images - you can *only* go back one step with that action. Though, as mentioned, I think these maybe should use the `x` or some other icon instead.

**Comment by mickr777** [comment]
image

**Comment by hipsterusername** [comment]
I'm less concerned about which icon we settle on and more concerned about the very clear need for improved UX here.

I've determined the main reason for confusion is that a common UX for deletion is to use the Delete Icon in the Toolbar to manage the deletion of images in the gallery. When viewing the gallery in the Workflow editor, the Trash Can is deceptively present, but functions completely differently.

Needs a different UX.

**Comment by hipsterusername** [comment]
@Millu can you work through the list and put some thought to it so we can make sure this PR gets in?

**Pull request closed without merging**
