### PR TITLE
fix: build frontend in  pypi-release workflow

### PR DESCRIPTION
**Pull request by psychedelicious**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [x] Yes
- [ ] No, because:

## Description

This was missing, resulting in the 3.5.0rc1 having no frontend.

## Related Tickets & Documents

- Discord installer thread: https://discord.com/channels/1020123559063990373/1149513695567810630/1185200427717898260
- Comments from here in the release chat: https://discord.com/channels/1020123559063990373/1020123559831539744/1185004017521279007

## QA Instructions, Screenshots, Recordings

I've run this locally and it works (I commented out the final steps of the workflow that do PyPi stuff to ensure I didn't accidentally deploy something).

You can run the workflow locally with https://github.com/nektos/act. Suggest using the `gh` CLI version, its very easy to set up if you have the github CLI installed. Then you can run `gh act -W .github/workflows/pypi-release.yml` to run the workflow locally in a docker image.

I don't know this local action runner would actually release to PyPi - as mentioned, I commented those steps out when testing - but it does successfully do both frontend and backend builds.

## Merge Plan

This needs @lstein 's approval.

## [optional] Are there any post deployment tasks we need to perform?

Cut an RC2

### CODE REVIEW

**Review by lstein — APPROVED** [review]
While reviewing this PR I did a comparison with the installer zip and realized that the contents of `.mypy_cache` and `__pycache__` directories were finding their way into the latter. So I piggybacked a small fix for this on top of the PR -- hope that's ok.

**Comment by psychedelicious** [comment]
I've made two further improvements:
[feat(installer): delete frontend build after creating installer](https://github.com/invoke-ai/InvokeAI/pull/5298/commits/0f1c5f382a681552d7903d016bcddb9a5f15e26c)

This prevents an empty `dist/` from breaking the app on startup.

[feat: add python dist as release artifact, as input to enable publish to pypi](https://github.com/invoke-ai/InvokeAI/pull/5298/commits/5bf61382a40923cc013edb1d4b94518517b25715)

- The release workflow never runs automatically. It must be manually kicked off.
- The release workflow has an input. When running it from the GH actions UI, you will see a "Publish build on PyPi" prompt. If this value is "true", the workflow will upload the build to PyPi, releasing it. If this is anything else (e.g. "false", the default), the workflow will build but not upload to PyPi.
- The `dist/` folder (where the python package is built) is uploaded as a workflow artifact as a zip file. This can be downloaded and inspected. This allows "dry" runs of the workflow.
- The workflow job and some steps have been renamed to clarify what they do

**Comment by lstein** [comment]
Running the workflow locally with `gh act` now fails at the artifact upload step with: 
```
[PyPI Release/build-and-release]   ❗  ::error::Unable to get the ACTIONS_RUNTIME_TOKEN env variable
[PyPI Release/build-and-release]   ❌  Failure - Main Upload build as workflow artifact
[PyPI Release/build-and-release] exitcode '1': failure
```
Using `--artifact-server-path` as suggested in several postings does not work. It looks like a local artifact server needs to be started in order to test the workflow locally.

**Review by lstein — APPROVED** [review]
Let's try it in production.

**Pull request merged**
