### PR TITLE
feat(ui): connection validation rework

### LINKED ISSUE #6380: [bug]: Nodes unable to connect ModelIdentifierField  without a ui_type set to an input ModelIdentifierField with a ui_type set
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

_No response_

### GPU VRAM

_No response_

### Version number

4.2.1

### Browser

chrome

### Python dependencies

_No response_

### What happened

While using my custom nodes in my XYGrid nodes pack. You are prevented from connecting an output ModelIdentifierField  (without a ui_type set) to an input ModelIdentifierField field that has a ui_type set. 

This was reported as a bug on my nodes pack today. https://github.com/skunkworxdark/XYGrid_nodes/issues/6

image

### What you expected to happen

It should allow you to connect them as the base type is the same. 

### How to reproduce the problem

_No response_

### Additional context

_No response_

### Discord username

skunkworxdark

### PR DESCRIPTION
**Pull request by psychedelicious**
## Summary

Major Changes:

- [feat(ui): add originalType to FieldType, improved connection validation](https://github.com/invoke-ai/InvokeAI/commit/fc967a85fd6f659356e6e9e9af6d1d6d0bd7589b)
  
  We now keep track of the original field type, derived from the python type annotation in addition to the override type provided by `ui_type`.
  
  This makes `ui_type` work more like it sound like it should work - change the UI input component only.
  
  Connection validation is extend to also check the original types. If there is any match between two fields' "final" or original types, we consider the connection valid.This change is backwards-compatible; there is no workflow migration needed.
  
- [feat(ui): add ModelIdentifierField field type](https://github.com/invoke-ai/InvokeAI/commit/78cf6afe630054f2f77b8eea2ce3fb96047305ef)
  
  This new field type accepts _any_ model. A field renderer lets the user select any available model.
  
- [feat(nodes): add ModelIdentifierInvocation](https://github.com/invoke-ai/InvokeAI/commit/6bab1a1be7006274209025134f685ca268fa1026)
  
  This node allows a user to select _any_ model, outputting a `ModelIdentifierField` for that model.

Minor Changes:

- [feat(ui): prevent connections to direct-only inputs](https://github.com/invoke-ai/InvokeAI/commit/aad80fbabccea2f7e572f3f632cef1ad93dd835a)
- [fix(ui): do not allow comparison between undefined original types](https://github.com/invoke-ai/InvokeAI/commit/711f0440e7d32b70d49d4c681cfc2ad51883fd02)

## Related Issues / Discussions

Closes #6380

## QA Instructions

The implementation in this PR is maximally flexible.

The increased flexibility comes at the cost of greater potential for footgun. Because model fields accept connections, and we allow any model field as an input, users could accidentally connect invalid fields. For example, a LoRA model could be connected to a ControlNet model input.

We could reduce the flexibility in a few ways:
- Revert the change to allow all model fields to accept input connections and/or revert the new `ModelIdentifierInvocation`.
- Add a setting to enable the new connection validation logic. It would be disabled by default.

## Merge Plan

n/a

## Checklist

- [x] _The PR has a short but descriptive title, suitable for a changelog_
- [x] _Tests added / updated (if applicable)_
- [x] _Documentation added / updated (if applicable)_

### CODE REVIEW

**Comment by psychedelicious** [comment]
@skunkworxdark
This change enables your nodes. I made some changes to the core nodes so that anything that has a model drop-down can accept an input, and added an input UI component for plain `ModelIdentifierField`. It renders a list of _all_ models.

This does render some of the nodes in your XY pack obsolete, hopefully that's a good thing!

**Review by hipsterusername — APPROVED** [review]

**Comment by skunkworxdark** [comment]
@psychedelicious 
Firstly, I'm fine about it making any of my nodes redundant. Anything that improves core I am happy with. 

After a brief look at the changes, I have no issues with this PR.

I assume that these changes don't alter the behaviour of the existing nodes like `MainModelLoaerInvocation` beyond allowing setting via a `ModelIdentifierInvocation`.  i.e. the `SDXLModelLoaderInvocation` will only continue to display only SDXL models in the UI dropdown and the `LoRALoaderInvocation` will only LoRAs.

So the potential footgun moment only comes if the new `ModelIdentifierInvocation` is used and the user misselects a model or connects it to the wrong place.  If this is the case then the chances of getting it wrong are low as most people will probably continue to use the existing loaders to select models in the workflows.

**Comment by psychedelicious** [comment]
> So the potential footgun moment only comes if the new ModelIdentifierInvocation is used and the user misselects a model or connects it to the wrong place. If this is the case then the chances of getting it wrong are low as most people will probably continue to use the existing loaders to select models in the workflows.

Yep, that's right. I'm nervous about breaking the seal of our relatively foolproof connection validation logic though. Maybe we can hint to the user that the connection they are making is risky - like highlighting the field with a warning color. I'll try some things out.

**Comment by skunkworxdark** [comment]
> Yep, that's right. I'm nervous about breaking the seal of our relatively foolproof connection validation logic though. Maybe we can hint to the user that the connection they are making is risky - like highlighting the field with a warning color. I'll try some things out.

That does sound like a good way of visualising a potential problem that would normally be hidden from the user.  So if a connection is accepted on the wider type then highlight it with a different colour or line style.

**Comment by psychedelicious** [comment]
As I was working through the edge cases, I was increasingly unsure of connection validation. I've rewritten all of it with full test coverage:
https://github.com/invoke-ai/InvokeAI/assets/4822129/df5cf677-b3bb-423e-bce4-83bbc8d13359

This teased out a number of unknown edge cases, now resolved. 

The connection validation logic also much cleaner. For example, before we had ~3 different places where connection validation logic was implemented, each in a slightly different way. The logic is now consolidated to a handful of utilities (each fully tested).

**Comment by psychedelicious** [comment]
- Resolved edge updating jank and some issues with edge styling.
- Fixed an issue with linear workflow view.
- Removed a lot of extraneous actions and complexity. We now rely much more on `reactflow`'s state management. Bug surface area for nodes is much smaller. This also makes the undo/redo more consistent because there are fewer combinations of actions.

**Comment by psychedelicious** [comment]
I tried to add a warning when falling back on the original type, but propagating a warning got hairy. For now, that node is marked as prototype and its description explains the dangers. Hopefully that's enough to prevent footguns - worst case scenario - you get an error, not a big deal.

---

I'm happy with where this is now. I did some careful testing and fixed a couple outstanding issues.

**Pull request merged**
