### PR TITLE
Fix webui metadata issue #734

### PR DESCRIPTION
**Pull request by holstvoogd**
Set correct seed in metadata on image generation with more then one image.

### CODE REVIEW

**Comment by psychedelicious** [comment]
Hi @holstvoogd , 

I believe there also needs to be logic to handle if variations were involved.

@lstein , @blessedcoolant 

This PR relates to a change I've been wanting to do - make `iterations` a client-side parameter. Reasons:
- Currently if you have iterations > 1, even if you specify a seed, iterations 2 and onward have random seeds. This is counterintuitive.
- It implies moving grid to be a client side operation, which is where that functionality should be IMO (I haven't added grid to InvokeUI because I'd rather let users select 3 images and click "Make a grid of these", and it adds a lot of complexity)
- It prepares the UI for using a queuing system

I can do this on the UI simply and users wouldn't know the difference, however I'm not sure if calling `prompt2image` multiple times with iterations = 1 would impact variations.

Alongside this proposed change, I would suggest considering a refactor of the Generate class to never be concerned with generating more than a single image. Instead, add logic to `dream.py` and any other clients for making more multiple images and assembling them into a grid.

If moving iterations to be a parameter for users of the Generate class won't break variations, please hold off on this PR and I will code it up, fixing this issue as I do.

**Comment by holstvoogd** [comment]
@psychedelicious

Yeah, I was thinking about varations etc too after fixing this, I think the generation it self works as expected, or at least as I expect it:
- iterations >1, variant = 0, with either a randomized or given seed produces a repeatable series of seeds
- iterations >1, variant > 0, produces variant of the given seed (or randomized one)

However, the metadata contains the variant seed as a seed instead of the actual base seed. And so the seed button also doesn't work. As a work-around, using 'use all' and then 'use seed' on the original image works.

I was going to have a stab at fixen that, but if you're working on refactoring this all I'll leave it :)

**Comment by holstvoogd** [comment]
I've fixed the behaviour with variations locally, so I figured I'd update this nonetheless in case it is useful after all 👍

**Comment by lstein** [comment]
I believe that when a fixed seed is given and iterations > 1, then the first image generated should have the fixed seed, and subsequent images will have "random" seeds. However, since the second and subsequent random seed is actually based on the content of the fixed seed, the combination of a fixed seed and n>1 will *always* give the same series of images, which is what I expect. The same rule applies to the grid.

For variations (-v > 0, -n > 1), then there are two seeds per image. The `first_seed` is either the first randomly generated seed or the fixed seed from the user. It is used to kick off generation of the series. Then each generated image, starting with the first one, has a different `image seed` which is the result of noising the `first_seed` by the specified amount. So this is why the normalized dream command for variations contain two seeds, the `-S seed`, which corresponds to the `first_seed`, and `-V seed:distance`, which is the `image seed` plus the amount of noise introduced into it to generate the variation. The terminology is confusing, and threw me through a loop when I tried to fix up regressions in prompt generation a few days ago.

I'm going to test this a little bit to make sure it works across all the use cases. Unfortunately I'm at a conference and may not be able to get time to work on it until Saturday.

**Comment by lstein** [comment]
> However, the metadata contains the variant seed as a seed instead of the actual base seed. And so the seed button also doesn't work. As a work-around, using 'use all' and then 'use seed' on the original image works.

That's interesting. When I was working on the variation prompts Tuesday, I guess I fixed the normalized prompt, but not the `sd-metadata`! Give me a heads-up if you're going to make more commits into this PR, otherwise tomorrow when I get back to work I'll do the patch to metadata generation myself and merge this in.

**Comment by holstvoogd** [comment]
@lstein It should work correctly now, no more commits from me on this :)

To be precise, I've tested with (n>1):
- no -v
- -v>0, no -V
- -v=0, -V seed:weight
- -v>0, -V seed:weight
- -v=0, -V seed:weight,seed:weight,..

That all seems to work great.

**Comment by psychedelicious** [comment]
@holstvoogd Thank you for the fixes and testing!

**Review by lstein — APPROVED** [review]
LGTM

**Pull request merged**
