### PR TITLE
Split requirements / pyproject installation in Dockerfile

### PR DESCRIPTION
**Pull request by mauwii**
This should make caching way easier and therefore speed up the image (re-)creation a lot.

Other small improvements:
- reorder .dockerignore
- rename amd flavor to rocm to align with cuda flavor
- use `user:group` for definitions
- add `--platform=${TARGETPLATFORM}` to base

### CODE REVIEW

**Comment by lstein** [comment]
@mauwii Just want to make you aware that `main` is going to be frozen for some time while the node architecture is integrated and the refactor happens. If you want to have this go into `v2.3` as well, let me know and I'll cherry pick it.

**Review by lstein — APPROVED** [review]
LGTM

**Comment by mauwii** [comment]
@lstein: I thought the freeze is only for python related content, which this PR would not belong to 🤔

**Comment by lstein** [comment]
> @lstein: I thought the freeze is only for python related content, which this PR would not belong to 🤔
> 
> Regarding cherry picking this into v2.3: While it wouldn't hurt, I also think it should not be necesarry, as long as files related to this PR won't get changed in v2.3 branch 🙈

You're absolutely correct. I'm just warning you that these changes won't be in a release for some time, whereas the 2.3 branch is going to have a few bugfix releases over the next few weeks.

**Pull request merged**
