### PR TITLE
(feat)(ui) Add Gallery Image Numbers

### PR DESCRIPTION
**Pull request by mickr777**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [ ] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [ ] Yes
- [ ] No

## Description
Add Gallery Image Numbers Based off order in a board (off by default)

was trying to find a way to determine an image number for my Retrieve Images from Board node.

also might be useful for future projects to know the number of an image in a board.

image
Animation3

## Related Tickets & Documents

- Related Issue #
- Closes #

## Added/updated tests?

- [ ] Yes
- [ ] No : _please replace this line with details on why tests
      have not been included_

### CODE REVIEW

**Comment by Millu** [comment]
This works as expected for me, and I see the use case of having it for certain nodes or pulling certain images, but adding it to the gallery UI makes it feel cluttered

**Comment by mickr777** [comment]
> This works as expected for me, and I see the use case of having it for certain nodes or pulling certain images, but adding it to the gallery UI makes it feel cluttered

Maybe if it only shows selection and onhover when its enabled in setting

Animation3

**Comment by psychedelicious** [comment]
The image services don't support this type of query (getting a list of images by index), so this would be a very narrow change, targeting one specific community node.

I'd rather create an `ImageCollection` component that lets you drag in the images you want (or a whole board). I had started on this some time ago but put it on backburner behind more impactful changes.

Would that support your use-case?

**Comment by mickr777** [comment]
> The image services don't support this type of query (getting a list of images by index) and I don't anticipate providing it. It's a fragile and inefficient way of retrieving images. This would be a very narrow change, targeting one specific community node.
> 
> I'd rather create an `ImageCollection` component that lets you drag in the images you want (or a whole board). I had started on this some time ago but put it on backburner behind more impactful changes.
> 
> Would that support your use-case?

Yes that would be ideal 👌, I just made this pr and the node to try and get it all working with the current code, as I was seeing more people asking for multi image input, I knew at some stage that something like image collection input would come along

**Comment by mickr777** [comment]
Too niche to be useful

**Pull request closed without merging**
