### PR TITLE
UI guides

### PR DESCRIPTION
**Pull request by hipsterusername**
Pushing UI Guide updates

### CODE REVIEW

**Comment by psychedelicious** [comment]
Thanks for working on this. There are a few technical issues I have fixed in my fork of your branch: https://github.com/psychedelicious/stable-diffusion/tree/UI-Guides-feedback

Because I do not have full access to this repo, I am raising a PR against your branch with some changes and feedback.

**Review by lstein — APPROVED** [review]
Thanks for the extensive documentation work. This greatly enhances the front end.

**Comment by lstein** [comment]
> Thanks for working on this. There are a few technical issues I have fixed in my fork of your branch: https://github.com/psychedelicious/stable-diffusion/tree/UI-Guides-feedback
> 
> Because I do not have full access to this repo, I am raising a PR against your branch with some changes and feedback.

@psychedelicious This PR has conflicts with OptionsAccordion.tsx, SeedVariationOptions.tsx and systemSlice.ts. Did you submit a PR that incorporates these additions and fixes the technical issues? I can't find it.

**Comment by psychedelicious** [comment]
@lstein we need @hipsterusername to rebase onto development, then it can be merged. this PR now incorporates the fixes and suggestions. further work in this area will include help tooltips for individual settings, and links to documentation!

**Comment by hipsterusername** [comment]
I’ll do that today, as soon as I can figure out how to get git to play nice with me

**Comment by psychedelicious** [comment]
Rebasing won't be fun with the changes to folder structure and name, plus a lot of other changes... in this situation, my brute-force method is to just copy the files that have changed to a folder outside the git repo, make a new branch, and paste/edit the changes back in. Maybe there is a better way though.

**Comment by hipsterusername** [comment]
Yep... realizing that. lol

**Comment by hipsterusername** [comment]
Closing - Conflicts addressed in #767

**Pull request closed without merging**
