### PR TITLE
update binary installer to use latest k-diffusers

### PR DESCRIPTION
**Pull request by lstein**
After checking out this PR, please follow the directions at https://github.com/invoke-ai/InvokeAI/blob/update-binary-installer/docs/installation/BUILDING_BINARY_INSTALLERS.md#-2-run-pip-compile-on-each-platform ("Run `pip compile` on each platform") to compile the Py3* files and push back to this PR.

### CODE REVIEW

**Comment by damian0815** [comment]
M1 is good to go

(also tested it by doing a local-only edit of install.sh to point to this branch)

**Comment by damian0815** [comment]
if this branch does not make it onto main please ping me, there is valuable work renaming install.sh to install.sh.in, as well as documentation etc.

**Comment by tildebyte** [comment]
Testing on Win 11 with a local edit of install.sh to point here, and getting

```
ERROR: Could not find a version that satisfies the requirement pypatchmatch (from invokeai) (from versions: none)
ERROR: No matching distribution found for pypatchmatch
```

is this expected?

**Comment by hipsterusername** [comment]
@tildebyte I don't think this is expected... but has to be unrelated to this PR. Can you blow out and try a normal 2.2 install to see if you run into same issues?

**Comment by tildebyte** [comment]
> @tildebyte I don't think this is expected... but has to be unrelated to this PR. Can you blow out and try a normal 2.2 compile to see if you run into same issues?

Talked to damian and got it sorted

**Comment by lstein** [comment]
superseded

**Comment by damian0815** [comment]
@lstein @tildebyte there is valuable work on here that needs to be merged into main

**Comment by damian0815** [comment]
after that has been done the binary installer zips need to be rebuilt and re-tested on all platforms.

**Comment by lstein** [comment]
The code in this PR has now been incorporated into the currently merged binary installer via a series of smaller PRs and is confirmed working on. This includes the `install.sh.in`, `install.bat.in`, `invoke.sh.in`, and `invoke.bat.in` scripts, as well as `requirements.in`, and the compiled requirements files.

Thank you all for the work Damian and Tildebyte did on this.

**Pull request closed without merging**
