### PR TITLE
[WebUI] Add Image To Image UI

### PR DESCRIPTION
**Pull request by blessedcoolant**
Adds dedicated Image to Image UI for the WebUI

### CODE REVIEW

**Comment by lstein** [comment]
The image2image tab is working very nicely. A couple of things I found confusing:
1. When you first load an image, two images appear, and the one on the right is the last image that you happen to generate. I think that the right image should only appear after you do an img2img generation.
2. Maybe have a little '>' or arrow symbol between the init image on the right and the generated image on the left to show their relationship?
3. I think the user should be able to drag and drop an image from the image gallery onto the image2image pane.
4. I also found a bug in back end (or maybe a feature enhancement). If you have a PNG image that has a flipped orientation in the EXIF data, your WebGUI code recognizes it and shows the image right side up. However, the backend doesn't check for flipped images, and so the generated image is upside down! I will fix this and send a PR.

**Comment by blessedcoolant** [comment]
> 1. When you first load an image, two images appear, and the one on the right is the last image that you happen to generate. I think that the right image should only appear after you do an img2img generation.

> 2. Maybe have a little '>' or arrow symbol between the init image on the right and the generated image on the left to show their relationship?

Yeah. Basically the right hand side displays the current image. I need think of how to isolate this from an img2img generation only in terms of user experience. Because if this tab only shows the img2img generations, then the user wont be able to preview their gallery.

I'll try to think of some ways to improve this but this will be in the scope of the next update.

> 3. I think the user should be able to drag and drop an image from the image gallery onto the image2image pane.

Agreed. Added to the list of todo things for the next patch -- that will add inpainting too.

> 4. I also found a bug in back end (or maybe a feature enhancement). If you have a PNG image that has a flipped orientation in the EXIF data, your WebGUI code recognizes it and shows the image right side up. However, the backend doesn't check for flipped images, and so the generated image is upside down! I will fix this and send a PR.

Oh. Looking forward to the PR.

**Comment by lstein** [comment]
The EXIF rotation is now in and working with the webui. I directly pushed to `development` and `release-candidate-2` and will push into the PR as well.

**Comment by blessedcoolant** [comment]
Awesome. Merge this up when you get the chance. I'll pull to my  local from dev after that.

**Comment by lstein** [comment]
Oh, apparently I cannot push to this PR. I'm asked to provide a username. But the autorotate code is in `release-candidate-2` so will be picked up at merge time.

**Comment by blessedcoolant** [comment]
Merge it to dev?

**Review by lstein — APPROVED** [review]
It works well. I'll merge it into development.

**Pull request merged**
