### PR TITLE
feat(ui): refactor control adapters

### PR DESCRIPTION
**Pull request by psychedelicious**
Control adapters logic/state/ui is now generalized to hold controlnet, ip_adapter and t2i_adapter. In the future, other control adapter types can be added.

TODO:

- [x] Limit IP adapter to 1
- [x] Add T2I adapter to linear graphs
- [x] Fix autoprocess
- [x] T2I metadata saving & recall
- [x] Improve on control adapters UI

## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [x] Yes
- [ ] No, because:

### CODE REVIEW

**Comment by psychedelicious** [comment]
This PR is ready for review.

State and UI related to control adapters were refactored to accomodate T2I adapter:
- The `controlNetSlice` is now `controlAdapterSlice`
- This slice uses `createEntityAdapter` to manage all control adapters
- Components that were previously for ControlNet only or IP Adapter only have been effectively merged into components for any Control Adapter
- The UI for control adapters was reworked (not a huge change), see video below
- Any number of control adapters may be added, but there are some limits in place for how many can be active at a given time, as required by our backend:
  - only 1 IP adapter at a time
  - only controlnet OR t2i adapter may be enabled at a time
  - see video for how the restrictions are handled in UI.

https://github.com/invoke-ai/InvokeAI/assets/4822129/ed2c8c55-a350-4e33-8314-51fc4369c9db

**Comment by hipsterusername** [comment]
Excellent job on this - Even with the restrictions, I see how this will easily evolve into the "unrestricted" world after @RyanJDick and @GreggHelt2 have unleashed our controls.

**Comment by hipsterusername** [comment]
Only thing I can think of that we might need is to have a warning displayed if user tries to add T2I while controlnet is enabled (currently just a dead button) or vice versa

**Comment by maryhipp** [comment]
I don't have any T2I adapters installed and behvaior is button is there and enabled, but clicking it does nothing. I would expect the button (for all of these, probably) to be disabled if I don't have any of that model installed

**Comment by psychedelicious** [comment]
Updated for multi ip adapter & tested working.

> I don't have any T2I adapters installed and behvaior is button is there and enabled, but clicking it does nothing. I would expect the button (for all of these, probably) to be disabled if I don't have any of that model installed

Forgot to add the disabled flag to the buttons, fixed

Behaviour is now:
- Button is disabled if no models of that type
- On add, selects first model, preferring first compatible with selected base model
- On add or enable of controlnet/t2i, disables the other

**Comment by psychedelicious** [comment]
Added some insurance for incompatible models, and toast for t2i/controlnet mutual exclusiveness.

[fix(ui): do not add control adapters with incompatible models to graph](https://github.com/invoke-ai/InvokeAI/pull/4812/commits/b24aef162dda456a7bf21f4c3e80deb630e9af8b)

[feat(ui): disable invoke button if enabled control adapter model does not match base model](https://github.com/invoke-ai/InvokeAI/pull/4812/commits/d0a3120ea55a0f2bf2950bbe8f33348e3b9b6f5e)

[feat(ui): display toast when enabling t2i/controlnet and disabling the other](https://github.com/invoke-ai/InvokeAI/pull/4812/commits/aa2ccfd086d658f15e80a8cd2a333287b92128a1)

**Review by blessedcoolant — APPROVED** [review]

**Comment by blessedcoolant** [comment]
Didn't check code but the UX functionality seems fine to me.

**Comment by blessedcoolant** [comment]
Ran some extra tests to check if the adapters are working as intended. They seem to be. Primarily tested color (for T2I) along with the IP adapters. The rest of the T2I dont mean that much coz they exist on ControlNet too but I reckon they'll work just fine too.

**Comment by psychedelicious** [comment]
Thanks for testing, fixed the issue with sync button.

**Pull request merged**
