### PR TITLE
Add DWPose pose estimation preprocessor node for ControlNet depth model

### PR DESCRIPTION
**Pull request by GreggHelt2**
This is a draft PR because there are still a few issues with deployment:

1) The controlnet_aux package, which this PR relies on, states that using DWPose requires:
```
pip install -U openmim
mim install mmengine
mim install "mmcv>=2.0.1"
mim install "mmdet>=3.1.0"
mim install "mmpose>=1.1.0"
```
I have added openmim as a requirement in pyproject.toml. But I'm not sure how to add the "mim install ..." steps in the InvokeAI installer -- any suggestions? So for this draft the "mim install ..." commands above all need to be performed by the user.

2) I had a (temporary) problem with config files for the models that DWPose needs to do pose estimation
These two config files are included in the controlnet_aux package as *.py files:

          controlnet_aux/dwpose/yolox_config/yolox_l_8xb8-300e_coco.py
          controlnet_aux/dwpose/dwpose_config/dwpose-l_384x288.py

Code further down in the mm* packages requires these two configs be specified by their file paths. And initially I hit problems with this path being wrong which triggered errors. Subsequent attempts at InvokeAI `pip install -e .` seemed to fix this, and I haven't been able to repeat the problem. But I'm worried it will reappear.

Here's an example of usage. Image at right bottom is estimated pose output by DWPose preprocessor and image at right top is generated image when using estimated pose with ControlNet openpose model.
Screenshot from 2023-09-26 15-24-09

### CODE REVIEW

**Comment by hipsterusername** [comment]
@lstein @blessedcoolant - What do you think about inclusion of mim?

Is this a dependency that should be optional? Do we have a way to even support "optional" dependencies? Perhaps this is also the same question we need to prioritize answering for community nodes

**Comment by Millu** [comment]
Closes [#4542](https://github.com/invoke-ai/InvokeAI/issues/4542)

**Comment by Millu** [comment]
Revisiting this, I installed all the `mm...` packages with pip and it is working as expected for me

@RyanJDick, not sure who else any concerns with using pip instead of mim to install the needed packages?

**Comment by RyanJDick** [comment]
> Revisiting this, I installed all the `mm...` packages with pip and it is working as expected for me
> 
> @RyanJDick, not sure who else any concerns with using pip instead of mim to install the needed packages?

If we can install everything with `pip` (I think we can), then I'd much prefer that over adding `openmim` as another dependency and having to integrate it into the install logic. For the purposes of installing packages, mim just seems to act as a wrapper around pip.

**Comment by Millu** [comment]
Updated the PR to include OpenMMLab dependencies in the pyproject.toml to be pip installed - got it working locally but would appreciate others testing it

**Comment by RyanJDick** [comment]
Just tried to test this. I hit an error when trying to pip install:
```bash
Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-9hvoen6z/mmcv_9d1ff0d8e08846a98af4b3f5d8f4a60d/setup.py", line 448, in <module>
          setup(
        File "/home/ryan/.pyenv/versions/3.10.12/envs/InvokeAI_3.10.12/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/ryan/.pyenv/versions/3.10.12/envs/InvokeAI_3.10.12/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/ryan/.pyenv/versions/3.10.12/envs/InvokeAI_3.10.12/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/ryan/.pyenv/versions/3.10.12/envs/InvokeAI_3.10.12/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/home/ryan/.pyenv/versions/3.10.12/envs/InvokeAI_3.10.12/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/ryan/.pyenv/versions/3.10.12/envs/InvokeAI_3.10.12/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/home/ryan/.pyenv/versions/3.10.12/envs/InvokeAI_3.10.12/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/home/ryan/.pyenv/versions/3.10.12/envs/InvokeAI_3.10.12/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/home/ryan/.pyenv/versions/3.10.12/envs/InvokeAI_3.10.12/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/home/ryan/.pyenv/versions/3.10.12/envs/InvokeAI_3.10.12/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/ryan/.pyenv/versions/3.10.12/envs/InvokeAI_3.10.12/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/home/ryan/.pyenv/versions/3.10.12/envs/InvokeAI_3.10.12/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/ryan/.pyenv/versions/3.10.12/envs/InvokeAI_3.10.12/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/home/ryan/.pyenv/versions/3.10.12/envs/InvokeAI_3.10.12/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/ryan/.pyenv/versions/3.10.12/envs/InvokeAI_3.10.12/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/home/ryan/.pyenv/versions/3.10.12/envs/InvokeAI_3.10.12/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/ryan/.pyenv/versions/3.10.12/envs/InvokeAI_3.10.12/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/home/ryan/.pyenv/versions/3.10.12/envs/InvokeAI_3.10.12/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "/home/ryan/.pyenv/versions/3.10.12/envs/InvokeAI_3.10.12/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 387, in _check_cuda_version
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (12.2) mismatches the version that was used to compile
      PyTorch (11.8). Please make sure to use the same CUDA versions.
```

My interpretation is that during installation mmcv is trying to build torch extensions from source and is using my host CUDA install rather than the one bundled with torch. Haven't found an easy workaround yet, and would rather not have to downgrade my host CUDA version.

**Comment by hipsterusername** [comment]
The joys of Python strike again

**Comment by Millu** [comment]
Closing as DWPose has been implemented!

**Pull request closed without merging**
