### PR TITLE
fix(nodes): use context for logger in param_easing

### PR DESCRIPTION
**Pull request by psychedelicious**

### CODE REVIEW

**Comment by GreggHelt2** [comment]
LGTM

**Comment by psychedelicious** [comment]
@GreggHelt2 Is the debug logging here actually needed at this stage?

**Review by lstein — APPROVED** [review]
Looks good to me.

**Comment by psychedelicious** [comment]
Hey @GreggHelt2 is there a particular need for logging of the parameter easing feature or can we get rid of the logging messages?

**Pull request merged**
