### PR TITLE
feat(mm): remove autoimport, revised startup model scanning

### PR DESCRIPTION
**Pull request by psychedelicious**
## Summary

Copying the meat-and-potatoes from commit messages. There are a few supporting changes (docs, frontend) per commits.

[feat(mm): remove autoimport; revise startup model scanning](https://github.com/invoke-ai/InvokeAI/commit/635a60e8e09c603c0adc6e86e89b6b35b33985d2)

These two changes are interrelated.

## Autoimport

The autoimport feature can be easily replicated using the scan folder tab in the model manager. Removing the implicit autoimport reduces surface area and unifies all model installation into the UI.

This functionality is removed, and the `autoimport_dir` config setting is removed.

## Startup model dir scanning

We scanned the invoke-managed models dir on startup and took certain actions:

- Register orphaned model files
- Remove model records from the db when the model path doesn't exist

### Orphaned model files

We should never have orphaned model files during normal use - we manage the models directory, and we only delete files when the user requests it.

During testing or development, when a fresh DB or memory DB is used, we could end up with orphaned models that should be registered.

Instead of always scanning for orphaned models and registering them, we now only do the scan if the new `scan_models_on_startup` config flag is set.

The description for this setting indicates it is intended for use for testing only.

### Remove records for missing model files

This functionality could unexpectedly wipe models from the db.

For example, if your models dir was on external media, and that media was inaccessible during startup, the scan would see all your models as missing and delete them from the db.

The "proactive" scan is removed. Instead, we will scan for missing models and log a warning if we find a model whose path doesn't exist. No possibility for data loss.

## Related Issues / Discussions

Discord thread: https://discord.com/channels/1020123559063990373/1149513695567810630/1222097965045514250

## QA Instructions

Test the revised startup model scan:
- Set `use_memory_db: true` in `invokeai.yaml`
- Start up the app
- You should have no models
- Set `scan_models_on_startup: true` in `invokeai.yaml`
- Start up the app
- It should register all your models

Test orphaned model change:
- Move a model out of your models dir
- Start the app
- You should get a warning in terminal saying the model is missing, but it should still be in the model manager. Generation should fail if you try with it
- Move the model back into the models dir
- Start the app
- Should have no warning, and the model should work
 
## Merge Plan

N/A

## Checklist

- [x] _The PR has a short but descriptive title, suitable for a changelog_
- [x] _Tests added / updated (if applicable)_ N/A
- [x] _Documentation added / updated (if applicable)_

### CODE REVIEW

**Comment by brandonrising** [comment]
I think ensuring the app can start up with registered model config paths not existing would be a solid pytest

**Comment by brandonrising** [comment]
Not sure if I'm having a caching issue, but I've rebuilt the frontend and backend a few times but this sync models button is still there even though it looks like it's gone in this PR. When I press it, I get a 405 from the backend 🤔 could just be a me problem though
Screenshot 2024-03-27 at 3 17 28 PM

**Review by brandonrising — APPROVED** [review]

**Comment by psychedelicious** [comment]
> I think ensuring the app can start up with registered model config paths not existing would be a solid pytest

I think we'll need full e2e tests for this, maybe in the future if the gh runners can handle it

**Review by hipsterusername — APPROVED** [review]

**Comment by midtownkc** [comment]
Changes like this really make invokeai suck.  The javascript interface straight up sucks.

**Pull request merged**
