### PR TITLE
Web UI: Fixes same seed reported when with_variations=[] and iterations > 1

### LINKED ISSUE #1223: web api returning incorrect seed information when generateImage gets unexpected input
**Describe your environment**
- GPU: cuda
- VRAM: 12gb
- CPU arch: x86
- OS: Windows 10
- Python: Anaconda
- Branch: development
- Commit: d8c1b78d832e1a6eb4352f2e88726cf7b0e6dcbd

**Describe the bug**
The web api returns incorrect seed information when fed unexpected input via the "generateImage" websocket interface. 

Specifically, inside the generateImage request I was including an empty `with_variation: []` property when it was not required, on a request with multiple iterations. The first seed was correct, and every image afterwards returned the same seed both via api and embedded in the png metadata.

Discovered by accident, I initially reported it [in discord here](https://discord.com/channels/1020123559063990373/1033403525373374464/1033403525373374464)  , and was asked by @psychedelicious to submit the issue.

I've attached the raw request and results from my bot log in case its useful.
**This isn't currently an issue for the web ui** , but it may mean there are issues with the parameter handling for generateImage 

[invokeai-api-bug-log.txt](https://github.com/invoke-ai/InvokeAI/files/9846530/invokeai-api-bug-log.txt)

### PR DESCRIPTION
**Pull request by psychedelicious**
Web UI: Fixes same seed reported when with_variations=[] and iterations > 1
Fixes #1223

### CODE REVIEW

**Comment by psychedelicious** [comment]
@ausbitbank can you please try this change out?

**Comment by ausbitbank** [comment]
I pulled your repository and checked out the fix-incorrect-seed branch , started the api and tested but got the same result still.

request (intercepted and edited to add with_variations: [] using burpsuite)
`42["generateImage",{"prompt":"test","iterations":2,"steps":15,"cfg_scale":7.5,"threshold":0,"perlin":0,"height":512,"width":512,"sampler_name":"k_lms","seed":3471630626,"seamless":false,"hires_fix":false,"progress_images":false,"variation_amount":0,"with_variations":[]},false,false]`

both responses have the same seed:
`42["generationResult",{"url":"outputs/000001.3471630626.png","mtime":1666535971.5529692,"metadata":{"model":"stable diffusion","model_id":null,"model_hash":"fe4efff1e174c627256e44ec2991ba279b3816e364b49f9be2abc0b3ff3f8556","app_id":"lstein/stable-diffusion","app_version":"v1.15","image":{"prompt":[{"prompt":"test","weight":1.0}],"steps":15,"cfg_scale":7.5,"threshold":0,"perlin":0,"height":512,"width":512,"seed":3471630626,"seamless":false,"hires_fix":false,"postprocessing":null,"sampler":"k_lms","variations":[],"type":"txt2img"}}}]`

`42["generationResult",{"url":"outputs/000002.3471630626.png","mtime":1666535977.6119702,"metadata":{"model":"stable diffusion","model_id":null,"model_hash":"fe4efff1e174c627256e44ec2991ba279b3816e364b49f9be2abc0b3ff3f8556","app_id":"lstein/stable-diffusion","app_version":"v1.15","image":{"prompt":[{"prompt":"test","weight":1.0}],"steps":15,"cfg_scale":7.5,"threshold":0,"perlin":0,"height":512,"width":512,"seed":3471630626,"seamless":false,"hires_fix":false,"postprocessing":null,"sampler":"k_lms","variations":[],"type":"txt2img"}}}]`

**Comment by lstein** [comment]
@psychedelicious should this be merged?

**Comment by lstein** [comment]
@psychedelicious Is this PR still in need of merging?

**Comment by ausbitbank** [comment]
@lstein I'm guessing no, since it doesn't solve the original issue of repeating seeds. 
Same issue still exists in the latest dev branch, but I would say its very low priority as it does not affect API clients giving the correct parameters as demonstrated by web ui..

**Pull request closed without merging**
