### PR TITLE
Improve model load times from disk: skip unnecessary weight init

### PR DESCRIPTION
**Pull request by RyanJDick**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission
      
## Have you updated all relevant documentation?
- [x] Yes
- [ ] No

## Description

This PR optimizes the time to load models from disk.
In my local testing, SDXL text_encoder_2 models saw the greatest improvement:
- Before change, load time (disk to cpu): 14 secs
- After change, load time (disk to cpu): 4 secs

See the in-code documentation for an explanation of how this speedup is achieved.

## Related Tickets & Documents

This change was previously proposed on the HF transformers repo, but did not get any traction: https://github.com/huggingface/transformers/issues/18505#issue-1330728188

## QA Instructions, Screenshots, Recordings

I don't expect any adverse effects, but the new context manager is applied while loading **all** models, so it would make sense to exercise everything.

## Added/updated tests?

- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by hipsterusername** [comment]
Great find - Will try to test later this evening

**Comment by hipsterusername** [comment]
Wow, this is significantly faster for SDXL. Great work on this!

**Review by lstein — APPROVED** [review]
I’m getting a 40-50% speed up on loading of large models. Really great work!

**Comment by psychedelicious** [comment]
I'm getting about 40% - 50% speedups also, sweet!

**Review by psychedelicious — APPROVED** [review]

**Comment by YouJiacheng** [comment]
Hello! Your implementation cannot strictly restore the original behavior after the context manager. 

There might be another library who expects monkey patching reset_parameter in base class will affect all sub classes without reset_parameter overriding.

For example, Conv2d inherit reset_parameter from _ConvNd. Your implementation will copy the method from _ConvNd to Conv2d after the context manager. This will be a dynamic overriding and shadows any monkey patch applied to _Conv2d.

**Pull request merged**
