### PR TITLE
Add defaults for controlnet/textual inversion/realesrgan

### PR DESCRIPTION
**Pull request by lstein**
This PR adds several default models to the ones selected at install time. It also removes the GFPGAN and text2clip models, which should shave a little time off the install process.

## ESRGAN:
* models/core/upscaling/realesrgan/RealESRGAN_x4plus.pth
* models/core/upscaling/realesrgan/RealESRGAN_x4plus_anime_6B.pth
* models/core/upscaling/realesrgan/ESRGAN_SRx4_DF2KOST_official-ff704c30.pth

## ControlNet
* models/sd-1/controlnet/canny
* models/sd-1/controlnet/depth
* models/sd-1/controlnet/lineart
* models/sd-1/controlnet/openpose

## Embedding (textual inversion)
* models/sd-1/embedding/EasyNegative.safetensors

### CODE REVIEW

**Review by psychedelicious — APPROVED** [review]
Thanks Lincoln, I've added and tested a RealESRGAN upscaling node, works great.

We can fully remove the restoration services now, they are not needed. I've removed all references to them in the nodes app layer and updated the tests.

It's just the backend that has the actual restoration code - I'll leave that to you to remove.

**Comment by psychedelicious** [comment]
@maryhipp @brandonrising @ebr 
This PR introduces preloading of:
- select ControlNet models (safe for commercial)
- 3x "official" [RealESRGAN models (BSD-3 License, also safe)](https://github.com/xinntao/Real-ESRGAN/blob/master/LICENSE)
- the [EasyNegative](https://huggingface.co/datasets/gsdf/EasyNegative) TI embedding, for which I could not find any explicit license info in a brief search

It also introduces an upscaling node, which is not yet exposed in the Linear UI. I'll add that later.

**Review by GreggHelt2 — APPROVED** [review]
LGTM

**Comment by lstein** [comment]
I've removed all the backend restoration code and will merge.

**Comment by psychedelicious** [comment]
I've added a couple small fixes:
- Type the `configuration` service correctly as `InvokeAIAppConfig`
- Update the `realesrgan` node to use the `models_path` var

**Review by blessedcoolant — APPROVED** [review]

**Pull request merged**
