### PR TITLE
Remove extra randn call in ksampler leading to break in reproducibility

### LINKED ISSUE #966: Current dev environment produce different pictures than before, could not use ddim and plms - noise output
**Describe your environment**
- GPU: [cuda]
- VRAM: [6GB]
- CPU arch: [x86]
- OS: [Windows]
- Python: [miniconda]
- Branch: On branch upstream-development  - Your branch is up to date with 'upstream/development'
- Commit: commit 4f247a3672474bd9c46060bab6087dbf9e2531f3

**Describe the bug**
On development branch pictures generated with the same arguments now are very different. 
Samplers ddim and plms produce noise instead of images

**To Reproduce**
Command: "brown corgi, clean background, flat design:1.0" -s 20 -S 1 -W 512 -H 512 -C 7.5 -A plms

**Expected behavior**
Expected picture the same as it was in main / development on 30 Sep

**Screenshots**
image

### PR DESCRIPTION
**Pull request by ArDiouscuros**
Hi @lstein 
I found one issue (?) in ksampler, an extra random generation. It will change all subsequent noise / random generations if we not set/reset the seed. Just removing it give me images much closer to saved results.
Probably fixes #966. Image comparison required.

### CODE REVIEW

**Comment by Any-Winter-4079** [comment]
This solves reproducibility but breaks the `img2img` fix from https://github.com/invoke-ai/InvokeAI/issues/889
A mix of both solutions is needed.

**Comment by lstein** [comment]
Thanks! I was just trying to figure this out myself. I hope your patch
fixes it!

L

**Comment by lstein** [comment]
So as @Any-Winter-4079 mentioned, this PR fixes the variation issue but breaks img2img. One simple fix for this will restore variations from `txt2img` but variation settings won't apply to `img2img`. Since the initial image already strongly contrains the variability of `img2img` I wonder if this will be a problem? To be honest, I've never explored using variations in combination with `img2img` so I'm not sure what we expect.

**Comment by ArDiouscuros** [comment]
I will check how it could be enabled to work with img2img

**Comment by lstein** [comment]
I just proposed PR #979 which restore variations to `txt2img` but doesn't break `img2img` However, variations don't work with `img2img`. This is a quick fix for now.

**Comment by Any-Winter-4079** [comment]
@lstein @ArDiouscuros Dirty fix/hack may be:
```
if x_T is not None:
            if S != total_steps -1:
                x = x_T + torch.randn([batch_size, *shape], device=self.device) * sigmas[0]
            else:
                x = x_T * sigmas[0]
```

**Comment by Any-Winter-4079** [comment]
I haven't tested variations, but the idea is, with txt2img we don't use strength, so S should be len(sigmas) - 1 (because we add one extra sigma). However, img2img uses strengths, which reduces the steps (except for -f1, but that's an extreme case). Hence, S and len(sigmas) -1 no longer coincide.

In the code, there is 
`total_steps = len(self.sigmas)`
so I just used that line instead.

Have not tested variations.

**Comment by ArDiouscuros** [comment]
@Any-Winter-4079 , @lstein 
I have made, as I think, a fix for both modes. But I could not check img2img b.c. I could not get the difference in pictures with or without the fix.
Could you please test and/or give some info how to test img2img ?

**Comment by Any-Winter-4079** [comment]
@ArDiouscuros yes, I think we have come up with 3 different ways to do the same thing :)
with lstein 's solution having been merged already

To test `img2img` I just run it, for example using this source image
[193515615-921b5f80-a2f3-4351-9459-b8e447ea765d 2.png.zip](https://github.com/invoke-ai/InvokeAI/files/9737319/193515615-921b5f80-a2f3-4351-9459-b8e447ea765d.2.png.zip)
and with the command
`"photograph of a tree on a hill with a river" -S 12345 -W 512 -H 512 -C 7.5 -I 193515615-921b5f80-a2f3-4351-9459-b8e447ea765d.png -A k_euler -f0.6 -s40`

You can change `-f` in the range (0,1) and see results. The higher `-f` (strength) the more creativity / more the result deviates from the original image, e.g.
Screenshot 2022-10-07 at 22 30 01

The issue with `img2img` was for low strengths, images looked washed out. See https://github.com/invoke-ai/InvokeAI/issues/889#issuecomment-1267664700 for an example.

**Pull request closed without merging**
