### PR TITLE
backend: more post-ldm-removal cleanup

### PR DESCRIPTION
**Pull request by keturn**

### CODE REVIEW

**Review by lstein — COMMENTED** [review]
Nice to see so much code disappearing.

**Comment by lstein** [comment]
Dangling call to `_model_to_cpu` here:
```
    def offload_model(self, model_name: str) -> None:
        """
        Offload the indicated model to CPU. Will call
        _make_cache_room() to free space if needed.
        """
        if model_name not in self.models:
            return

        print(f">> Offloading {model_name} to CPU")
        model = self.models[model_name]["model"]
        model.offload_all()
        self.models[model_name]["model"] = self._model_to_cpu(model)

        gc.collect()
        if self._has_cuda():
            torch.cuda.empty_cache()
```

Also, pyflakes is complaining about `undefined name 'model_description'` I'll commit fixes.

**Review by lstein — APPROVED** [review]
Seems to be working now.

**Comment by keturn** [comment]
Thanks for catching that!

**Pull request merged**
