### PR TITLE
Cancel, Error/Logging, and Gallery UX improvements

### LINKED ISSUE #817: Web server backend crashes if a file in local storage is missing
**Describe your environment**
- GPU: CUDA
- VRAM: 24 GB
- CPU x86
- OS: Linux
- Python: Anaconda, python 3.9
- Branch: development
- Commit: 14616f41786b2282e3686d86b2c79f9ddc95f479

**Describe the bug**
I recently deleted all the contents of my output directory. Now the web server backend gives a FileNotFound error whenever I try to perform a render. I had to reset the WebUI in order to get back to a usable state.

**To Reproduce**
1. Generate a bunch of images
2. Turn off the backend server (may not be necessary)
3. Delete the images
5. Restart the server
6. Try to generate a new prompt
7. Generation fails with a FileNotFound error on one of the previously generated and now deleted images.

### LINKED ISSUE #847: Web UI - Canceling doesn't update UI as expected
Canceling doesn't update the UI (progress bar, status message) as expected.

### LINKED ISSUE #848: Web UI - "Load more" button should give feedback if no more images
"Load more" button should give feedback if no more images to load.

### LINKED ISSUE #849: Web UI - Missing files are not handled gracefully
Missing files are not handled gracefully by the web UI - fatal crashes and errors abound.

### PR DESCRIPTION
**Pull request by psychedelicious**
This PR includes 3 unrelated commits. It cannot be merged until I update it with a compiled JS bundle, pending merging of #846. See #853 for why and a solution.

**Changes/Commits**

[Improves canceling UX](https://github.com/invoke-ai/InvokeAI/commit/a86643121aec9825d9379b8d9bacd87333ba442c) - resolves #847:
- Canceling previously didn't update the status text @ top right as you'd expect. This is improved/fixed.
- You may now cancel between generation and each postprocessing step.

[Improves error & logs UX](https://github.com/invoke-ai/InvokeAI/commit/465e4a5ab1d37f507ec4735752577bedf1382d56) - resolves #849, resolves #817:
- Each major action the server takes (e.g. load all images, upscale image, generate image) is now in a try-except. Exceptions are displayed in the terminal output and the message is sent to the UI.
- The status text @ top right indicates if an error has occurred as does the log viewer button at bottom left. Clicking either clears the error indicators.
- The log viewer is now resizable - much more usable. 
- Note that this only mostly addresses #849 and #817. A future improvement is to detect missing images (in gallery or init/mask images) and remove them from the UI.

[Improves gallery 'Load more' UX](https://github.com/invoke-ai/InvokeAI/commit/f4e5a71009e9cd1b7a38a648e474bf758b4bdf71) - resolves #848:
- When all images in the outputs folder have been loaded, the 'Load more' button disappears.

### CODE REVIEW

**Comment by lstein** [comment]
I just approved and merged #846.

**Comment by psychedelicious** [comment]
Thanks @lstein , I have added merged changes from development and added the updated JS bundle. this is now ready for review.

**Comment by psychedelicious** [comment]
Thanks to #869 I found a bug that caused images to sometimes not load. 

The bug was triggered when the user deleted some images and then loaded more, and this caused the next page of images requested to be offset incorrectly. 

34db28b6dad152b231ddbf6a80000656392d7bf8 fixes this by refactoring how images are loaded; pagination is now based on timestamps instead of a page number and offset.

At some point, my code formatter kicked in and changed a lot of whitespace in the server script. Sorry!

This is ready for review.

**Comment by psychedelicious** [comment]
I've merged all the changes here in with the rework of the UI in PR #879. As we worked on #879, we fixed a number of other bugs, so that PR supersedes this one in a big way. Closing.

**Pull request closed without merging**
