### PR TITLE
Possible fix for crash introduced in #1948

### PR DESCRIPTION
**Pull request by blessedcoolant**
Not sure if this was the intended logic you were going for. If it is, then it should fix a crash introduced in #1948 .. Please give it a test. @lstein

### CODE REVIEW

**Review by hipsterusername — APPROVED** [review]

**Comment by hipsterusername** [comment]
Approved, assuming @lstein gives it the blessing of "working as intended"

**Review by lstein — APPROVED** [review]
Apologies for introducing the regression!

The proposed fix wasn't quite right. This should fix it. Tested in both venv and conda environments.

**Comment by blessedcoolant** [comment]
> Apologies for introducing the regression!
> 
> The proposed fix wasn't quite right. This should fix it. Tested in both venv and conda environments.

LGTM

**Comment by ebr** [comment]
LGTM - was just about to pick it up when I saw this PR

**Pull request merged**
