### PR TITLE
Mac MPS FP16 fixes

### PR DESCRIPTION
**Pull request by gogurtenjoyer**
This PR is to allow FP16 precision to work on Macs with MPS. In addition, it centralizes the torch fixes/workarounds required for MPS into a new backend utility `mps_fixes.py`. This is conditionally imported in `api_app.py`/`cli_app.py`.

Many MANY thanks to @StAlKeR7779 for patiently working to debug and fix these issues.

### CODE REVIEW

**Comment by psychedelicious** [comment]
Thanks for working on this! I'm looking forward to generating my my m1. 

Are the methods patched totally nonfunctional on mps, or just didn't fully work for what invoke does?  

My concern is that we alter some functionality in a dependency by monkeypatching torch. 

Would it be feasible to have an mps_fixes module that exports wrappers for each of these torch functions, and we use those wrapper torch functions instead?

I wonder if this could be implemented as a `@mps_compat` decorator… that'd be a very clean way to handle it. It's opt-in and explicit instead of non-negotiable and invisible, and still easy to rip out once the root causes in torch are addressed.

**Comment by gogurtenjoyer** [comment]
Thanks! The methods patched are non-functional in FP16 precision on MPS at the very least, and yeah I'd love any ideas to minimize future work to remove these as they become no longer necessary. We did initially have a decorator func to do the wrapping but there were some concerns there, but it sounds like your idea is better than what we had, too.

**Comment by psychedelicious** [comment]
@StAlKeR7779 has a good point (in our chat) - the effect of the monkey-patching on any dependencies who use torch, is that torch works for them on MPS, so my concern is actually a good thing :)

**Review by lstein — APPROVED** [review]
Nice work! All the Mac users will be very excited about this.

**Review by StAlKeR7779 — APPROVED** [review]

**Pull request merged**
