### PR TITLE
Fix basicsr conflicts

### PR DESCRIPTION
**Pull request by lstein**
# Fix `basicsr` incompatibilities

The issue is the basicsr 1.4.2 doesn't work on Windows, and 1.4.1 doesn't work on Mac. However, GFPGAN requires 1.4.2 or higher.
    
To work around this, we pull in either of two different branches of the invoke-ai fork of GFPGAN, depending on the OS. This seems to be working well with the conda install, but I'm still getting issues with the pip-only install when trying to load the _Windows_ requirements file on Linux ("torch not found" error). I'm not sure if this is a problem that will appear on a real Windows system, but needs testing. The workaround is to run `pip install torch==1.12.*`

### CODE REVIEW

**Comment by lstein** [comment]
@Vargol See if this fixes the `basicsr` problems on Mac and let me know the result in a comment.

**Comment by Vargol** [comment]
Looks good. 

```
ln -sf environments-and-requirements/requirements-mac-mps-cpu.txt requirements.txt
pip --prefer-binary install -r requirements.txt
```
installed without issue, and I was able to start the GUI and run a prompt after finishing the setup.

**Comment by addianto** [comment]
Hello. Sorry if I suddenly barge in into the discussion.

> To work around this, we pull in either of two different branches of the invoke-ai fork of GFPGAN, depending on the OS. This seems to be working well with the conda install, but I'm still getting issues with the pip-only install when trying to load the _Windows_ requirements file on Linux ("torch not found" error). I'm not sure if this is a problem that will appear on a real Windows system, but needs testing. The workaround is to run `pip install torch==1.12.*`

It did appear at #1409. I still experienced it when re-install InvokeAI recently using  93cdb476d919b779e32a638aae15e56cc46b7adb using pip-based install method. The workaround is to install `torch` and `torchvision` manually using `pip` before installing the required packages from `requirements.txt` file.

**Comment by lstein** [comment]
@Vargol and @addianto,  I have implemented a different fix that involved tinkering with our fork of GFPGAN. If you have a chance, could you go to the main or development branch and try updating your environments?

Thanks.

**Comment by addianto** [comment]
Will do. Thanks for the update. 👍

**Comment by addianto** [comment]
Hello @lstein,

I tried running `pip install` on two instances of InvokeAI. First is the instance based on `main` branch (58f65d49b6cd17c8fc70e86b32a41ca7a98ce304) with `torch` dependency installed manually, i.e. not through `pip install -r requirements`.

I called `python -m pip install --prefer-binary -r .\requirements.txt` to update the environment.
There is no error whatsoever. The updated GFPGAN seems successfully installed as well based on the following log:

```
Collecting clip
  Cloning https://github.com/openai/CLIP.git (to revision main) to c:\users\REDACTED\appdata\local\temp\pip-install-dqtvhdv0\clip_8abb61d2a34b48a595d197c9980bff08
  Running command git clone --filter=blob:none --quiet https://github.com/openai/CLIP.git 'C:\Users\REDACTED\AppData\Local\Temp\pip-install-dqtvhdv0\clip_8abb61d2a34b48a595d197c9980bff08'
  Resolved https://github.com/openai/CLIP.git to commit d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
  Preparing metadata (setup.py) ... done
Collecting k-diffusion
  Cloning https://github.com/Birch-san/k-diffusion.git (to revision mps) to c:\users\REDACTED\appdata\local\temp\pip-install-dqtvhdv0\k-diffusion_c1af56a85e014732b38fa664471be9de
  Running command git clone --filter=blob:none --quiet https://github.com/Birch-san/k-diffusion.git 'C:\Users\REDACTED\AppData\Local\Temp\pip-install-dqtvhdv0\k-diffusion_c1af56a85e014732b38fa664471be9de'
  Resolved https://github.com/Birch-san/k-diffusion.git to commit 9bfd658ba7190f6e1403d8c77f6c8e26a4a9a7dc
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting clipseg
  Cloning https://github.com/invoke-ai/clipseg.git (to revision relaxed-python-requirement) to c:\users\REDACTED\appdata\local\temp\pip-install-dqtvhdv0\clipseg_4dbad855101a451d9c3490686686f0b3
  Running command git clone --filter=blob:none --quiet https://github.com/invoke-ai/clipseg.git 'C:\Users\REDACTED\AppData\Local\Temp\pip-install-dqtvhdv0\clipseg_4dbad855101a451d9c3490686686f0b3'
  Running command git checkout -b relaxed-python-requirement --track origin/relaxed-python-requirement
  branch 'relaxed-python-requirement' set up to track 'origin/relaxed-python-requirement'.
  Switched to a new branch 'relaxed-python-requirement'
  Resolved https://github.com/invoke-ai/clipseg.git to commit 1f754751c85d7d4255fa681f4491ff5711c1c288
  Preparing metadata (setup.py) ... done
Collecting gfpgan
  Cloning https://github.com/invoke-ai/GFPGAN to c:\users\REDACTED\appdata\local\temp\pip-install-dqtvhdv0\gfpgan_8282f53a5f5a4c92aae88d4c7045190f
  Running command git clone --filter=blob:none --quiet https://github.com/invoke-ai/GFPGAN 'C:\Users\REDACTED\AppData\Local\Temp\pip-install-dqtvhdv0\gfpgan_8282f53a5f5a4c92aae88d4c7045190f'
  Resolved https://github.com/invoke-ai/GFPGAN to commit 51593f7bb5a9a86c58dd91ae2e7fd6b20aa486b4
  Preparing metadata (setup.py) ... done
Obtaining file:///D:/REDACTED/workspace/ai-art/frontend/InvokeAI-fork (from -r .\requirements.txt (line 8))
  Preparing metadata (setup.py) ... done
```

The second instance is probably more related to the dependency issue that supposed to be addressed by this PR.
I tried to perform fresh installation of InvokeAI based on latest commit on `development` branch (d998b2f80654cfddc4df3a05cec9f6b5a72b89bf). It still fails when the installation process attempted to install `basicsr`.

Here I attached stdout and stderr output from  `pip install -v -r requirements.txt` invocation:

[pip_error_development.log](https://github.com/invoke-ai/InvokeAI/files/10032492/pip_error_development.log)

**Comment by lstein** [comment]
Much obliged for the testing and the log. So it looks like the path of
least resistance here is to modify the installation instructions to have
the user run the command:

```
pip install pytorch==1.12 torchvision torchaudio
```

Just prior to running `pip install -r requirements.txt`. Will this work?

Lincoln

On Thu, Nov 17, 2022 at 9:56 AM Daya Adianto ***@***.***>
wrote:

>
>
The second instance is probably more related to the dependency issue that

**Comment by addianto** [comment]
> Much obliged for the testing and the log. So it looks like the path of least resistance here is to modify the installation instructions to have the user run the command: ``` pip install pytorch==1.12 torchvision torchaudio ``` Just prior to running `pip install -r requirements.txt`. Will this work?

I think it will work, at least on manual, `pip`-based installation. The `pip` commands in `docs/installation/INSTALL_MANUAL.md` may need to be modified to this example:

```shell
pip install --extra-index-url https://download.pytorch.org/whl/cu116 --trusted-host https://download.pytorch.org torch==1.12.1 torchvision==0.13.1
pip install --prefer-binary -r requirements.txt # Copy-pasted/symbolic linked to requirements-win-colab-cuda.txt
```

**Pull request closed without merging**
