### PR TITLE
Responsive for devices under 600px

### PR DESCRIPTION
**Pull request by pandasonic-collective**
This doesn't not work for the Canvas Painting yet, but works on img2img and text2img

### CODE REVIEW

**Comment by lstein** [comment]
I don't know enough about the web code to review this, I'm afraid.

**Review by hipsterusername — APPROVED** [review]
Approved - Thanks for the contribution!

**Comment by netsvetaev** [comment]
@pandasonic-collective do you plan to work on this further? I would like to design an app-like UI.

**Review by psychedelicious — APPROVED** [review]
Thanks!

**Comment by pandasonic-collective** [comment]
> @pandasonic-collective do you plan to work on this further? I would like to design an app-like UI.

yes, I will be working on some more updates

**Pull request merged**
