### PR TITLE
Fix models.yaml.example and test-invoke-conda

### PR DESCRIPTION
**Pull request by mauwii**
- fix model dl path for sd-v1-4.ckpt
- copy configs/models.yaml.example to configs/models.yaml

### CODE REVIEW

**Comment by mauwii** [comment]
@lstein looks like the secret HUGGINGFACE_TOKEN was deleted:

https://github.com/invoke-ai/InvokeAI/actions/runs/3364870031/jobs/5579720485#step:9:5 (there should be a *** in this line if the secret would still exist...)

Since this got deleted the download of the models is not possible which let the action fail ....

**Comment by lstein** [comment]
> @lstein looks like the secret HUGGINGFACE_TOKEN was deleted:
> 
> https://github.com/invoke-ai/InvokeAI/actions/runs/3364870031/jobs/5579720485#step:9:5 image There should be a *** in this line if the secret would still exist...
> 
> Since this got deleted the download of the models is not possible which let the action fail ....

You're sure it was deleted? I didn't delete it.

**Review by lstein — APPROVED** [review]
Thanks. I'll put the HUGGINGFACE token back in.

**Comment by lstein** [comment]
Just checked. There are "Environment Secrets", "Repository Secrets" and "Organization Secrets". There is a valid HUGGINGFACE_TOKEN secret under "Repository Secrets." Is this correct?

**Comment by mauwii** [comment]
> Just checked. There are "Environment Secrets", "Repository Secrets" and "Organization Secrets". There is a valid HUGGINGFACE_TOKEN secret under "Repository Secrets." Is this correct?

Just checked my settings and also have it stored as a Repository Secret, maybe some other security settings protect the secret from being used 🤔

**Comment by lstein** [comment]
By the way,@mauwii, I see how you are having to update the actions each time I make a big change to the structure of the repository (most recently, renaming models.yaml to models.yaml.example). In the future, I will coordinate with you via the discord channel before making such changes. You must find this a bit frustrating!

**Comment by lstein** [comment]
There are multiple messages that you must be a collaborator in order to access the secrets. I've just sent you an invite to become a collaborator with read/write access to the repository. But I'm not sure if this will help, because the actions don't run as your user, do they?

**Comment by mauwii** [comment]
> By the way,@mauwii, I see how you are having to update the actions each time I make a big change to the structure of the repository (most recently, renaming models.yaml to models.yaml.example). In the future, I will coordinate with you via the discord channel before making such changes. You must find this a bit frustrating!

Well, big frustrating is maybe oversized, it's more that I like challanges ;P But of course I would appreciate it ;)

> There are multiple messages that you must be a collaborator in order to access the secrets. I've just sent you an invite to become a collaborator with read/write access to the repository. But I'm not sure if this will help, because the actions don't run as your user, do they?

Well, it would at least stop confirmation of pull requests of people not part of the orga 🤔  Isn't there some setting like "first time contributors must be confirmed" or something like that 🤔

**Comment by mauwii** [comment]
@lstein This is a screenshot of the settings of my fork:

image

Maybe this helps you 🤷🏻‍♂️

**Pull request merged**
