### PR TITLE
feat: serve HTTPS when configured with `ssl_certfile`

### LINKED ISSUE #3970: [bug]: keyfile and certfile config keys are ignored - running over SSL is not possible
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24GB

### What version did you experience this issue on?

3.0.0

### What happened?

I have `invokeai.yaml` configured with the options below for `Web Server`, but the local server does not use **https** when I run `invoke.bat`, it starts up on (insecure) `http://localhost:9090` as instead.

```yaml
InvokeAI:
  Web Server:
    host: 0.0.0.0
    port: 9090
    web: true
    useSSL: true
    certfile: D:\dev\ssl\cert.pem
    keyfile: D:\dev\ssl\key.key
    allow_origins: [ '*' ]
    allow_credentials: true
    allow_methods:
    - '*'
    allow_headers:
    - '*'
 
 ...
```

### Screenshots

_No response_

### Additional context

_No response_

### Contact Details

_No response_

### PR DESCRIPTION
**Pull request by keturn**
## What type of PR is this? (check all applicable)

- Feature

## Have you discussed this change with the InvokeAI team?
- not yet

      
## Have you updated all relevant documentation?
- Yes

## Description

The web server will use HTTPS when given a SSL certificate file, added to the Web section of the configuration file.

## Related Tickets & Documents

- Closes #3970

### CODE REVIEW

**Review by psychedelicious — CHANGES_REQUESTED** [review]
Does what it says on the tin!

I used this command to generate a self-signed certificate on linux:
```sh
# for Common Name, use localhost
openssl req -x509 -sha256 -nodes -newkey rsa:2048 -days 365 -keyout localhost.key -out localhost.crt
```

Then ran the app like this:
```sh
python scripts/invokeai-web.py --ssl_certfile localhost.crt --ssl_keyfile localhost.key
```

I had to tell my browser it's OK that the cert is self signed.

---

Can you please run `make ruff` from the repo root to fix up the formatting? You may need to install the `test` extras to get `ruff` installed.

**Comment by keturn** [comment]
> Can you please run `make ruff` from the repo root to fix up the formatting?

Oh, ruff formatting is different than black formatting? we're not using black anymore? alrighty then, I'll back out that first blackening commit.

**Review by lstein — APPROVED** [review]
Neat!

**Comment by psychedelicious** [comment]
> > Can you please run `make ruff` from the repo root to fix up the formatting?
> 
> Oh, ruff formatting is different than black formatting? we're not using black anymore? alrighty then, I'll back out that first blackening commit.

It's almost exactly the same as ruff, but since we have removed the black config from `pyproject.toml`, I suspect your black run has used the default black config.

**Review by psychedelicious — APPROVED** [review]

**Pull request merged**
