### PR TITLE
Adding automated isort GHA enforcement and pre-commit hooks

### PR DESCRIPTION
**Pull request by lillekemiker**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [x] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [ ] Yes
- [x] No

## Description
This PR does three things:
* Adds a github workflow that checks if all imports are isort compliant
* Adds a pre-commit hook for running isort on all local commits
* Updates all imports to be isort compliant except for cases where code functionality is dependent on import order.

To be clear, it is bad that any code is dependent on import order but it is beyond the scope of this PR to fix that.
Code currently not covered by unit tests could still be affected.

This is the third step suggested in this discussion:

https://github.com/invoke-ai/InvokeAI/discussions/3721

## Related Tickets & Documents

- Related Issue #
- Closes #

## Added/updated tests?

- [ ] Yes
- [x] No : _please replace this line with details on why tests
      have not been included_

## [optional] Are there any post deployment tasks we need to perform?
If any changes are made in open PRs to the files `invokeai/backend/model_management/__init__.py` or `tests/nodes/test_graph_execution_state.py`, ensure that the `isort: split` comments are kept in place in the merged code unless the PR fixes the issue with import order being important.

### CODE REVIEW

**Comment by psychedelicious** [comment]
What setup is needed for the pre commit hooks to run? I don't think they are for me

**Comment by lillekemiker** [comment]
@psychedelicious 
```sh
pip install pre-commit
pre-commit install
```
After this, every `git commit` will be preceded by running the hooks. It can get a little annoying if you are in the habit of committing intermediate stuff before making it compliant. In that case you can add the `--no-verify` option to the `git commit` call if you really want to bypass the checks. If you change the hooks, you just run the `pre-commit install` command again to update. To run all all the hooks without committing, you can run `pre-commit run -a`

**Comment by psychedelicious** [comment]
Suppose we oughta add this to pyproject.toml then? Not sure what the convention is for python.

(With the frontend, the precommit hooks are installed and configured automatically when you install the frontend dev environment. Though this reminds me, they have been disabled since we started the migration... need to turn them back on)

**Comment by lillekemiker** [comment]
I'm honestly not sure what the convention is. So far I have only ever worked on projects with a relatively small number of collaborators and it was sorta left up to the individual to decide whether or not they wanted to use them, since some people might find them annoying. People who didn't use them just ran the risk of having to deal with it once they opened the PR and GHA workflows started complaining. I have never looked into how to, or even if, they can be automatically set up in a dev environment during installation.

**Comment by lillekemiker** [comment]
I added it to the `test` dependencies but people will still have to run `pre-commit install` themselves. A little quick googling suggested that there isn't a good way around that.

**Comment by psychedelicious** [comment]
Unfortunately, it seems we cannot have both `husky` (the frontend pre-commit tool) and `pre-commit` active on the same repo.

`pre-commit install` prompted me to run `git config --unset-all core.hooksPath`, and `git config core.hooksPath` printed `invokeai/frontend/web/.husky`.

After a brief search, it looks like `pre-commit` won't coexist with `husky`, so we'd need to choose one or the other. I'm happy to use `pre-commit` and configure it to run the frontend stuff.

**Review by psychedelicious — APPROVED** [review]

**Comment by lillekemiker** [comment]
Oh that's annoying. Hmm. This stackoverflow link has a few suggestions but I'm not loving any of them
https://stackoverflow.com/questions/64001471/pylint-with-pre-commit-and-esllint-with-husky

The options I can think of:
* Run everything in pre-commit (downside: it doesn't install automatically so people might not use it)
* Run everything in husky (downside: won't work for people without Node.js installed)
* Use pre-commit "migration mode" as per link (downside: seems brittle and husky would have to be installed first or it won't work)
* Call husky from pre-commit hooks when present (downside: not sure but husky might overwrite pre-commit hooks whenever updated)

I think I am in favor of just using `pre-commit` but it depends a bit on how necessary you find the automatic installation part.

**Comment by psychedelicious** [comment]
Running all through `pre-commit` is fine for me. Frontend contributions are less common, and besides - this is just a convenience to reduce the number of commits that end up stuck on a github format check action. No biggie.

**Comment by Millu** [comment]
@lillekemiker what do you think the best path forward is given the merge conflicts?

**Comment by lillekemiker** [comment]
@Millu - I resolved the conflicts

**Review by ebr — APPROVED** [review]

**Review by hipsterusername — APPROVED** [review]

**Review by brandonrising — APPROVED** [review]

**Pull request merged**
