### PR TITLE
Fix docker deployment for ubuntu 23 EOL.

### PR DESCRIPTION
**Pull request by rick-github**
## Summary

Ubuntu 23 has EOL'd and the docker image fails to build.  Updates to Ubuntu 24 LTS and replaces libgl1-mesa-glx which is no longer available.   Also fixes a broken continuation in the Dockerfile, does a sanity check of the passwd file, and sets some environment variables so that caching is done in $INVOKEAI_ROOT.

## Related Issues / Discussions

Closes: #7387

## Checklist

- [ x] _The PR has a short but descriptive title, suitable for a changelog_
- [ ] _Tests added / updated (if applicable)_
- [ ] _Documentation added / updated (if applicable)_
- [ ] _Updated `What's New` copy (if doing a release after this PR)_

### CODE REVIEW

**Comment by ebr** [comment]
Thanks for the contribution @rick-github . I think the best path forward would be to upgrade to ubuntu 24.04. We should be able to get this sorted in the next couple of days.

**Comment by rick-github** [comment]
Sure, feel free to add/modify.

**Comment by rick-github** [comment]
Updated to Ubuntu 24, moved python requirement to 3.13.

**Comment by ebr** [comment]
@rick-github This grew into a bit of a bigger change, and I didn't want to push directly to `main` of your fork. So I opened another PR: https://github.com/invoke-ai/InvokeAI/pull/7401. Your commits are included unchanged, so you're still getting the attribution. Would appreciate you testing it out!
Thanks again for getting this started, it's been long overdue.

**Comment by ebr** [comment]
I'm gong to close this PR as it's superceded by https://github.com/invoke-ai/InvokeAI/pull/7401. Let's continue there.

**Pull request closed without merging**
