### PR TITLE
Inpainting improvements

### PR DESCRIPTION
**Pull request by Kyle0654**
lstein NOTE: This has been merged but is reopened in order to make the conversation more visible.
----

Improve inpainting by color-correcting resulting image to match initial image, then pasting original image over result using a blurred-outward version of the inpainting mask.

## 3 passes of inpaint using old method
 textcompare-image-diff

## 3 passes of inpaint using new method
 textcompare-image-diff (1)

### CODE REVIEW

**Comment by lstein** [comment]
Oh darn. I had just done this and was readying a PR. I'm going to do this anyway so that we can compare. I actually refactored a lot of the img2img and generate code to make it short and clean, and I think a combination of what we've done would probably be good.

**Comment by lstein** [comment]
So what I did in my version is to pass Images to img2img and inpaint rather than Tensors, as was done before. Then the conversion to tensors is done at that level, which makes much more sense. This enables you to get rid of the additional `pil_image` and `pil_mask` arguments. I'm going to do the same thing with your PR, if you don't mind.

**Comment by lstein** [comment]
@Kyle0654 see PR #1 on your branch for a suggested merge of our two PRs

**Comment by Kyle0654** [comment]
> pass Images to img2img and inpaint rather than Tensors

Yes please!

I left a few comments. Only major one is that we should enforce those parameters being Pillow images, since the later `sample_to_image` will fail if they aren't. May also need some small UI refactor.

Also, I'm considering alpha in the input image as separate from the mask image for future outpainting support. The alpha on the initial image would assume to be outpaint regions, whereas the mask would be inpaint (or inpaint+outpaint) regions. That's how my other code works currently at least.

**Comment by Kyle0654** [comment]
Alright I merged your changes in.

**Comment by blessedcoolant** [comment]
@psychedelicious has tested this and said it works well. It's a lot easier to test once it is in dev because we'll be able to use the GUI. Approving this. @lstein can merge if your changes are done too.

**Review by blessedcoolant — APPROVED** [review]

**Review by lstein — APPROVED** [review]
Looks great. Thanks for the work on this.

**Comment by lstein** [comment]
Merged from command line.

**Comment by lstein** [comment]
I've merged the integrated PR into `development`. However, I think the algorithm needs to be tweaked a bit. Here is the Lincoln and Parrot picture with text mask "parrot" and the prompt "man with winged angel on shoulder". Same seed, steps, etc.

Before the inpaint PR:



After the inpaint PR:



There are mask problems in both images, but after the postprocessing fixes, I'm seeing more of the ghostly outline of the parrot.

**Comment by psychedelicious** [comment]
Can you please upload the visualized mask for that test? 

txt2mask masks are often many non-contiguous regions. Maybe that is cause, in which case, the txt2mask threshold may be need tweaking.

**Comment by lstein** [comment]
> Can you please upload the visualized mask for that test?
> 
> txt2mask masks are often many non-contiguous regions. Maybe that is cause, in which case, the txt2mask threshold may be need tweaking.

This one is a manually drawn mask. As soon as I’m back at my desk I’ll upload the mask itself.

**Comment by Kyle0654** [comment]
How tight is the mask for the parrot? The looks almost like when I blur regularly instead of blurring out in my outpainting testing.

**Comment by lstein** [comment]
Here is the image and the transparent mask. Also the derived mask.

Lincoln-and-Parrot-512-transparent
Lincoln-and-Parrot-512
black-and-white-mask

**Comment by lstein** [comment]
> 

Ordinarily I'd think that more steps are needed or a higher strength should be used, but what bothers me is that there is a difference between the original inpainting implementation and the one with the image post-processing.

**Comment by Kyle0654** [comment]
Hrm that's indeed weird. The parrot is fully masked, and it should only be doing any blur outward...

**Comment by Kyle0654** [comment]
Do you mind trying to change line 145 of inpaint.py, changing `dilate` to `erode`? I think I may have used the wrong method and it's blurring inward instead of outward.

**Comment by Kyle0654** [comment]
Yep, that's it:
image
Before on the left, after on the right.

**Comment by Kyle0654** [comment]
Okay I've made the change. I also switched the default model back to 1.4 - I haven't installed 1.5 yet, and nothing would work (since it didn't fall back to 1.4 automatically when 1.5 wasn't found).

**Comment by lstein** [comment]
Thanks for fixing the problem. No problem reverting back to 1.4. I shall put in a fallback mechanism.

**Comment by lstein** [comment]
I was getting various merge and conflict errors, so just committed the fix directly. This is now merged into `development`

**Pull request closed without merging**
