### PR TITLE
[feat] Better status reporting when loading embeds and concepts

### PR DESCRIPTION
**Pull request by lstein**
This PR improves the console reporting of the process of recognizing trigger tokens and loading their embeds.

1. Do not report "concept is not known to HuggingFace" if the trigger term is in fact a local embedding trigger.
2. When a trigger term is first recognized during a session, report the fact.
This should help debug embedding issues in the future.

Note that the local embeddings produced by the new InvokeAI TI training script default to the format <trigger> with literal angle brackets. This sets them off from the rest of the text well and will enable autocomplete at some point in the future. However, this means that they supersede like-named HuggingFace concepts, and may cause problems for people uploading them to the HuggingFace repository (although that problem already exists).

### CODE REVIEW

**Comment by hipsterusername** [comment]
I think we may benefit from some documentation here regarding priority order of local vs HF.

Additionally, I've personally been confused about trigger words to use for .pts manually added to embeddings folder. On init, it seems to refer to file-name as the trigger term - Is that correct?

**Comment by i3oc9i** [comment]
Probably we want to skip `.DS_Store` files when scanning embeds on MacOs in order to avoid to report as warning:

`>> Failed to load embedding located at /Users/ivano/Code/Ai/invokeai/embeddings/.DS_Store. Unsupported file.`

**Comment by lstein** [comment]
> I think we may benefit from some documentation here regarding priority order of local vs HF.
> 
> Additionally, I've personally been confused about trigger words to use for .pts manually added to embeddings folder. On init, it seems to refer to file-name as the trigger term - Is that correct?

Agreed. I'll modify the documentation on HuggingFace concepts as a second PR.

I started using "trigger term" because the official terms "initializer_token" and "placeholder_token" were just too confusing and the online documentation frequently interchanges them. In fact, the trigger term is embedded in the model and has nothing to do with the filename. The HuggingFace concept library embeds enforce that the trigger term has to be surrounded by angle brackets, but embeds trained elsewhere don't necessarily follow that convention. So the .pt files can have any name, and the only way of knowing what trigger terms they contain is to look at the startup messages when a model loads. There is an API call that retrieves all the loaded trigger terms and at some point should be called out into the CLI and Web UIs.

**Comment by lstein** [comment]
> Probably we want to skip `.DS_Store` files when scanning embeds on MacOs in order to avoid to report as warning:
> 
> `>> Failed to load embedding located at /Users/ivano/Code/Ai/invokeai/embeddings/.DS_Store. Unsupported file.`

Thanks for the suggestion. I've just fixed this, but don't have a Mac to test on. Could you see if my change quenched the warnings?

**Comment by i3oc9i** [comment]
@lstein 

> Thanks for the suggestion. I've just fixed this, but don't have a Mac to test on. Could you see if my change quenched the warnings?

Yes it works, thank you !!

**Review by hipsterusername — APPROVED** [review]

**Comment by ShaguarWKL** [comment]
> produced by the new InvokeAI TI training script default to the format with literal angle brackets. This sets them off from the rest of the text well and will enable autocomplete at some point in the future. However, this means that they supersede like-named HuggingFace concepts, and may cause problems for people uploading them to the HuggingFace repository (although that problem already exists).

It's not just .DS_Store. I think ignoring all non .pt files would be the way to go and error spits out only if unable to read a .pt file.

WindowsTerminal_2023-02-08_10-41-12

**Comment by ShaguarWKL** [comment]
> I think we may benefit from some documentation here regarding priority order of local vs HF.
> 
> Additionally, I've personally been confused about trigger words to use for .pts manually added to embeddings folder. On init, it seems to refer to file-name as the trigger term - Is that correct?

Seems like Invoke appends the steps to the trigger. I am assuming this is probably due to some trained with proper datasets and some just with images without enough metadata or just a trigger word.

So in the screenshot, all the AmandaComaPT are filenames with AmandaComaPT as trigger word as well. testTurner is CharTurnerV2. olfn is Old-Fashioned that has -6250 appened to it.

WindowsTerminal_2023-02-08_10-48-20
 for some.

**Pull request merged**
