### PR TITLE
refactor: remove configure script

### LINKED ISSUE #5988: [bug]: can't disable the nsfw filter
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 3090

### GPU VRAM

24

### Version number

4.0.0-rc2

### Browser

Firefox 123.0.1

### Python dependencies

_No response_

### What happened

the invokeai docs state that to disable the nsfw filter you pass the parameter `--no-nsfw_filter`, however this doesn't work:

```yaml
command: ["invokeai-web", "--host", "0.0.0.0", "--no-nsfw_checker"]
```

```text
[2024-03-19 09:56:32,072]::[InvokeAI]::INFO --> NSFW checker initialized
```

When running interactively it seems this flag is not recognised:

```
invokeai-web --no-nsfw_checker
Unknown args: ['--no-nsfw_checker']
```

### What you expected to happen

- The NSFW checker not to be loaded (this is desired to improve performance)
- A config parameter in invokeai.yaml that can be set to disable it so that the container entrypoint command doesn't have to be overridden.

### How to reproduce the problem

- Launch invokeai via docker/docker-compose.
- Set the command to include the --no-nsfw_checker
- Check the logs after starting the container and load the app

### Additional context

[docs](https://invoke-ai.github.io/InvokeAI/installation/010_INSTALL_AUTOMATED/#out-of-memory-issues)

image

### Discord username

protoporpoise

### PR DESCRIPTION
**Pull request by psychedelicious**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Feature
- [x] Bug Fix
      
## Have you updated all relevant documentation?
- [x] Yes
- [ ] No

## Description

This PR moves all application initialization logic out of external scripts (like the configure and model install scripts) and into the app.

- The app initializes its directories as needed, and writes a default config file if one doesn't exist
- Remaining core models (upscaling, lama, nsfw) are downloaded when they are first requested
- If the user has no main models installed on startup, a tooltip directs them to the model manager tab @maryhipp this has a feature flag
- New starter models tab in model manager
- Add `--config` CLI arg, allows users to specify any config file
- Massive cleanup of unused scripts and code

## Related Tickets & Documents

- Closes #5988 (NSFW checker is never loaded unless it is requested in a node)

## QA Instructions, Screenshots, Recordings

Test from a fresh install and from a v3.7.0 runtime dir.

## Merge Plan

This PR can be merged when approved

## Added/updated tests?

- [x] Yes
- [ ] No : _please replace this line with details on why tests
      have not been included_

### CODE REVIEW

**Comment by hipsterusername** [comment]
How are users guided to configure settings like VRAM/RAM cache, etc? Do we feel like these defaults are going to be set correctly for folks?

**Review by maryhipp — APPROVED** [review]
UI changes look good

**Comment by psychedelicious** [comment]
Defaults are the same as they were before. 

There's a link in the config file to the docs, which describes every setting

And example file with all default values is written alongside the config

And I'll be adding our config json schema to the schema store. This gives editors like vscode autocomplete, error hilighting and tooltip help for each setting. 

I think that's more help than users get currently

**Review by brandonrising — APPROVED** [review]

**Comment by lstein** [comment]
The process of updating from current `main` to this PR was not as clean as one might wish. After building the frontend and running pip --upgrade, I ran `invokeai-web`. First result:

```
...
  File "/home/lstein/Projects/InvokeAI/invokeai/app/services/config/config_default.py", line 460, in get_config
    incoming_config = load_and_migrate_config(config.config_file_path)
  File "/home/lstein/Projects/InvokeAI/invokeai/app/services/config/config_default.py", line 412, in load_and_migrate_config
    raise RuntimeError(f"Failed to load config file {config_path}: {e}") from e
RuntimeError: Failed to load config file /home/lstein/invokeai-main/invokeai.yaml: 1 validation error for InvokeAIAppConfig
schema_version
  Input should be a valid string [type=string_type, input_value=4, input_type=int]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
```

So I removed `invokeai.yaml`, relaunched, and got:
```
  File "/home/lstein/Projects/InvokeAI/invokeai/app/services/config/config_default.py", line 450, in get_config
    example_config.write_file(config.config_file_path.with_suffix(".example.yaml"), as_example=True)
  File "/home/lstein/Projects/InvokeAI/invokeai/app/services/config/config_default.py", line 234, in write_file
    with open(dest_path, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/lstein/invokeai/invokeai.example.yaml'
```

Then I realized that the root finding mechanism has changed. I store my `.venv` in a directory named `~/invokeai-main`, not `~/invokeai`. Previous versions used the path in the environment variable `$VIRTUAL_ENV` as a fallback in the event that neither `--root` nor `INVOKEAI_ROOT` were defined. This apparently no longer works. Is this change intentional?

Running `invokeai-web --root <correct path>` got me up and running. So I went to check out the new starter model page to check it out. It looks great! 

However when I tried to add `SD 1.5 (base)` by pressing the "+" button, I got the progress bar and ultimately a "completed" message. But the new model didn't appear on the Model Manager list, and syncing models a few times had no effect. Also the `SD 1.5 (base)` item in the Starter Models panel didn't change to indicate that the model was installed. I had expected the "+" to turn into a "-", the entry to highlight or disappear, or some other user interface to indicate the model was installed.

Trying to reinstall `SD 1.5 (base)` gave me a duplicate model exception, so it's being installed on the backend. Restarting the server fixed the problem. The model now shows up on the model manager list.

Repeating this with Dungeons and Diffusion, which I have never previously installed, and had the same experience.

Another anomaly: pressing the trash can icon next to any model deletes it from the backend, but doesn't update the front end. I have to reload the web page.

Model dependency installation is working after a fashion. When I deleted and reinstalled "IP Adapter Plus Face" it did try to install the corresponding image encoder. Unfortunately the install progress bar reported a "fail" after the download completed, presumably because deleting the IP Adapter does not delete the encoder (and shouldn't, since they are shared), and we got a duplicate model error on the backend. This could be fixed by checking that the dependency is already installed, and if so not trying to install it again. Presumably this will work as expected on a virgin system.

This being said, it is great to get rid of the old configure script. It was the first bit of python code I ever wrote, and I am delighted that I will never have to wrestle with `npyscreen` again. 

Great job!

**Review by lstein — COMMENTED** [review]
There are minor cosmetic issues with the starter models panel that are noted in my other comment.

**Comment by psychedelicious** [comment]
> The process of updating from current main to this PR was not as clean as one might wish. After building the frontend and running pip --upgrade, I ran invokeai-web. First result: <schema_version error>

This is expected - I needed to change the schema version from an int to a string to align the config version w/ app version.

> So I removed invokeai.yaml, relaunched, and got: <error writing file>

I've fixed the issue with writing the file (need to create the parent dir first). I cannot replicate the issue with the root dir not being respected, maybe was an interaction with the first issue?

> <model list not updating>

This was mostly fixed in a separate PR, and this config PR has been update to include the fix. Needed to make one more change to get the starter models list to refresh, thanks for pointing this out.

> Model dependency installation is working after a fashion

Yep, good catch! I've updated it to not attempt to re-install dependencies.

Note that the dependencies are derived using the model source. I couldn't think of a better way to handle this - as we know, "name" isn't reliable.

**Comment by psychedelicious** [comment]
I moved HF token setup to the web UI. There is no prompt in the terminal now. If there is no token (or an invalid token), the UI shows a toast and direct the user to update it:

https://github.com/invoke-ai/InvokeAI/assets/4822129/f0ae64f8-3afe-4218-951e-13057b30c169

Below the entry field is a link to https://huggingface.co/settings/tokens.

**Review by lstein — APPROVED** [review]
LGTM

**Pull request merged**
