### PR TITLE
fix(ui): hide refiner collapse if refiner not installed

### PR DESCRIPTION
**Pull request by psychedelicious**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [x] Yes
- [ ] No, because:

## Description

fix(ui): hide refiner collapse if refiner not installed

### CODE REVIEW

**Comment by blessedcoolant** [comment]
Would it not be better to leave it disabled rather than hidden? Because that would indicate to the user that they need to install the model. Otherwise it'll just seem like a missing feature.

**Comment by psychedelicious** [comment]
@blessedcoolant was a request from @hipsterusername but ya maybe we want the collapsible panel to have a disabled state instead? 

(Currently if you have no refiner models, you can expand the panel but its all disabled)

**Comment by blessedcoolant** [comment]
> (Currently if you have no refiner models, you can expand the panel but its all disabled)

Yep. And this lets the user know that the feature is available but disabled coz no models are installed. If we move it entirely, then there's no feedback for the user that this is an issue of missing models rather than the refiner feature not existing at all.

**Comment by hipsterusername** [comment]
Having a dead options panel in the middle of the UI is a pretty bad UX. Think there have to be better answers than leaving it entirely. Disabled, at the bottom, with the text “no refiner models” in grey?

**Comment by psychedelicious** [comment]
Ok, how about this:
image

It's the same as the current behaviour when you have no LoRAs installed.

**Review by blessedcoolant — APPROVED** [review]

**Pull request merged**
