### PR TITLE
add board dropdown to use instead of current board

### PR DESCRIPTION
**Pull request by maryhipp**
only works for txt2img and img2img right now

### CODE REVIEW

**Comment by maryhipp** [comment]
@psychedelicious wdyt?

**Comment by psychedelicious** [comment]
@maryhipp Sorry, I had written this but never clicked the button.

This takes up quite a bit of space in the rather cramped parameters panel, but I'm not sure where else to put it. I'm just pretty sure this is not the right place...

**Comment by maryhipp** [comment]
maybe a small icon dropdown next to invoke button like we have for cancel? green with an icon that is suggestive of boards?

**Comment by maryhipp** [comment]
Screenshot 2023-07-14 at 8 31 45 AM
Screenshot 2023-07-14 at 8 31 09 AM

**Comment by blessedcoolant** [comment]
> Screenshot 2023-07-14 at 8 31 45 AM Screenshot 2023-07-14 at 8 31 09 AM

I like this

**Comment by psychedelicious** [comment]
@maryhipp yep that looks good, but not bright green. `colorScheme: 'base'` is probably appropriate

**Comment by psychedelicious** [comment]
Hmm, the list of boards could be really long. This should probably be a bit more sophisticated, I'd like to hold off on this change until we have a good UX - would probably involve `IAIMantineSearchableSelect`.

**Pull request closed without merging**
