### PR TITLE
reintroduce fix for m1 from https://github.com/invoke-ai/InvokeAI/pull/579 missing after merge

### PR DESCRIPTION
**Pull request by skurovec**
Make results reproducible (so runs with the same seed produce the same result). Implements fix by @wbowling referenced in https://github.com/invoke-ai/InvokeAI/issues/397#issuecomment-1240679294

### CODE REVIEW

**Review by Any-Winter-4079 — APPROVED** [review]
LGTM

**Comment by Any-Winter-4079** [comment]
@skurovec dev branch probably needs the same fix too

**Comment by skurovec** [comment]
@Any-Winter-4079 how to do that, another PR? Or is there way to use this also to development?

**Comment by Any-Winter-4079** [comment]
I'd just do another PR but to development branch this time.

**Pull request merged**
