### PR TITLE
Fix for crashes in txt2img hires fix mode

### PR DESCRIPTION
**Pull request by ArDiouscuros**

### CODE REVIEW

**Review by blessedcoolant — APPROVED** [review]

**Comment by blessedcoolant** [comment]
Tested quite a bit. Seems to have no crashes so far.

However I do note that your script still defaults to DDIM for the img2img part. Maybe you could update it to use the KSamplers as they are now supported.

**Review by lstein — APPROVED** [review]
Thanks for finding and fixing these problems. That required quite a bit of detective work.

**Comment by lstein** [comment]
I'll remove the restriction on other samplers.

**Comment by blessedcoolant** [comment]
@lstein Please also make the same updates to dev. Thanks.

**Comment by lstein** [comment]
I did, along with txtimg2img fix.

**Pull request merged**
