### PR TITLE
Multi-image latent melding

### PR DESCRIPTION
**Pull request by Philip-K**
This adds a feature to pass a text file containing a list of init images (using parameters --init_img_set or -J).  These images are then translated into latent space and then averaged.  Additionally, the standard deviation of the latent elements is used to weight the added seed noise to attempt to preserve common semantic features.  This is done using parameter --set_quantile or -Q, where latent values with 0 standard deviation receiving 0 seed noise, linearly ramped to the value at quantile Q, with latent values at or above that value receiving the normal seed noise amount.
That method was arrived at experimentally with some educated guesswork and trial and error.  I've really only tested it against a simple test case but it seems to be doing what I want.
For that test case, I started with a crappy drawing and prompt:
`"an alien planet in space. starry background. extremely detailed. octane render." -s100 -IF:\SD\stable-diffusion\inputs\test_in.png -f0.8 -n50`
test_in
And I get out some images:
Initial_Set
Lets say I like the stripy atmosphere and want more in that direction.  I could use the existing tools and pick one image to pass back trough.  For example using image 2781870806:
`"an alien planet in space. starry background. extremely detailed. octane render." -s40 -IF:\SD\stable-diffusion\outputs\img-samples\000001.2781870806.png -f0.5 -n20`
I_f0 5
I get some variations but its a lot of the same.  I could increase -f to 0.7 and get this:
I_f0 7
Better, but still pretty similar and its starting to lose the stripes on some of them.  Now with this PR, I can create a text file targeting three options:
```
F:\SD\stable-diffusion\outputs\img-samples\000001.2205133845.png
F:\SD\stable-diffusion\outputs\img-samples\000001.2705058584.png
F:\SD\stable-diffusion\outputs\img-samples\000001.2781870806.png
```
And pass that in with this:
`"an alien planet in space. starry background. extremely detailed. octane render." -s40 -JF:\SD\stable-diffusion\inputs\stripes.txt -f0.5 -Q0.1 -n20`
J_Q0 1
It doesn't perfectly preserve the stripes but there is a lot more diversity.  I can also play with -Q to try to get more variety in exchange for preserving the stripes less, with Q=0 being equivalent to just averaging the latent values and not adjusting the seed noise weight.
Q=0.05:
J_Q0 05
Q=0
J_Q0
And lastly, to show that it is picking up on the strips and that it isn't just a consequence of running an image through twice, I can try an image set with no stripes:
```
F:\SD\stable-diffusion\outputs\img-samples\000001.76905574.png
F:\SD\stable-diffusion\outputs\img-samples\000001.109090291.png
F:\SD\stable-diffusion\outputs\img-samples\000001.991658416.png
```
`"an alien planet in space. starry background. extremely detailed. octane render." -s40 -JF:\SD\stable-diffusion\inputs\no_stripes.txt -f0.5 -Q0.1`
J_NS

### CODE REVIEW

**Comment by bmaltais** [comment]
Interesting PR. I will need to spend some quality time playing with this. Thanks.

**Comment by Philip-K** [comment]
You may want to play with some different -f and -Q values, or so I'm finding out.  I just did:
`"film still of a very fat batman. fullbody photo" -s50 -C10.0`
start
And used this subset to try to extract photo realistic, forward facing, and full body as in boots to head and not cut off at the shins:
```
F:\SD\stable-diffusion\inputs\batman\000028.215025828.png
F:\SD\stable-diffusion\inputs\batman\000029.663199382.png
F:\SD\stable-diffusion\inputs\batman\000029.721316611.png
F:\SD\stable-diffusion\inputs\batman\000029.1970728595.png
F:\SD\stable-diffusion\inputs\batman\000029.2648616081.png
F:\SD\stable-diffusion\inputs\batman\000029.3437957224.png
F:\SD\stable-diffusion\inputs\batman\000029.3401610362.png
```
The first few attempts were pretty bad:
-f0.6 -Q0.15:

-f0.5 -Q0.1 (also note the speckle pattern on this one.  Seems to be a thing if f is too low and Q is too high for the similarity of the image):

And then finally found what I was going for with -f0.7 -Q0.05:
set

**Comment by bmaltais** [comment]
I ran another experiment, this time using SD created images vs internet ones as a source from the following prompt:

`chris farley as the joker, gritty and dark, purple suit, vibrant and colorful -n8 -s640 -s30`

Picked the 4 best ones where he was facing forward and ran it again with:

`chris farley as the joker, gritty and dark, purple suit, vibrant and colorful -n8 -s640 -s100 -Joutputs/t/t.txt -f0.7 -Q0.05`

It kind of did better but the resulting colors a much more muted.

Example image from 1st generation:



Ans one of the resulting output:



So it does tend to create more blurry/desaturated results.

**Comment by Philip-K** [comment]
I'm not sure I'm seeing the blurriness, at least in the ones you posted, but I agree that it is a bit desaturated.  I'm now looking back at my batman one, and except for the yellow in the belt and logo, it is quite desaturated.  I don't know the details of this model, nor am I an ML pro.  So my guess is as good as yours on why that may be happening.  Maybe there is a better way to blend the latent values or weigh them?  I'll need to play around and try some things.

**Comment by morganavr** [comment]
It's an interesting feature. Thanks for sharing it @Philip-K 
With it I got results that would not be possible without it, particularly it can generate people without background (only solid color background) with these settings:  `-s100 -C12 -n 50 -J C:/SD/inputs/stripes.txt -f 0.75 -Q 0.65`
stripes.txt contains 5 example images of a person close up photo.

**Comment by tildebyte** [comment]
Interesting stuff, but the implementation details are way over my head 😀

I added lstein, bakkot, and blessedcoolant as reviewers.

**Comment by Philip-K** [comment]
@bmaltais Just made a change to the init_latent to now be `torch.normal(init_latent_set.mean, 0.5 * init_latet_set.std())`.  This seems to reduce the color desaturation some.  The background is still a bit muted, but it looks like it has more texture and I think the character has better color.

The 0.5 is a bit arbitrary, but at 1 I was getting a weird confetti artifact some of the time.

Unfortunately I think this will break @morganavr use case.  It might make sense to add a setting to switch the function but I don't want to over-complicate it for the user.

**Comment by bakkot** [comment]
When I tried averaging latents previously and then viewing the results, it was basically just overlaying the images. Have you tried rendering the images you get from this process directly? Is it meaningfully different than just overlaying the images?

**Comment by bmaltais** [comment]
@Philip-K The one with Q1 appear to stick with the original color saturation but, as you said, has tons of artifacts . I will test the modified version. I appreciate your work as it is pushing the possibilities of the solution. Maybe a solution to the saturation will be devised by someone with more knowledge of torch . I wish I knew more about the whole process to be able to help better.

**Comment by bmaltais** [comment]
OK, I have done more research and I think why this approach if not going to be successful. It is an interesting one but it will not work as expected. 1st, let set the stage. I created a bunch of images using this prompt: `"full shot superheroine, muscular physique, gorgeous face, analogous color, hyperrealistic, highly detailed, digital painting artstation HQ concept art smooth, sharp focus, illustration, art by artgerm and greg rutkowski" -s30 -W512 -H768 -C7.5 -Ak_euler -n16`

I picked 7 images from the lot that looked good. Here is the photoshop stack merge median from them:

median

Notice how this create a dull rendition. My understanding is that this is what is happening when you average all the images in the latent space and explain why the output always tend to look washed out... because averaging a bunch of images will always tend toward neutral grey.

So running this prompt: `"full shot superheroine, muscular physique, gorgeous face, analogous color, hyperrealistic, highly detailed, digital painting artstation HQ concept art smooth, sharp focus, illustration, art by artgerm and greg rutkowski" -s60 -W512 -H768 -C7.5 -Ak_euler -Ioutputs/t/median.png -f0.5 -S77777` gave me this result:



and if I run the prompt with your PR: `"full shot superheroine, muscular physique, gorgeous face, analogous color, hyperrealistic, highly detailed, digital painting artstation HQ concept art smooth, sharp focus, illustration, art by artgerm and greg rutkowski" -s60 -W512 -H768 -C7.5 -Ak_euler -Joutputs/t/t.txt -f0.5 Q0.01 -S77777



You can clearly see similarities... So I think this is sort of explaining why this will not give satisfactory as it stand.

**Comment by Philip-K** [comment]
@bmaltais thanks for the info. I think that pretty clearly shows where the color muting is coming from. As it stands there is definitely work that needs to be done, but I think we now have some good verification test cases. I'm not yet convinced that there isn't a path forward here, and have some ideas to try, but unfortunately won't be able to try them out until Tues at the earliest.

**Comment by lstein** [comment]
This is a fascinating idea and I very much appreciate all the work that @Philip-K put into this and the testing that @bmaltais has done. 

For now I'm going to hold off on my review until @Philip-K gives the thumbs up that the desaturation issues have been addressed and @bmaltais has had a chance to kick the tires again.

**Comment by bmaltais** [comment]
Now that the variance feature was implemented I think this would limit the dissimilarities between images and might help keep the saturation up and overall result... will need to see if this PR will still merge in main as is... more testing.

**Review by bmaltais — CHANGES_REQUESTED** [review]
This merge did not make it work. Need more fixing.

**Comment by bmaltais** [comment]
OK, I have made the melding PR work again in the new 1.13 code base... but it still create similar washed out as before... as expected. While I was testing this... it got me thinking... since those images we select should come from other SD produced images... we know the seed for each of them... so what if instead of loading the actual images in the latent space we loaded an average of all the noise of the selected seed as the starting noise for the new images. It should, in theory, have a similar effect on the over all features of the images... without the washed out effect...

Just a tought.

**Comment by bakkot** [comment]
@bmaltais Yeah, that works well (usually). If you know the seeds you used, and the other settings are the same, you can use the new [variations](https://github.com/lstein/stable-diffusion/blob/main/VARIATIONS.md) feature to do that: say your two images were made with seeds `123` and `456`. Then generating using `-S 123 -V 456:0.5` will use a latent halfway between those two seeds, and that will _usually_ (but not always) give you an image which is in some sense "between" the two images you started with.

**Comment by bmaltais** [comment]
Bu what if you don't want to start form the same seed... say you have generated a bunch of batched from the same prompt... the current variation implementation does not allow to mix different starting seed images. I hacked the code to force it to use only the seeds from the selected images and average it using the associated weight. It does appear to work quite well...

So perhaps this is how the melding PR could improve things... by leveraging a config files that would include all the seed valued and weight for each and not require an actual seed image... since at the end we just want to retain noise characteristic from the selected images... and add just a tad bit of noide to get variations based on those.

**Comment by bakkot** [comment]
> Bu what if you don't want to start form the same seed... say you have generated a bunch of batched from the same prompt... the current variation implementation does not allow to mix different starting seed images.

The current variations feature _does_ allow you to mix different starting seeds. That's what the `-V` syntax does, as in the example I gave.

**Comment by bmaltais** [comment]
> 

Well... I mean... it insist on a -S<value> to use as the starting seed on top of which the variations are applied...

**Comment by bmaltais** [comment]
Here is an example of what I mean. Given the following 3 images with known seeds for the prompt:

`"full shot superheroine, muscular physique, gorgeous face, analogous color, hyperrealistic, highly detailed, digital painting artstation HQ concept art smooth, sharp focus, illustration, art by artgerm and greg rutkowski"`





I can force the variation feature to return me only the 1st image with:

`"full shot superheroine, muscular physique, gorgeous face, analogous color, hyperrealistic, highly detailed, digital painting artstation HQ concept art smooth, sharp focus, illustration, art by artgerm and greg rutkowski" -s30 -W512 -H768 -C7.5 -Ak_euler -V399316793:1,404318740:0 -S2857788652`

I can get an average of the 3 with:

`"full shot superheroine, muscular physique, gorgeous face, analogous color, hyperrealistic, highly detailed, digital painting artstation HQ concept art smooth, sharp focus, illustration, art by artgerm and greg rutkowski" -s30 -W512 -H768 -C7.5 -Ak_euler -V399316793:0.3333,404318740:0.3333 -S2857788652`



Or I can get the 2nd one with:

`"full shot superheroine, muscular physique, gorgeous face, analogous color, hyperrealistic, highly detailed, digital painting artstation HQ concept art smooth, sharp focus, illustration, art by artgerm and greg rutkowski" -s30 -W512 -H768 -C7.5 -Ak_euler -V399316793:0,404318740:1 -S2857788652`

**Comment by bakkot** [comment]
Yes, so, how it works is that the `-S` is the first seed, and the weights on `-V` are basically how far to move in the direction of that seed, from where you are currently. So `-S 123 -V 456:0.5` will start at the seed 123 and then move halfway to 456. And yes, setting `:1` will move all the way to the second point.

Doing this move-then-move process isn't _quite_ the same as taking an actual [average of multiple points in spherical coordinates](https://mathweb.ucsd.edu/~sbuss/ResearchWeb/spheremean/paper.pdf) when you have more than 2 seeds, but it works ok for our purposes, I think (and I don't really want to implement that algorithm).

**Comment by lstein** [comment]
Hi all. This PR has been in draft form for 25 days and I don't see any activity on it. I'm going to close it for now. Please feel free to update and reopen. `development` has moved on quite a ways since the last update, so there will be a little bit of work to avoid conflicts. I'm sorry for how this has worked out.

**Pull request closed without merging**
