### PR TITLE
Support runwayML custom inpainting model

### PR DESCRIPTION
**Pull request by lstein**
# Inpaint using the runwayML custom inpainting model

This is still a work in progress but seems functional. It supports inpainting, txt2img and img2img on the ddim, plms and k* samplers.

## Installation

To test this, get the file `sd-v1-5-inpainting.ckpt` from https://huggingface.co/runwayml/stable-diffusion-inpainting and place it at `models/ldm/stable-diffusion-v1/sd-v1-5-inpainting.ckpt`

## Usage

Launch invoke.py with `--model inpainting-1.5` and proceed as usual. All the usual arguments and settings should work (but haven't been systematically tested)

## Caveats
1. The inpainting model takes about 800 Mb more memory than the standard 1.5 model. This model will not work on 4 GB cards.
2. I think performance is a bit slower as well, but have not benchmarked.
3. The inpainting model is temperamental. It wants you to describe the entire scene and not just the masked area to replace. So if you want to replace the parrot on a man's shoulder with a crow, the prompt "crow" may fail. Try "man with a crow on shoulder" instead. The symptom of a failed inpainting is that the area will be erased and replaced with background.
4. When using img2img mode, the inpainting model **really** does not like to change the image much compared to standard 1.4 or 1.5. High configuration guidance scales, strengths and step counts are needed. This seems like a feature of the model, but I can't be sure.

### CODE REVIEW

**Comment by Any-Winter-4079** [comment]
I'll test after class. Thanks!

**Comment by Any-Winter-4079** [comment]
There's a lot to test, but starting with basic `txt2img`.
The 1.5 inpainting model seems to be able to generate coherent images with `txt2img`. Nice! The output is different, but it's a different model with more training steps done (so it's somewhat expected).
### Inpainting 1.5
`"an anime girl" -s 50 -S 3031912972 -W 512 -H 512 -C 7.5 --fnformat {prefix}.{seed}.png -A plms`
Screenshot 2022-10-25 at 19 50 06

### 1.4
Now, for regular 1.4, I see images have changed.
`!switch stable-diffusion-1.4`
`"an anime girl" -s 50 -S 3031912972 -W 512 -H 512 -C 7.5 --fnformat {prefix}.{seed}.png -A plms`
image

DDIM
`"an anime girl" -s 50 -S 3031912972 -W 512 -H 512 -C 7.5 --fnformat {prefix}.{seed}.png -A ddim`
image

**Comment by lstein** [comment]
@Any-Winter-4079 The changes that you are seeing in the 1.4 model might actually be due to an unrelated PR I worked on a couple of days ago and merged last night (I'll have to look it up). Appallingly enough, it turned out that when you surround the prompt with quotation marks ("), the quotes were being passed to the generation engine. So "an anime girl" and __an anime girl__ without the quotes, could give different results!

You might want to try the comparison without quotation marks in the prompts.

**Comment by lstein** [comment]
This model is very intriguing. Even in straight `img2img` mode it is great at making targeted changes. For exampe, I can change the pattern of a subject's clothing from leopard to zebra print without changing her their, posture, or background. On the other hand, I can't make big changes, such as changing their posture or the overall style of the image, even with high step and CFG.

Outpainting, which I tested with the `outcrop` restoration module, works quite well with this model. Better than 1.4 by far.

**Comment by Any-Winter-4079** [comment]
It seems to produce the same result with an without "" for me.

**Comment by lstein** [comment]
So you're seeing differences using the 1.4 model between the PR and the pre-PR code base? I'll check it out on my own end. There were a bunch of fiddly changes, but hope I didn't inadvertently change the noise generation part of the code, which would most likely cause this.

**Comment by Any-Winter-4079** [comment]
> So you're seeing differences using the 1.4 model between the PR and the pre-PR code base?

Yes, but I pulled other changes (not just this PR).
You can check using `mps_noise`, so you can recreate my own image.
Old images on Mac: https://github.com/invoke-ai/InvokeAI/blob/development/docs/help/SAMPLER_CONVERGENCE.md

**Comment by Any-Winter-4079** [comment]
About 1.5-inpainting:
`txt2img` seems to work. From the limited experiments I've done, I'd say regular 1.5 is better (also, keeps relation with 1.4)
image

**Comment by lstein** [comment]
There are so many variations of parameters that it has hard to do an apples-to-apples comparison. 

One conclusion that I've reached is that the strength option (`-f`) only makes things worse for the inpainting model. I am thinking of ignoring its value and using 1.0. I think it made sense to have this in the non-inpainting model because that model is blindly drawing on top of an image encoded in latent space and strength controls how much modification is allowed. In the inpainting model the model "understands" that it is replacing part of the image.

**Comment by Any-Winter-4079** [comment]
> There are so many variations of parameters that it has hard to do an apples-to-apples comparison.

The above results are using the same parameters, including seeds and source images and masks. Everything is the same except for the model.

I'll try the strength part and also keep the testing.

**Comment by Any-Winter-4079** [comment]
Oh, by the way. When using `inpaint_st.py`, the other day I could load a Dreambooth .ckpt as main model (in my case, to define the style) and use 1.5 inpainting on top. So it's like using 2 models at the same same time.

I'm not sure how to do this now that 1.5 inpainting is the main model.

**Comment by Any-Winter-4079** [comment]
Using mask:
`"miranda kerr with blonde hair" -W512 -H512 -C7.5 -S3031912972 -I mirkerr.png -M mirkerr_mask.png`
Screenshot 2022-10-26 at 12 36 22
vs. yesterday
Screenshot 2022-10-26 at 12 39 22

Using clipseg:
Screenshot 2022-10-26 at 12 39 52
vs. yesterday
Screenshot 2022-10-26 at 12 40 40

**Comment by lstein** [comment]
This PR will break both `--hires` and `--embiggen`, as they reimplement some low-level image generation steps that don't work with the new model. If you try to use these switches they will be ignored.

I will fix these before marking the PR as ready for merging.

**Comment by lstein** [comment]
No much of a difference between yesterday and today. 

What happens to your test image when you raise -C modestly to anything between 10.0 and 15.0?

**Comment by Any-Winter-4079** [comment]
-C 7.5
Screenshot 2022-10-26 at 12 36 22
-C 15
Screenshot 2022-10-26 at 13 06 36

**Comment by Any-Winter-4079** [comment]
I see barely any change between yesterday and today (left side of image, hair is a bit different, but that's about it)
image
For the Miranda Kerr example, I prefer yesterday's (it abides more by the original image in hair length, etc.) but it's hard to draw meaningful conclusions. I'll best a bit more.

**Comment by Any-Winter-4079** [comment]
With the latest version, single word prompts do work.
`"macaw" -s 50 -S 3096140878 -W 512 -H 512 -C 7.5 --fnformat {prefix}.{seed}.png -I 197632255-563dc05b-58cf-498b-88c2-8e2ae274b2a4.png -A k_lms -M 197632285-8d7f0f15-0c2d-4adb-8bb5-b9e4914a1de3.png -f 0.1`
Screenshot 2022-10-26 at 13 18 26

**Comment by Any-Winter-4079** [comment]
I'm doing a small experiment with 20 images and yesterday's vs. today's code version, using single-word prompts.

> This PR will break both --hires and --embiggen, as they reimplement some low-level image generation steps that don't work with the new model. If you try to use these switches they will be ignored.

About this, I've never even set up embiggen so I couldn't tell. This might be a good excuse to do so.

**Pull request merged**
