### PR TITLE
fix clipseg loading problems

### PR DESCRIPTION
**Pull request by lstein**
The directory "models" in the main InvokeAI directory was conflicting with loading "models.clipseg". To fix this issue, I have renamed the models.clipseg to clipseg_models.clipseg, and applied this change to the 'models-rename' branch of invoke-ai's fork of clipseg.

After pulling this PR, please delete `src/clipseg` and rerun `conda env update`

UPDATE: I have also folded in the !mask command to visualize the regions found by `clipseg`. See docs/features/INPAINTING.md for the details.

### CODE REVIEW

**Comment by lstein** [comment]
This ought to fix #1150

**Comment by psychedelicious** [comment]
Followed instructions to re-do the clipseg installation, it works. I did need to run `preload_models.py` again.

Also, there were issues with the `preload_models.py` script. I have sorted those out. I've gotta get off the computer, so I have just made a PR to `clipseg-fix`: https://github.com/invoke-ai/InvokeAI/pull/1179

**Review by psychedelicious — APPROVED** [review]
- Tested out the `!mask` command - works great. The threshold does what it should as well. 
- Feature also works as expected when used with img2img
- I deleted my `src/clipseg/weights` dir and re-ran `preload_models.py`, it re-loaded the models successfully

Awesome feature!

**Comment by lstein** [comment]
I'm going to take this as a "yes" and force merge.

**Pull request merged**
