### PR TITLE
update dockerfile

### PR DESCRIPTION
**Pull request by mauwii**
- Using the new scripts/configure_invokeai.py to create the necesarry files on the volume (models, configs, ...).
- Works on x86, aarch64 and arm64
- uses pip instead of conda
- sized down to 3GB (but will try to use alpine instead of ubuntu to get another 90% less size)

### CODE REVIEW

**Comment by mauwii** [comment]
need to dig a bit deeper with alpine, still think it's possible but after almost 2h playing around with it I think it's fine to just merge the ubuntu container for now 🙈

**Comment by ebr** [comment]
@mauwii I don't think Alpine will work due to musl/libc incompatibilities. Ubuntu is more common/compatible anyway.

Also, I realize there may have been some inspiration by the work I've done on the Docker setup that we've discussed over the past week: https://github.com/invoke-ai/InvokeAI/pull/1544, but perhaps we could join forces on improving this Dockerfile together? I specifically didn't want to modify your Dockerfile so that you could review my PRs first. My version has some significant optimizations and results in a smaller image that's only 4 layers, and I think it would be beneficial to the project.

**Comment by mauwii** [comment]
I think it still will make sence to have a cloud optimized Dockerfile (like yours), and one that will also work on ARM64/aarch64, so that those people who have reasons for this usecase don't get locked out, and vice versa people who want to run it on cloud hardware don't have to suffer from unoptimized images ;)

And no, I started this already before your PR came in, so no inspiration from there at all 🙈

**Comment by damian0815** [comment]
what's the relationship between this and the one by @ebr ? seems odd to have two of them.. and how would you like me to review it?

**Comment by mauwii** [comment]
> what's the relationship between this and the one by @ebr ? seems odd to have two of them.. 
ebr`s Dockerfile is cloud optimized while this one is not, but therefore is able to run on developer machines unecesarry of the arch/os neither requires nvidia gpu.

> and how would you like me to review it? should i try and put it on runpod, or just look at the code and thumbs up if it appears ok?

imho the best way would be to verify that build.sh / run.sh is working locally.

**Comment by lstein** [comment]
I'll try to build the docker locally later today.

**Comment by mauwii** [comment]
I would suggest we enable PR Validation for `build-container.yml` now as well, since this should be faster than the other workflows and it would prevent that development branch fails because of it (like it does atm).

**Comment by damian0815** [comment]
i'm trying this out now

**Comment by damian0815** [comment]
first comment, 

```
damian@Damians-mac-mini docker-build % cd docker-build/
damian@Damians-mac-mini docker-build % ./build.sh
./build.sh: line 7: ./docker-build/env.sh: No such file or directory
```
i won't fail the review for this but it would be nice if the script used `dirname $0` to avoid this problem

**Comment by damian0815** [comment]
@mauwii error'd:
```
 => ERROR [invokeai  8/10] RUN source "/opt/conda/etc/profile.d/conda.sh"   && conda init bash   && source ~/.  131.2s
------
 > [invokeai  8/10] RUN source "/opt/conda/etc/profile.d/conda.sh"   && conda init bash   && source ~/.bashrc   && conda env create     --name "invokeai"   && rm -Rf ~/.cache   && conda clean -afy   && echo "conda activate invokeai" >> ~/.bashrc:
#14 1.353 no change     /opt/conda/condabin/conda
#14 1.353 no change     /opt/conda/bin/conda
#14 1.353 no change     /opt/conda/bin/conda-env
#14 1.353 no change     /opt/conda/bin/activate
#14 1.353 no change     /opt/conda/bin/deactivate
#14 1.353 no change     /opt/conda/etc/profile.d/conda.sh
#14 1.353 no change     /opt/conda/etc/fish/conf.d/conda.fish
#14 1.353 no change     /opt/conda/shell/condabin/Conda.psm1
#14 1.353 no change     /opt/conda/shell/condabin/conda-hook.ps1
#14 1.353 no change     /opt/conda/lib/python3.9/site-packages/xontrib/conda.xsh
#14 1.353 no change     /opt/conda/etc/profile.d/conda.csh
#14 1.353 modified      /root/.bashrc
#14 1.353
#14 1.353 ==> For changes to take effect, close and re-open your current shell. <==
#14 1.353
#14 5.810 Collecting package metadata (repodata.json): ...working... /root/.bashrc: line 41:    55 Killed                  "$CONDA_EXE" $_CE_M $_CE_CONDA "$@"
------
executor failed running [/bin/bash -c source "${conda_prefix}/etc/profile.d/conda.sh"   && conda init bash   && source ~/.bashrc   && conda env create     --name "${project_name}"   && rm -Rf ~/.cache   && conda clean -afy   && echo "conda activate ${project_name}" >> ~/.bashrc]: exit code: 137
```

**Comment by mauwii** [comment]
@damian0815 you should checkout the PR first, since there is no Conda at all I am sure you tested the development branch :-/

**Comment by damian0815** [comment]
same again, after about the same time. is it timing out?

**Comment by mauwii** [comment]
how can it be the same when there is no conda?!

**Comment by damian0815** [comment]
> @damian0815 you should checkout the PR first, since there is no Conda at all I am sure you tested the development branch :-/

lolololol yes sorry

**Comment by mauwii** [comment]
also run the build.sh script from repo root (like `./docker-build/build.sh`)

**Comment by damian0815** [comment]
yeah, that looks better. i did checkout the PR, except immediately realised i don't have space on my laptop to fit a fat docker image, Parsec'd into my mac mini and promptly forgot that i needed to checkout the PR *there* too.

**Comment by ebr** [comment]
> what's the relationship between this and the one by @ebr ? seems odd to have two of them.. and how would you like me to review it? should i try and put it on runpod, or just look at the code and thumbs up if it appears ok, or something else..?

At this point there seems to be non-negligible amount of overlap between this PR and my https://github.com/invoke-ai/InvokeAI/pull/1544. I would recommend merging this PR first, and then I will rebase mine on top of it, taking care of any conflicts (e.g. `.dockerignore` is definitely going to conflict, etc).

I think after that's done, it should be possible to combine the Dockerfiles into a single file that can be used in either local or cloud deployments and perhaps reduce the overall amount of input needed for build configuration.

**Comment by mauwii** [comment]
only necesarry input here is the HUGGINGFACE_TOKEN, rest is optional ;)

**Comment by damian0815** [comment]
built apparently fine but died immediately running while trying to load the v1.5 model:

```
damian@Damians-mac-mini stable-diffusion % ./docker-build/run.sh
* Initializing, be patient...
>> Initialization file /root/.invokeai not found. Creating a new one...
>> InvokeAI runtime directory is "/data"
Compiling and loading c extensions from "/usr/local/lib/python3.10/dist-packages/patchmatch".
/usr/bin/find: ‘csrc/’: No such file or directory
/usr/bin/find: ‘csrc/’: No such file or directory
rm -rf build/obj libpatchmatch.so
/usr/bin/find: ‘csrc/’: No such file or directory
/usr/bin/find: ‘csrc/’: No such file or directory
/usr/bin/find: ‘csrc/’: No such file or directory
make: pkg-config: No such file or directory
make: pkg-config: No such file or directory
[link] libpatchmatch.so ...
g++: fatal error: no input files
compilation terminated.
make: *** [Makefile:44: libpatchmatch.so] Error 1
## NOT FOUND: GFPGAN model not found at /data/models/gfpgan/GFPGANv1.4.pth
>> GFPGAN Disabled
## NOT FOUND: CodeFormer model not found at /data/models/codeformer/codeformer.pth
>> CodeFormer Disabled
>> ESRGAN Initialized
>> Using device_type cpu
>> Current VRAM usage:  0.00G
>> Scanning Model: stable-diffusion-1.5
>> Model Scanned. OK!!
>> Loading stable-diffusion-1.5 from /data/models/ldm/stable-diffusion-v1/v1-5-pruned-emaonly.ckpt
damian@Damians-mac-mini stable-diffusion %
```

**Comment by damian0815** [comment]
`g++: fatal error: no input files` is maybe the culprit

**Comment by damian0815** [comment]
but also weird that
```## NOT FOUND: GFPGAN model not found at /data/models/gfpgan/GFPGANv1.4.pth
```
and
```
## NOT FOUND: CodeFormer model not found at /data/models/codeformer/codeformer.pth
```
because aren't those downloaded by `configure_invokeai.py`?

**Comment by mauwii** [comment]
> `g++: fatal error: no input files` is maybe the culprit

this is expected until patchmatch is fixed, and doesn't break the app (it also happens when you run localy...)

`## NOT FOUND: GFPGAN model not found at /data/models/gfpgan/GFPGANv1.4.pth` is a bit strange, did you really download all the models to the volume? (happens after the image was built when using build.sh)

**Comment by mauwii** [comment]
image

**Comment by mauwii** [comment]
image

**Comment by mauwii** [comment]
My output of build.sh:

```
./docker-build/build.sh                         
You are using these values:
Dockerfile:              docker-build/Dockerfile
project_name:            invokeai
volumename:              invokeai_data
arch:                    aarch64
platform:                Linux/aarch64
invokeai_tag:            invokeai:aarch64

Volume already exists
[+] Building 158.1s (11/11) FINISHED                                                                                                                                                
 => [internal] load build definition from Dockerfile                                                                                                                           0.0s
 => => transferring dockerfile: 961B                                                                                                                                           0.0s
 => [internal] load .dockerignore                                                                                                                                              0.0s
 => => transferring context: 34B                                                                                                                                               0.0s
 => [internal] load metadata for docker.io/library/ubuntu:22.10                                                                                                                1.2s
 => [auth] library/ubuntu:pull token for registry-1.docker.io                                                                                                                  0.0s
 => [1/5] FROM docker.io/library/ubuntu:22.10@sha256:edc5125bd9443ab5d5c92096cf0e481f5e8cb12db9f5461ab1ab7a936c7f7d30                                                          0.0s
 => [internal] load build context                                                                                                                                              0.0s
 => => transferring context: 42.95kB                                                                                                                                           0.0s
 => CACHED [2/5] RUN apt-get update   && apt-get install -y     --no-install-recommends     build-essential     gcc     git     libgl1-mesa-glx     libglib2.0-0     pip       0.0s
 => CACHED [3/5] WORKDIR /invokeai                                                                                                                                             0.0s
 => [4/5] COPY . .                                                                                                                                                             0.1s
 => [5/5] RUN cp   ./environments-and-requirements/requirements-lin-cuda.txt   requirements-lin-cuda.txt   && pip install     --no-cache-dir     -r requirements-lin-cuda.t  152.6s
 => exporting to image                                                                                                                                                         4.0s 
 => => exporting layers                                                                                                                                                        4.0s 
 => => writing image sha256:2faa7eb7d493eb722a69d2588d4b82bba6d6acdf33d5292f1553806ab4b8ce00                                                                                   0.0s 
 => => naming to docker.io/library/invokeai:aarch64                                                                                                                            0.0s 
                                                                                                                                                                                    
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them                                                                                
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
/data/models/ldm/stable-diffusion-v1/
/data/models/ldm/stable-diffusion-v1/
/data/models/ldm/stable-diffusion-v1/
Installing bert tokenizer (ignore deprecation errors)...
...success
Installing CLIP model (ignore deprecation errors)...
Tokenizer...
Text model...
...success
Installing models from RealESRGAN...
Installing RealESRGAN model file https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.5.0/realesr-general-x4v3.pth......exists
Installing GFPGAN models...
Installing GFPGAN weights model file https://github.com/TencentARC/GFPGAN/releases/download/v1.3.0/GFPGANv1.4.pth......exists
Installing GFPGAN weights model file https://github.com/xinntao/facexlib/releases/download/v0.1.0/detection_Resnet50_Final.pth......exists
Installing GFPGAN weights model file https://github.com/xinntao/facexlib/releases/download/v0.2.2/parsing_parsenet.pth......exists
Installing CodeFormer model file...
Installing CodeFormer model file https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/codeformer.pth......exists
Installing clipseg model for text-based masking......success
Installing safety model for NSFW content detection...
AutoFeatureExtractor...
StableDiffusionSafetyChecker...
...success
Loading Python libraries...

Welcome to InvokeAI. This script will help download the Stable Diffusion weight files
and other large models that are needed for text to image generation. At any point you may interrupt
this program and resume later.

(Initializing with runtime root /data)

** DOWNLOADING DIFFUSION WEIGHTS **
* v1-5-pruned-emaonly.ckpt: complete file found. Skipping.
* sd-v1-5-inpainting.ckpt: complete file found. Skipping.
* vae-ft-mse-840000-ema-pruned.ckpt: complete file found. Skipping.
Successfully installed stable-diffusion-1.5, inpainting-1.5, ft-mse-improved-autoencoder-840000
** /data/configs/models.yaml exists. Renaming to /data/configs/models.yaml.orig
Successfully created new configuration file /data/configs/models.yaml

** DOWNLOADING SUPPORT MODELS **

** Model Installation Successful **
You're all set! You may now launch InvokeAI using one of these two commands:
Web version: 
    python scripts/invoke.py --web  (connect to http://localhost:9090)
Command-line version:
   python scripts/invoke.py

Remember to activate that 'invokeai' environment before running invoke.py.

Or, if you used one of the automated installers, execute "invoke.sh" (Linux/Mac) 
or "invoke.bat" (Windows) to start the script.

Have fun!
```

**Comment by damian0815** [comment]
here's my output of build.sh:

```
damian@Damians-mac-mini stable-diffusion % ./docker-build/build.sh
You are using these values:
Dockerfile:		 docker-build/Dockerfile
project_name:		 invokeai
volumename:		 invokeai_data
arch:			 x86_64
platform:		 Linux/x86_64
invokeai_tag:		 invokeai:x86_64

Volume already exists
[+] Building 1014.0s (10/10) FINISHED
 => [internal] load build definition from Dockerfile                                                              0.0s
 => => transferring dockerfile: 961B                                                                              0.0s
 => [internal] load .dockerignore                                                                                 0.0s
 => => transferring context: 161B                                                                                 0.0s
 => [internal] load metadata for docker.io/library/ubuntu:22.10                                                   1.9s
 => [internal] load build context                                                                                 0.6s
 => => transferring context: 13.07MB                                                                              0.6s
 => [1/5] FROM docker.io/library/ubuntu:22.10@sha256:edc5125bd9443ab5d5c92096cf0e481f5e8cb12db9f5461ab1ab7a936c7  2.6s
 => => resolve docker.io/library/ubuntu:22.10@sha256:edc5125bd9443ab5d5c92096cf0e481f5e8cb12db9f5461ab1ab7a936c7  0.0s
 => => sha256:edc5125bd9443ab5d5c92096cf0e481f5e8cb12db9f5461ab1ab7a936c7f7d30 1.42kB / 1.42kB                    0.0s
 => => sha256:f0a63f53b736b9211a5313a7219f6cc012b7cf4194c7ce2248fac8162b56dceb 529B / 529B                        0.0s
 => => sha256:8a7f92156625b8656618357c6ab1e0a641888de25010da43014db17b5eb6e514 1.46kB / 1.46kB                    0.0s
 => => sha256:daae843197f7407fa8b43bb15fdb45858a6ae776e755cd31ba485d5aa0fb4eaa 27.46MB / 27.46MB                  1.6s
 => => extracting sha256:daae843197f7407fa8b43bb15fdb45858a6ae776e755cd31ba485d5aa0fb4eaa                         0.8s
 => [2/5] RUN apt-get update   && apt-get install -y     --no-install-recommends     build-essential     gcc    104.7s
 => [3/5] WORKDIR /invokeai                                                                                       0.0s
 => [4/5] COPY . .                                                                                                0.1s
 => [5/5] RUN cp   ./environments-and-requirements/requirements-lin-cuda.txt   requirements-lin-cuda.txt   &&   885.7s
 => exporting to image                                                                                           19.0s
 => => exporting layers                                                                                          19.0s
 => => writing image sha256:3644cfe22267d11d96bee0c29be4f4781f863c1e64926c15f239419c2fae2474                      0.0s
 => => naming to docker.io/library/invokeai:x86_64                                                                0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
/data/models/ldm/stable-diffusion-v1/
Loading Python libraries...

Welcome to InvokeAI. This script will help download the Stable Diffusion weight files
and other large models that are needed for text to image generation. At any point you may interrupt
this program and resume later.

** INITIALIZING INVOKEAI RUNTIME DIRECTORY **
InvokeAI models and configuration files will be placed into /data and image outputs will be placed into /data/outputs.

You may change these values at any time by editing the --root and --output_dir options in "/root/.invokeai",
You may also change the runtime directory by setting the environment variable INVOKEAI_ROOT.

Creating the initialization file at "/root/.invokeai".

(Initializing with runtime root /data)

** DOWNLOADING DIFFUSION WEIGHTS **
* v1-5-pruned-emaonly.ckpt: Downloading...
v1-5-pruned-emaonly.ckpt: 100%|██████████| 4.27G/4.27G [06:04<00:00, 11.7MiB/s]
/data/models/ldm/stable-diffusion-v1/
* sd-v1-5-inpainting.ckpt: Downloading...
sd-v1-5-inpainting.ckpt: 100%|██████████| 4.27G/4.27G [05:45<00:00, 12.3MiB/s]
/data/models/ldm/stable-diffusion-v1/
* vae-ft-mse-840000-ema-pruned.ckpt: Downloading...
vae-ft-mse-840000-ema-pruned.ckpt: 100%|██████████| 335M/335M [00:24<00:00, 13.5MiB/s]
Installing bert tokenizer (ignore deprecation errors)...
Successfully installed stable-diffusion-1.5, inpainting-1.5, ft-mse-improved-autoencoder-840000
** /data/configs/models.yaml exists. Renaming to /data/configs/models.yaml.orig
Successfully created new configuration file /data/configs/models.yaml

** DOWNLOADING SUPPORT MODELS **
Downloading tokenizer_config.json: 100%|██████████| 28.0/28.0 [00:00<00:00, 1.82kB/s]
Downloading vocab.txt: 100%|██████████| 226k/226k [00:00<00:00, 454kB/s]
Downloading tokenizer.json: 100%|██████████| 455k/455k [00:00<00:00, 744kB/s]
Downloading config.json: 100%|██████████| 570/570 [00:00<00:00, 39.0kB/s]
...success
Installing CLIP model (ignore deprecation errors)...
Tokenizer...
Downloading vocab.json: 100%|██████████| 939k/939k [00:00<00:00, 1.32MB/s]
Downloading merges.txt: 100%|██████████| 512k/512k [00:00<00:00, 840kB/s]
Downloading special_tokens_map.json: 100%|██████████| 389/389 [00:00<00:00, 26.0kB/s]
Downloading tokenizer_config.json: 100%|██████████| 905/905 [00:00<00:00, 63.4kB/s]
Text model...
Downloading config.json: 100%|██████████| 4.41k/4.41k [00:00<00:00, 304kB/s]
Downloading pytorch_model.bin: 100%|██████████| 1.59G/1.59G [02:06<00:00, 13.5MB/s]
```

**Comment by damian0815** [comment]
running again, i'm not getting the "You're all set!" message and ff

```
damian@Damians-mac-mini stable-diffusion % ./docker-build/build.sh
You are using these values:
Dockerfile:		 docker-build/Dockerfile
project_name:		 invokeai
volumename:		 invokeai_data
arch:			 x86_64
platform:		 Linux/x86_64
invokeai_tag:		 invokeai:x86_64

Volume already exists
[+] Building 1.4s (10/10) FINISHED
 => [internal] load build definition from Dockerfile                                                              0.0s
 => => transferring dockerfile: 37B                                                                               0.0s
 => [internal] load .dockerignore                                                                                 0.0s
 => => transferring context: 34B                                                                                  0.0s
 => [internal] load metadata for docker.io/library/ubuntu:22.10                                                   1.3s
 => [1/5] FROM docker.io/library/ubuntu:22.10@sha256:edc5125bd9443ab5d5c92096cf0e481f5e8cb12db9f5461ab1ab7a936c7  0.0s
 => [internal] load build context                                                                                 0.1s
 => => transferring context: 41.84kB                                                                              0.1s
 => CACHED [2/5] RUN apt-get update   && apt-get install -y     --no-install-recommends     build-essential       0.0s
 => CACHED [3/5] WORKDIR /invokeai                                                                                0.0s
 => CACHED [4/5] COPY . .                                                                                         0.0s
 => CACHED [5/5] RUN cp   ./environments-and-requirements/requirements-lin-cuda.txt   requirements-lin-cuda.txt   0.0s
 => exporting to image                                                                                            0.0s
 => => exporting layers                                                                                           0.0s
 => => writing image sha256:3644cfe22267d11d96bee0c29be4f4781f863c1e64926c15f239419c2fae2474                      0.0s
 => => naming to docker.io/library/invokeai:x86_64                                                                0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
/data/models/ldm/stable-diffusion-v1/
/data/models/ldm/stable-diffusion-v1/
/data/models/ldm/stable-diffusion-v1/
Installing bert tokenizer (ignore deprecation errors)...
...success
Installing CLIP model (ignore deprecation errors)...
Tokenizer...
Text model...
damian@Damians-mac-mini stable-diffusion %
```

**Comment by mauwii** [comment]
It's a bit strange actually, yes :-/

**Comment by mauwii** [comment]
could you clone the repo to another folder again (or do a git reset --hard origin/update-dockerfile, but if you have custom changes this would delete them, why I recommend a new clone)

Since the scripts are cloned from the source folder now, I suspect there is the root cause of your problem.

**Comment by damian0815** [comment]
i'm trying to run `sh` inside the container by replacing the command to start invoke with `/bin/sh` and it's giving me 
```
SyntaxError: Non-UTF-8 code starting with '\xa7' in file /bin/sh on line 2, but no encoding declared; see https://python.org/dev/peps/pep-0263/ for details
```
which i don't know how to fix

**Comment by mauwii** [comment]
Ahhhh - you could also try to `export ARCH=aarch64` before running the built

**Comment by mauwii** [comment]
btw: to run /bin/sh you would need to add `--entrypoint="/bin/sh"` to the docker run command, since the entrypoint is actualy python, which can indeed not run /bin/sh ;P

**Comment by damian0815** [comment]
> Ahhhh - you could also try to `export ARCH=aarch64` before running the built

same problem (incomplete build of models image)

```
damian@Damians-mac-mini stable-diffusion-docker % ARCH=aarch64 ./docker-build/build.sh
You are using these values:
Dockerfile:		 docker-build/Dockerfile
project_name:		 invokeai
volumename:		 invokeai_data
arch:			 aarch64
platform:		 Linux/aarch64
invokeai_tag:		 invokeai:aarch64

Volume already exists
[+] Building 126.7s (10/10) FINISHED
 => [internal] load build definition from Dockerfile                                                              0.0s
 => => transferring dockerfile: 37B                                                                               0.0s
 => [internal] load .dockerignore                                                                                 0.0s
 => => transferring context: 34B                                                                                  0.0s
 => [internal] load metadata for docker.io/library/ubuntu:22.10                                                   1.0s
 => [1/5] FROM docker.io/library/ubuntu:22.10@sha256:edc5125bd9443ab5d5c92096cf0e481f5e8cb12db9f5461ab1ab7a936c7  2.4s
 => => resolve docker.io/library/ubuntu:22.10@sha256:edc5125bd9443ab5d5c92096cf0e481f5e8cb12db9f5461ab1ab7a936c7  0.0s
 => => sha256:edc5125bd9443ab5d5c92096cf0e481f5e8cb12db9f5461ab1ab7a936c7f7d30 1.42kB / 1.42kB                    0.0s
 => => sha256:342a2a2185759db2435ea1260cdcef460ef3ab9b1e27313219cee7b38d97cdf8 529B / 529B                        0.0s
 => => sha256:bd0f2ee1f44f455fd39461966b77ea59a9ea596ea71359c52ab7e91571afac2e 1.48kB / 1.48kB                    0.0s
 => => sha256:c2a61899dd54b8fa20d519378edf37b06404d36e3ec868e7419d7ec51730b03b 26.68MB / 26.68MB                  1.6s
 => => extracting sha256:c2a61899dd54b8fa20d519378edf37b06404d36e3ec868e7419d7ec51730b03b                         0.7s
 => [internal] load build context                                                                                 0.0s
 => => transferring context: 34.51kB                                                                              0.0s
 => [2/5] RUN apt-get update   && apt-get install -y     --no-install-recommends     build-essential     gcc     20.3s
 => [3/5] WORKDIR /invokeai                                                                                       0.0s
 => [4/5] COPY . .                                                                                                0.1s
 => [5/5] RUN cp   ./environments-and-requirements/requirements-lin-cuda.txt   requirements-lin-cuda.txt   && p  94.1s
 => exporting to image                                                                                            8.6s
 => => exporting layers                                                                                           8.6s
 => => writing image sha256:4107da08284a14a21ecc3bdfc15e26fdfc8c1d7ebe384efe6d935f4a1102274a                      0.0s
 => => naming to docker.io/library/invokeai:aarch64                                                               0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension:
  warn(f"Failed to load image Python extension: {e}")
/data/models/ldm/stable-diffusion-v1/
/data/models/ldm/stable-diffusion-v1/
/data/models/ldm/stable-diffusion-v1/
Installing bert tokenizer (ignore deprecation errors)...
...success
Installing CLIP model (ignore deprecation errors)...
Tokenizer...
Text model...
damian@Damians-mac-mini stable-diffusion-docker %
```

**Comment by damian0815** [comment]
> btw: to run /bin/sh you would need to add `--entrypoint="/bin/sh"` to the docker run command, since the entrypoint is actualy python, which can indeed not run /bin/sh ;P

doesn't seem to work. i made a copy of build.sh → build-debug.sh, edited command to
```
docker run \
  --rm \
  --platform "$platform" \
  --name "$project_name" \
  --hostname "$project_name" \
  --mount source="$volumename",target=/data \
  --mount type=bind,source="$HOME/.huggingface",target=/root/.huggingface \
  --env HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN} \
  --entrypoint="/bin/sh"
  -it \
  "${invokeai_tag}" \
  /bin/sh
```

result:
```
"docker run" requires at least 1 argument.
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container
```

**Comment by mauwii** [comment]
you missed the backslash behind `--entrypoint="/bin/sh"`

**Comment by mauwii** [comment]
now u try to run /bin/sh /bin/sh, which will not work

**Comment by damian0815** [comment]
ok i managed to get into the image and figure out i need to type `python3` instead of `python`. whee. 

but it's not more informative, it just says "killed":

```
# python3 scripts/configure_invokeai.py --yes
Loading Python libraries...

/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension:
  warn(f"Failed to load image Python extension: {e}")
Welcome to InvokeAI. This script will help download the Stable Diffusion weight files
and other large models that are needed for text to image generation. At any point you may interrupt
this program and resume later.

** INITIALIZING INVOKEAI RUNTIME DIRECTORY **
InvokeAI models and configuration files will be placed into /data and image outputs will be placed into /data/outputs.

You may change these values at any time by editing the --root and --output_dir options in "/root/.invokeai",
You may also change the runtime directory by setting the environment variable INVOKEAI_ROOT.

Creating the initialization file at "/root/.invokeai".

(Initializing with runtime root /data)

** DOWNLOADING DIFFUSION WEIGHTS **
/data/models/ldm/stable-diffusion-v1/
* v1-5-pruned-emaonly.ckpt: complete file found. Skipping.
/data/models/ldm/stable-diffusion-v1/
* sd-v1-5-inpainting.ckpt: complete file found. Skipping.
/data/models/ldm/stable-diffusion-v1/
* vae-ft-mse-840000-ema-pruned.ckpt: complete file found. Skipping.
Successfully installed stable-diffusion-1.5, inpainting-1.5, ft-mse-improved-autoencoder-840000
** /data/configs/models.yaml exists. Renaming to /data/configs/models.yaml.orig
Successfully created new configuration file /data/configs/models.yaml

** DOWNLOADING SUPPORT MODELS **
Installing bert tokenizer (ignore deprecation errors)...
...success
Installing CLIP model (ignore deprecation errors)...
Tokenizer...
Text model...
Killed
```

same result if i skip `--yes` on the command

**Comment by damian0815** [comment]
i apt install'd gdb but no further info:

```
[Thread 0xffffac97f1a0 (LWP 413) exited]
[Thread 0xffffaf18f1a0 (LWP 412) exited]
[Thread 0xffffb199f1a0 (LWP 411) exited]

Program terminated with signal SIGKILL, Killed.
The program no longer exists.
(gdb)
```

**Comment by mauwii** [comment]
how high is your setting for RAM etc in Docker?

image

**Comment by damian0815** [comment]
> how high is your setting for RAM etc in Docker?

bingo

pushed it up to 4GB (was 2) and now it seems to be getting past that

**Review by damian0815 — APPROVED** [review]
confirmed working on macos with aarch64 platform

**Comment by damian0815** [comment]
@mauwii should i merge it or do you want to?

**Comment by mauwii** [comment]
just did a small last minute fix to the build script. As soon as the checks are done I will merge it 🤓

**Review by lstein — APPROVED** [review]
I'm satisfied from the conversation that the various issues have been fixed and am happy to approve this PR.

**Review by lstein — APPROVED** [review]
I approve the merged changes.

**Pull request merged**
