### PR TITLE
Remove unneeded `pip install -e` from environment.yaml which prevents deployment with Meadowrun

### PR DESCRIPTION
**Pull request by doegox**
As it is, the repo (and the original compviz) is not deployable with Meadowrun on Amazon AWS.
All it takes to get it working is to remove the line `-e .` at the bottom of `environment.yaml` because
Meadowrun doesn’t (yet) support installing the current code as an editable pip package.
This change does not affect regular usage of the repo AFAIK

Taken from https://github.com/hrichardlee/stable-diffusion/commit/b0cc2e6fa0cd17275bbdee41b974aac0f94b39d3
and the explanation at https://medium.com/@meadowrun/how-to-run-stable-diffusion-on-ec2-e447333d820

I tested deployment on AWS from my fork
Thank you !

### CODE REVIEW

**Comment by lstein** [comment]
I think this will be a problem on conda deploys. If the `pip -e .` is removed, then conda doesn't add the `InvokeAI` directory to the system path and dream.py and the web GUI will return module not found errors. I will check this again on a virgin install, but I think it is a fundamental conflict with MeadowRun. Perhaps we should create an `environment-meadowrun.yaml` file?

**Comment by tildebyte** [comment]
> If the `pip -e .` is removed, then conda doesn't add the `InvokeAI` directory to the system path

Correct. Same for 'pip' installs. `pip install .` (without the -e) *might* work, but I haven't tested it.

**Comment by doegox** [comment]
I see, yes having a second yaml file would be nice too and safer regarding conda

**Comment by lstein** [comment]
I'm going to close this PR, OK? Please go ahead and copy environment.yaml to environment-meadowrun.yaml, add it to your local repository, and then generate a new PR. This will get you on the CONTRIBUTORS list. (If you don't care, I can go ahead do do it...)

**Comment by doegox** [comment]
Hi, I don't care being listed as contributor for such small thing ;) feel free to add directly the file, thanks!

**Pull request closed without merging**
