### PR TITLE
enable or disable safety checker at configure time

### PR DESCRIPTION
**Pull request by lstein**
The configure script now asks the user whether they wish to activate the safety filter by default. It also asks for their preferred sampler and steps. These values get written into ~/.invokeai

See discussion on Discord at: https://discord.com/channels/1020123559063990373/1038203262911914115

### CODE REVIEW

**Review by damian0815 — APPROVED** [review]
thanks for implementing this, the wording is more neutral than i'd prefer but that's ok.

**Review by blessedcoolant — APPROVED** [review]

**Comment by blessedcoolant** [comment]
LGTM.

**Comment by lstein** [comment]
The CI actions are picking up a bug. I am fixing it.

**Review by psychedelicious — APPROVED** [review]
Code reviewed and tested.

**Comment by lstein** [comment]
For some reason this PR does not seem to want to pass the CI tests, even though it doesn't touch the environment files. I am going to have to withdraw it, port the changes, and make a new PR.

Weird!

**Comment by lstein** [comment]
Checks are not passing. Retire this PR.

**Pull request closed without merging**
