### PR TITLE
Update diffusers to 0.26.0 and fix imports/names

### PR DESCRIPTION
**Pull request by Malrama**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [X] Bug Fix
- [X] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [ ] Yes
- [X] No, because I don't think this is needed

      
## Have you updated all relevant documentation?
- [ ] Yes
- [ ] No

## Description

A [new version](https://github.com/huggingface/diffusers/releases) of diffusers has just released yesterday with some major [refractions](https://github.com/huggingface/diffusers/commit/1f0705adcfe9e57db1bb90c2938922249b186cfc). I tried to catch all imports, but it is possible that I missed some. The old imports will be deprecated in version 0.29.0, so I tried to find them all and change them while I am at it.
If you like, please look if I missed some somewhere.

There seem to be some scripts that might use the old imports. But as I said, for now, there is nothing breaking.

Fixed the hotfix.py for a name change (fix?) [introduced upstream here](https://github.com/huggingface/diffusers/commit/fee93c81eb7c5e9fe1618f858f1e369567170edc)

Everything seems to be running fine for me. Invoke is generating images! However, I would like you guys to test it first because of some refactoring changes that I might have missed.

Thank you very much and kind regards.

## Related Tickets & Documents

- Related Issue #
- Closes #

## Added/updated tests?

- [ ] Yes
- [ ] No : _please replace this line with details on why tests
      have not been included_

### CODE REVIEW

**Comment by hipsterusername** [comment]
Can you fix style checks? Thanks for this update!

**Comment by Malrama** [comment]
> Can you fix style checks? Thanks for this update!

How and which one? I don't know what's wrong :/

**Comment by Malrama** [comment]
Fixed 👍

**Comment by Millu** [comment]
Works on Mac!

**Pull request merged**
