### PR TITLE
[ui]: migrate all styling to chakra-ui theme

### PR DESCRIPTION
**Pull request by psychedelicious**
- Migrate UI from SCSS to Chakra's CSS-in-JS system 
  - better dx
  - more capable theming 
  - full RTL language support (we now have Arabic and Hebrew)
  - general cleanup of the whole UI's styling
- Tidy npm packages and update scripts, necessitates update to github actions

To test this PR in dev mode, you will need to do a `yarn install` as a lot has changed.

thanks to @blessedcoolant for helping out on this, it was a big effort.

### CODE REVIEW

**Review by blessedcoolant — APPROVED** [review]

**Comment by blessedcoolant** [comment]
Congrats @psychedelicious for taking on this tedious task. Great job.

**Comment by blessedcoolant** [comment]
@lstein Please review this and merge when you get the chance.

**Review by netsvetaev — APPROVED** [review]

**Comment by netsvetaev** [comment]
wow! @psychedelicious, that’s huge. Very nice work, thanks!

**Review by hipsterusername — APPROVED** [review]
👏 🎉

**Review by mauwii — APPROVED** [review]

**Pull request merged**
