### PR TITLE
wip(ui): Add Gradient Mask to Canvas

### PR DESCRIPTION
**Pull request by blessedcoolant**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Feature

## Have you discussed this change with the InvokeAI team?
- [x] Yes

    
## Description

This PR eliminates what we have been calling a `Coherence Pass` on the Unified Canvas and instead replaces the denoise mask creation with the `Gradient Mask Denoising` node added in #5760 .

Making this change leads to a few side effects that I will list here.

1. Because the mask is capable of smoothing itself out during the diffusion, the paste back is blended in quite well. So we no longer need to blur the mask anymore. So all mask blurring operations on the Canvas have now been removed.

2. The color correction that was being applied to the images on paste back has also been replaced with just a regular softened paste back. Initially I was trying to get rid of the paste back entirely but we still have the lossy problem of the VAE decode which alters the entire image slightly rather than just the masked area. This new paste back uses a custom node called `IAICanvasPasteBackInvocation` which will specifically be used for canvas paste back operations. It's essentially a variant of the `Image Paste` node but designed to work exclusively with the canvas.

3. The Coherence Pass now has three options which control the parameters of the Denoising Mask - Mode (defaulted to Gaussian), Min Denoise (defaulted to 0) and Edge Size (which controls the size of the edge in Inpainting and additionally the paste back blur factor during outpainting).

Works on Canvas Inpaint, Outpaint for both 1.5x and SDXL models.

## Merge Plan

THOROUGHLY TEST EVERYTHING before merging. Right now LoRA's and etc are not working on the UI. I've updated the graphs but could not test if they're all working properly still as a result.

## [optional] Are there any post deployment tasks we need to perform?

If this PR is merged before the rest of the UI is fully functional, then we run tests again to make sure all graphs work as intended and make any fixes necessary.

## Post

We really have to consider a way to get rid of the intermediates being saved to disk each time. We stack up on intermediates real fast. A 15-20 min session on the canvas leads to close to a 1000 intermediates which have bare minimal post work usage in my opinion. Not saving each of these to disk each time will dramatically improve the graph execution time. However this is a bigger issue we need to handle in how the images are handled with Invoke. Another day, another discussion, another PR but just thought I'd make a note here.

### CODE REVIEW

**Comment by blessedcoolant** [comment]
Forgot to note above but I also added a `IAICanvasPasteBackInvocation` which we will exclusively use for Canvas related paste back operation. This in functionality does something similar to image paste back but more in tandem with how the canvas wants it. I didn't want to alter the Image Paste node too much to work it the way I wanted it to with the canvas.

**Review by hipsterusername — APPROVED** [review]

**Review by psychedelicious — APPROVED** [review]
I've rebased the branch and changed the new node's name, tested things out.

I'm getting some strange outputs when inpainting. The video shows 5x gens for each method:

https://github.com/invoke-ai/InvokeAI/assets/4822129/56fdad47-df37-4d38-916d-e85dc8b14290

Some are fine but others end up with the middle of the inpainted area weird and green. Most of the time it works perfectly, so I'm guessing I'm just hitting an edge case or my settings (the defaults) aren't quite right. Can't remember if I saw this in the OG coherence mode.

The perf improvement is awesome and the graphs are less terrifying. Great work @dunkeroni & @blessedcoolant!

**Comment by dunkeroni** [comment]
@psychedelicious that's a bit concerning.

What are your steps/CFG on that test?

Are you using an Inpainting model, or a normal one? The new node does not prepare a masked latents tensor for inpainting models, so they might have weird results. We need to migrate the code for that from inside the normal create makes node into the denoise latents node.

**Comment by psychedelicious** [comment]
@dunkeroni This was using deliberate (non-inpainting), Euler at 50 steps.

**Pull request merged**
