### PR TITLE
install frontend/dist into package directory

### PR DESCRIPTION
**Pull request by lstein**
- When invokeai installed with `pip install .`, the frontend will be in the venv directory under invokeai.
- When invokeai installed with `pip install -e .`, the frontend will be in the source repo. -invoke_ai_web_sever.py will look in both places using relative
  addressing.

### CODE REVIEW

**Review by damian0815 — APPROVED** [review]
LGTM (but i didn't try to run it)

**Review by blessedcoolant — APPROVED** [review]

**Comment by blessedcoolant** [comment]
Didnt try either but code seems fine to me.

**Review by psychedelicious — APPROVED** [review]
I ran into 3 issues, but the purpose of this PR isn't to address these. So I will approve this. 

1. I get `Failed to build basicsr gfpgan`, but they install successfully later using a different method. I saw this on prior install attempts as well. It is tempting to just abort the install because it looks like it has failed. 

2. After installing, though I already have a `.invokeai` file, I am prompted a to select output directory. 

3. After installation, when attempting to run the web UI, I get `ModuleNotFoundError: No module named 'patchmatch’`. I had to go to the ‘developer console’ and run `pip install git+https://github.com/invoke-ai/PyPatchMatch@0.1.1#egg=pypatchmatch`. Everything works after that, and I get the frontend files in the right place.

**Comment by lstein** [comment]
Three of the checks are hanging on the install requirements phase. I don't believe this is due to the PR, but I will investigate and fix.

**Comment by damian0815** [comment]
in case it got lost in the shuffle on discord last night, i was able to run this (following lstein's suggestion to `pip install .` and `pip install -e .` and check that the frontend works after each), and it worked fine.

**Pull request merged**
