### PR TITLE
non-uniform cfg_scale, including 1.0 value

### PR DESCRIPTION
**Pull request by telepancake**
Allow different cfg_scale value per each step, including 1.0 that is the fast unguided step. E.g.

`
dream> chair -G 0 -S 1 -s 10 -C 20 -A ddim
opt.cfg_scale [20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0]
. . .
>>   1 image(s) generated in 6.26s
`

`
dream> chair -G 0 -S 1 -s 10 -C 20,20,1,1,1,1,1,1,1,1 -A ddim
opt.cfg_scale [20.0, 20.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
. . .
>>   1 image(s) generated in 4.41s
`

### CODE REVIEW

**Comment by tildebyte** [comment]
@telepancake; Have you tested with other sample schedulers?

**Comment by telepancake** [comment]
yes. k_lms and k_euler* behaived as expected, k_dpm* steps seemed slower even with 1.0 (unguided)

**Review by lstein — CHANGES_REQUESTED** [review]
This is a novel and interesting idea! I second @tildebyte 's comments about providing documentation for the user. How does changing the CFG at each step help you tune the image? 

A couple of requested changes to improve the user experience:

1. Even when I don't use the feature (i.e. just type a prompt) I get the `opt.cfg_scale [20....]` message. This is an unexpected change in behavior and  should be suppressed unless the user has opted for the non-uniform CFG.
2. The normalized prompt that gets written to the CLI and to the image doesn't use the same syntax as the prompt that generated it. The prompt looks like `-C20,20,20,1,1,1`, but the normalized prompt is `-C[20,20,20,1,1,1]`. Cutting and pasting this back into the dream> prompt gives a hard crash:
~~~~
Traceback (most recent call last):
  File "scripts/dream.py", line 705, in <module>
    main()
  File "scripts/dream.py", line 112, in main
    main_loop(t2i, opt.outdir, opt.prompt_as_dir, cmd_parser, infile)
  File "scripts/dream.py", line 210, in main_loop
    opt.cfg_scale = [float(i) for i in opt.cfg_scale.split(',')]
  File "scripts/dream.py", line 210, in <listcomp>
    opt.cfg_scale = [float(i) for i in opt.cfg_scale.split(',')]
ValueError: could not convert string to float: '[20'
~~~~
3. From this error message, I think you need to catch exceptions generated when parsing the -C value.

**Comment by lstein** [comment]
I apologize for pinging you on this, but the underlying code base is changing rapidly and it will soon be very difficult to merge this PR with the current development. Could you indicate if you are going to be pushing more commits and/or rebasing as suggested earlier?

**Comment by tildebyte** [comment]
A word of warning: @Doggettx said, in https://github.com/CompVis/stable-diffusion/commit/3b5c504bb0c11a882252c0eb2b1955474913313a (their prompt2prompt ("Cross- attention") work upstream), "I have a new version that supports negative prompts and guidance scale guidance through the prompt"

**Comment by Doggettx** [comment]
Coincidently just checked in that new version an hour ago here https://github.com/Doggettx/stable-diffusion/commit/ccb17b55f2e7acbd1a112b55fb8f8415b4862521 it supports guidance scale modifications through the prompt with `{scale:step}` (see description of check-in).  Should be fairly easy to implement now, only needs a wrapper (provided) around the model.

**Comment by telepancake** [comment]
looked at https://github.com/Doggettx/stable-diffusion/commit/ccb17b55f2e7acbd1a112b55fb8f8415b4862521 and it looks like a superset of what I tried here. Once I get around to do it, I'll try and see if it makes sense to rework on top of it, for now you can punt this PR 👍

**Comment by telepancake** [comment]
The first two commits from this PR - you might consider applying those, I considerr them more of a bugfix

**Comment by tildebyte** [comment]
> looked at [Doggettx@ccb17b5](https://github.com/Doggettx/stable-diffusion/commit/ccb17b55f2e7acbd1a112b55fb8f8415b4862521) and it looks like a superset of what I tried here. Once I get around to do it, I'll try and see if it makes sense to rework on top of it, for now you can punt this PR +1

That'd be awesome; I took a look last night and realized that some of the work is in the (deprecated) 'txt2img.py', and I didn't understand *that* script very well at all to begin with...

**Comment by lstein** [comment]
I'm afraid this PR has gone stale due to the changing code base. I am closing it for now. Please feel free to submit a new PR for this that includes a `docs/features` document describing how to use the non-uniform cfg-scale feature.

**Pull request closed without merging**
