### PR TITLE
[WebUI] Even off JSX string syntax

### PR DESCRIPTION
**Pull request by dreglad**
Assuming that mixing `"literal strings"` and `{'JSX expressions'}` throughout the code is not for a explicit reason but just a result IDE autocompletion, I changed all props to be consistent with the conventional style of using simple string literals where it is sufficient. 

This is a somewhat trivial change, but it makes the code a little more readable and uniform

### CODE REVIEW

**Comment by blessedcoolant** [comment]
Yep. A lot of them were due to IDE auto completes. Thanks for cleaning this up. Can you please rebase this against main again? Thank you.

**Comment by dreglad** [comment]
Sure!

**Comment by blessedcoolant** [comment]
> Sure!

Thank you. Tag me when it's up and I'll run a quick review and merge it.

**Comment by dreglad** [comment]
@blessedcoolant Done, I just rebased later master and made a quick check, let me know if any tests fail

**Comment by blessedcoolant** [comment]
> @blessedcoolant Done, I just rebased later master and made a quick check, let me know if any tests fail

Hey. Thanks for the rebase. Seems like IAIInput.tsx has a bad merge. I can see the merge HEADs in there. And why is there a modellist.tsx as a brand new file?

**Comment by lstein** [comment]
@blessedcoolant This PR has been up for some time. What is its disposition?

**Comment by blessedcoolant** [comment]
@lstein Needs to be brought up to date with main. And fix up whatever is left. Then we can merge it up.

**Comment by lstein** [comment]
> @lstein Needs to be brought up to date with main. And fix up whatever is left. Then we can merge it up.

I have updated with main and didn't get any conflicts.

**Comment by blessedcoolant** [comment]
@dreglad Thanks for this PR. If you can confirm that all them have been fixed and rebase it against the main, I'll merge and approve. Thank you for your work on this.

**Review by psychedelicious — APPROVED** [review]
I've taken the liberty of updating this PR, handling the potentially messy rebase and fixing the string syntax for all of the new files we've added.

**Comment by blessedcoolant** [comment]
> I've taken the liberty of updating this PR, handling the potentially messy rebase and fixing the string syntax for all of the new files we've added. I've tested the changes briefly and there were no obvious problems (not that any would be expected!).
> 
> 
> 
> @blessedcoolant Can you please review?

Awesome. Thanks for getting it done. Code seems fine but I'll run a quick test when I'm on the PC and merge this in.

**Review by blessedcoolant — APPROVED** [review]

**Pull request merged**
