### PR TITLE
[Major Update] All New WebUI and Desktop Mode

### PR DESCRIPTION
**Pull request by blessedcoolant**
# All New WebUI

This PR brings in the new design for the new WebUI.

The new redesign presents a simple and easy to use GUI for anyone. The main options that are required for prompt generation are readily available with the more detailed settings presented to you as advanced options.

The New WebUI currently supports text to image generation, image to image generation, image upscaling, face restoration, variations, progress images and seamless tiling with more being worked on.

Currently only the Text to Image tab is populated. However you will find other tabs in the UI. These tabs will be released in future patches. These tabs will provide dedicated UI's for image to image, inpainting, outpainting , node workflow and post processing.

### Usage

New `dream.py` arguments.

- `--web` - Launches WebUI on a local server
- `--host` - To set the host of your server
- `--port` - To set the port of your server
- `--cors` - To white list your server and port if you are getting CORS errors

**Example usage:**

```python
dream.py <other arguments> --web
```

# Desktop Mode

You can now run the WebUI as a desktop app on your computer. This will launch using your systems browser as a desktop window instead of inside a regular browser.

To use desktop mode, you need to install `pip install flaskwebgui`

### Usage

```python
dream.py <other_arguments> --gui
```

---

# Testing Notes

- If you have tested previous version of the WebUI, it is recommend you delete your LocalStorage. Sometimes this might cause some issues with persistence. You just need to do this once.

---

This is still a draft. I will refine the UI a bit more and will fix any bugs that pop up along with @psychedelicious. Props to him for his incredible work on the new WebUI. Great job.

---

We will test this PR for a few days before going pushing this to dev and eventually the main release.

### CODE REVIEW

**Comment by blessedcoolant** [comment]
@lstein @tildebyte @psychedelicious

**Comment by hipsterusername** [comment]
Great work!!!

**Comment by lstein** [comment]
Fantastic!

**Comment by tildebyte** [comment]
Spanks. "Loving it!"[1]

[1] Two Minute Papers FTW

**Comment by lstein** [comment]
Tested. Here are my comments:
1. I really like the big font and the new layout
2. However, the tabs ("Image to image", "Inpainting", etc) don't seem to be functional? I guess they are for future implementation.
3. I needed to do a `pip install flaskwebgui` to run the first time.
4. On startup, I see this nonfatal error message:
~~~
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/u/lstein/.conda/envs/ldm/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/u/lstein/.conda/envs/ldm/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/u/lstein/.conda/envs/ldm/lib/python3.9/site-packages/socketio/server.py", line 730, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/u/lstein/.conda/envs/ldm/lib/python3.9/site-packages/socketio/server.py", line 755, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/u/lstein/.conda/envs/ldm/lib/python3.9/site-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/u/lstein/.conda/envs/ldm/lib/python3.9/site-packages/flask_socketio/__init__.py", line 826, in _handle_event
    ret = handler(*args)
TypeError: handle_request_images() takes from 0 to 1 positional arguments but 3 were given
Exception in thread Thread-10:
~~~
This seemed to clear when I cleared local storage and reloaded.
4. There's been some divergence in the call signature of  `img_callback() ` in ldm.models.diffusion.ksampler. I added back the `step` argument, which was lost when I merged in k* img2img support.
5. I find the camera icon used to kick off generation to be confusing. I interpret it as a screenshot button.
6. If the seed field is set to zero, then when I select a previously-generated image and click "use seed", it does not populate the field as expected.
7. Sometimes, when using an image for img2img, I get the following crash. I'm not exactly sure how to reproduce it.
~~~
Traceback (most recent call last):
  File "/u/lstein/projects/SD/InvokeAI/backend/invoke_ai_web_server.py", line 697, in generate_images
    self.generate.prompt2image(
  File "/u/lstein/projects/SD/InvokeAI/ldm/generate.py", line 414, in prompt2image
    results = generator.generate(
  File "/u/lstein/projects/SD/InvokeAI/ldm/dream/generator/base.py", line 72, in generate
    image = make_image(x_T)
  File "/u/lstein/projects/SD/InvokeAI/ldm/dream/generator/img2img.py", line 44, in make_image
    samples = sampler.decode(
  File "/u/lstein/.conda/envs/ldm/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/u/lstein/projects/SD/InvokeAI/ldm/models/diffusion/sampler.py", line 349, in decode
    img_callback(x_dec,step)
  File "/u/lstein/projects/SD/InvokeAI/backend/invoke_ai_web_server.py", line 554, in image_progress
    self.socketio.emit(
  File "/u/lstein/.conda/envs/ldm/lib/python3.9/site-packages/flask_socketio/__init__.py", line 460, in emit
    self.server.emit(event, *args, namespace=namespace, to=to,
  File "/u/lstein/.conda/envs/ldm/lib/python3.9/site-packages/socketio/server.py", line 319, in emit
    self.manager.emit(event, data, namespace, room=room,
  File "/u/lstein/.conda/envs/ldm/lib/python3.9/site-packages/socketio/base_manager.py", line 171, in emit
    self.server._emit_internal(eio_sid, event, data, namespace, id)
  File "/u/lstein/.conda/envs/ldm/lib/python3.9/site-packages/socketio/server.py", line 643, in _emit_internal
    self._send_packet(eio_sid, self.packet_class(
  File "/u/lstein/.conda/envs/ldm/lib/python3.9/site-packages/socketio/server.py", line 648, in _send_packet
    encoded_packet = pkt.encode()
  File "/u/lstein/.conda/envs/ldm/lib/python3.9/site-packages/socketio/packet.py", line 64, in encode
    encoded_packet += self.json.dumps(data, separators=(',', ':'))
  File "/u/lstein/.conda/envs/ldm/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/u/lstein/.conda/envs/ldm/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/u/lstein/.conda/envs/ldm/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/u/lstein/.conda/envs/ldm/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type int64 is not JSON serializable
~~~

**Comment by blessedcoolant** [comment]
> However, the tabs ("Image to image", "Inpainting", etc) don't seem to be functional? I guess they are for future implementation.

Yes. Placeholders for now.

> I needed to do a pip install flaskwebgui to run the first time.

Yep. Needed for Desktop Mode. Added to requirements.

> This seemed to clear when I cleared local storage and reloaded.

Only an issue when someone has tested the old WebUI. A simple reset from the setting will fix it.

> 4. There's been some divergence in the call signature of img_callback() in ldm.models.diffusion.ksampler. I added back the step argument, which was lost when I merged in k* img2img support.

Yep. This needed a fix from your end.

> 5. I find the camera icon used to kick off generation to be confusing. I interpret it as a screenshot button.

Will create a custom icon for it.

> 6. If the seed field is set to zero, then when I select a previously-generated image and click "use seed", it does not populate the field as expected.

I believe @psychedelicious already made a PR on dev to address this?

> 7. Sometimes, when using an image for img2img, I get the following crash. I'm not exactly sure how to reproduce it.

Never faced it. @psychedelicious Did you come across this bug?

**Comment by psychedelicious** [comment]
> > 6. If the seed field is set to zero, then when I select a previously-generated image and click "use seed", it does not populate the field as expected.
> 
> I believe @psychedelicious already made a PR on dev to address this?

This is a different bug related to IAINumberInput, I've just PR'd a fix.

**Comment by blessedcoolant** [comment]
> > > 6. If the seed field is set to zero, then when I select a previously-generated image and click "use seed", it does not populate the field as expected.
> > 
> > 
> > I believe @psychedelicious already made a PR on dev to address this?
> 
> This is a different bug related to IAINumberInput, I've just PR'd a fix.

Merged.

**Comment by psychedelicious** [comment]
> > 13\. Sometimes, when using an image for img2img, I get the following crash. I'm not exactly sure how to reproduce it.
> 
> Never faced it. @psychedelicious Did you come across this bug?

No I haven't but it seems the issue is `step` here being an `int64`:
```python
 File "/u/lstein/projects/SD/InvokeAI/ldm/models/diffusion/sampler.py", line 349, in decode
    img_callback(x_dec,step)
```

**Comment by lstein** [comment]
> > > 13. Sometimes, when using an image for img2img, I get the following crash. I'm not exactly sure how to reproduce it.
> > 
> > 
> > Never faced it. @psychedelicious Did you come across this bug?
> 
> No I haven't but it seems the issue is `step` here being an `int64`:
> 
> ```python
>  File "/u/lstein/projects/SD/InvokeAI/ldm/models/diffusion/sampler.py", line 349, in decode
>     img_callback(x_dec,step)
> ```
> 
> Will need @lstein to investigate this.

Investigated and found two places where the wrong value was being used for step. Committed to development and should be working now.

**Pull request closed without merging**
