### PR TITLE
add option to CLI and pngwriter that allows user to set PNG compression level

### PR DESCRIPTION
**Pull request by lstein**
# Problem

When running `img2img` repeatedly on the same image, the PNG compression/decompression artefacts add up.

# Solution

This PR adds a new feature that enables the user to change the level of PNG compression used, including turning it off completely.

# Details

- In CLI: the new argument is --png_compression <0..9> (-z<0..9>)
  -- this can be applied either on the command line, or at the `invoke>` prompt
- In API, pass new argument `compress_level` to PngWriter.save_image_and_prompt_to_png()

Compression ranges from 0 (no compression) to 9 (maximum compression). Default value is 6 (as specified by Pillow package).

This addresses an issue first raised in #652.

### CODE REVIEW

**Comment by tildebyte** [comment]
Will this be "sticky", like setting the sample scheduler from the CLI?

**Comment by lstein** [comment]
> Will this be "sticky", like setting the sample scheduler from the CLI?

It isn't currently. The value specified on the command line is the default level of compression. Individual invoke> commands can change it, but just for that one command.

I learned belatedly that PNG compression isn't lossy like JPG, and so this won't fix the problem we observe with loss of fidelity across multiple img2img passes. This seems to be an artefact of the diffusion process itself.

**Comment by tildebyte** [comment]
>  The value specified on the command line is the default level of compression. Individual invoke> commands can change it, but just for that one command

This is what I meant by "sticky" :D

**Comment by lstein** [comment]
Then the answer is "yes"

L

**Review by tildebyte — APPROVED** [review]

**Pull request merged**
