### PR TITLE
Increases socketio timeout to reduce disconnections

### PR DESCRIPTION
**Pull request by psychedelicious**
Straightforward change, increases 3 different timeout-related values for server and client to reduce disconnections. 

Shouldn't disconnect unless something takes over 60 seconds now. 

@timdesrochers While testing the changes, I was able to maintain connection during a 55-second thread-blocking task. 

Another improvement is to reload images on reconnect - I had implemented this previously but reverted, IIRC because I was having it load ALL images every reconnect, which was painful when you have tons of images. What it *should* do is load only images that are not already loaded into the gallery. I'll implement this soon.

### CODE REVIEW

**Review by lstein — APPROVED** [review]
LGTM

**Comment by lstein** [comment]
I'm getting a rebase conflicts notice and will have to address this later today when I'm done a round of coding.

**Comment by timdesrochers** [comment]
>
> @timdesrochers While testing the changes, I was able to maintain connection during a 55-second thread-blocking task.
> 

Awesome! I'll try and test it out this evening

**Comment by psychedelicious** [comment]
@lstein I amended a commit in this branch (changed a timeout number) and had git trouble with that. I may have messed something up. I've made a new branch from development with a single, clean commit: https://github.com/psychedelicious/stable-diffusion/tree/socketio-timeout-2

Maybe that branch will merge cleanly?

**Comment by psychedelicious** [comment]
I have added a number of other related improvements. Closing this PR and making a new one.

**Pull request closed without merging**
