### PR TITLE
Fixes `vite dev` with arbitrary socketio port

### PR DESCRIPTION
**Pull request by psychedelicious**
Supersedes #756 

Previously, the socketio port was hardcoded into the client. This was necessary because, while developing the client, we use a dev server that runs on a different port than the socketio server and so had no way to infer the socketio port.

This PR resolves the issue by:
- changing the `dev` command in `package.json` to use build mode `testing`
- injecting an JS environment variable `VITE_SOCKETIO_PORT` (the socketio port, defined in new file `.env.testing`) if and only if we are in vite build mode `testing`
- using that variable to initialize socketio if said variable exists, else infer the port from the url e.g. javascript `window.location`

For those who use `yarn dev`:
- if they are happy with the standard server port of 9090, no change is needed to what they do
- if they are not happy with port 9090, they can run the server with whatever port they want, but need to edit `.env.local` to match that port they are using

The change should have no effect on the vast majority of users bc they would never run `yarn dev` (or the corresponding npm command).

### CODE REVIEW

**Comment by blessedcoolant** [comment]
Sounds like a plan. @RobertBolender try it out and see if it solves your issue. I'll approve it after.

**Review by RobertBolender — APPROVED** [review]
LGTM 👍

**Comment by psychedelicious** [comment]
Ok, I feel silly - there is a much simpler solution. The vite dev server can proxy the socketio connections. I'll update this PR later.

**Comment by psychedelicious** [comment]
Changes:
- Revert the old solution
- Let the socket.io `port` always be inferred from the URL
- Use vite dev server's built-in proxying, which support socket.io, to proxy socket.io traffic to the flask server. The proxy only is used when running the vite dev server so.

**Review by lstein — APPROVED** [review]
Looks good to me.

**Pull request merged**
