### PR TITLE
feat: Add Gradient Mask Denoising

### PR DESCRIPTION
**Pull request by dunkeroni**
(cherry picked from commit 4131d1e17584a275598d123ddca2beec1c623640)

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [X] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [X] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [ ] Yes
- [X] No (interestingly Create Denoise Mask is not featured in our default nodes doc?)

## Description
Adds a boolean option to the Create Denoise Mask node and the related DenoiseMaskField that will apply an adaptive denoising area based on the mask image value and the timestep when enabled.  
The effect of this is, when a blurred mask is provided, the denoising area will start inside the mask area and expand as the remaining denoising strength decreases, improving edge coherence without requiring a second pass.  

This PR does NOT include adding Gradient as an option to the Canvas Coherence settings. However, I have hacked that together to test and it should be easy enough to implement for someone who knows what they're doing. Simply send the blurred mask with the gradient bool enabled, and skip the coherence pass.

### SDXL Example  
From left to right:  
Standard Mask | Blurred Mask | Blurred Mask with Gradient
image

Original image and mask  
image
image

Workflow:  
[SDXL_Denoise_Comparison.json](https://github.com/invoke-ai/InvokeAI/files/14107419/SDXL_Denoise_Comparison.json)

### SD1 Example
image

Original image  
image

Workflow:  
[SD1_Denoise_Comparison.json](https://github.com/invoke-ai/InvokeAI/files/14107423/SD1_Denoise_Comparison.json)

## Added/updated tests?

- [ ] Yes
- [X] No : Changes are a new optional field. Any existing features relying on denoise mask should not be affected.

## [optional] Are there any post deployment tasks we need to perform?
Integrate to canvas coherence settings in a future PR.

### CODE REVIEW

**Comment by hipsterusername** [comment]
@Millu - May need to update our docs for Denoise Mask (and include updates for this!)

**Comment by hipsterusername** [comment]
@blessedcoolant - Do you want to tackle the UI updates for this, since you handled a lot of the coherence pass stuff?

**Comment by blessedcoolant** [comment]
- Gradient Mask Denoising is now the default on Canvas
- Coherence Pass has been entirely removed. No longer needed.
- Coherence Pass replaced with Mask Settings which allow you to control the Blur Method and Blur Strength for the masks.

Please test on both regular, SDXL and Refiner before merging.

Great job @dunkeroni

**Comment by psychedelicious** [comment]
Daaaaamn. Coherence pass is canceled? Is outpainting/inpainting a single-pass operation now?

**Comment by blessedcoolant** [comment]
> Daaaaamn. Coherence pass is canceled? Is outpainting/inpainting a single-pass operation now?

If all of it works out and the results are satisfactory, then yes.

**Comment by dunkeroni** [comment]
Merged into next branch with PRs #5760 and #5769

**Pull request closed without merging**
