### PR TITLE
Outcropping and other improvements

### PR DESCRIPTION
**Pull request by lstein**
# New outpainting extension called `outcrop`

This extension complements the existing `outpainting` extension by allowing the image to grow larger by the specified amount. You can also grow multiple sides of the image together. For details see [OUTPAINTING](https://github.com/invoke-ai/InvokeAI/blob/outcropping-and-other-improvements/docs/features/OUTPAINTING.md)

Here's a before and after from running `!fix images/curly.png --outcrop top 64 right 64`:

curly 942491079 outcrop-02

# Refactored post-processing code

The face restoration, upscaling, outpainting and outcropping extensions now have a similar call pattern and are located in ldm/dream/restoration/ The `embiggen` extension has not yet been converted to use the new pattern, and more cleanup is desperately needed.

# Postprocessing provenance stored in image metadata.

The series of postprocessing steps are now written into the image metadata as called for in the RFC. However, the RFC doesn't  tell us how to indicate the arguments for each step so for now I'm just stuffing the whole command in there (yuck). However, it does preserve the information needed to reconstruct the image:

~~~
scripts/sd-metadata.py outputs/img-samples/curly.942491079.upscale.png 
outputs/img-samples/curly.942491079.upscale.png:
 {
    "model": "stable diffusion",
    "model_id": "stable-diffusion-1.4",
    "model_hash": "fe4efff1e174c627256e44ec2991ba279b3816e364b49f9be2abc0b3ff3f8556",
    "app_id": "lstein/stable-diffusion",
    "app_version": "v1.15",
    "image": {
        "height": 512,
        "width": 512,
        "steps": 50,
        "cfg_scale": 7.5,
        "seed": 942491079,
        "prompt": [
            {
                "prompt": "pretty curly-haired redhead woman",
                "weight": 1.0
            }
        ],
        "postprocessing": [
            {
                "tool": "outcrop",
                "dream_command": "!fix \"test-pictures/curly.png\" -s 50 -S 942491079 -W 512 -H 512 -C 7.5 -A k_lms -c top 64 right 64"
            },
            {
                "tool": "gfpgan",
                "dream_command": "!fix \"outputs/img-samples/curly.942491079.outcrop-02.png\" -s 50 -S 942491079 -W 512 -H 512 -C 7.5 -A k_lms -G 0.8"
            },
            {
                "tool": "upscale",
                "dream_command": "!fix \"outputs/img-samples/curly.942491079.gfpgan.png\" -s 50 -S 942491079 -W 512 -H 512 -C 7.5 -A k_lms -U 4.0 0.75"
            }
        ],
        "sampler": "k_lms",
        "variations": [],
        "type": "txt2img"
    }
}

~~~

### CODE REVIEW

**Comment by psychedelicious** [comment]
Just wanna say that result is incredible. So it knew it needed to redo the right hand edge but maintained (more-or-less) that side of the subject?

**Comment by psychedelicious** [comment]
> However, the RFC doesn't tell us how to indicate the arguments for each step so for now I'm just stuffing the whole command in there (yuck). 

I am adding a dict to the post processing array for each post processing, format like this:
```python
postprocessing =[
    {
        “type”: “esrgan” | “gfpgan” | “codeformer” | [etc],
        [parameter name]: [parameter value],
        [parameter name]: [parameter value],
        …
    },
    …
]
```

type is the specific type, e.g. esrgan not upscale. 

The parameter values are exactly the same format as the method that takes them wants.

**Comment by lstein** [comment]
Sorry there are so many changed files. This was really a major overhaul...and isn't done yet!

**Comment by ioma8** [comment]
This looks fantastic!

**Comment by ioma8** [comment]
So according to my understanding you can outcrop only images made with SD? So there is no way to add custom image and custom prompt for the outcrop generation from eg. regular photo?

**Comment by ioma8** [comment]
Anyway I have one suggestion. I did outcropping on classic 512x512 SD generated image on left side by 150 pixels. My 32Gb M1 MacBook Pro crashed due to RAM overflow. I understand that generating larger images takes up more memory space. BUT - wouldnt it be good idea to pass to the generator *just* the 512x512 cropped frame overflowing to the side of the outpainted / outcropped side (in case just on side is outcropped)? DALL-E works like this. On their infinite canvas never whole image goes into the generation, but just "generation frame" as they call it. When the generation in the generation frame would be finished, it would be back stitched to the original image, so the final size would be large as it should be. See my sketch for better understanding.
image

**Comment by lstein** [comment]
> Anyway I have one suggestion. I did outcropping on classic 512x512 SD generated image on left side by 150 pixels. My 32Gb M1 MacBook Pro crashed due to RAM overflow. I understand that generating larger images takes up more memory space. BUT - wouldnt it be good idea to pass to the generator _just_ the 512x512 cropped frame overflowing to the side of the outpainted / outcropped side (in case just on side is outcropped)? DALL-E works like this. On their infinite canvas never whole image goes into the generation, but just "generation frame" as they call it. When the generation in the generation frame would be finished, it would be back stitched to the original image, so the final size would be large as it should be. See my sketch for better understanding. image

That's a nice idea. I hadn't thought of it that way.

**Comment by lstein** [comment]
> > However, the RFC doesn't tell us how to indicate the arguments for each step so for now I'm just stuffing the whole command in there (yuck).
> 
> I am adding a dict to the post processing array for each post processing, format like this:
> 
> ```python
> postprocessing =[
>     {
>         “type”: “esrgan” | “gfpgan” | “codeformer” | [etc],
>         [parameter name]: [parameter value],
>         [parameter name]: [parameter value],
>         …
>     },
>     …
> ]
> ```
> 
> type is the specific type, e.g. esrgan not upscale.
> 
> The parameter values are exactly the same format as the method that takes them wants.
> 
> (Written on my phone maybe I got the syntax wrong)

Yeah, I saw that last night when I was playing with the WebGUI. I'll change the output to look like your model.

**Pull request merged**
