### PR TITLE
Add execution stat reporting after each invocation

### PR DESCRIPTION
**Pull request by lstein**
## What type of PR is this? (check all applicable)

- [X] Feature

## Have you discussed this change with the InvokeAI team?
- [X] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [X] Yes
- [ ] No

## Description

This PR adds execution time and VRAM usage reporting to each graph invocation. The log output will look like this:

```
[2023-08-02 18:03:04,507]::[InvokeAI]::INFO --> Graph stats: c7764585-9c68-4d9d-a199-55e8186790f3                                                                                              
[2023-08-02 18:03:04,507]::[InvokeAI]::INFO --> Node                 Calls  Seconds  VRAM Used                                                                                                 
[2023-08-02 18:03:04,507]::[InvokeAI]::INFO --> main_model_loader        1   0.005s     0.01G                                                                                                  
[2023-08-02 18:03:04,508]::[InvokeAI]::INFO --> clip_skip                1   0.004s     0.01G                                                                                                  
[2023-08-02 18:03:04,508]::[InvokeAI]::INFO --> compel                   2   0.512s     0.26G                                                                                                  
[2023-08-02 18:03:04,508]::[InvokeAI]::INFO --> rand_int                 1   0.001s     0.01G                                                                                                  
[2023-08-02 18:03:04,508]::[InvokeAI]::INFO --> range_of_size            1   0.001s     0.01G                                                                                                  
[2023-08-02 18:03:04,508]::[InvokeAI]::INFO --> iterate                  1   0.001s     0.01G                                                                                                  
[2023-08-02 18:03:04,508]::[InvokeAI]::INFO --> metadata_accumulator     1   0.002s     0.01G                                                                                                  
[2023-08-02 18:03:04,508]::[InvokeAI]::INFO --> noise                    1   0.002s     0.01G                                                                                                  
[2023-08-02 18:03:04,508]::[InvokeAI]::INFO --> t2l                      1   3.541s     1.93G                                                                                                  
[2023-08-02 18:03:04,508]::[InvokeAI]::INFO --> l2i                      1   0.679s     0.58G                                                                                                  
[2023-08-02 18:03:04,508]::[InvokeAI]::INFO --> TOTAL GRAPH EXECUTION TIME:  4.749s                                                                                                            
[2023-08-02 18:03:04,508]::[InvokeAI]::INFO --> Current VRAM utilization 0.01G                                                                                                                 
```
On systems without CUDA, the VRAM stats are not printed.

The current implementation keeps track of graph ids separately so will not be confused when several graphs are executing in parallel. It handles exceptions, and it is integrated into the app framework by defining an abstract base class and storing an implementation instance in `InvocationServices`.

### CODE REVIEW

**Review by hipsterusername — APPROVED** [review]
Lgtm. We might consider throwing in the session ID to be able to differentiate if multiple are being run in parallel.

also black test is failing

**Comment by lstein** [comment]
> Lgtm. We might consider throwing in the session ID to be able to differentiate if multiple are being run in parallel.
> 
> also black test is failing

I'm going to keep track of the graph ids so that each graph is reported separately rather than getting mixed. So don't merge yet.

**Comment by lstein** [comment]
> Lgtm. We might consider throwing in the session ID to be able to differentiate if multiple are being run in parallel.
> 
> also black test is failing

This is now done.

**Review by Kyle0654 — APPROVED** [review]

**Comment by psychedelicious** [comment]
This is just too freaking cool! Love it.
image

**Review by psychedelicious — APPROVED** [review]
❤️

**Review by ebr — APPROVED** [review]

**Comment by lstein** [comment]
> This is just too freaking cool! Love it. image

I wonder if it makes sense to sort the nodes chronologically?

**Pull request merged**
