### PR TITLE
Update 050_INSTALLING_MODELS.md

### PR DESCRIPTION
**Pull request by LoganPederson**
Using Windows 10 I found I needed to use double backslashes to import a new model, when using single backslash the output would say "e:_ProjectsCodemodelsldmstable-diffusion-model-to-import.ckpt is neither the path to a .ckpt file nor a diffusers repository id. Can't import." This added tip in the documentation will help Windows users overcome this.

### CODE REVIEW

**Comment by lstein** [comment]
Single forward slashes should work too. Can you confirm that this works?

**Comment by LoganPederson** [comment]
Single forward slashes does indeed work. The default format uses backslashes when dragging and dropping the file to the cli, or copying from file explorer.

**Review by lstein — APPROVED** [review]
Thank you!

**Review by mauwii — APPROVED** [review]
Thank you!

**Pull request merged**
