### PR TITLE
[installation] Update requirements to python 3.10-11

### PR DESCRIPTION
**Pull request by lstein**
## What type of PR is this? (check all applicable)

- [X] Optimization
- [X] Documentation Update

## Have you discussed this change with the InvokeAI team?
- [X] Yes
      
## Have you updated all relevant documentation?
- [X] Yes

## Description

This PR drops python 3.9 support and updates relevant documentation. 3.10-specific features, such as the `match` statement, can now be used.

### CODE REVIEW

**Review by psychedelicious — APPROVED** [review]
Woohoo! I'm not sure how to test this - I guess build the installer and run it? - but the changes look straightforward enough.

**Comment by Millu** [comment]
Similarly, looks good to me! 

I'm a little nervous about the friction this could cause for users currently using Invoke with Python 3.9. We don't really have any good way of communicating with users unless they're reading release notes or the Discord (which if they're just updating from option 9, they're probably not) 

Thinking about it, I'd like to hold off on merging this until 3.3 if possible - we can a announce the deprecation of python 3.9 in the release notes and follow versioning best practice by only releasing a breaking change with a new version

**Review by ebr — APPROVED** [review]

**Comment by lstein** [comment]
> Woohoo! I'm not sure how to test this - I guess build the installer and run it? - but the changes look straightforward enough.

I tested it by trying to do an install from scratch in an environment running Python 3.9. It refused to move forward, as expected.

**Review by hipsterusername — APPROVED** [review]

**Review by psychedelicious — APPROVED** [review]
Because 3.9 is still widely used and may be required for users' other apps, we may want to suggest something like `pyenv` as a way to have multiple python versions installed. 

A user recently linked me to this article, which has nice instructions for all platforms: https://www.k0nze.dev/posts/install-pyenv-venv-vscode/

**Pull request merged**
