### PR TITLE
Web UI: Adds initial inpainting implementation

### PR DESCRIPTION
**Pull request by psychedelicious**
## Inpainting 

Adds an initial inpainting UI.

A lot of work has gone into making inpainting smooth and usable, both on the UI and backend. This includes the awesome internal inpainting improvements in #1218 and #1221.

### Features
- In-browser mask painting
- Mask color / opacity (to help you see the mask - doesn't add color to the image)
- Unlimited undo/redo
- Mask persists reloads
- Standard-ish image editor keyboard shortcuts
- Bounding box to inpaint only in certain areas (remember SD does best with images around 512x512 - you'll want to keep your bounding box close to that size)

### Other changes in this PR
- Gallery: floating mode, resizable thumbnails, option to maintain aspect ratio, performance boost, context menu on thumbnails
- Many UI bug fixes and styling improvements
- Number sliders - I know it's a simple thing to add and is so much easier to use than number inputs. Sorry its taken so long to start adding these, we will be using sliders where it feels right.
- Codeformer is supported (was an earlier PR but in case you missed it, it's here)

## Try it out
- Right click an image in the gallery to send it to Inpainting, or click the Paintbrush icon above the main image display
- There are a lot of hotkeys - most are on the buttons' tooltips  
- One isn't listed anywhere and is important: hold spacebar with cursor over the image editor to move the bounding box around

### Troubleshooting

This is a major update with many changes(a few thousand lines of code), so on the first run, you may need to:
- Use Reset Web UI in Settings (top right gear icon)
- Update your environment, e.g. `conda env update -f environment.yml` (`conda env update -f environment-mac.yml` for macOS)

It is possible that the app will totally break and not load the first time you open it. If that happens, use your browser's dev tools to reset the app's local storage.

## Next steps
A lot of hard work has gone into this feature, we are pretty happy with it so far. Please try this out and let us know how it goes, what works well, what doesn't, what else we can add. 

### TODO

- [x] Fix image gallery aspect ratio preference not persisting. 
- [x] Fully updated hotkeys + categorization
- [x] Move inpaint replace higher up .. because it is a proper option and fix the switch stylling so it doesnt cut off 
- [x] Add disable conditions for the reset buttons on bounding box sliders.
- [x] Right click image in gallery > gallery disappears
- [x] moving bounding box is ending when the mouse cursor goes outside the canvas ... this is when holding space ... needs to stay on until space is held
- [x] Alt still switches brush on alt tab and other alt actions (switched to z for brush toggle, shift for modifier hotkeys)
- [x] 2. If I hold spacebar and try to move box, while coursor is hovering handles, the box lost it's focus 
- [x] bug: painting over the box handles stops any painting in progress
- [x] Delete image hover button needs to hide when gallery image size is small
- [x] Adds auto-switch toggle to gallery
- [x] Inpainting drag and drop
- [x] Brush strokes do not composite correctly on first load of canvas
- [x] if you drag outside of the image boundary the brush stops depositing mask-paint - this is very noticeable when the brush size is larger - **should be fixed**
- [x] Gallery layout when pinned
- [ ] When no image in inpainting, default to txt2img? Img2prompt?
- [ ] Canvas editor lag in Safari - cause unclear, sometimes clearing brush history fixes it, sometimes triggered by moving the bounding box or using a hotkey... maybe event listener related...
- [ ] 3. No need in width/height settings, they are disabled. Maybe it's better to replace them with "inpaint box" ones. Or change behavior to box size changing. 
- [ ] 4. Box size smaller than 512 can't generate anything meaningful, we can limit it (alert user?)
- [ ] Cancel button shows pending cancel operation

### CODE REVIEW

**Comment by psychedelicious** [comment]
Brief demo (without generation - but that does work!):
https://user-images.githubusercontent.com/4822129/197396623-0e4ce64c-1f3c-48e5-abce-5517c7846155.mov

**Comment by psychedelicious** [comment]
I've done a bit of polishing, improved performance and fixed a few issues. Appreciate feedback or suggestions. 

The only big thing that is missing is the side-by-side image display - but I've run out of steam for today and will work on that later.

**Comment by DavidBates** [comment]
Everything works for me up until I hit "Invoke" in the gui, painting, erasing, inverting. all smooth. Once I hit Invoke I get the following: 
```
>> using provided input image of size 2048x2048
>> image will be resized to fit inside a box 2048x2048 in size.
>> after adjusting image dimensions to be multiples of 64, init image is 2048x2048
>> Using recommended DDIM sampler for inpainting.
/AppleInternal/Library/BuildRoots/a0876c02-1788-11ed-b9c4-96898e02b808/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:705: failed assertion `[MPSTemporaryNDArray initWithDevice:descriptor:] Error: product of dimension sizes > 2**31'
```
Restarting the backend works but hitting invoke kills it again. 
M1 Max Mac, OSX 12.6

**Comment by psychedelicious** [comment]
@DavidBates Your input image is 2048x2048 pixels - that's very large. Currently, inpainting re-processes the whole image, so it's basically trying to do img2img on a 2048x2048px image. 

A future update will provide a unified inpainting and outpainting editor which lets you do inpainting in a given bounding box. This way you can load a large input image, then do inpainting on a small area of it.

**Comment by DavidBates** [comment]
@psychedelicious can confirm that the default image size works perfectly. Thank you.

**Comment by SieR-VR** [comment]
Comment review due his request;
Very good! There's lots of features I've lost. 

And some feedback:
- Ctrl + drag toward horizontally to change brush size
- Store brush size for each (brush, eraser)

**Comment by psychedelicious** [comment]
> Comment review due his request; Very good! There's lots of features I've lost.
> 
> And some feedback:
> 
>     * Ctrl + drag toward horizontally to change brush size
> 
>     * Store brush size for each (brush, eraser)

@SieR-VR , we have been working on other parts of this but I still want to add your suggestions. Just to let you know.

I have added a bounding box; now you can select a part of the image to inpaint. At this point, I think it is not much work to expand the inpainting canvas and also handle outpainting, but I am concerned that much of the work you have done will not be utilized.

Can we collaborate on the outpainting, working from this PR? This PR is already fairly well-tested and integrated with the rest of the application. Would be great to build on this because we feel it is pretty solid.

**Comment by psychedelicious** [comment]
This PR includes the latest color correction code.

I thought I had broken something and ended up doing a soft reset to development, bye commit history. Oh well.

**Comment by netsvetaev** [comment]
Get an error

```
sh /Users/artur/Downloads/install.sh 
Installing InvokeAI..

Initialized empty Git repository in /Users/artur/.git/
remote: Enumerating objects: 10352, done.
remote: Counting objects: 100% (348/348), done.
remote: Compressing objects: 100% (171/171), done.
remote: Total 10352 (delta 185), reused 282 (delta 148), pack-reused 10004
Receiving objects: 100% (10352/10352), 85.80 MiB | 3.16 MiB/s, done.
Resolving deltas: 100% (6732/6732), done.
From https://github.com/cmdr2/InvokeAI
 * [new branch]      Any-Winter-4079-Any-Winter-4079-Textual_Inversion -> origin/Any-Winter-4079-Any-Winter-4079-Textual_Inversion
 * [new branch]      backend-processor-schema -> origin/backend-processor-schema
 * [new branch]      development             -> origin/development
 * [new branch]      development-invoke      -> origin/development-invoke
 * [new branch]      gh-pages                -> origin/gh-pages
 * [new branch]      img2img-on-all-samplers -> origin/img2img-on-all-samplers
 * [new branch]      inpainting-improvement  -> origin/inpainting-improvement
 * [new branch]      installation-directory  -> origin/installation-directory
 * [new branch]      invoke-development      -> origin/invoke-development
 * [new branch]      invoker-framework       -> origin/invoker-framework
 * [new branch]      main                    -> origin/main
 * [new branch]      model-switching         -> origin/model-switching
 * [new branch]      release-candidate-2     -> origin/release-candidate-2
 * [new tag]         2.0.0-rc1                -> 2.0.0-rc1
 * [new tag]         2.0.0-rc2                -> 2.0.0-rc2
 * [new tag]         2.0.0-rc3                -> 2.0.0-rc3
 * [new tag]         2.0.0-rc4                -> 2.0.0-rc4
 * [new tag]         2.0.0-rc5                -> 2.0.0-rc5
 * [new tag]         2.0.0-rc6                -> 2.0.0-rc6
 * [new tag]         2.0.0-rc7                -> 2.0.0-rc7
 * [new tag]         2.0.0-rc8                -> 2.0.0-rc8
 * [new tag]         release-0.95             -> release-0.95
 * [new tag]         release-1.02             -> release-1.02
 * [new tag]         release-1.03             -> release-1.03
 * [new tag]         release-1.04             -> release-1.04
 * [new tag]         release-1.05             -> release-1.05
 * [new tag]         release-1.06             -> release-1.06
 * [new tag]         release-1.07             -> release-1.07
 * [new tag]         release-1.08             -> release-1.08
 * [new tag]         release-1.09             -> release-1.09
 * [new tag]         release-1.10             -> release-1.10
 * [new tag]         release-1.11             -> release-1.11
 * [new tag]         release-1.13             -> release-1.13
 * [new tag]         release-1.14             -> release-1.14
 * [new tag]         release-1.14.1           -> release-1.14.1
 * [new tag]         release-2.0.0            -> release-2.0.0
 * [new tag]         release-candidate-1.14   -> release-candidate-1.14
 * [new tag]         release-candidate-1.14.1 -> release-candidate-1.14.1
 * [new tag]         release-candidate-1.14.2 -> release-candidate-1.14.2
 * [new tag]         release-candidate-1.14.3 -> release-candidate-1.14.3
 * [new tag]         release-candidate-1.14.4 -> release-candidate-1.14.4
 * [new tag]         release_0.91             -> release_0.91
 * [new tag]         release_0.96             -> release_0.96
 * [new tag]         release_1.0              -> release_1.0
 * [new tag]         release_1.01             -> release_1.01
 * [new tag]         show                     -> show
 * [new tag]         v2.0.0                   -> v2.0.0
 * [new tag]         version_0.9              -> version_0.9
Branch 'main' set up to track remote branch 'main' from 'origin'.
Switched to a new branch 'main'

CondaValueError: prefix already exists: /Users/artur/miniconda3/envs/invokeai

Traceback (most recent call last):
  File "/Users/artur/scripts/preload_models.py", line 6, in <module>
    from transformers import CLIPTokenizer, CLIPTextModel
ModuleNotFoundError: No module named 'transformers'

Now you need to install the weights for the stable diffusion model.
Please follow the steps at https://invoke-ai.github.io/InvokeAI/installation/INSTALL_MAC/ to complete the installation
```

**Comment by lstein** [comment]
Is this PR ready for review? It is still marked "draft".

**Comment by psychedelicious** [comment]
> Is this PR ready for review? It is still marked "draft".

Good question. I have a list of fixes to resolve before merging, but it is certainly in a reviewable state. 

One major WIP:
- It is not clear how to get an image into inpaint (right click image from gallery), and we need to add support for uploading an image. 

I think I can address all of the issues today.

**Comment by psychedelicious** [comment]
Added more complete todo list to first post in the thread.

**Comment by lstein** [comment]
I just took the inpainting out for a spin and it works great. If you haven't already you should try launching with the runway inpaint model. You get wonderful control because if the mask isn't perfect the model will fix the regions you painted over inadvertently.

So here is my wish list for improvements:

1. Provide a way to upload an initial image directly into inpainting, or at least to pass the init image from the img2img panel into the inpainting panel.
2. Start the inpainting panel in the split view, or have some sort of preview icon system that clues the user that the split view is available. I spent a minute or so trying to figure out where my inpainted generations were going.
3. Double-click the eraser to clear the mask.
4. The "invert mask" option only changes the way the mask is displayed. Instead (or in addition) there should be an actual invert mask operation. This would let me toggle between inpainting into the foreground or into the background.

Boy, I wish we had the outpainting (or at least outcropping) support in the WebGUI, but I'm greedy. This will be great for the 2.1 release.

**Comment by Fortyseven** [comment]
Pulled this down, first thing I poked at was the gallery -- I made the size it's smallest and accidentally clicked the trashcan since it's almost half the size of the thumbnail, and lost a pic (on me for disabling confirmation  :wink:).

image

Not sure what to suggest, but figured it'd be worth mentioning.

**Comment by psychedelicious** [comment]
> Pulled this down, first thing I poked at was the gallery -- I made the size it's smallest and accidentally clicked the trashcan since it's almost half the size of the thumbnail, and lost a pic (on me for disabling confirmation  :wink:).
> 
> 
> 
> image
> 
> 
> 
> Not sure what to suggest, but figured it'd be worth mentioning.

Should be in your recycle bin

**Comment by Fortyseven** [comment]
I was about to snark about not being on Windows, but I'm an idiot -- I _do_ have a Trash metaphor in Ubuntu that I've largely ignored (thought I'd disabled it, honestly). I had no idea they were all stacking up over there. *Good to know!* :grin:

**Comment by JakeHL** [comment]
I've noticed you made a lot changes to the gallery list with some extra settings. I made [this pr](https://github.com/invoke-ai/InvokeAI/pull/1272) against develop yesterday that adds a toggle to automatically select newly generated images or not. Based on your changes here I'll delete the PR, would it be possible for you to add this setting in the new settings UI that you have added? It's a really small fix and increases quality of life with the tool tenfold in my opinion.

**Comment by psychedelicious** [comment]
@JakeHL No worries at all! I've implemented the feature in this PR.

**Comment by JakeHL** [comment]
I've just found a bug(?) on this branch after pulling a few minutes ago where you can't cancel invocations. I think it's new as I pulled yesterday and didn't experience it.

**Comment by psychedelicious** [comment]
> Edit: this happens after changing the model. Resetting the UI fixes the problem. It looks like setIsCancelable(false) is called when the model change request is emitted but not set back once it has completed.

It should be set back when the model change finishes. I made some changes, should be good now.

Image upload + user upload gallery is implemented, also UI model switching.

The last thing to do is figure out a few styling things - some buttons are really crowded.

**Comment by psychedelicious** [comment]
Ready for review!

**Comment by psychedelicious** [comment]
Improved file uploading UI. Now supports:
- drag and drop anywhere onto app
- click the big grey button if no initial image is set
- paste images directly into work area #1286 @Fortyseven thanks for the request

How it works
- Uploaded images always go to the User tab in gallery
- Dropping/pasting an image adds it as the current working image for that tab, e.g. 
  - txt2img it's set as the current image
  - img2img it's put on the left as init image
  - inpainting it's loaded onto the canvas
- Only one image at a time

Also a host of small bug fixes and tweaks.

I ran into a nasty FF bug while testing this. I was trying to paste non-image files (like a .zip, .mov, .txt) to test error handling, but FF kept reporting the mimetype or whatever it is as `image/png`. Chromium and the OS pasted the image correctly, and a clipboard viewer showed tthe correct thing. So FF was caching my clipboard somehow... gross!

**Review by blessedcoolant — APPROVED** [review]

**Comment by blessedcoolant** [comment]
Good to go. Approved.

**Review by lstein — APPROVED** [review]
Great work! I will start merging now. I'm afraid there are some conflicts.

**Comment by lstein** [comment]
It's merged. I wasn't able to rebase due to too many conflicts, so it's a 3-way merge. Apologies to @tildebyte !

**Comment by tildebyte** [comment]
Ouch, those are the worst. I feel your pain :D

**Pull request merged**
