### PR TITLE
ui: api cleanup

### PR DESCRIPTION
**Pull request by psychedelicious**
*migrate from `openapi-typescript-codegen` to `openapi-typescript` and `openapi-fetch`*

`openapi-typescript-codegen` is not very actively maintained - it's been over a year since the last update.
`openapi-typescript` and `openapi-fetch` are part of the actively maintained repo. key differences:

- provides a `fetch` client instead of `axios`, which means we need to be a bit more verbose with typing thunks
- fetch client is created at runtime and has a very nice typescript DX
- generates a single file with all types in it, from which we then extract individual types. i don't like how verbose this is, but i do like how it is more explicit.
- removed npm api generation scripts - now we have a single `typegen` script

overall i have more confidence in this new library.

*use nanostores for api base and token*

very simple reactive store for api base url and token. this was suggested in the `openapi-fetch` docs and i quite like the strategy.

*organise rtk-query api*

split out each endpoint (models, images, boards, boardImages) into their own api extensions. tidy!

### CODE REVIEW

**Comment by psychedelicious** [comment]
also this fixes the issue where resetting init/control image do not clear them correctly.

**Comment by psychedelicious** [comment]
@maryhipp Appreciate if you can double-check that this is working on commercial

**Review by blessedcoolant — APPROVED** [review]

**Comment by maryhipp** [comment]
Testing notes:
* (oss back-end) saving canvas generation from bottom toolbar doesn't seem to be working/making network request
* when I load my front-end seems to be making a request with two intermediate query params `http://localhost:5173/api/v1/images/?isIntermediate=false&limit=20&offset=0&categories=general&is_intermediate=false` (this is against commercial back-end but could have been happening with OSS and i didn't notice - doesn't seem to impact network call)
* I see a token in socket connection and some http requests, but not in:
  *  the initial GET /images request (so getting 401)
  * the session creation
  * probably more....will add here

**Comment by maryhipp** [comment]
I have no idea why the api requests using the $client are not working (baseURL and headers are not being applied) -  I found the docs and agree that it should be so am a bit stumped

**Comment by psychedelicious** [comment]
@maryhipp 
Ahhh it's clear why the `$client` requests don't work - only the `$client` is reactive, not the destructured properties of it. I saw noticed this in the example and confused but I assumed the `nanostores` library did some proxy or reactivity magic. This is not the case.

I've updated the thunks to retrieve the client in each thunk, to ensure the `baseUrl` and `authToken` are always used.

**Comment by psychedelicious** [comment]
[fix(ui): fix incorrect boards endpoint matchers being used](https://github.com/invoke-ai/InvokeAI/pull/3572/commits/f2445c613f3ad9019644c26a84c69cbbe59f7fb7)
[f2445c6](https://github.com/invoke-ai/InvokeAI/pull/3572/commits/f2445c613f3ad9019644c26a84c69cbbe59f7fb7)

Should fix some stale-data issues with the auto-adding of images to selected boards, and deleting images from boards.

[fix(nodes): fix LatentsToImage not using is_intermediate when creat…](https://github.com/invoke-ai/InvokeAI/pull/3572/commits/f232c76bf8bc861a8380f0786df70723719accf2)
[f232c76](https://github.com/invoke-ai/InvokeAI/pull/3572/commits/f232c76bf8bc861a8380f0786df70723719accf2)

…ing images

[fix(ui): fix canvas staging area](https://github.com/invoke-ai/InvokeAI/pull/3572/commits/8a77c1b19e06a0e5c8cb99de75e6c7a2f20ffecc)
[8a77c1b](https://github.com/invoke-ai/InvokeAI/pull/3572/commits/8a77c1b19e06a0e5c8cb99de75e6c7a2f20ffecc)

Missed some of the `imageUpdated` stuff

[fix(ui): fix duplicate is_intermediate query param when fetching im…](https://github.com/invoke-ai/InvokeAI/pull/3572/commits/d98bce2894bf6f378673e03a3f1c5113b3336c73)
[d98bce2](https://github.com/invoke-ai/InvokeAI/pull/3572/commits/d98bce2894bf6f378673e03a3f1c5113b3336c73)

…ages

**Pull request merged**
