### PR TITLE
Optional refined model for Txt2Mask

### PR DESCRIPTION
**Pull request by spezialspezial**
Don't merge right now, just wanted to show the necessary changes

### CODE REVIEW

**Comment by spezialspezial** [comment]
refined

**Comment by lstein** [comment]
That looks very good. I obviously haven't played with this at all and won't have time for a few days.  Are there any downsides to using the refined model?

**Comment by spezialspezial** [comment]
Not sure yet. I have put it in on my side and will report back if I notice something

**Comment by lstein** [comment]
Merged from command line. Nice work!

**Pull request merged**
