### PR TITLE
Remove Inpaint Replace

### PR DESCRIPTION
**Pull request by hipsterusername**
This removes the inpaint replace feature, which has been deprecated as part of diffusers work.

### CODE REVIEW

**Comment by hipsterusername** [comment]
@keturn @blessedcoolant - Not sure if there's anything else beyond the front-end files that needs to be removed for inpaint replace, or if already done as part of the diffusers migration

**Comment by blessedcoolant** [comment]
I cannot test the PR yet given my flooding situation but if the idea is to remove the feature from the front end, I think everything is covered.

However, you don't manually remove it from the dist folder. You remove it from the public/locales and it will automatically get ported over to the dist folder when you build it.

So you'll need to make that change. Do a build so the changes are reflected and ported over to dist.

**Comment by hipsterusername** [comment]
Aye! I went ahead and did a yarn build, but not sure that it made the changes - is there a different/specific build process for the locales files? Given they'll get carried forward in the next build (even if mine somehow didn't catch them), and they're not going to impact anything negatively, I'm inclined to let that take care of it.

**Comment by blessedcoolant** [comment]
> Aye! I went ahead and did a yarn build, but not sure that it made the changes - is there a different/specific build process for the locales files? Given they'll get carried forward in the next build (even if mine somehow didn't catch them), and they're not going to impact anything negatively, I'm inclined to let that take care of it.

No just a regular yarn build should do it. The reason they probably didn't get ported over in your build because you already made those change manually.

Rest of it seems good to me code wise at least. If someone else can run once and check if all works as intended, I can approve it. 

If you tested it and works fine , let me know. I can approve it now. Code seems fine.

**Comment by hipsterusername** [comment]
I ran it - Inpaint replace wasn't there. That's about all I'd expect!

**Comment by blessedcoolant** [comment]
Not passing the value should effectively disable it from the generation process but if it's being cleaned up, we should also probably remove it from the backend. 

Tagging @lstein as I believe he was the one who wrote the initial Inpaint Replace code. If he wants to remove from the backend too .. unless it's already been removed, then he can add to this PR otherwise it's good to go.

**Comment by psychedelicious** [comment]
May I ask why it is no longer needed with diffusers?

**Comment by keturn** [comment]
> If he wants to remove from the backend too .. unless it's already been removed, then he can add to this PR otherwise it's good to go.

It's "removed" in the sense that I neglected to include it in the new implementation.

**Comment by hipsterusername** [comment]
> May I ask why it is no longer needed with diffusers?

After extensive testing, we determined that increasing Img2img to 1 effectively was doing the same as Inpaint Replace On + High Strength Img2img. There were seemingly no cases where mid-range settings on inpaint replace actually produced any kind of meaningfully coherent output, and the implementation was simplified from both a code and user perspective by relying on Img2Img = 1 in situations where user wants to completely ignore the original RGB.

**Comment by lstein** [comment]
> > May I ask why it is no longer needed with diffusers?
> 
> After extensive testing, we determined that increasing Img2img to 1 effectively was doing the same as Inpaint Replace On + High Strength Img2img. There were seemingly no cases where mid-range settings on inpaint replace actually produced any kind of meaningfully coherent output, and the implementation was simplified from both a code and user perspective by relying on Img2Img = 1 in situations where user wants to completely ignore the original RGB.

The backend inpaint replace code is still in the deprecated `ckpt_*` folder tree. If I get around to it, I will remove that code, but eventually all the ckpt handling code will be removed.

**Review by lstein — APPROVED** [review]
Remove away!

**Review by psychedelicious — APPROVED** [review]
Tested, all good!

**Comment by blessedcoolant** [comment]
Seems good. Merging it.

**Pull request merged**
