### PR TITLE
Remove fastapi-socketio dependency, doesn't really do much for us and…

### PR DESCRIPTION
**Pull request by brandonrising**
… isn't well maintained

## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [x] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [x] Yes
- [ ] No

## Related Tickets & Documents

- Related Issue #
- Closes #

## Added/updated tests?

- [ ] Yes
- [ ] No : _please replace this line with details on why tests
      have not been included_

### CODE REVIEW

**Comment by brandonrising** [comment]
https://github.com/pyropy/fastapi-socketio/blob/master/fastapi_socketio/socket_manager.py

For reference on what this dependency was doing for us and how much it's being maintained

**Comment by brandonrising** [comment]
This pip module reminds me of this https://qz.com/646467/how-one-programmer-broke-the-internet-by-deleting-a-tiny-piece-of-code

**Comment by hipsterusername** [comment]
Wow, talk about middle-man.

**Review by psychedelicious — APPROVED** [review]
Nice, tested working. Even better IDE hints with this, and I'm glad we've moved to using the standard ASGI convention.

**Review by blessedcoolant — APPROVED** [review]

**Pull request merged**
