### PR TITLE
Web UI 2.2 bugfixes

### PR DESCRIPTION
**Pull request by psychedelicious**
Web UI 2.2 bugfixes

### CODE REVIEW

**Comment by mickr777** [comment]
I am also getting on linux:
local variable 'init_img_path' referenced before assignment
Traceback (most recent call last):
  File "/InvokeAI/backend/invoke_ai_web_server.py", line 574, in generate_images
    original_image = Image.open(init_img_path)
UnboundLocalError: local variable 'init_img_path' referenced before assignment

**Comment by AshtakaOOf** [comment]
Is this only for bugfixes, or you could add batch size too?

**Comment by mickr777** [comment]
@psychedelicious 
just a random bug, I cant seem to find the steps that cause it as it so random.

but moving and zooming canvas, resizing the bounding box with mouse randomly stops working.
after this happens I can click to brush tool and and back to move tool and it all works again

**Comment by psychedelicious** [comment]
@AshtakaOOf 
> Is this only for bugfixes, or you could add batch size too?

We will add bug fixes only on this PR.

**Comment by psychedelicious** [comment]
@mickr777 

I've noticed this occasionally also. Will investigate.

**Comment by Fortyseven** [comment]
Looks like the brush will become invisible _inside_ the selection bounds if "darken outside selection" is enabled. 

image

**Comment by mickr777** [comment]
@psychedelicious 
FYI from commit 7c658c6 in development this is happing the model list 
(Thought I would mention here since it effects the webui)
image
image

**Review by hipsterusername — APPROVED** [review]

**Review by netsvetaev — APPROVED** [review]

**Review by blessedcoolant — APPROVED** [review]

**Review by blessedcoolant — APPROVED** [review]

**Review by blessedcoolant — APPROVED** [review]

**Review by lstein — APPROVED** [review]
Lots of typescript to review! I didn't see any obvious problems.

**Review by blessedcoolant — APPROVED** [review]

**Review by hipsterusername — APPROVED** [review]

**Pull request merged**
