### PR TITLE
Web Docs Update

### PR DESCRIPTION
**Pull request by hipsterusername**
Included some documentation for the Web docs.

I think we likely need to revisit documentation for the project broadly, but beyond the scope of getting 2.0 release out the door.

### CODE REVIEW

**Comment by hipsterusername** [comment]
@blessedcoolant

**Comment by blessedcoolant** [comment]
Hey seems good for most part. Sorry for the trouble but I made a last minute change. I replaced the Invoke button from the camera icon to a Invoke text button. Maybe you could update that change? Thanks.

**Comment by hipsterusername** [comment]
@blessedcoolant - No worries, updated!

**Comment by blessedcoolant** [comment]
The images will need updating coz the icon is no longer the camera.

**Comment by hipsterusername** [comment]
`Invoke` is the new black.

**Comment by hipsterusername** [comment]
@blessedcoolant - Final.

**Comment by blessedcoolant** [comment]
Only 1 update is updated?

**Comment by hipsterusername** [comment]
weird - reuploading

**Review by blessedcoolant — APPROVED** [review]

**Pull request merged**
