### PR TITLE
Global replace [ \t]+$, add "GB"

### PR DESCRIPTION
**Pull request by thinkyhead**
- Strip all trailing whitespace from text files.
- Add missing "GB" designation on download size.

### CODE REVIEW

**Comment by lstein** [comment]
I would be more comfortable with this PR if it weren't also changing a bunch of .py and .js files. We'll have to do some extended testing on this to make sure that there wasn't a whitespace change that inadvertently broke something.

**Comment by thinkyhead** [comment]
Trailing whitespace removal is 100% safe and will have zero effect on the code. You'll notice that the regex ends in a `$` which guarantees that it only replaces trailing whitespace. I do this regex replace all the time in the project I maintain, in that case with a mix of Python, C++, Javascript, shell scripts, etc. all in the same project, and it's just fine. Scan through the changes in the files tab above and you will see that all the changes are perfectly safe.

**Comment by thinkyhead** [comment]
Did a quick rebase on `main` and rechecked to make sure no non-text files were affected, and no "patch" files were affected.

**Review by mauwii — APPROVED** [review]
Generated some images via web and looked over the docs, seems to be fine.

**Review by lstein — APPROVED** [review]
Thank you!

**Pull request merged**
