### PR TITLE
Re-add feat/mix cnet t2iadapter

### PR DESCRIPTION
**Pull request by hipsterusername**
Reverts invoke-ai/InvokeAI#4923, which was a revert on the premature merge. 

slide to the left. revert, revert.

### CODE REVIEW

**Comment by psychedelicious** [comment]
This should wait for the diffusers release right?

**Comment by hipsterusername** [comment]
Yes, indeed, didn't note - Just keeping this PR live for then.

**Comment by psychedelicious** [comment]
draft to prevent accidental merge

**Comment by hipsterusername** [comment]
Diffusers release is anticipated for monday. @Millu - Let's make sure to get this merged into 3.4 once that update is made and we get dependencies updated.

**Comment by hipsterusername** [comment]
@psychedelicious - we can pretty much just disregard conflict right? will get regenerated

**Comment by hipsterusername** [comment]
@psychedelicious Can you approve? Counting me as PR author here lol

**Review by psychedelicious — APPROVED** [review]

**Review by GreggHelt2 — APPROVED** [review]
Yay, the required diffusers update just got released!
LGTM

**Pull request merged**
