### PR TITLE
fix: offload the depth_anything models correctly

### PR DESCRIPTION
**Pull request by blessedcoolant**
## What type of PR is this? (check all applicable)

- [x] Optimization

## Description

- Offloads the depth anything models correctly. Not a big deal for the small size but might be nice for lower end PC's trying to load the larger model.

### CODE REVIEW

**Comment by psychedelicious** [comment]
Why does this node have an offload field?

**Comment by blessedcoolant** [comment]
> Why does this node have an offload field?

To offload the depth anything model. Is there another way to handle this? I wasn't sure so did it this way.

**Comment by psychedelicious** [comment]
> To offload the depth anything model. Is there another way to handle this? I wasn't sure so did it this way.

I don't think the user has any business deciding whether or not the model should be offloaded - that should be up to the model manager (or just always happen, if the model manager doesn't handle it).

**Comment by blessedcoolant** [comment]
> > To offload the depth anything model. Is there another way to handle this? I wasn't sure so did it this way.
> 
> I don't think the user has any business deciding whether or not the model should be offloaded - that should be up to the model manager (or just always happen, if the model manager doesn't handle it).

If it offloads each time, it becomes problematic for larger models. For example, I made the Meshgraphormer node today. That has a considerably larger model that takes time to initialize. If I don't manually keep it in memory, it will run each time I press invoke and that's numerous seconds wasted.

**Comment by psychedelicious** [comment]
I understand that's a problem but still, whether or not to offload a model isn't something that should be on a node.

How is this handled in the linear UI? Is there an extra switch to toggle the offloading?

**Comment by hipsterusername** [comment]
Agree - the model should be managed exclusively by the model mgr. What problem are we solving here that can’t be solved by the model mgr?

**Comment by blessedcoolant** [comment]
> Agree - the model should be managed exclusively by the model mgr. What problem are we solving here that can’t be solved by the model mgr?

The problem of me not knowing how to do it with the model manager. I was hoping Lincoln or someone could take a look at that in the previous PR but they said it was okay. But I somehow still felt that it wasn't doing what it was meant to do. Maybe someone can take another jab at it? Or at least point me in the right direction. I might figure out if I spend time on it but I cannot find a straightforward example.

**Comment by psychedelicious** [comment]
Unfortunately, the controlnet processors' models are not handled by the model manager. In fact, we have the same issue with the other processor models - they are all loaded directly via diffusers and not cleaned up manually.

Can you please try something @blessedcoolant - on `main` (not this PR), in `dependencies.py`, change the `ItemStorageMemory` to have a max size of 1:
```py
        graph_execution_manager = ItemStorageMemory[GraphExecutionState](max_items=1)
```

Then disable the manual offloading for this node and do a few generations.

Does the model free vram automatically when you do this?

If you do this, then the gc should be able to do its thing automatically. With max_size > 1, the old session will still be in memory, and the model will still be referenced and not gc'd. The change in this PR moves the model class to the global scope, which then requires you to manually gc it bc it always has a ref.

---

Side-note: `offload` may not be the right term here, we use in the app to mean "move the model from VRAM to RAM", but here it's just freeing the memory.

**Comment by hipsterusername** [comment]
@blessedcoolant - Any thoughts here? Should we port this to next?

**Comment by psychedelicious** [comment]
This is a general issue that needs backend MM changes. Nodes shouldn't be responsible for managing models.

**Comment by blessedcoolant** [comment]
Like @psychedelicious said, should be handled my MM. So I guess no.

**Pull request closed without merging**
