### PR TITLE
remove debug branch, set fail-fast to false

### PR DESCRIPTION
**Pull request by mauwii**
to find out if only mac or ubuntu is broken
(otherwise if one fails the otherone automatically cancels)

### CODE REVIEW

**Comment by mauwii** [comment]
@tildebyte @lstein did you delete your SD_V1_4_URL secret?

**Review by lstein — APPROVED** [review]
Ironically I'm attending a talk on building GitHub CI tests right now.

**Comment by mauwii** [comment]
If yes, I would suggest that I change the action to use a secret named `HUGGINGFACE_TOKEN` instead of `SD_V1_4_URL`, which would make it easier for others to add the secret as well as maintaining the URL which should be used to download.

**Comment by lstein** [comment]
I haven't touched the secret since I created it. I'm not up on how the CI
system actually works, but if you tell me what buttons to click and knobs
to turn, I'll do it.

Lincoln

**Comment by mauwii** [comment]
updated instructions in current PR #1285

**Pull request merged**
