### PR TITLE
Added French Locale

### PR DESCRIPTION
**Pull request by ParisNeo**
I have upgraded all the fr.json files to include the French translations.
I hope this can make it to the next version.
If you have some remarks feel free to tell me.

I'm glad to participate.

### CODE REVIEW

**Comment by blessedcoolant** [comment]
A few changes are needed.

1. The should go inside public/locales and not dist/locales. The dist folder gets built automatically when the frontend is built.
2. Is French already implemented? If not, I'll implement it after you make the above changes.

Thanks for the PR.

**Comment by ParisNeo** [comment]
Thank you for the information.
I noticied that there are fr.json files but didn't find it in the UI when I've installed it.

That's why I decided to add it.
I'll make the necessary changes.

**Comment by ParisNeo** [comment]
I have changed the public/locale fr.json files
I have squashed all my changes to a single  commit.
Sorry I have inadvertedly closed the pull request, then I've reopened it.

Is there a development documentation for the front end? I have few Ideas that I'm going to bring to my fork and I'll be doing pull requests to the invokeai repo if you want to integrate them in the main project.

**Comment by blessedcoolant** [comment]
> I have changed the public/locale fr.json files I have squashed all my changes to a single commit. Sorry I have inadvertedly closed the pull request, then I've reopened it.

No worries. Thanks for making the changes.

I added French to the language picker. Approved. Should get merged when the changes pass.

> Is there a development documentation for the front end? I have few Ideas that I'm going to bring to my fork and I'll be doing pull requests to the invokeai repo if you want to integrate them in the main project.

Hit us up on discord on dev-chat. If you aren't on it, let me know your discord, i'll give you access. We can discuss what features you want to add and go ahead accordingly. Thanks for your interest and contribution.

**Review by blessedcoolant — APPROVED** [review]

**Comment by ParisNeo** [comment]
OK, I've logged to the discord server. My discord pseudonyme is:
SpaceNerduino#8152

**Comment by blessedcoolant** [comment]
> OK, I've logged to the discord server. My discord pseudonyme is: SpaceNerduino#8152

Added you as a Github Contributor. That should let you access dev-chat.

**Pull request merged**
