### PR TITLE
Add empty_cache() for MPS hardware

### PR DESCRIPTION
**Pull request by gogurtenjoyer**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [ ] Yes
- [x] No, because: small change, has been discussed loosely

      
## Have you updated all relevant documentation?
- [x] Yes (n/a)
- [ ] No

## Description
Pytorch has added an `empty_cache()` method for MPS, just as it has had for CUDA. This PR adds a `mps.empty_cache()` wherever there was a `torch.cuda.empty_cache()` in model_cache.py and latent.py. It helps significantly, especially after VAE decode.

`from torch import mps` was added, as there's currently a namespace issue in torch, so `torch.mps` can't be used as `torch.cuda` can be.

This change has been tested by myself and another MPS user - the torch.cuda.empty_cache() calls never caused any bother on non-CUDA hardware, so I'm hoping that the reverse is also true. I don't have the hardware to test this, though.

## Related Tickets & Documents

- Related Issue #
- Closes #

## QA Instructions, Screenshots, Recordings

Test that you are able to load models and generate images as normal. 

## Added/updated tests?

- [ ] Yes
- [x] No : I don't believe that there are any new tests required, as long as there's existing tests for model loading and generating.

## [optional] Are there any post deployment tasks we need to perform?
Nope.

### CODE REVIEW

**Comment by Millu** [comment]
I just gave this a test and seems to be working without issue! 

Thanks for starting to think about how we can continue to improve performance!

**Comment by gogurtenjoyer** [comment]
Thanks very much for testing! Glad it works (or rather that it doesn't cause issues on other hardware) - I know that something more robust will probably need to be done in terms of device abstraction down the road, but hoping this'll do the trick for now.

**Comment by Millu** [comment]
> Thanks very much for testing! Glad it works (or rather that it doesn't cause issues on other hardware) 

Probably should have been clearer - I'm on an M1. We'll need some NVIDIA/AMD enabled folks to test as well

**Comment by hipsterusername** [comment]
> > Thanks very much for testing! Glad it works (or rather that it doesn't cause issues on other hardware)
> 
> Probably should have been clearer - I'm on an M1. We'll need some NVIDIA/AMD enabled folks to test as well

Shared in discord, logging here for record

[2023-09-10 23:13:27,073]::[InvokeAI]::ERROR --> Error while invoking:
Cannot execute emptyCache() without MPS backend.
 
 (tested on Windows)

**Comment by gogurtenjoyer** [comment]
Okay, thanks! I'm going to redo this a bit so that we check if the device is MPS first, if so we'll import mps from torch and empty_cache() in the regular places. I'll post a new commit in a bit.

**Comment by gogurtenjoyer** [comment]
@hipsterusername this new commit should hopefully not cause errors on Windows, if you get a chance to test it! Thanks 👍

**Comment by hipsterusername** [comment]
All looking good to me @gogurtenjoyer

**Review by psychedelicious — APPROVED** [review]
Doesn't explode for me on linux

**Review by hipsterusername — APPROVED** [review]

**Pull request merged**
