### PR TITLE
Hopefully fix Embiggen for MBP users and other misc. fixes

### PR DESCRIPTION
**Pull request by travco**
Didn't hit the code path for this in my testing because I wasn't doing it on CPU. Adds a copy of the get_noise function into the embiggen generator (because... yea, that's required as a generator class - makes sense).

### CODE REVIEW

**Comment by travco** [comment]
Updated the PR to use the get_noise from txt2img instead. Frankly it probably can be just stubbed as a function since embiggen itself doesn't need noise generated and pushed to the device, it calls img2img which then does it, but since get_noise is expected to return a tensor I didn't want to return a null.

**Comment by daviddrummond95** [comment]
I tested it and it works on my system: 
Platform: Mac
OS: 13.0 (beta)
Video Card: M2, 24GB
Python version: 3.10.5
Pytorch version: 1.12.1

**Comment by lstein** [comment]
I'm doing a refactor of the post-processing functions, which currently is just GFPGAN and ESRGAN. The idea is to create a series of objects which can work together as a pipeline to modify images coming out of txt2img and img2img. This will also allow the user to run the post-processor on images generated in the past.

I rather think that Embiggen is a post-processor too, and not a generator. Would you agree with that? If so, I'll be moving it around in the tree a bit and doing mild surgery on it. Just a heads up.

**Comment by tildebyte** [comment]
Please squash all of this down to a single commit. You have 19 added lines in a single file… and 13 commits.

**Review by lstein — CHANGES_REQUESTED** [review]
It looks to me like you can achieve the effect you want by making Embiggen inherit from txt2img. This will avoid duplicating code. Apologies if I'm misunderstanding or this introduces unwanted side-effects, but try:
~~~~
from ldm.dream.generator.txt2img import Txt2Img
class Embiggen(Txt2Img):
...etc
~~~~

**Comment by travco** [comment]
> Please squash all of this down to a single commit. You have 19 added lines in a single file… and 13 commits.

Yep, sorry, this was a hasty toss-up PR to fix it for the folks with MBPs, 11 of those commits are from using this fork for #437 (which ended up being a lot of changes) and then it diverging when they were merged into the development branch.

> I rather think that Embiggen is a post-processor too, and not a generator. Would you agree with that? If so, I'll be moving it around in the tree a bit and doing mild surgery on it. Just a heads up.

I'd agree it fits better as a post processor @lstein, I just put it in the "cleanest" way that I could see at the time where it could intake all the arguments that it needs (which is everything Img2Img needs and more).
As long as you don't end up losing the use-case of using Embiggen to perform Img2Img an init_image larger than the GPU could otherwise handle, sounds good to me.

> It looks to me like you can achieve the effect you want by making Embiggen inherit from txt2img. This will avoid duplicating code. Apologies if I'm misunderstanding or this introduces unwanted side-effects ...

It would, though I think there is better stop-gap fix here than inheriting/importing from both - because it is ultimately a wrapper around Img2Img and it doesn't *actually* need to init noise for itself. Img2Img will do it again and use what it made instead anyway.
I've gone the other way and replaced the generate function since there are a bunch of other steps that embiggen doesn't need/use in there. Yes, it's more lines, but also less compute spent doing nothing.

Added in some other fixes:
- Found some "structure recreation" at higher strengths which may produce duplicated structures in each tile and make the tiling effect more obvious. Included a change to Embiggen to remain deterministic but iterate seeds sent to Img2Img internally to avoid this behavior.
- Tweaked the gradient on the corner of the alpha layers. It's a *really* minor change, but in the incredibly rare case where it can be noticed, it bothered me.
- Drop unnecessary passing of init_img to Img2Img

**Comment by tildebyte** [comment]
@travco;

> Yep, sorry, this was a hasty toss-up PR to fix it for the folks with MBPs

No worries, as long as we get there in the end 😁

**Comment by travco** [comment]
Since the PR is still open (and I finally tracked down the cause of these) added a commit to fix a long standing quirk:
 - The trailing upper-right edge of a tile could make a semi-transparent (but still noticeable) vertical line artifact when the contents of the underlying tiles diverged too much.

It's hard to describe, but conveniently we're working in images

The above has a **small** but noticeable vertical line in the center between the two "wings", which is caused by upper-right corner of the bottom-left tile not being fully covered by the gradient transparency of the rounded corner of the tile that goes over it (because it can't - it needs to "fade in" both the top and the left side of the new tile to not show seams).

Doing it the new way:

Poof, and the artifact is gone. Nothing can really be done for the underlying divergence between how img2img is transforming each of the underlying tiles, but at least there isn't a hard cutoff anymore.

Fix is an asymmetric mask added to the top-right corner of tiles that aren't in the first row or last column. Which looks like this:
alphaLayerLTaC

**Comment by lstein** [comment]
My development environment is down for weekend maintenance, but I'll test this on Monday when the systems are back up.

**Comment by krummrey** [comment]
Tried it on my MBP 16GB, works! Another great feature in the toolchain.

**Pull request merged**
