### PR TITLE
fix img2img on mps by working around pytorch bug

### LINKED ISSUE #2418: [bug]: img2img (and inpainting) produces only terrible noise on Mac
img2img and inpainting produces totally unrecognizable noise on Mac.

### Screenshots

from whosawhatsis:

inpainted area is completely garbled

### PR DESCRIPTION
**Pull request by damian0815**
horribly, temporarily send the vae to `.cpu()` so that good latents can be produced

closes #2418

### CODE REVIEW

**Comment by pbakaus** [comment]
Awesome, any workaround is better than the current state (img2img / canvas being broken)!

Curious - what's the expected performance hit for this? How much of the pipeline does this MPS->CPU change represent?

**Comment by damian0815** [comment]
@pbakaus it makes the "preparing" stage a little slower, but it shouldn't be too much in the grand scheme of things - the generation loop still takes a couple of orders of magnitude more time to complete.

**Comment by keturn** [comment]
Wait, what? You're saying that `vae.encode` doesn't work on mps at all? but `vae.decode` does?

Is this true with the upstream [StableDiffusionImg2ImgPipeline](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py#L480) as well?

**Comment by whosawhatsis** [comment]
> Wait, what? You're saying that `vae.encode` doesn't work on mps at all? but `vae.decode` does?
> 
> Is this true with the upstream [StableDiffusionImg2ImgPipeline](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py#L480) as well?

I've been getting garbage trying to get my custom diffusers script to work with img2img on MPS. It's not the same garbage that invoke has been giving me, but it's also garbage.

**Comment by damian0815** [comment]
@keturn (shrug)
Screen Shot 2023-01-30 at 21 14 49

the pytorch bug in question is very bad - part of what makes pytorch efficient is that a tensor can be a "view" onto another tensor's memory, so as long as the numbers don't change you can have tonnes of massive arrays that actually all just point back to one. 
except in some situations that occur quite often MPS pytorch says "yep here's a pointer to the numbers" and it's just .. wrong

**Comment by keturn** [comment]
> (this is with [the img2img pipeline example colab](https://github.com/huggingface/notebooks/blob/main/diffusers/image_2_image_using_diffusers.ipynb?rgh-link-date=2023-01-30T20%3A16%3A50Z))

so that looks fine, right? Which means the upstream vae.encode isn't inherently broken on mps?

Can we add a `clone` to the inputs and/or outputs of `vae.encode` so it works for us too, without moving its computation to CPU?

Or are you saying the bug is subtle enough that vae.encode itself might be broken (even if it works in the minimal example) depending on other outside factors and the context we're using it in?

**Comment by damian0815** [comment]
> Can we add a `clone` to the inputs and/or outputs of `vae.encode` so it works for us too, without moving its computation to CPU?

i spent a good couple of hours `.clone()`ing everything i possibly could around this code, sending things to `.cpu()` and back, writing out `.pickle` files and comparing them in a separate process. pushing the vae to cpu() is a bad solution but it is really the only thing that makes it work.

**Review by lstein — APPROVED** [review]
Looks like a decent workaround. Is there any way we can remember to revert this bit of code when pytorch is fixed?

**Comment by damian0815** [comment]
@lstein i wrote a `# TODO` that pycharm helpfully draws purple rather than the regular comment colour - i assume there's some way to list all the TODOs automatically

**Pull request merged**
