### PR TITLE
Remove Prompt-to-Prompt Cross-Attention Control

### PR DESCRIPTION
**Pull request by RyanJDick**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [x] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [x] Yes
- [ ] No

## Description

This PR removes support for Prompt-to-Prompt Cross-Attention Control (aka .swap()).

The decision was made to drop support for this feature, because:

- It does not currently work with SDXL. The fact that no on is complaining about this inidicates that the feature is not heavily used.
- It has awkward interactions with other attention-based features making it annoying to maintain.
- As currently implemented, it is currently not compatible with IP-Adapter or regional prompting.
- Due to all of its incompatibilities (SDXL, IP-Adapter, regional prompting) it’s easy to foot-gun yourself if you try to use it.

## QA Instructions, Screenshots, Recordings

I smoke tested that SD and SDXL generation still work.

## Merge Plan

- [ ] Change the target branch to main before merging.

## Added/updated tests?

- [ ] Yes
- [x] No: N/A

### CODE REVIEW

**Comment by keturn** [comment]
These are all good reasons and I can't contest them, but I'm sad to see it go. 😿 I still believe that attention-map visualization is a really useful tool for understanding how prompts are interpreted, and these sort of attention-manipulation functions have been promising for getting more versatility out of the text-to-image process without retraining.

#4541 is still around in case we ever get a sponsor for this sort of thing in the future.

**Review by lstein — APPROVED** [review]
I agree with the rationale for removing this. It is a lot of code to maintain for a feature that does not seem to be used frequently.

**Comment by RyanJDick** [comment]
Note for next time: this was not intended to be merged into `[ryan/regional-prompting-naive](https://github.com/invoke-ai/InvokeAI/tree/ryan/regional-prompting-naive)` (see merge plan). https://github.com/invoke-ai/InvokeAI/pull/5916 is much harder to review and manage conflicts on now.

**Comment by RyanJDick** [comment]
I've reverted and opened a new PR here: https://github.com/invoke-ai/InvokeAI/pull/6123

**Pull request merged**
