### PR TITLE
add powershell wrapper for the Windows installer

### PR DESCRIPTION
**Pull request by ebr**
*proposal / for discussion*

hoping :crossed_fingers: for a "pipe to bash" equivalent on Windows, to put this activity "on rails" such that there's less room for user error.

Requires testing by someone on a Windows system with antivirus enabled, in Powershell, by copying and pasting this command:

```
Invoke-WebRequest -Uri https://raw.githubusercontent.com/invoke-ai/InvokeAI/1acba80e6691b5b0a81377366228c9d9e8232f71/source_installer/Install.ps1 -UseBasicParsing -OutFile Install.ps1; .\Install.ps1
```

If that pans out, such command can be added to documentation, for a `curl | bash -c `-like  experience (yuck, but it does help)

### CODE REVIEW

**Review by lstein — COMMENTED** [review]
I'd like to help out with this one, but I don't feel comfortable enough in the Windows powershell environment to feel qualified to review. I'd suggest @hipsterusername and @tildebyte as suitable reviewers.

**Comment by tildebyte** [comment]
> Requires testing by someone on a Windows system with antivirus enabled, in Powershell

I'm happy to try it, but I don't (and won't) use a 3rd-party AV

**Comment by tildebyte** [comment]
So far, so good, with a minor syntactical caveat:

```
Suggestion [3,General]: The command Install.ps1 was not found, but does exist in the current location.
PowerShell does not load commands from the current location by default.
If you trust this command, instead type: ".\Install.ps1".
See "get-help about_Command_Precedence" for more details.
```

retrying with the suggested fix works as expected

**Comment by ebr** [comment]
thx @tildebyte, I updated the command in the PR description. maybe we could ask someone in Discord to give this a try?

**Comment by ebr** [comment]
this is probably not going to be useful; closing and can reopen if we so decide

**Pull request closed without merging**
