### PR TITLE
Allow k_dpmpp_2s_ancestral and k_dpmpp_2m

### PR DESCRIPTION
**Pull request by spezialspezial**
Tested and works so far for 'k_dpmpp_2s_ancestral' and 'k_dpmpp_2m'. NOT working for 'k_dpm_fast', 'k_dpm_adaptive' out of the box

### CODE REVIEW

**Comment by hipsterusername** [comment]
@spezialspezial - Any chance you can walk through the purpose of these changes?

It doesn't seem to add any samplers to the constants the app uses, so it doesn't seem to be a full addition of samplers?

**Review by damian0815 — CHANGES_REQUESTED** [review]
not approved. this kind of code is a security risk. plus there's no frontend support. compare the amount of code in #1389 - this is what's needed to add a new sampler.

**Comment by spezialspezial** [comment]
> @spezialspezial - Any chance you can walk through the purpose of these changes?

The purpose is beeing able to use k_dpmpp_2s_ancestral and k_dpmpp_2m as an api user until you catch up with the webgui. 

> It doesn't seem to add any samplers to the constants the app uses, so it doesn't seem to be a full addition of samplers?

I'm using prompt2image, the argument is untyped but likely considered a string or None. Not sure about constants. You mean there is an enumeration to use?

I agree, it's a probably not suitable from your point of view. Well, maybe it's useful to know I'm using it for a while now and there seems to be no problem at runtime.

**Comment by spezialspezial** [comment]
Very good samplers by the way, you're missing out

**Comment by hipsterusername** [comment]
Would love to have them added, but like @damian0815 said, we'd need you to make the full updates required to support this - Reference #1389 for guidance.

Thanks!

**Comment by spezialspezial** [comment]
Makes sense. I've read about the Mac issues and I understand Apple user support is a concern. I'm not using a Mac nor the Birch-san fork which makes it hard to evaluate. I'm sure some solution will pop up from the Mac base. It's easy to patch for people inclined so no harm.

**Comment by damian0815** [comment]
> Very good samplers by the way, you're missing out

if you scroll up a couple of lines from your changes you'll find they're already implemented

```
       elif self.sampler_name == 'k_dpmpp_2_a':
            self.sampler = KSampler(self.model, 'dpmpp_2s_ancestral', device=self.device)
        elif self.sampler_name == 'k_dpmpp_2':
            self.sampler = KSampler(self.model, 'dpmpp_2m', device=self.device)
```

**Comment by lstein** [comment]
As far as i'm aware we already support these samplers on all platforms.

**Pull request closed without merging**
