### PR TITLE
add k_dpmpp_2_a and k_dpmpp_2 solvers options

### PR DESCRIPTION
**Pull request by victorca25**
Following up from https://github.com/invoke-ai/InvokeAI/pull/1383, these are the changes needed in case anyone wants to test the new DPM++ solvers (https://github.com/crowsonkb/k-diffusion/commit/2d2240ba480d4b6096497252d164bb06345fe61a), but based on the development branch.

Copying the same notes as before for reference:

On Mac M1 k_dpmpp_2 results in black images, the ancestral k_dpmpp_2_a works, but I think it suffers from the same as https://github.com/invoke-ai/InvokeAI/issues/1350 , so it might work better elsewhere.

To use, k-diffusion (src/k-diffusion/k_diffusion/sampling.py) has to be updated with the sample_dpmpp_2s_ancestral() and sample_dpmpp_2m() functions. Might be interesting to evaluate these new versions. More info: https://github.com/crowsonkb/k-diffusion/issues/40

### CODE REVIEW

**Comment by keturn** [comment]
If we are prioritizing the 🧨diffusers migration for the next release, please hold off on merging this (and any other sampler changes) until _after_ we get the diffusers backend in place. (#1384 and related.)

After that, I expect the preferred way to use DPM++ solvers will be via https://github.com/huggingface/diffusers/pull/1132

**Comment by victorca25** [comment]
From what I understand in the PR, the migration to diffusers is in a pretty raw state, isn't it?

I don't think it's too much of a change to worry about, unless the change to diffusers will happen in the following 2-3 days vs. having the options to test if the solvers help.

**Comment by keturn** [comment]
Granted, this PR doesn't add much in the way of _code_ that will make more work for the diffusers port. It adds some entries to some lists to allow Invoke access to more functions implemented in k-diffusion.

But I'm not sure yet to what extent a diffusers-based pipeline will support direct use of k-diffusion, and if it _doesn't_ then access to those samplers is something we'll have to walk back. At least until we figure out how to support them (and whether supporting k-diffusion _and_ diffusers-provided methods is worth the effort, given how much overlap there will be between the two).

**Comment by victorca25** [comment]
Sounds like the move to diffusers is indeed very raw, if there are so many unknowns.

Maybe by the time it's ready, there's already something new to go with instead. Sounds a bit too early for a code freeze, but anyways there's the option if anyone wants to test it.

**Comment by lstein** [comment]
I've read through the crowson merge conversation but the main use case is supporting DPM-Solver. Will we see concrete gains in performance and/or image quality, or is this future proofing the repo against improvements that follow?

**Comment by Birch-san** [comment]
😕 dpmpp samplers worked for me without any changes. I'm running pytorch nightly; that might be the difference?

also: I rebase that mps branch whenever k-diffusion changes. if you have those samplers you're probably up-to-date, but be sure to compare what you have locally with what's in GitHub.

> But I'm not sure yet to what extent a diffusers-based pipeline will support direct use of k-diffusion

@keturn supported fully:  
https://twitter.com/Birchlabs/status/1589786655040614400

**Comment by victorca25** [comment]
@lstein DPM++ Solvers were merged to Auto's repo 3 days ago (https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/4304). The main benefit of the new version of the solvers is producing high quality results at much lower steps number (some examples in the link above).

@Birch-san great work! I was testing with a manually updated version of k-diffusers, before you updated the code, but I'll now test it again rebasing to your repo and update Pytorch to see if the issues are fixed!

**Comment by Birch-san** [comment]
> what are the advantages to using the DPM-Solver++ module?

@lstein high-quality results in as few as 5 sampler steps:  
https://twitter.com/Birchlabs/status/1589038086633455616

**Comment by Birch-san** [comment]
there's also an official (i.e. non-k-diffusion) implementation of DMP-Solver++. it can be integrated into a CompVis repo like so:  
https://twitter.com/Birchlabs/status/1589260241929052160

**Comment by ausbitbank** [comment]
Just wanna say I applied this patch a few days ago and the new samplers are pretty amazing. Lots of my prompts are coherent in 5-10 steps. It's a fairly clean change too, would love to see this merged

**Comment by victorca25** [comment]
@lstein I'm setting the PR as ready for review now, I think it's worth adding these options for further testing, but it seems to be working fine!

**Comment by discordinated** [comment]
On M1 Max I needed to do some other stuff to get it running:

Update sampling.py in my miniconda3 env to https://github.com/crowsonkb/k-diffusion/blob/master/k_diffusion/sampling.py 

Installed torchsde via pip

I think I might have tweaked something else too, can't remember. 

I can now generate using k_dpmpp_2 and k_dpmpp_2_a in the CLI. However I can't work out how to get it to show in the webui - I've hacked it by editing the page after load ... but can't currently find where those option values are being pulled from. 

Generations are fast and I seem to be able to make larger images that before. Needs more testing, but seems very positive.

**Comment by victorca25** [comment]
@discordinated did you update the environment? The latest k-diffusion by @Birch-san already has the samplers merged, so it shouldn't be needed to switch to crowsonkb's.
Also regarding the webui, a quick fix is to add the new samplers names to the static .js files in ```frontend/dist/assets```, since those don't update automatically (AFAIK). I had added them in the initial commit at https://github.com/invoke-ai/InvokeAI/pull/1383, but it wasn't required.

**Comment by victorca25** [comment]
@lstein @CapableWeb some users are interested in testing the samplers and results have been positive so far. Is there something else that should be done before considering merging the changes? Let me know if I can help.

**Review by lstein — APPROVED** [review]
LGTM

**Comment by lstein** [comment]
I'm happy to merge this in now, but we need another reviewer. I will add a few candidates.

**Comment by hipsterusername** [comment]
Also inclined to approve and merge, but poking @keturn for his thoughts since he'll be owning the diffusers work.

**Comment by hipsterusername** [comment]
@victorca25 - Thanks for your work on this, and on behalf of the team, thanks for understanding why its been open for as long as it has been. I know users value these samplers quite a bit, and I am _personally_ excited to get my hands on them.

We're in the process of migrating to diffusers (branch is https://github.com/invoke-ai/InvokeAI/tree/dev/diffusers) - In the interest of not moving the goal posts on @keturn more than has been already, could you look into compatibility with diffusers and introduce a PR off of dev/diffusers that would add these samplers into our diffusers work as well?

Know it's a bigger ask than us just reviewing existing code and merging in, but we're trying to make sure we can ensure that we'll be able to maintain compatibility for these once we migrate before approving & merging in on our legacy backend. 

Whether you take that on or not, any insight you can share on compatibility w/ diffusers would be appreciated!

**Comment by discordinated** [comment]
> @discordinated did you update the environment? The latest k-diffusion by @Birch-san already has the samplers merged, so it shouldn't be needed to switch to crowsonkb's. Also regarding the webui, a quick fix is to add the new samplers names to the static .js files in `frontend/dist/assets`, since those don't update automatically (AFAIK). I had added them in the initial commit at #1383, but it wasn't required.

Sorry for slow reply - hectic days here. Yes I did but to double check I started over.  I installed Invoke again the other day to check out 2.2 so I just used 'gh pr checkout 1389' to get this PR branch, then did a 'git pull' for good measure. It was all up to date. Then I updated the env using  'conda env update' and then edited the GUI .js to show the samplers in the webui. All good to that point. When trying to generate using one of the new samplers I had this error:

`>> Image generation requested: {'prompt': 'snow covered slope, a microscopic photo, by Matthias Weischer, plasticien, 8k fabric texture details, icebergs, broken glass photo, stock photo', 'iterations': 1, 'steps': 40, 'cfg_scale': 8.5, 'threshold': 0, 'perlin': 0, 'height': 768, 'width': 1024, 'sampler_name': 'k_dpmpp_2_a', 'seed': 718800835, 'progress_images': False, 'progress_latents': True, 'save_intermediates': 5, 'generation_mode': 'txt2img', 'init_mask': '...', 'seamless': False, 'hires_fix': True, 'variation_amount': 0}
ESRGAN parameters: False
Facetool parameters: False
{'prompt': 'snow covered slope, a microscopic photo, by Matthias Weischer, plasticien, 8k fabric texture details, icebergs, broken glass photo, stock photo', 'iterations': 1, 'steps': 40, 'cfg_scale': 8.5, 'threshold': 0, 'perlin': 0, 'height': 768, 'width': 1024, 'sampler_name': 'k_dpmpp_2_a', 'seed': 718800835, 'progress_images': False, 'progress_latents': True, 'save_intermediates': 5, 'generation_mode': 'txt2img', 'init_mask': '', 'seamless': False, 'hires_fix': True, 'variation_amount': 0}
Generating:   0%|                                                                                                                                       | 0/1 [00:00<?, ?it/s]>> Ksampler using model noise schedule (steps >= 30)
>> Sampling with k_dpmpp_2s_ancestral starting at step 0 of 40 (40 new sampling steps)
Generating:   0%|                                                                                                                                       | 0/1 [00:00<?, ?it/s]
'sample_dpmpp_2s_ancestral'


Traceback (most recent call last):
  File "/Users/USERNAME/InvokeAI/backend/invoke_ai_web_server.py", line 1116, in generate_images
    self.generate.prompt2image(
  File "/Users/USERNAME/InvokeAI/ldm/generate.py", line 482, in prompt2image
    results = generator.generate(
  File "/Users/USERNAME/InvokeAI/ldm/invoke/generator/base.py", line 91, in generate
    image = make_image(x_T)
  File "/Users/USERNAME/miniconda3/envs/invokeai/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/USERNAME/InvokeAI/ldm/invoke/generator/txt2img2img.py", line 53, in make_image
    samples, _ = sampler.sample(
  File "/Users/USERNAME/miniconda3/envs/invokeai/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/USERNAME/InvokeAI/ldm/models/diffusion/ksampler.py", line 214, in sample
    K.sampling.__dict__[f'sample_{self.schedule}'](
KeyError: 'sample_dpmpp_2s_ancestral'
`

I then swapped /Users/USERNAME/miniconda3/envs/invokeai/lib/python3.10/site-packages/k_diffusion/sampling.py for https://github.com/crowsonkb/k-diffusion/blob/master/k_diffusion/sampling.py --  torchsde didn't give an error this time, so must still be installed. Restarted invokeai with --web and it works and generates an image:

`>> Image generation requested: {'prompt': 'snow covered slope, a microscopic photo, by Matthias Weischer, plasticien, 8k fabric texture details, icebergs, broken glass photo, stock photo', 'iterations': 1, 'steps': 40, 'cfg_scale': 8.5, 'threshold': 0, 'perlin': 0, 'height': 768, 'width': 1024, 'sampler_name': 'k_dpmpp_2_a', 'seed': 718800835, 'progress_images': False, 'progress_latents': True, 'save_intermediates': 5, 'generation_mode': 'txt2img', 'init_mask': '...', 'seamless': False, 'hires_fix': True, 'variation_amount': 0}
ESRGAN parameters: False
Facetool parameters: False
{'prompt': 'snow covered slope, a microscopic photo, by Matthias Weischer, plasticien, 8k fabric texture details, icebergs, broken glass photo, stock photo', 'iterations': 1, 'steps': 40, 'cfg_scale': 8.5, 'threshold': 0, 'perlin': 0, 'height': 768, 'width': 1024, 'sampler_name': 'k_dpmpp_2_a', 'seed': 718800835, 'progress_images': False, 'progress_latents': True, 'save_intermediates': 5, 'generation_mode': 'txt2img', 'init_mask': '', 'seamless': False, 'hires_fix': True, 'variation_amount': 0}
>> Setting Sampler to k_dpmpp_2_a
/Users/USERNAME/InvokeAI/ldm/modules/embedding_manager.py:155: UserWarning: The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1659484612588/work/aten/src/ATen/mps/MPSFallback.mm:11.)
  placeholder_idx = torch.where(
Generating:   0%|                                                                                                                                       | 0/1 [00:00<?, ?it/s]>> Ksampler using model noise schedule (steps >= 30)
>> Sampling with k_dpmpp_2s_ancestral starting at step 0 of 40 (40 new sampling steps)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 40/40 [00:56<00:00,  1.42s/it]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 40/40 [00:56<00:00,  1.22s/it]
>> Interpolating from 704x512 to 1024x768 using DDIM sampling
>> Running DDIMSampler sampling starting at step 10 of 40 (30 new sampling steps)
Decoding image: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [01:35<00:00,  3.17s/it]
{'prompt': 'snow covered slope, a microscopic photo, by Matthias Weischer, plasticien, 8k fabric texture details, icebergs, broken glass photo, stock photo', 'iterations': 1, 'steps': 40, 'cfg_scale': 8.5, 'threshold': 0, 'perlin': 0, 'height': 768, 'width': 1024, 'sampler_name': 'k_dpmpp_2_a', 'seed': 718800835, 'progress_images': False, 'progress_latents': True, 'save_intermediates': 5, 'generation_mode': 'txt2img', 'init_mask': '', 'seamless': False, 'hires_fix': True, 'variation_amount': 0, 'init_img': ''}
>> Image generated: "/Users/USERNAME/InvokeAI/outputs/img-samples/000523.1f74594d.718800835.png"
Generating: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [02:42<00:00, 162.95s/it]
>> Usage stats:
>>   1 image(s) generated in 163.30s
`

**Comment by victorca25** [comment]
Hello @hipsterusername,
I don't have much time to look into diffusers for now, but as @Birch-san mentioned before, it is fully possible to use the k-diffuser samplers in a diffusers pipeline: https://github.com/invoke-ai/InvokeAI/pull/1389#issuecomment-1307299193

**Review by lstein — APPROVED** [review]
Thank you for this!

**Review by hipsterusername — APPROVED** [review]
Excited! As a note, we should communicate to all users this is “experimental” — as we move to diffusers there may be reproducibility or availability gaps, but it’s good to hear compatibility overall shouldn’t be an issue!

**Pull request merged**
