### PR TITLE
Add support for multi-gpu rendering

### PR DESCRIPTION
**Pull request by lstein**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [X] Yes - a long time ago
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [ ] Yes
- [X] No

## Description

This PR adds speculative support for parallel rendering across multiple GPUs. 

1. The model loader has been enhanced to keep track of all the CUDA GPUs available. When the loader is asked to load a model into VRAM, the first unused CUDA device is selected. If all CUDA devices are available, the loader will block until a timeout is reached. There is no support for multiple CPU or MPS devices right now.
3. The model manager now has an attribute called `gpu_count` which provides the number of GPU devices potentially available.
4. In `invokeai/app/services/invocation_processor/invocation_processor_default.py`, I upped the `__thread_limit` semaphore to the number of GPUs known to the model manager. I think this will cause up to `gpu_count` processing threads to be started.

The intended effect is to speed up batch image generation by allowing up to N workflows execute in parallel, where N is the number of GPUs on the user's system. There will be no effect on the speed of individual image renders, but an overall increase when you are running a batch of them.

The code is untested at the current time, and I imagine that some new locking code must be placed in `DefaultInvocationProcessor` in order to make it thread safe.  

## Related Tickets & Documents

- Related Issue #4745
- Closes #

## QA Instructions, Screenshots, Recordings

This needs a multi-GPU system to test. I'm in the process of gaining access to one.

## Merge Plan

This PR is in draft state. Do not merge.

## Added/updated tests?

- [ ] Yes
- [ ] No : _please replace this line with details on why tests
      have not been included_

### CODE REVIEW

**Comment by hipsterusername** [comment]
We might find that more folks are in need of batch size support over needing multi-gpu orchestration. This would add a fair bit of complexity into the session processing logic and UX would it not?

**Comment by lstein** [comment]
> We might find that more folks are in need of batch size support over needing multi-gpu orchestration. This would add a fair bit of complexity into the session processing logic and UX would it not?

I think batching requires a pretty fundamental reorganization of how the denoise latents node works. It would have an arbitrary number of conditioned/unconditioned prompt inputs, passes a list of latents to the vae decoder, and then the vae would produce an arbitrary number of images for further processing.

**Comment by psychedelicious** [comment]
Seems reasonable for the intended functionality.

Comment copied from #5737:

> I am thinking about how to implement multi-GPU support for parallel rendering. The current idea is to do this at the ModelManager level, where the manager provides a semaphore that tracks the number of GPUs that are currently free. The model locker would be modified so that when the caller requests that a model be moved into the rendering device (e.g. CUDA) it picks an unused GPU and/or blocks until one is released and available.
> 
> Under this scenario, you would want to acquire the semaphore and keep dequeue and executing sessions until the semaphore blocks. Would it be better to start multiple _process() threads here, or put that logic in the body of _process()?
> 
> Another issue is that not all sessions will need access to the GPU. So maybe there is a way of distinguishing those that do from those that don't?

If nodes could report if they need GPU or only CPU, we could parallelize both CPU and GPU at the node or workflow level. I think it's safe to assume the vast majority of workflows will require GPU, so parallelizing at the node level might be more impactful.

We could allocate 1 GPU per workflow, but in the processor, we can a parallelize CPU-only nodes. That said, CPU-only tasks are mostly not a performance bottleneck. For example, executing 20 add integer nodes in synchronously may be much faster than distributing that work across however many threads. The overhead of creating a thread might dwarf the boost from parallel node processing.

This is definitely outside my comfort zone - just thinking out loud.

**Comment by lstein** [comment]
superseded

**Comment by sHaggYcaT** [comment]
guys, could you pls explain: is it any way to use batch with multiple GPUs? Or not yet?

**Comment by Neosettler** [comment]
@sHaggYcaT my very limited understanding is that a "batch" would use x amount of process per GPU, not necessarily using multiple GPUs. Being an advocate for multiple GPU features, combining "batch" with multiple GPUs would definitely be a glorious enhancement.

**Pull request closed without merging**
