### PR TITLE
Allow symlinks creation during model install rather than copying the model

### PR DESCRIPTION
**Pull request by brandonrising**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [X] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [ ] Yes
- [X] No, because:

      
## Have you updated all relevant documentation?
- [ ] Yes
- [X] No

## Description

This PR allows users to elect into using symlinks for model installs rather than doubling the disk space usage of the models they're installing

### CODE REVIEW

**Comment by brandonrising** [comment]
Is there a reason not to do it this way?

**Comment by hipsterusername** [comment]
@brandonrising - Have you tested? If this works, it'd make sense to me.

**Comment by brandonrising** [comment]
> @brandonrising - Have you tested? If this works, it'd make sense to me.

Only tested some on a mac so far. Planning on testing on windows/linux today, but it works really well on a mac for standard generations.

**Comment by lstein** [comment]
Symlinks require elevated permissions on windows. There needs to be a check for this

**Review by lstein — COMMENTED** [review]
A couple of comments.

1) As noted above, symlinks won’t work on Windows unless the user is running as an Admin or has enabled Developer mode. So you should catch an exception and revert to physical copying if the call fails.

2) As an alternative to doing the symlinking, there is an unused option named `inplace` that can be passed to the install methods. If this is set, then local model file is not moved or copied; instead its current path is simply registered with the model configuration record. It looks like I simply neglected to expose this feature to the API, but I could do this. What do you think?

**Comment by psychedelicious** [comment]
Not a fan of platform-specific behaviours and special handling.

You shouldn't need to access the db to see model paths, you can just open the model manager tab right? We can easily expose the paths there if we haven't already.

**Comment by brandonrising** [comment]
> Not a fan of platform-specific behaviours and special handling.
> 
> You shouldn't need to access the db to see model paths, you can just open the model manager tab right? We can easily expose the paths there if we haven't already.

Yeah that's fair. I didn't run into any issues running it on windows, but maybe I've just always been running it in admin mode. Honestly, in-place installs like @lstein suggested would resolve the issues I'm having anyway. I could switch this PR to do that instead.

**Comment by psychedelicious** [comment]
I'd much prefer an in-place install option. It probably shouldn't be the default, because it shifts the responsibility of managing the model files to the user. We can add a checkbox to the MM UI, with a blurb explaining the feature. 

How does in-place interact with the diffusers conversion cache? What if my in-place model is on a different drive from my root models dir -  say, a mounted network drive or external drive - is that going to tank performance of the JIT model conversion?

**Comment by psychedelicious** [comment]
That said, I don't think we need this for v4. We have a lot of changes to model installation happening, maybe we should work towards this for a minor release after we are confident in the model installation process.

**Comment by brandonrising** [comment]
Closing in favor of in place installs

**Pull request closed without merging**
