### PR TITLE
feat(ui): migrate theming to chakra ui

### PR DESCRIPTION
**Pull request by psychedelicious**
*looks like this #2814 was reverted accidentally. instead of trying to revert the revert, this PR can simply be re-accepted and will fix the ui.*

- Migrate UI from SCSS to Chakra's CSS-in-JS system 
  - better dx
  - more capable theming 
  - full RTL language support (we now have Arabic and Hebrew)
  - general cleanup of the whole UI's styling
- Tidy npm packages and update scripts, necessitates update to github actions

To test this PR in dev mode, you will need to do a `yarn install` as a lot has changed.

thanks to @blessedcoolant for helping out on this, it was a big effort.

### CODE REVIEW

**Comment by neecapp** [comment]
The mobile UI no longer reflows to single column with this change. Is that intentional?

**Review by mauwii — APPROVED** [review]

**Review by blessedcoolant — APPROVED** [review]

**Comment by psychedelicious** [comment]
@neecapp  yes, insofar as this is the unstable main branch you are on. User-facing release is on branch v2.3 while we doing some major works on main.

Need to redo the responsive design stuff still.

**Comment by neecapp** [comment]
:+1: Yes, I know.

Just wondering, since there wasn't any mention of future work or things that were intentionally not addressed that will have follow-on work in the original PR description.

**Comment by psychedelicious** [comment]
@neecapp sorry, you're right, should have mentioned this as a breaking change. will get it re-implemented soon, maybe tonight.

**Pull request merged**
