### PR TITLE
feat(install): new install method; resolve deps using pip compile

### PR DESCRIPTION
**Pull request by tildebyte**
Sorry about the brain dump below, but writing it out in an organized format would've taken me a week, and I'm pretty sure that I've still left *something* out.

#### NO dependencies (on the OS side, that is)

- standalone Python - no installation
- git is only used by pip for cloning

#### NO Conda

- native Python 'venv' - no Conda of any kind
- micromamba is **only** used to install git
  - sadly, git is too complex and can't be installed standalone the way Python
    can

#### NO git clone of main repo

- InvokeAI released source is downloaded as a tarball, unpacked, and moved into place
- end-users CAN'T get tripped up trying to use wrong branches, git pull, etc.
- `update` script MUST handle updates, NOT git (#TODO)
- users who want to use dev branches or participate in dev activities MUST
  (yeah, I know) join the Discord and ask for help, which will be on an
  as-available basis as users following the approved install process will have
  priority

#### Misc

- error trap each install step to allow for easier troubleshooting
- ahead-of-time and not-end-user-visible 'pip-compile' fully resolves all
  dependencies at "build time" - install speed for users is limited only by
  download speed and storage access speed (TL;DR `pip install` doesn't have to do
  the dependency resolution step)
- `pip install` is quite verbose (vs. Conda)

#### Gotchas

- requirements files must be `pip-compiled` per individual platform
  - see platform matrix under 'A'ddl info' below
  - requirements files SHOULD live in '/installer' - the install script will copy
    the appropriate file in place for the runtime platform
  - if we don't have a contributor or volunteer who can do this - we can't support the platform
- the release tarball URL will need to be updated with the final release tarball name
- we have to remember to remove 'requirements.in' from 'main' (or release branch) for release
- NOT related to this installer, but discovered during testing: Windows Long
  File Path support MUST be enabled. I have a GitHub gist showing the manual
  steps, and a double-clickable REG file in this PR

#### A'ddl info

As best I can work out

- platform matrix

   ```text
    - Python ver
        py3.10
    - platform.system
        darwin
        linux
        windows
    - platform.machine
        arm64
        x86_64
    - cd (compute device)
        cpu
        cuda
        mps[1]
        rocm

    NOTE: please follow this format for all platforms

    "{py}-{platform.system}-{platform.machine}-{cd}-reqs.txt"

    e.g.
    py3.10-windows-x86_64-cuda-reqs.txt
    py3.10-darwin-arm64-cpu-reqs.txt
    py3.10-darwin-arm64-mps-reqs.txt
    py3.10-linux-x86_64-rocmreqs.txt

    [1] Is MPS a separate thing?
   ```

#### TODO

- Rework update strategy
  - Not to be cruel, but at this point UPDATING is the *least* of our worries; we need a stable
    *initial* install
  - Simply exploding a newly-released tarball in the same directory as an
    existing installation would be fine
  - EXCEPT: All of our outputs *go into the install folder by default* - this is a terrible idea.
  - There's a reason all the major OS vendors have (the equivalent of) a 'Documents' folder
    pre-created for new accounts
  - We should change our default output folder to the platform-specific 'Documents' folder
  - Custom 'models.yaml' files?
  - Other user-modifiable files I haven't thought of?
- Installer troubleshooting doc for known issues e.g.
  - What happens if there's a network interruption
  - Windows Long File Paths NOT enabled
  - Unpacking and running the installer inside an existing install

Signed-off-by: Ben Alkov <ben.alkov@gmail.com>

### CODE REVIEW

**Comment by tildebyte** [comment]
ping @psychedelicious, @Kyle0654, @hipsterusername, @blessedcoolant, @lstein and please ping anyone I might've forgotten

I need:

- REVIEWS
- TESTING

Not ACKs. This is not ready for ACKs.

This is Windows-only atm. Lin/Mac shell script is still W.I.P.

**Comment by tildebyte** [comment]
Testing (again; Windows-only): MAKE SURE LongPaths IS ENABLED

Grab https://raw.githubusercontent.com/tildebyte/InvokeAI/feat-install-pip-compile/installer/install.bat, put it in a new, empty folder, and run it.

**Comment by lstein** [comment]
What would kill several birds with one stone is for us to make InvokeAI an installable package, so that the user can install it with `pip install invokeai`. This would mean we get rid of all the relative paths and have a single configuration file that specifies:

1. The default outputs directory (there is no standard "Documents" in Linux. Each distribution organizes the home directory differently)
2. The location of the weights
3. The location of BERT, clip, gfpgan, esrgan, and clipseg models

We put the configuration file in the user's home directory at a platform-specific location, such as `.config/` in Linux.

Now `invoke.py` can be on the user's PATH and it acts just like any other command.

**Comment by tildebyte** [comment]
Testing for darwin/linux is now available:

Grab https://github.com/tildebyte/InvokeAI/blob/feat-install-pip-compile/installer/install.sh, COPY THE TEXT FROM THERE (for some reason, the "raw" version is outdated) and save it in a new empty folder, and run it.

**Comment by lstein** [comment]
Can you create a pair of these installers for Linux and Windows running AMD cards? The conda pytorch channel does not have builds for pytorch-rocm, so none of our documented installation protocols will work. What I've been doing is illustrated in the enclosed shell script plus an `environment-rocm.yml` file. I'm still not able to get `clipseg` to install in a single step because it tries to bring in the wrong version of torch.
[rocm-install.zip](https://github.com/invoke-ai/InvokeAI/files/9955543/rocm-install.zip)

**Comment by lstein** [comment]
> Can you create a pair of these installers for Linux and Windows running AMD cards? The conda pytorch channel does not have builds for pytorch-rocm, so none of our documented installation protocols will work. What I've been doing is illustrated in the enclosed shell script plus an `environment-rocm.yml` file.
> 
> Note that I don't think all the requirements are necessary as direct dependencies and I'm experimenting with trimming down the requirements file considerably.
> 
> [install-rocm.zip](https://github.com/invoke-ai/InvokeAI/files/9955651/install-rocm.zip)

Forget about creating windows AMD installer. It turns out that the ROCm driver for Windows is not available.

**Review by lstein — CHANGES_REQUESTED** [review]
A couple of questions:

1. Do we have confirmation of successful installs on Darwin/OSX?
2. Could you put back the INSTALL_*.md files? Some people will want to continue using conda and the manual install method. I'll take care of integrating them into the main install instructions.
3. Need the "installation troubleshooting doc" referred to at the end of INSTALLL.md.

**Comment by tildebyte** [comment]
> A couple of questions:
> 
>     1. Do we have confirmation of successful installs on Darwin/OSX?

Not yet, we still need to work around the greenlet build issue *for users who have Python installed via brew*. AFAICT, it will work for "non-expert" users.

>     2. Could you put back the INSTALL_*.md files? Some people will want to continue using conda and the manual install method. I'll take care of integrating them into the main install instructions.

I think that that would be a mistake. My entire purpose in undertaking this was to replace all of the half-measure install methods with one single one which works on all platforms, and never exposes the end-user to a need to install or use any other tool (no Python, no git, no conda).

>     3. Need the "installation troubleshooting doc" referred to at the end of INSTALLL.md.

W.I.P. because I need a lot more testing *by other people*. My testing has been uncharacteristically trouble-free (I've literally made a career out of being able to break software without really trying :D ). My current feeling is that this is very close to release, and the troubleshooting doc could grow over time as we see issues arise.

**Comment by tildebyte** [comment]
> Note that I don't think all the requirements are necessary as direct dependencies and I'm experimenting with trimming down the requirements file considerably.

If you check the 'requirements.in' in this PR, you'll see the minimum of our *direct* requirements (minus torchvision - for weird reasons I don't grok, I had to pin *it* to get the correct version of torch, even though multiple of our direct dependencies pull in an appropriate version of torch)

**Comment by tildebyte** [comment]
> How do we create and maintain these compiled files, such as `py3.10-windows-x86_64-cuda-reqs.txt` ?

`pip-compile -r --annotate --annotation-style split --generate-hashes --emit-index-url --allow-unsafe --output-file py3.10-windows-x86_64-cuda-reqs.txt requirements.in` on the appropriate platform. This could be added into a release-time Git Hub action or other automation.

Regardless, the resulting requirements files would still need to be reviewed by a human to see 1) what's changed and 2) what differences (if any) there are across platforms. AFAICT from my testing, there are **no** major differences in requirements between platforms (other than obviously platform-dependent packages like CUDA-enabled torch), which is one of the things which gives me confidence in this generally.

The resulting requirements files would also need to be tested (again, possibly via automation)

**Comment by lstein** [comment]
I've hand-incorporated this into the release-candidate-2-1-3 branch and will mark the install directory as owned by @tildebyte to acknowledge his authorship.

**Pull request closed without merging**
