### PR TITLE
[ui] chore(Accessibility): various additions

### PR DESCRIPTION
**Pull request by ElrikUnderlake**
# Overview
Adding a few accessibility items (I think 9 total items). Mostly `aria-label`, but also a `<VisuallyHidden>` to the left-side nav tab icons. Tried to match existing copy that was being used. Feedback welcome

### CODE REVIEW

**Review by blessedcoolant — CHANGES_REQUESTED** [review]
Can you make the labels that are in English at the moment also localization friendly?

**Comment by blessedcoolant** [comment]
Small note. Because it is possible that accessibility labels would be different from regular labels, maybe we need to have a different category for them in the localization file?

I'd like to get @psychedelicious thoughts on this.

**Comment by psychedelicious** [comment]
Fine by me to add an `accessibility` key to `en.json` and put all the those strings in there.

**Comment by blessedcoolant** [comment]
Seems good. Please make a build. I'll give a final check and merge it in.

**Comment by psychedelicious** [comment]
Thanks for your contribution! Do you have any other suggestions regarding accessibility? I have a suspicion or colors are not great for readability :/

**Comment by blessedcoolant** [comment]
Agreed. In all the dev process, we didn't pay a lot of attention to accessibility stuff but we'd love to correct that. So if you have any ideas on how we can improve that, please hit us up on Discord. We'll talk things out and see what can be done.

**Review by psychedelicious — APPROVED** [review]

**Comment by ElrikUnderlake** [comment]
Thanks! 😸

@blessedcoolant how do I make a build? Is it `yarn build` in the react app or do I build frontend + backend together somehow?

**Comment by blessedcoolant** [comment]
@ElrikUnderlake Just `yarn build` in the frontend will do it.

**Comment by ElrikUnderlake** [comment]
Thanks @blessedcoolant, done

**Review by blessedcoolant — APPROVED** [review]

**Pull request merged**
