### PR TITLE
Initial Slider & Img2Img=1 Updates

### PR DESCRIPTION
**Pull request by hipsterusername**
Adding a slider for Hi Res Fix to control Img2Img

Updated Img2img to accept values of 1 (replacing Inpaint Replace)

### CODE REVIEW

**Comment by blessedcoolant** [comment]
Has the backend been updated to recognize 1 as a valid value?

**Comment by hipsterusername** [comment]
That was the intent w/ removal of Inpaint Replace. @keturn ack'ed removal of inpaint replace which leads me to _believe_ it's now supported, but will look to him for input on that front.

This is still a draft, for now, given that I'm still working on getting the Hi-Res opt to respect the Img2Img Strength Slider passing in a value.

**Comment by hipsterusername** [comment]
Backend has not been updated, after testing. Will need to make those updates as well.

**Comment by keturn** [comment]
get_make_image takes a strength argument: https://github.com/invoke-ai/InvokeAI/blob/6608343455b2ddee8f7305e2885848bb2ab8cfc5/ldm/invoke/generator/txt2img2img.py#L22-L24

and it does use it when doing the img2img part of hi res: https://github.com/invoke-ai/InvokeAI/blob/6608343455b2ddee8f7305e2885848bb2ab8cfc5/ldm/invoke/generator/txt2img2img.py#L72-L78

it's possible it gets lost somewhere along the way between the UI and there.

**Comment by hipsterusername** [comment]
> it's possible it gets lost somewhere along the way between the UI and there.

I'm positive it's this. I'll dig in.

On a different note, I've updated generate.py to not choke on values of 1, and can confirm its allowing for full replacement.

**Comment by hipsterusername** [comment]
@psychedelicious @blessedcoolant - I'm splitting out the Hi Res Slider work, as I think my initial thought that it'd be easy to just use the existing img2img slider implementation is proving to be wrong.

This simplifies this PR into a pretty trivial change

**Comment by blessedcoolant** [comment]
Why are we still disabling the usage of 0.0 as a value? Effectively it should do nothing right? Any reason to prevent the user from supplying 0?

**Comment by hipsterusername** [comment]
I think it literally would do nothing, so unsure theres a reason TO enable it. Would it break, probably not.

**Review by psychedelicious — APPROVED** [review]
Sorry for the late review, I wanted to get the big reorg done before this as it would have made the reorg rebase trickier.

I've taken the liberty of rebasing your branch against main and tidying the commit up.

**Comment by hipsterusername** [comment]
@lstein Looks like you might need to approve this as code owner.

**Review by mauwii — APPROVED** [review]

**Pull request merged**
