### PR TITLE
add ability to retrieve current list of embedding trigger strings

### PR DESCRIPTION
**Pull request by lstein**
This PR adds a new attributer to ldm.generate, `embedding_trigger_strings`:

```
gen = Generate(...)
strings = gen.embedding_trigger_strings
strings = gen.embedding_trigger_strings()
```

The trigger strings will change when the model is updated to show only those strings which are compatible with the current model. Dynamically-downloaded triggers from the HF Concepts Library will only show up after they are used for the first time. However, the full list of concepts available for download can be retrieved programatically like this:

```
from ldm.invoke.concepts_lib import HuggingFAceConceptsLibrary
concepts = HuggingFaceConceptsLibrary()
trigger_strings = concepts.list_concepts()
```

### CODE REVIEW

**Review by damian0815 — APPROVED** [review]
lgtm

**Comment by hipsterusername** [comment]
@blessedcoolant @keturn - Looks like you're up for review as code owner in order to get this merged.

**Review by blessedcoolant — APPROVED** [review]

**Review by blessedcoolant — APPROVED** [review]

**Comment by blessedcoolant** [comment]
Think this needs a review from @keturn .. I'm the codeowner for this for some reason the PR is still requesting it from a code owner.

**Comment by keturn** [comment]
…why is this so many lines?

Oh, I see.

In the future, if you're going to reformat a file and it changes more than a handful of lines, please do that in its own commit — if not its own PR. It'll make it much easier to see which changes are functional.

**Review by keturn — APPROVED** [review]
I was admittedly distracted during this review between trying to pick out the functional changes from all the noise and occasionally cursing the choices of what I presume is an auto-formatter.

What was left didn't seem objectionable. I don't know what could possibly require a review from me _and_ damian _and_ blessedcoolant, that seems overkill for a change of this scope.

**Pull request merged**
