### PR TITLE
feat: Add SDXL To Linear UI

### PR DESCRIPTION
**Pull request by blessedcoolant**
## What type of PR is this? (check all applicable)

- [x] Feature

## Have you discussed this change with the InvokeAI team?
- [x] Yes

## Description

This PR adds support for SDXL Models in the Linear UI

### DONE

- SDXL Base Text To Image Support
- SDXL Base Image To Image Support
- SDXL Refiner Support
- SDXL Relevant UI

## [optional] Are there any post deployment tasks we need to perform?

Double check to ensure nothing major changed with 1.0 -- In any case those changes would be backend related mostly. If Refiner is scrapped for 1.0 models, then we simply disable the Refiner Graph.

### CODE REVIEW

**Comment by lstein** [comment]
Great work!

I preliminary testing, I bumped into an issue with img2img's interaction with the refiner. If I crank denoising strength all the way up to 1.0 for the base model, but leave refiner denoising start at 0.7, I get a final image that has a denoising strength of 0.7, not 1.0. In fact, adjusting the base denoising strength has very little effect when the refiner is active.

**Comment by lstein** [comment]
I don't know whether this is related to this PR or not, but the other thing I noticed is that while the installed SDXL models are showing up in the Web Model Manager, the SDXLR model is not.

**Review by psychedelicious — APPROVED** [review]
awesome work team

**Comment by blessedcoolant** [comment]
Merging once checks pass.

**Pull request merged**
