### PR TITLE
Fix init file creation if runtime directory already exists

### LINKED ISSUE #1613: [bug]: If runtime directory exists, configuration script does not create the initfile
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

16

### What happened?

Until recently, if the `~/.invokeai` init file did not exist, the `invoke.py` script would automatically proceed to create the file (albeit without correct defaults), and continue to load the CLI or web UI.

After a recent change (possibly #1517?), the `invoke.py` script tries to run `configure_invokeai.py` to reconfigure the root dir. But if the model config directory already exists (specifically, it checks for the `configs/stable-diffusion/v1-inference.yaml` file), the logic in the configure script bypasses the code path that creates the initfile altogether.

This means if we're missing the init file, but have an existing runtime dir, the application can never load, because it goes into an infinite loop with `emergency_model_reconfigure`, looking for the initfile but never creating it.

Potential workaround is to comment out https://github.com/invoke-ai/InvokeAI/blob/development/scripts/configure_invokeai.py#L697, which causes full re-initialization of the runtime dir even if it exists.

### Screenshots

_No response_

### Additional context

_No response_

### Contact Details

_No response_

### PR DESCRIPTION
**Pull request by ebr**
Fixes #1613

### CODE REVIEW

**Comment by lstein** [comment]
This is looking good. I'll do a little runtime testing before approving.

**Review by lstein — CHANGES_REQUESTED** [review]
I'm afraid there's a problem. I deleted ~/.invokeai, and ran `configure_invokeai.py`. It successfully found `~/invokeai/` and created the init file `~/invokeai/.invokeai`. It also updated models correctly. Good so far.

The problem occurred when I ran `invoke.py`:
```
(venv-test) lstein@5ce206d7371b:~/Projects/InvokeAI$ python scripts/invoke.py 
* Initializing, be patient...
Loading Python libraries...

An exception has occurred: expected str, bytes or os.PathLike object, not NoneType
```
I suspect it isn't finding the init file correctly? Sadly there is no traceback associated with this error, which should be fixed.

I added traceback calls to `args.py` and here is the problem:
```
* Initializing, be patient...
Loading Python libraries...

An exception has occurred: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/data/lstein/InvokeAI/ldm/invoke/args.py", line 176, in parse_args
    initfile = os.path.join(get_root(), ".invokeai")
  File "/usr/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by ebr** [comment]
Right, I see the problem - I had the `INVOKEAI_ROOT` set when testing, so it never hit the code path where `get_root()` returns `None`. Sorry about that.

I'd like to step back and refactor this so that there's a single approach to the root dir / initfile location, such that it's not re-implemented in three places in subtly different ways. Would you be opposed to having some of this logic moved to `Globals` (or a similar shared config module), such that all modules/scripts can take advantage of it?

**Comment by lstein** [comment]
I very much favor a refactoring, and Globals is a better place to put it than the alternatives (e.g. `args`). What do you say we reverse the logic and make the `invokeai` directory the thing that is in a predictable location (unless overridden by `--root` or the environment variable) and the init file is _always_ located inside the `invokeai` directory. I think this solves the circularity issue.

**Comment by ebr** [comment]
Closing this, continued in #1798

**Pull request closed without merging**
