### PR TITLE
feat: nsfw/watermark updates

### LINKED ISSUE #6092: [bug]: Image data not saved
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

1080 TI

### GPU VRAM

_No response_

### Version number

3.7.0

### Browser

Brave

### Python dependencies

_No response_

### What happened

Hello, I've been having a problem for a while now, the generations I make don't record any data. As a result, I can no longer use these options: Remix Image, Use prompt, use seed, use all...

I've tried different models (1.5 and XL) and nothing changes.

Thanks for your help.

### What you expected to happen

That all generations have their own integrated data.

### How to reproduce the problem

No idea

### Additional context

_No response_

### Discord username

_No response_

### LINKED ISSUE #6252: [bug]: NSFW checker is not working
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

NVIDIA GeForce RTX 2060

### GPU VRAM

6GB

### Version number

4.1

### Browser

124.0.6367.60 (Official Build) (64-bit) (cohort: M124 Rollout) 

### Python dependencies

_No response_

### What happened

The NSWF checker is not working, the button to activate it is greyed out in the UI. When I click on it nothing happens.

image

### What you expected to happen

I expected that when I click on the NSFW checker button that it will activate.

### How to reproduce the problem

Start the app, go to the web interface, click on settings and try to activate the NSFW cheker.

### Additional context

when I put in the command prompt the folder the invoke.bat is in this line: invoke.bat --nsfw_checker
I get this error: invokeai-web: error: unrecognized arguments: --nsfw_checker

so it does not work in the commands either.

### Discord username

shotgunner42

### PR DESCRIPTION
**Pull request by psychedelicious**
## Summary

Currently, NSFW checking doesn't work on new installs due to a catch-22. See #6252.

I had an idea to move NSFW and watermark to be config settings, then do the check/watermark in the invocation API as images are saved. The NSFW check and watermarking are thus fully automatic and transparent, and works on workflows too - without any user changes. This was really easy to implement.

It works well, but there is a problem on canvas where a graph does many image-saving operations.

For example, an inpaint graph does at least 6x image saves: 4x resize, 1x VAE decode and 1x paste-back. Each time, the image is checked - possibly blurred - and watermarked.

### Watermark changes the image

Watermarking subtly changes the images each time an image is saved and this introduces some chaos which impact how the model handles the images. The final output is markedly different than what you would have gotten without any watermarking.

### NSFW detection early borks the rest of generation

If an early image in the "chain" is NSFW, it still gets passed along. There are two possible outcomes:
1. The final image is still NSFW, and is the result of blurring the image, adding the caution symbol, blurring that image again and adding the caution symbol again, and so on. The result is a super-blurred image with blurred caution symbols and then a sharp caution symbol on top.
2. At some point the image was determined to no longer be NSFW (because it was blurred and a caution symbol put on it, and this was enough to change the determination). Then that gets used as the input to canvas, and the final result is this black and yellow smudge that somewhat follows the original prompt. 

### Other ideas

Ok, so this isn't viable. Some other ideas:
1. Remove both NSFW check and watermark entirely.
2. Just fix the model download and leave NSFW and watermark as part of the graphs, and a UI setting.
3. Raise a `NSFWImageError` on NSFW detection - IMO, this is how it should work anyways. The user would get a toast with the error.
4. Only do the check and watermark on terminal/leaf nodes. 

## Related Issues / Discussions

Closes #6252
Closes #6092

## QA Instructions

n/a for now

## Merge Plan

n/a

## Checklist

- [x] _The PR has a short but descriptive title, suitable for a changelog_
- [ ] _Tests added / updated (if applicable)_
- [x] _Documentation added / updated (if applicable)_

### CODE REVIEW

**Comment by lstein** [comment]
@psychedelicious If you like I'd be happy to work on this after getting the model manager API updates in. Both the NSFW and watermarking features do have real use cases, even if they aren't used all that frequently.

**Comment by psychedelicious** [comment]
@lstein Sure thing.

After thinking about it more, I'm leaning towards:
- If `watermark` is enabled in config, watermark every image. This is a already done in the PR. As described, the watermarking can change outputs, but I think this is reasonable. The expectation is that watermarking applies to _all_ outputs, so we can't really get around it changing images. And this is the only sane way to support watermarking in the workflow editor.
- If `nsfw_check` is enabled in the config, raise a `NSFWImageDetectedError` to immediately fail the graph. My thinking is, if you want to check for NSFW and NSFW is detected, there's no point in continuing with that generation - it should immediately stop.

If that makes sense, there would only be some minor changes needed for this PR.

**Comment by lstein** [comment]
> @lstein Sure thing.
> 
> After thinking about it more, I'm leaning towards:
> 
> * If `watermark` is enabled in config, watermark every image. This is a already done in the PR. As described, the watermarking can change outputs, but I think this is reasonable. The expectation is that watermarking applies to _all_ outputs, so we can't really get around it changing images. And this is the only sane way to support watermarking in the workflow editor.
> * If `nsfw_check` is enabled in the config, raise a `NSFWImageDetectedError` to immediately fail the graph. My thinking is, if you want to check for NSFW and NSFW is detected, there's no point in continuing with that generation - it should immediately stop.
> 
> If that makes sense, there would only be some minor changes needed for this PR.

This sounds reasonable. I'll see if I can get this working later this week.

**Comment by psychedelicious** [comment]
After thinking through things, this approach isn't viable. We need NSFW and watermark to be user-configurable via the UI, it cannot be something that is set in the config file.

This is superseded by #6360.

**Pull request closed without merging**
