### PR TITLE
Trigger phrases

### PR DESCRIPTION
**Pull request by maryhipp**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [x] Yes
- [ ] No, because:

## Description
* Update model manager to allow trigger phrase management as part of model metadata for main models and concept models (subject to change with @psychedelicious 's schema rework)
* Adapt Embedding popover on prompts to work for trigger phrases, as well. Now only embeddings that are compatible with base model will be displayed alongside trigger phrases configured for the currently selected models, as well as enabled concept models. 

## QA Instructions, Screenshots, Recordings
Screenshot 2024-02-28 at 12 07 07 PM

Screenshot 2024-02-28 at 12 07 33 PM

## Added/updated tests?

- [ ] Yes
- [ ] No : _please replace this line with details on why tests
      have not been included_

### CODE REVIEW

**Review by lstein — APPROVED** [review]
Looks good and works nicely. Thanks!

**Comment by brandonrising** [comment]
Seems like it works great for main models! Should we also have it show triggers for loras currently active? Could be a future feature too

**Comment by maryhipp** [comment]
Oh that is a great point, I forgot about trigger phrases for other models. @psychedelicious do you want to review this as-is and I can make a follow-up PR for integrating trigger phases for other models? I'm guessing we may also want to disable the feature for things like controlnets that shouldn't really have trigger phrases?

**Comment by hipsterusername** [comment]
> Oh that is a great point, I forgot about trigger phrases for other models. @psychedelicious do you want to review this as-is and I can make a follow-up PR for integrating trigger phases for other models? I'm guessing we may also want to disable the feature for things like controlnets that shouldn't really have trigger phrases?

Right. Should be for Main/Concept models - Anything that is touching the text encoder

**Comment by psychedelicious** [comment]
Superseded by #5865, sorry see notes there

**Pull request closed without merging**
