### PR TITLE
Add 'Random Float' node <3

### PR DESCRIPTION
**Pull request by Dekita**
does what it says on the tin :)

## What type of PR is this? (check all applicable)
- [ ] Refactor
- [ x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [x ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [ ] Yes
- [ x] No, because, I mentioned it in the discord, but idk who 'officially' noticed it :)
      
## Have you updated all relevant documentation?
- [ ] Yes
- [ x] No

## Description
Adds a random float node to the math category

### CODE REVIEW

**Review by Millu — CHANGES_REQUESTED** [review]
Thank you for adding this! A couple of comments: 

* Keeping in line with the random integer node, I don't think we should have a seed input - this would be a used to generate a seed. 
* Also, I know it's fun to have, but do you mind removing the attribution comment to help keep the codebase clean?

**Comment by Dekita** [comment]
just seen this today. I altered the function as requested, but also added a random float with seed function in case folks would like it :)

**Comment by Millu** [comment]
The commit gets automatically added to the PR! 

However, I'm not sure what the value of the node with a "seed" field is. By the nature of the node, a random float will be generated, and the value of surfacing a seed would be to have the same float, which renders the "Random Float" node redundant in the workflow. 

I think we should only add the random float without the seed and then go ahead and merge this.

**Comment by Dekita** [comment]
yeah thats fine, i can always just use my seeded float node if i ever need it :D 

updated my commit to remove the seeded variant :)

**Review by Millu — APPROVED** [review]

**Comment by psychedelicious** [comment]
After some thought, I think we actually *do* want our random nodes to have a seed value. If we provide the seed for all RNG (including the random int/float nodes), workflows are fully reproducible.

**Review by psychedelicious — APPROVED** [review]

**Pull request merged**
