### PR TITLE
Remove LowRA from Initial Models

### PR DESCRIPTION
**Pull request by Millu**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [ ] Yes
- [X] No, because:

      
## Have you updated all relevant documentation?
- [ ] Yes
- [X] No

## Description
Removing LowRA from the initial models as it's been deleted from CivitAI. 

## Related Tickets & Documents

https://discord.com/channels/1020123559063990373/1168415065205112872

- Related Issue #
- Closes #

## Added/updated tests?

- [ ] Yes
- [ ] No : _please replace this line with details on why tests
      have not been included_

### CODE REVIEW

**Comment by hipsterusername** [comment]
Do we want to just host it elsewhere or replace it with a different default LoRA?

**Comment by blessedcoolant** [comment]
Why was it removed?

**Comment by Millu** [comment]
> Do we want to just host it elsewhere or replace it with a different default LoRA?

I can't find it online, but we can host - I'm sure someone's got it downloaded. Alternatively a Zovya LoRA could be a good replacement

> Why was it removed from CivitAI?

I have no idea - no details on it

**Review by lstein — APPROVED** [review]
LGTM

**Pull request merged**
