### PR TITLE
Installer fixes

### PR DESCRIPTION
**Pull request by lstein**
Two fixes:

- Micromamba download URL for Macintoshes was incorrect in the source installer version. This has been fixed.
- Added documentation for fixing the #1463 issue in which a fresh install of Conda didn't work because of a misnamed ssl library

### CODE REVIEW

**Comment by lstein** [comment]
Got a report from a user that updated installer script is still not picking up the right micromamba version on Macs, so converting this into a draft while investigating.

**Review by hipsterusername — APPROVED** [review]

**Comment by psychedelicious** [comment]
I can't get this to work on M1 mac, I get an error like:
```
  src/greenlet/greenlet.cpp:16:10: fatal error: 'Python.h' file not found
      #include <Python.h>
               ^~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
```

I cherry-picked #1488 and ran the `create_installers.sh` script to make a new installer, followed the instructions and ran the new installer in a new directly, but ended with the same issue. 

I did not have any issues with micromamba - at least, I didn't have any before the installer failed as described above.

**Comment by psychedelicious** [comment]
Perhaps my previous comment can be safely disregarded - I've just tested #1506, using the instructions in the PR, and it works just fine.

**Comment by lstein** [comment]
This is superseded, thankfully. So I'm closing.

**Pull request closed without merging**
