### PR TITLE
Create prompts_fromfile.py

### PR DESCRIPTION
**Pull request by skunkworxdark**
Custom node that reads prompts from a file one line per prompt and outputs them as a prompt collection.  With controls for add in a pre_prompt, post_prompt, start line number, and max_prompts

### CODE REVIEW

**Comment by blessedcoolant** [comment]
@psychedelicious Thoughts on this? It basically replicates our from_file functionality from the CLI. Works as expected in the node editor. Is this something we wanna consider for the linear UI ?

**Comment by psychedelicious** [comment]
We already have some limited support for loading prompts from a file using the dynamicprompts library, but it's not actually implemented. 

Im happy to explore this feature for the linear ui but I won't have time to really give it thought for a while.

@skunkworxdark please look up the dynamicsprompts library and our current dynamic prompts node, maybe there's a way to integrate the functionality or use the existing library, which supports all the cool combinatorial prompt generation

**Comment by blessedcoolant** [comment]
If syncing with Dynamic Prompts is a hassle, we can just merge the node for usage in the node editor for those who like running from files and then later figure how to sort it out. That's an option too imo.

**Comment by skunkworxdark** [comment]
Fairly new to this but I will take a look at the dynamic prompts and see if I can figure out how it might fit.

**Comment by skunkworxdark** [comment]
I am closing this PR as I have managed to mess it up by syncing my branch back to the invoke main.  I will reopen a new PR at some point and do it properly next time.

**Pull request closed without merging**
