### PR TITLE
 feat: add private node for linear UI image outputting 

### LINKED ISSUE #4645: [bug]: flicker between generation preview and final result
### What version did you experience this issue on?

b152fbf72f163e4a60bda7a54747d0a752d63ca1

### What happened?

When generating an image, at the end of the preview the display flips back to the previously-displayed image for a bit before showing the completed one.

I think this is a regression. It was a problem in one of the recent releases and got fixed (or at least mitigated to a large extent) and came back after queues landed.

### Screenshots

[flicker-preview.webm](https://github.com/invoke-ai/InvokeAI/assets/83819/15d6d10b-ecd7-4b8f-b2d3-b82141d1585e)

### LINKED ISSUE #4688: [bug]: Duplicate images are generated
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

_No response_

### What version did you experience this issue on?

3.2.0rc2

### What happened?

When we generate an image, it is generated twice

### Screenshots

image

### Additional context

_No response_

### Contact Details

_No response_

### PR DESCRIPTION
**Pull request by psychedelicious**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [x] Yes
- [ ] No, because:

## Description

[feat: add private node for linear UI image outputting](https://github.com/invoke-ai/InvokeAI/commit/4599517c6c309d71cd32a535076c2e12c585d75f)

Add a LinearUIOutputInvocation node to be the new terminal node for Linear UI graphs. This node is private and hidden from the Workflow Editor, as it is an implementation detail.

The Linear UI was using the Save Image node for this purpose. It allowed every linear graph to end a single node type, which handled saving metadata and board. This substantially reduced the complexity of the linear graphs.

This caused two related issues:
- Images were saved to disk twice
- Noticeable delay between when an image was decoded and showed up in the UI

To resolve this, the new LinearUIOutputInvocation node will handle adding an image to a board if one is provided.

Metadata is no longer provided in this unified node. Instead, the metadata graph helpers now need to know the node to add metadata to and provide it to the last node that actually outputs an image. This is a `l2i` node for txt2img & img2img graphs, and a different image-outputting node for canvas graphs.

HRF poses another complication, in that it changes the terminal node. To handle this, a new metadata util is added called `setMetadataReceivingNode()`. HRF calls this to change the node that should receive the graph's metadata.

This resolves the duplicate images issue and improves perf without otherwise changing the user experience.

---

Also fixed an issue with HRF metadata.

## Related Tickets & Documents

- Closes #4688
- Closes #4645

## QA Instructions, Screenshots, Recordings

Generate some images with and without a board selected. Images should end up in the right board per usual, but a bit quicker. Metadata should still work.

### CODE REVIEW

**Comment by psychedelicious** [comment]
Note for reviewers: The changes to the graph builder functions are scarier than they look. It's just adding an extra arg to the metadata function, but git makes it look like a lot has changed.

**Comment by Millu** [comment]
Seems to be working for me! Only one of each image is created and there isn't a delay!

**Review by hipsterusername — APPROVED** [review]

**Comment by blessedcoolant** [comment]
Seems to be fine. Another thing that needs addressing is on the UI end where we avoid the display of the older image after progress for a split second before the new image is settled in.

**Review by maryhipp — CHANGES_REQUESTED** [review]
Want to make sure @hipsterusername doesn't merge this. 

I

**Comment by blessedcoolant** [comment]
> Want to make sure @hipsterusername doesn't merge this.
> 
> I

Oh dang. I merged. Should I revert?

**Pull request merged**
