### PR TITLE
fix for "1 leaked semaphore objects to clean up at shutdown" on M1

### PR DESCRIPTION
**Pull request by skurovec**
Implements fix by @Any-Winter-4079 referenced in https://github.com/invoke-ai/InvokeAI/issues/1016#issuecomment-1276825640

### CODE REVIEW

**Comment by Vargol** [comment]
Hi, 
In the the second forward, has h been checked that it's on the mps device  after its been derived from x ?

**Comment by skurovec** [comment]
From my testing it looks like h inferring device from x:

```"beautiful landscape" -s 15 -S 3972197351 -W 2048 -H 1024 -C 7.5 -A k_lms```

```
Devices:  x mps:0 h mps:0
Devices:  x mps:0 h mps:0
Devices:  x mps:0 h mps:0
Devices:  x mps:0 h mps:0
Devices:  x mps:0 h mps:0
Devices:  x mps:0 h mps:0
Devices:  x mps:0 h mps:0
Devices:  x mps:0 h mps:0
Devices:  x mps:0 h mps:0
Devices:  x mps:0 h mps:0
Devices:  x mps:0 h mps:0
Devices:  x cpu h cpu
Devices:  x mps:0 h mps:0
Devices:  x mps:0 h mps:0
```

**Comment by Vargol** [comment]
Okay, should be get h back on the mps as soon as we can (assuming none of the other bits of processing break).
I'm sure it won't make too much difference.

I've also noticed that in https://github.com/invoke-ai/InvokeAI/issues/1016 up mention the images are not consistent at smaller sizes which concerns me a little, even though I know technically it should be running the same code. Does the new code get triggered at that size where it wasn't before ?

**Comment by skurovec** [comment]
I have consistent images pre and post patch. But different image than @Any-Winter-4079 with same seed

**Comment by skurovec** [comment]
```"beautiful landscape" -s 50 -S 1962347883 -W 512 -H 512 -C 7.5 -A k_lms```

development branch


branch with fix

**Comment by skurovec** [comment]
@Vargol Any-Winter-4079 just commented, that he copied wrong seed, co images ARE consistent

**Comment by Any-Winter-4079** [comment]
Yeah, my bad. It was late and I copied the wrong seed haha

**Review by Any-Winter-4079 — APPROVED** [review]
LGTM

**Pull request merged**
