### PR TITLE
Fixed startup issues with the web UI.

### PR DESCRIPTION
**Pull request by JPPhoto**
Fixed an import statement for the web UI server.
Fixed the new `run_patches()` function to create destination directories if they don't exist.

### CODE REVIEW

**Comment by psychedelicious** [comment]
This is a duplicate of #2875

**Comment by blessedcoolant** [comment]
I fixed the import issue in #2875 but yours has another fix that needs to be made too. I will close my PR. Wouldn't it be better to import from `invokeai.frontend.merge`  rather than going relative?

Either works but just wondering. Closing my PR.

**Review by blessedcoolant — APPROVED** [review]

**Review by keturn — APPROVED** [review]
LGTM

**Review by psychedelicious — APPROVED** [review]
Model merging works w/ this change, ty

**Comment by JPPhoto** [comment]
> Wouldn't it be better to import from `invokeai.frontend.merge` rather than going relative?

@blessedcoolant It seemed that everything else in this file used relative syntax so I copied the pattern.

**Comment by blessedcoolant** [comment]
> > Wouldn't it be better to import from `invokeai.frontend.merge` rather than going relative?
> 
> @blessedcoolant It seemed that everything else in this file used relative syntax so I copied the pattern.

All good. Guess this needs a review from @lstein before it is mergeable.

**Pull request merged**
