### PR TITLE
feat(ui): improve error handling

### PR DESCRIPTION
**Pull request by psychedelicious**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [x] Yes
- [ ] No, because:

## Description

[feat(ui): add error handling for enqueueBatch route, remove sessions](https://github.com/invoke-ai/InvokeAI/commit/71e60f22a10991fe2675509a3c2b42f6a7d75804)

This re-implements the handling for the session create/invoke errors, but for batches.

Also remove all references to the old sessions routes in the UI.

[feat(ui): improve canvas image error UI](https://github.com/invoke-ai/InvokeAI/commit/9de23d7376a2598fd43e6c8ce336d95f7ece095b)

image

### CODE REVIEW

**Comment by psychedelicious** [comment]
@maryhipp Needs testing for 403 errors

**Comment by maryhipp** [comment]
A 403 correctly shows the error state 🔥

**Comment by maryhipp** [comment]
I had a canvas session and then deleted the image in question (had to reset my DB) - now the error state is there but the mask state is overlayed. I think it would make sense to remove the canvas state when this happens as well, but maybe not? Just something to point out
Screenshot 2023-09-26 at 9 51 00 AM

**Review by maryhipp — APPROVED** [review]

**Comment by psychedelicious** [comment]
@maryhipp the images may also fail to load due to network issue - for example, your internet drops and then you click the canvas tab. We can't reset the state when that happens.

To handle this intelligently I need to rewrite the was images are fetched and loaded into an HTML canvas (it's more complicated than you'd think)

**Pull request merged**
