### PR TITLE
performance: low-memory option for calculating guidance sequentially

### PR DESCRIPTION
**Pull request by keturn**
In theory, this reduces peak memory consumption by doing the conditioned and un-conditioned predictions one after the other instead of in a single mini-batch.

In practice, it doesn't reduce the reported "Max VRAM used for this generation" for me, even without xformers. (But it does slow things down by a good 18%.)

That suggests to me that the peak memory usage is during VAE decoding, not the diffusion unet, but ymmv. It does [improve things for gogurt's 16 GB M1](https://github.com/invoke-ai/InvokeAI/pull/2732#issuecomment-1436187407), so it seems worthwhile.

To try it out, use the `--sequential_guidance` option: https://github.com/invoke-ai/InvokeAI/blob/2dded6826742b7b3be3d09ec1d64231e632e24c3/ldm/invoke/args.py#L487-L492

### CODE REVIEW

**Comment by gogurtenjoyer** [comment]
Here's some statistics on my M1 Pro 16GB which is typically teetering on being memory-starved:

With `sequential_conditioning = False `:
>>   6 image(s) generated in 207.22s

with `sequential_conditioning = True `:
>>   6 image(s) generated in 133.00s

Full stats below:
```
with sequential_conditioning = False 
-----

100%|█████████████████████████████████████████████████████████████████████████| 22/22 [00:30<00:00,  1.39s/it]
100%|█████████████████████████████████████████████████████████████████████████| 22/22 [00:30<00:00,  1.19it/s]

>> Image generated: "/Users/gogurt_hater/invokeai-diffusers/InvokeAI/invokeai/outputs/img-samples/000043.7852ddcd.3168936092.png"

100%|█████████████████████████████████████████████████████████████████████████| 22/22 [00:23<00:00,  1.08s/it]
100%|█████████████████████████████████████████████████████████████████████████| 22/22 [00:23<00:00,  1.23it/s]

>> Image generated: "/Users/gogurt_hater/invokeai-diffusers/InvokeAI/invokeai/outputs/img-samples/000044.72f64de2.166843413.png"

100%|█████████████████████████████████████████████████████████████████████████| 22/22 [00:26<00:00,  1.22s/it]
100%|█████████████████████████████████████████████████████████████████████████| 22/22 [00:26<00:00,  1.22it/s]

>> Image generated: "/Users/gogurt_hater/invokeai-diffusers/InvokeAI/invokeai/outputs/img-samples/000045.120dbff5.1436095986.png"

100%|█████████████████████████████████████████████████████████████████████████| 22/22 [00:25<00:00,  1.16s/it]
100%|█████████████████████████████████████████████████████████████████████████| 22/22 [00:25<00:00,  1.22it/s]

>> Image generated: "/Users/gogurt_hater/invokeai-diffusers/InvokeAI/invokeai/outputs/img-samples/000046.f316c708.466999993.png"

100%|█████████████████████████████████████████████████████████████████████████| 22/22 [00:25<00:00,  1.15s/it]
100%|█████████████████████████████████████████████████████████████████████████| 22/22 [00:25<00:00,  1.23it/s]

>> Image generated: "/Users/gogurt_hater/invokeai-diffusers/InvokeAI/invokeai/outputs/img-samples/000047.e80cfcce.3740062591.png"

100%|█████████████████████████████████████████████████████████████████████████| 22/22 [00:26<00:00,  1.20s/it]
100%|█████████████████████████████████████████████████████████████████████████| 22/22 [00:26<00:00,  1.22it/s]

>> Image generated: "/Users/gogurt_hater/invokeai-diffusers/InvokeAI/invokeai/outputs/img-samples/000048.c22d68bf.1643234179.png"

Generating: 100%|███████████████████████████████████████████████████████████████| 6/6 [03:26<00:00, 34.34s/it]

>> Usage stats:
>>   6 image(s) generated in 207.22s



with sequential_conditioning = True 
-----

100%|█████████████████████████████████████████████████████████████████████████| 22/22 [00:24<00:00,  1.13s/it]
100%|█████████████████████████████████████████████████████████████████████████| 22/22 [00:24<00:00,  1.45it/s]

>> Image generated: "/Users/gogurt_hater/invokeai-diffusers/InvokeAI/invokeai/outputs/img-samples/000049.e6a2742b.3168936092.png"

100%|█████████████████████████████████████████████████████████████████████████| 22/22 [00:18<00:00,  1.18it/s]
100%|█████████████████████████████████████████████████████████████████████████| 22/22 [00:18<00:00,  1.46it/s]

>> Image generated: "/Users/gogurt_hater/invokeai-diffusers/InvokeAI/invokeai/outputs/img-samples/000050.51fcd2e0.166843413.png"

100%|█████████████████████████████████████████████████████████████████████████| 22/22 [00:16<00:00,  1.30it/s]
100%|█████████████████████████████████████████████████████████████████████████| 22/22 [00:16<00:00,  1.47it/s]

>> Image generated: "/Users/gogurt_hater/invokeai-diffusers/InvokeAI/invokeai/outputs/img-samples/000051.3efe2657.1436095986.png"

100%|█████████████████████████████████████████████████████████████████████████| 22/22 [00:16<00:00,  1.31it/s]
100%|█████████████████████████████████████████████████████████████████████████| 22/22 [00:16<00:00,  1.46it/s]

>> Image generated: "/Users/gogurt_hater/invokeai-diffusers/InvokeAI/invokeai/outputs/img-samples/000052.1ec8389d.466999993.png"

100%|█████████████████████████████████████████████████████████████████████████| 22/22 [00:18<00:00,  1.21it/s]
100%|█████████████████████████████████████████████████████████████████████████| 22/22 [00:18<00:00,  1.47it/s]

>> Image generated: "/Users/gogurt_hater/invokeai-diffusers/InvokeAI/invokeai/outputs/img-samples/000053.6788c389.3740062591.png"

100%|█████████████████████████████████████████████████████████████████████████| 22/22 [00:18<00:00,  1.22it/s]
100%|█████████████████████████████████████████████████████████████████████████| 22/22 [00:18<00:00,  1.46it/s]

>> Image generated: "/Users/gogurt_hater/invokeai-diffusers/InvokeAI/invokeai/outputs/img-samples/000054.9aaf6390.1643234179.png"

Generating: 100%|███████████████████████████████████████████████████████████████| 6/6 [02:10<00:00, 21.74s/it]

>> Usage stats:
>>   6 image(s) generated in 133.00s
```

Note: I'm using pytorch nightly from the 15th, which has some MPS speedups.

**Comment by keturn** [comment]
gogurt's results look good, so I think this is worth keeping.

I've added a command line flag for it, currently `--sequential_guidance`.

I'm ambivalent about it for a number of reasons:
- Is "sequential" the right word? Should it be "serial" instead?
- I'm okay with the internals (`Globals` and `InvokeAIDiffuserComponent`) using this technical name, but I fear it's too jargony and implementation-specific to be a user-facing configuration option. Should we call it something like `--low_mem` instead?
- Ideally we wouldn't rely on an esoteric configuration option at all, and we'd do it dynamically based on image size and maximum allowable RAM budget (like adjust_memory_efficient_attention tries to do), but I feel like that approach hasn't been very reliable for us, so we'll need to have an explicit option like this.

**Comment by keturn** [comment]
I was thinking I needed to write (or mark TODO) this in to the other "apply conditioning" method as well, for cross-attention control, but looking again I see that _always_ does the sequential method.

Not sure if that's happenstance, or because it has higher RAM requirements to start with, or if the cross-attention control implementation requires it to be run in that order.

In any case, I guess that means I can take this out of Draft now.

**Review by lstein — APPROVED** [review]
LGTM

**Review by damian0815 — APPROVED** [review]
Looks good. re naming, what about "unbatched"? because "parallel" is basically batch_size=2 attention processing

**Review by lstein — APPROVED** [review]

**Pull request merged**
