### PR TITLE
fix off by one error in ksampler steps

### PR DESCRIPTION
**Pull request by lstein**

### CODE REVIEW

**Comment by lstein** [comment]
This fixes Issue #900

**Comment by tildebyte** [comment]
Are we **certain** that this is an actual off-by-one, and not simply 20 steps from 0-19 vs 1-20?

We **are** in Python-land here, and EVERYTHING is zero-indexed.

**Comment by psychedelicious** [comment]
Ahh, much better :) looks good, thanks.

**Review by psychedelicious — APPROVED** [review]

**Comment by tildebyte** [comment]
I'm still very suspicious of this change.

**Comment by lstein** [comment]
Superseded by #925

**Pull request closed without merging**
