### PR TITLE
fix(nodes): respect nodes denylist

### PR DESCRIPTION
**Pull request by psychedelicious**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Description

In #5838 graph validation was updated to resolve the issue with the nodes union and import order. That broke the nodes denylist functionality.

However, because the corresponding test was marked as `xfail`, we didn't catch the issue.

- Fix the nodes denylist handling
- Update the tests

## QA Instructions, Screenshots, Recordings

The test coverage is sufficient.

## Merge Plan

This PR can be merged when approved

## Added/updated tests?

- [x] Yes
- [ ] No : _please replace this line with details on why tests
      have not been included_

### CODE REVIEW

**Comment by psychedelicious** [comment]
I think the test failure is related to how pytest scopes test runs. I'll pick this up later.

**Review by brandonrising — APPROVED** [review]

**Comment by lstein** [comment]
I have fixed the "test_deny_nodes()" test so that it doesn't interfere with later tests. The fix involved clearing the config cache after the test finishes running so that the `allow_nodes` and `deny_nodes` values are returned to their defaults, and also clearing `BaseInvocation._typeadapter` so that the cached graph typeadapter is returned to its default state. There is no public API for clearing the typeadapter, so I directly clear the protected `_typeadapter` attribute in the test. I debated whether it would be better to add a `clear_cached_typeadapter()` to the BaseInvocation API, but this seems like overkill.

**Review by lstein — APPROVED** [review]
LGTM

**Comment by psychedelicious** [comment]
Thanks! It looks like this picked up the config migrator though, need to wait for that to merge before this PR can merge

**Comment by lstein** [comment]
> Thanks! It looks like this picked up the config migrator though, need to wait for that to merge before this PR can merge. Or bring the changes in this PR into the config migrator PR.

Sorry - wonder how that happened?

**Comment by psychedelicious** [comment]
Superseded by #7235

**Pull request closed without merging**
