### PR TITLE
Outpainting extension

### PR DESCRIPTION
**Pull request by dominicletz**
Two changes here:
- Adding a new command prompt flag -D
- Default strength when using -D is upped to 0.83
- Added prompt parsing from the image supplied in -I if there is no prompt

This outpainting extension makes it easy to extend an existing generated image to any direction top,right,bottom,left. E.g. let's take this image of Erwin that I generated:

`dream> "Portrait of Erwin Smith from Attack On Titan, tone mapped, intricate, elegant, highly detailed, digital painting, artstation, concept art, smooth, sharp focus, illustration, art by artgerm and greg rutkowski and Alphonse mucha" -s50 -W448 -H448 -C7.5 -Aplms -G0.6 -F -S224862249`

And we want to extend it to the top so we can see his face:

`dream> -I ./erwin.png -D bottom -n 10`

Now we get a couple of extension candidates such as:

This is achieved in this PR by creating a masked image from the original image that is shifted to the half:

debug

In order to generate visually similar extensions the transparent area is actually filled with the flipped version of the original picture like this (the red area is actually fully transparent):

new_top_transparent

Additionally there is a 10% alpha channel dither in the middle of the picture that helps to avoid a visible or logical edge at the border of the transparent area. This helped a lot getting better images.

Finally the default strength value when using -D is upped to 0.83 as that improves image quality quite a bit. 

I feel there could be a even better way to generate a filling for the transparent area, might experiment with that more in the future.

### CODE REVIEW

**Comment by bmaltais** [comment]
Great PR. Looking forward to test it.

**Comment by i3oc9i** [comment]
@bmaltais 
you can easily test this  PR, 
 
you do
`git checkout development`

then you do
`gh pr checkout 489`

you will get a local`utpainting_extension` branch to have fun.

**Comment by lkewis** [comment]
This is fantastic, working really well from my testing and a huge time saver

**Comment by lstein** [comment]
This is a great step forward. However, I'm having a bit of a problem with images that only need to be extended by a small amount. For example, here is a reindeer girl, whose antlers are cropped at the top:



I'd like to extend the antlers upwards by just a little bit (like 30 pixels), but when I specify -D top I get this:


and when I specify -D bottom I get that:


This sort of thing happens regardless of whether or not I specify the same text prompt used to generate the original image (which was *reindeer girl, digital art, soft focus, artstation*)

Would you consider an alternative in which you indicate the number of pixels to extend? The syntax would be:
~~~~
dream> -I ./reindeer-girl.png -D top 64
~~~~

By which I mean to extend the top by 64 pixels (has to work in multiples of 64). This would avoid having to shift the entire image up or down by half. 

If you're willing to dig in more deeply, I think a general solution is to noise the area up the extended area with latent noise in the same way that txt2img does. There are examples to follow in the [AUTOMATIC1111)[https://github.com/AUTOMATIC1111/stable-diffusion-webui] fork.

**Review by lstein — CHANGES_REQUESTED** [review]
Give option to shift image by less than half, to make it easier to fill in smaller cropped areas.

**Comment by thealanle** [comment]
@dominicletz 
This is super fun! One thing I noticed is that your additions to `dream.py` are called whenever an `init_img` is passed, even if the user isn't using your outpainting extension technique:

```
if opt.init_img:
    try:
        im = Image.open(opt.init_img)
        # '-F' argument appears (M1) in the dream prompt even though
        # it's not a main loop argument
        oldprompt = im.text['Dream'].replace(" -F", "")
        oldargs = parser.parse_args(shlex.split(oldprompt))
        if len(opt.prompt) == 0:
            opt.prompt = oldargs.prompt
```

This has the consequence that the metadata from `opt.init_img` is being read and parsed even if it doesn't need to be used. It seems reasonable to check `opt.prompt` at the start of your code block, rather than toward the end. 

```
if opt.init_img and not opt.prompt:
    try:
        im = Image.open(opt.init_img)
        # '-F' argument appears (M1) in the dream prompt even though
        # it's not a main loop argument
        oldprompt = im.text['Dream'].replace(" -F", "")
        oldargs = parser.parse_args(shlex.split(oldprompt))
        opt.prompt = oldargs.prompt
```
You could even restrict this to be used only with your outpainting extension by requiring `opt.out_direction` in the conditional too.

In my case, I needed to supply new prompts because (I think) an earlier version of the webserver was not correctly writing the command metadata to the images. Your code was crashing `dream.py` when parsing an image with malformed metadata, even if a new prompt was supplied.

I also found it pretty handy to use a different prompt for the outpainting extension rather than the original prompt from the `init_img`, especially when working with character portraits, otherwise you end up with faces where torsos should be. 

In any case, I was able to go from `Portrait of a well dressed dinosaur, vivid animal portrait, holi dye, in the style of Pedro Correa and Greg Rutkowski`:


to this (original + top + bottom blended with a gradient layer mask in Photoshop):
000006 3109216953-outpaint

It's a bit seam-y and loses some of the original style, but I'd call that a usable result! I'm definitely interested in seeing how different approaches to filling with noise prior to outpainting can help with cohesion, especially with regard to style.

**Comment by dominicletz** [comment]
> In my case, I needed to supply new prompts because (I think) an earlier version of the webserver was not correctly writing the command metadata to the images. Your code was crashing `dream.py` when parsing an image with malformed metadata, even if a new prompt was supplied.

It should definitely not crash, and your comment about sometimes requiring different prompts is spot-on. I've pushed on change a bit later that should fix the crashes - there is a second `except` clause now. But if this is creating more trouble I think the feature could be removed. It's convenience only anyway.

**Comment by dominicletz** [comment]
> By which I mean to extend the top by 64 pixels (has to work in multiples of 64). This would avoid having to shift the entire image up or down by half.
> 
> If you're willing to dig in more deeply, I think a general solution is to noise the area up the extended area with latent noise in the same way that txt2img does. There are examples to follow in the [AUTOMATIC1111)[https://github.com/AUTOMATIC1111/stable-diffusion-webui] fork.

Definitely should be able to specify by how much to extend. The number of pixels is actually a better idea than the percentage I was thinking of before. Will definitely add that. For the noise thanks for the pointer will check it out. Might take some time though, this week is busy

**Comment by dominicletz** [comment]
> to this (original + top + bottom blended with a gradient layer mask in Photoshop):

On combining the images: The new image will always blend into the original image pixel perfectly - so best is to put the original "below" and the new image "on top" so the gap is bridged by the new image. That should result in an edge free result. 

Should be straight forward to write a script that combines the generated images based on their `-D` and `-I` parameters to one large image. Might try that...

**Comment by lstein** [comment]
@dominicletz just checking in. Will you be working more on this? I think the minimum viable product is to allow the image offset to be set to a specified number of pixels (or even a percentage) rather than the full 50%. The latent noise stuff can be added later as part of an enhancement to inpainting in general.

**Comment by dominicletz** [comment]
Yep will add the pixel offset

**Comment by dominicletz** [comment]
@lstein I think it's good to go. `-D <direction> (<pixels>)` is now working. That said I think there is some other regression on the newest development as I'm getting only black images on my M1 now :-(

**Comment by Any-Winter-4079** [comment]
Testing this currently on M1.

**Comment by dominicletz** [comment]
> First, it is awesome. Just to nitpick/inquire, I lose a bit of the bottom of the image when I outpaint to the top.

Yes, this is expected. In order to keep the memory usage constant, the image is really shifted to the number of pixels specified. So result size is always the same as the original. This allows keeping extending an image in multiple steps

**Comment by Any-Winter-4079** [comment]
> > First, it is awesome. Just to nitpick/inquire, I lose a bit of the bottom of the image when I outpaint to the top.
> 
> Yes, this is expected. In order to keep the memory usage constant, the image is really shifted to the number of pixels specified. So result size is always the same as the original. This allows keeping extending an image in multiple steps

Maybe they could be merged after the new image is created? Example:

- Chosen sampler to create 448,448.
- Then -I and -D 64 with img above.
-  Chosen sampler is ran to create 448,448.
- Images are merged at the end, to save a 512,448 file to disk.

I'm just asking in case that helps with the thin line I see overlapping them manually.

**Comment by dominicletz** [comment]
> Another thing that may be ironed out later is the output does not include the -D option

Good catch the should definitely be fixed. It seems I anyway need to rebase again, because since this morning there are two new merge conflicts:-)

**Comment by lstein** [comment]
I'm working through the backlog of PRs. This is the next on the list.

**Comment by krummrey** [comment]
Has anyone tried to use the [OpenCV inpaint](https://docs.opencv.org/3.4/df/d3d/tutorial_py_inpainting.html) to fill the empty space?

**Pull request merged**
