### PR TITLE
Logging Improvements

### PR DESCRIPTION
**Pull request by blessedcoolant**
This PR improves the logging module a tad bit along with the documentation.

**New Look:**

WindowsTerminal_XaijwCqFpo

## Usage

**General Logger**

InvokeAI has a module level logger. You can call it this way.

In this below example, you will use the default logger `InvokeAI` and all your messages will be logged under that name.

```python

from invokeai.backend.util.logging import logger

logger.critical("CriticalMessage") // In Bold Red
logger.error("Info Message") // In Red
logger.warning("Info Message") // In Yellow
logger.info("Info Message") // In Grey 
logger.debug("Debug Message") // In Grey
```

Results:

```
[12-05-2023 20]::[InvokeAI]::CRITICAL --> This is an info message [In Bold Red]
[12-05-2023 20]::[InvokeAI]::ERROR --> This is an info message [In Red]
[12-05-2023 20]::[InvokeAI]::WARNING --> This is an info message [In Yellow]
[12-05-2023 20]::[InvokeAI]::INFO --> This is an info message [In Grey]
[12-05-2023 20]::[InvokeAI]::DEBUG --> This is an info message [In Grey]
```

**Custom Logger**

If you want to use a custom logger for your module, you can import it the following way.

```python

from invokeai.backend.util.logging import logging
logger = logging.getLogger(name='Model Manager')

logger.critical("CriticalMessage") // In Bold Red
logger.error("Info Message") // In Red
logger.warning("Info Message") // In Yellow
logger.info("Info Message") // In Grey 
logger.debug("Debug Message") // In Grey
```

Results:

```
[12-05-2023 20]::[Model Manager]::CRITICAL --> This is an info message [In Bold Red]
[12-05-2023 20]::[Model Manager]::ERROR --> This is an info message [In Red]
[12-05-2023 20]::[Model Manager]::WARNING --> This is an info message [In Yellow]
[12-05-2023 20]::[Model Manager]::INFO --> This is an info message [In Grey]
[12-05-2023 20]::[Model Manager]::DEBUG --> This is an info message [In Grey]
```

**When to use custom logger?**

It is recommended to use a custom logger if your module is not a part of base InvokeAI. For example: custom extensions / nodes.

### CODE REVIEW

**Review by ebr — APPROVED** [review]
:heart_eyes:

**Comment by psychedelicious** [comment]
Any reason to make DEBUG and INFO the same colour? Prefer if they are different

**Comment by blessedcoolant** [comment]
> Any reason to make DEBUG and INFO the same colour? Prefer if they are different

General format. Debug and Info are meant to be the same state of message -- one meant for dev logging and the other for user info logging. But I don't think anyone will go on strike if we change colors. If you have a color in mind, let me know. I'll look up what is compatible with the consoles.

**Comment by psychedelicious** [comment]
I'm used to the log level strategy where log levels are like degrees of severity/importance

TRACE (DEBUG wasn't enough and you want EVERYTHING to be logged, -vv)

DEBUG/VERBOSE (used when something isn't working as expect but no errors and you want to figure it out, -v)

INFO (normal operation logging, default setting)

WARN (something seems off but isn't a show stopper)

ERROR (something went wrong but the app still works)

FATAL/CRITICAL (app cannot recover)

There is often like the opposite of -v where you only show warnings and above or errors and above

So each log level would have a diff style/color temperature

Anyways rambling about log levels but ya diff colors make it much easier to see get a handle on the state of things at a glance

**Comment by blessedcoolant** [comment]
@psychedelicious Changed debug messages to cyan/blue.

WindowsTerminal_JYKvQwe9U1

**Review by lstein — APPROVED** [review]
Looks nice!

**Pull request merged**
