### PR TITLE
Write prompts in >300 non-English languages

### PR DESCRIPTION
**Pull request by lstein**
translate-cropped

## What type of PR is this? (check all applicable)

- [ X] Feature

## Have you discussed this change with the InvokeAI team?
- [X ] Yes - many months ago

## Have you updated all relevant documentation?
- [ ] Yes
- [X ] No - needs discussion whether this is a good thing to put up - see caveats

## Description
This is a very simple invocation that uses the Python `translators` package to detect and translate ~380 different languages into English for passing to the Compel node. The example here shows the Punjabi for "banana sushi tastefully arranged with flowers".

Detection of the source language is automatic. If desired a source language selection menu could be added to the UI. If the `translators` package is not installed, a message appears in the text box advising the user on how to install it.

The caveat here is that translators uses a variety of Internet servers to do the translations, which means that the user's prompts will be sent to untrusted servers, including some in China.

### CODE REVIEW

**Comment by hipsterusername** [comment]
Yeah, don't love the non-local/untrusted servers aspect. I think this is a great option for folks though - Maybe it should be a community node?

**Comment by lstein** [comment]
> Yeah, don't love the non-local/untrusted servers aspect. I think this is a great option for folks though - Maybe it should be a community node?

How do I make a community node?

**Comment by hipsterusername** [comment]
It would, I'm just leery of having a core node that comms to untrusted servers

**Comment by psychedelicious** [comment]
Agree that this is probably better suited as a community node - I don't trust translation services with our users' data. I'm sure it's mostly fine, but just makes me feel a bit uneasy.

It's a great idea though!

**Comment by lstein** [comment]
> Agree that this is probably better suited as a community node - I don't trust translation services with our users' data. I'm sure it's mostly fine, but just makes me feel a bit uneasy.
> 
> It's a great idea though!

How about if the translation feature can be turned on and off in the core, default to off? I'm just looking for "wow" factors that will distinguish us from A1111 and other competitors.

**Comment by hipsterusername** [comment]
Most of the "wow factors" in other projects are community extensions that get adopted. Think we just need to maintain an easy way for people to discover the most common/useful of these.

CC: @Millu

**Comment by lstein** [comment]
> 

Is there a better way to distribute these extensions beyond posting them on the Discord community nodes channel?

**Pull request closed without merging**
