### PR TITLE
Allows inpainting in GUI to work on devices

### PR DESCRIPTION
**Pull request by mikedg1**
The inpainting stage was only using mouse events. Added support for touch events. Tested in Chrome on MacOS using dev tools to simulate mobile, as well as Chrome on a Galaxy Fold 3

### CODE REVIEW

**Review by psychedelicious — CHANGES_REQUESTED** [review]
Thanks @mikedg1 . I've tested this and confirmed the actual drawing does work. 

There is a problem when moving/resizing the bounding box - it also draws. Probably, we should add a piece of state `isTransformingWithTouch` to gate the drawing logic. 

But - I won't ask for you to fix this (unless you really want to) because:
- Our next release will substantially upgrade the canvas to support outpainting and it also handles things a bit differently
- There is a workaround - namely you can undo after transforming the bounding box to undo the unintentional brush strokes - so I'd say this simple change is good enough for now.

One thing I will request is a `yarn build` - we do not have CI/CD working so an updated bundle needs to accompany PRs. Thanks again.

**Review by lstein — CHANGES_REQUESTED** [review]
Please run `yarn build` to rebuild the frontend and add the commit to this PR. I'll then merge it unless someone else gets to it first.

**Comment by mikedg1** [comment]
Ran npm run build. That should be equivalent to the yarn build right? It's been a while since I did frontend dev.
Also, it looks like frontend/dist is .gitignore'd, did I include everything needed to be updated in the PR?

**Comment by bbecausereasonss** [comment]
This is so needed

**Comment by psychedelicious** [comment]
> Ran npm run build. That should be equivalent to the yarn build right? It's been a while since I did frontend dev. Also, it looks like frontend/dist is .gitignore'd, so I manually added the changed index.*.js. Did I mess up some step?

That's fine for just the build, but FYI they do create different frozen dependency files. For this project, we are using yarn. If you had changed the dependencies, we'd need you to use yarn.

`frontend/dist` is `.gitignore`'d in the repo root `.gitignore`, but there is another `.gitignore` in `frontend` which manages that directory; these files should definitely not be `.gitignore`'d by git...

**Comment by psychedelicious** [comment]
Ok, I'm not sure what happened with the .gitignore but the build is fine @mikedg1 . Thank you! 

@lstein Approved.

**Review by psychedelicious — APPROVED** [review]

**Comment by lstein** [comment]
I see that these fixes have been integrated. Can I close the PR?

**Comment by psychedelicious** [comment]
@lstein 
> I see that these fixes have been integrated. Can I close the PR?

Yes fine to close, this was cherry picked into the 2.2 web ui pr branch.

**Comment by lstein** [comment]
Closing as per @psychedelicious

**Pull request closed without merging**
