### PR TITLE
{release} 4.0.0rc1

### PR DESCRIPTION
**Pull request by brandonrising**
## What type of PR is this? (check all applicable)

Release - Invoke 4.0.0-rc1

## Have you discussed this change with the InvokeAI team?
- [x] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [ ] Yes
- [ ] No

## Description
InvokeAI 4.0.0-rc1 Release

## QA Instructions, Screenshots, Recordings
Test Installer: 
[InvokeAI-installer-v4.0.0.zip](https://github.com/invoke-ai/InvokeAI/files/14544185/InvokeAI-installer-v4.0.0.zip)

## Merge Plan

This PR can be merged when approved

## Added/updated tests?

- [ ] Yes
- [ ] No : Release PR, all changes have associated testing

### CODE REVIEW

**Review by psychedelicious — COMMENTED** [review]
Expect this will fail the workflow bc the version won't match the tag exactly

**Comment by brandonrising** [comment]
> Expect this will fail the workflow bc the version won't match the tag exactly

should we switch to a v in front

**Comment by hipsterusername** [comment]
Yes, think so

**Comment by psychedelicious** [comment]
The `tag_release.sh` script already appends `v` to the version, so for this release the tag will be `v4.0.0rc1`.

**Review by hipsterusername — APPROVED** [review]

**Pull request merged**
