### PR TITLE
Only run workflows on the main respository, not on forks.

### PR DESCRIPTION
**Pull request by dsully**
Only run workflows on the main repository, not on forks.

### CODE REVIEW

**Comment by mauwii** [comment]
Sorry, but I want to have the workflows also running on my Fork. I already played around with this (https://github.com/invoke-ai/InvokeAI/pull/2559), but was running into the problem that the PR-Verification did not trigger then ...

**Comment by dsully** [comment]
Ok.. I keep getting `mkdocs` and other workflow failures when I push to my fork.

**Comment by mauwii** [comment]
So don't get me wrong, I like the Idea that the workflows don't run automatically on Forks a lot, but it should be possible to run them optionally without the needs to change the workflow files.

**Comment by dsully** [comment]
In that case, adding https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow and logic around that might solve the problem you're describing?

**Comment by mauwii** [comment]
Why don't you just disable the Workflows in your Fork?

Go to Actions, select a workflow, in the top right you can disable it:

image

**Comment by dsully** [comment]
Ha. Yes, I can do that instead..

**Pull request closed without merging**
