### PR TITLE
New IP-Adapter model type (`IPAdapterPlusXL`)

### PR DESCRIPTION
**Pull request by RyanJDick**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [x] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [ ] Yes
- [ ] No

## Description

Add support for IPAdapterPlusXL based on https://github.com/tencent-ailab/IP-Adapter/commit/6219530507cb4696a0496f10c0e5a4f1dbdc7672.

This is required to support the new IP-Adapter model here: https://huggingface.co/InvokeAI/ip-adapter-plus_sdxl_vit-h

## QA Instructions, Screenshots, Recordings

I tested manually that all of the IP-Adapter models here still work: https://huggingface.co/InvokeAI

## Added/updated tests?

- [ ] Yes
- [x] No : Model dependent tests are coming soon, but not here yet.

### CODE REVIEW

**Comment by hipsterusername** [comment]
@RyanJDick keeping light model separate?

**Review by hipsterusername — APPROVED** [review]

**Comment by RyanJDick** [comment]
> @RyanJDick keeping light model separate?

The `ip-adapter_sd15_light.bin` model actually uses the standard `IPAdapter` architecture, so no new model is needed to run it. The only description I've found of what is meant by 'light' is in the [commit message](https://huggingface.co/h94/IP-Adapter/commit/94e28fff1b6932cada2f95358d7191eca2106001): "`add the light version of ip-adapter (more compatible with text even scale=1.0)`"

**Comment by hipsterusername** [comment]
Yep - Looks like it does `just work`

**Comment by hipsterusername** [comment]
@RyanJDick - Think I merged this prematurely.

[2023-10-04 22:48:00,108]::[InvokeAI]::ERROR --> Error while invoking:
Unexpected IP-Adapter model format: C:\Users\kentr\Invoke\models\sdxl\ip_adapter\ip_adapter_plus_sdxl_vit_h

**Comment by RyanJDick** [comment]
> @RyanJDick - Think I merged this prematurely.
> 
> [2023-10-04 22:48:00,108]::[InvokeAI]::ERROR --> Error while invoking: Unexpected IP-Adapter model format: C:\Users\kentr\Invoke\models\sdxl\ip_adapter\ip_adapter_plus_sdxl_vit_h

@hipsterusername How did you install that model? The name is different than the `InvokeAI/ip-adapter-plus_sdxl_vit-h` repo name. The name itself doesn't matter, but I'm wondering if the directory contents might be incorrect.

**Comment by hipsterusername** [comment]
> > @RyanJDick - Think I merged this prematurely.
> > [2023-10-04 22:48:00,108]::[InvokeAI]::ERROR --> Error while invoking: Unexpected IP-Adapter model format: C:\Users\kentr\Invoke\models\sdxl\ip_adapter\ip_adapter_plus_sdxl_vit_h
> 
> @hipsterusername How did you install that model? The name is different than the `InvokeAI/ip-adapter-plus_sdxl_vit-h` repo name. The name itself doesn't matter, but I'm wondering if the directory contents might be incorrect.

Pulled from the GH repo. I can delete and retest this morning

**Pull request merged**
