### PR TITLE
Respect http[s] protocol when making socket.io middleware

### LINKED ISSUE #973: frontend does not respect security (`https`) of base URL
I'm trying to run on a runpod.io instance, but the frontend's socket communications doesn't seem to be respecting the security/protocol of the base URL:

```
Mixed Content: The page at 'https://<uuid>-<port>.proxy.runpod.io/' was loaded over HTTPS, but requested 
an insecure XMLHttpRequest endpoint 
'http://<uuid>-<port>.proxy.runpod.io/socket.io/?EIO=4&transport=polling&t=OEoR1LP'. 
This request has been blocked; the content must be served over HTTPS.
```

(This is running against current `development` branch).

The workaround is to do SSH tunnelling, but you pay more on runpod for an instance that allows that.

### PR DESCRIPTION
**Pull request by damian0815**
Closes #973

### CODE REVIEW

**Review by psychedelicious — CHANGES_REQUESTED** [review]
The splitting of hostname and port is a remnant of old code. Let's just do this:

```javascript
  const { origin } = new URL(window.location.href);

  const socketio = io(origin, {
    timeout: 60000,
  });
  ```

Can you please update the PR accordingly? I cannot make code suggestions.

**Comment by damian0815** [comment]
try that

**Review by psychedelicious — APPROVED** [review]
Just tested the revision, all good. Thanks!

**Comment by ookami125** [comment]
This change also worked for me getting it to run in docker behind traefik.

**Comment by colemickens** [comment]
Would it be appropriate to go ahead and regenerate the frontend and commit it, since that's a thing that's going on in this repo?

Very surprised this isn't merged or affecting more folks.

**Comment by gfosco** [comment]
Ran into this and resolved it a bit differently, replacing `http://` with just `//`.. but this origin change is better.

:+1:

**Comment by hipsterusername** [comment]
@damian0815 - Can you rebase and also do a yarn build? I'll merge once everything is ready

**Comment by damian0815** [comment]
on it

**Comment by hipsterusername** [comment]
@damian0815 - It's possible that @psychedelicious already took care of it. Mentioned that his bundle includes these changes. Given that, if you rebase, I'll go ahead and merge

**Comment by damian0815** [comment]
@hipsterusername rebased and yarn built

**Review by hipsterusername — APPROVED** [review]

**Pull request merged**
