### PR TITLE
Better AMD clarification

### PR DESCRIPTION
**Pull request by cosmii02**
To better clarify that AMD is supported when using linux

### CODE REVIEW

**Comment by keturn** [comment]
I haven't run on AMD myself. Do we need to mention something about ROCm? my impression is that this doesn't just work on a plain Ubuntu install.

**Comment by cosmii02** [comment]
Well yeah, but this is hw compatibility listing

**Review by lstein — APPROVED** [review]
Thank you. 

Yes, we do need a ROCm install section, as it is a bit of a challenge to get running. I am planning to write this, as I have an AMD system.

**Comment by cosmii02** [comment]
@lstein Would you like to collaborate with the amd documentation making? I'm open to help 😀

**Comment by lstein** [comment]
> @lstein Would you like to collaborate with the amd documentation making? I'm open to help grinning

I can certainly use the help! How about I open up a PR containing a new mostly blank AMD document that you can edit and push back?

**Comment by cosmii02** [comment]
> > @lstein Would you like to collaborate with the amd documentation making? I'm open to help grinning
> 
> I can certainly use the help! How about I open up a PR containing a new mostly blank AMD document that you can edit and push back?

Sure :)

**Comment by lstein** [comment]
> > > @lstein Would you like to collaborate with the amd documentation making? I'm open to help grinning
> > 
> > 
> > I can certainly use the help! How about I open up a PR containing a new mostly blank AMD document that you can edit and push back?
> 
> Sure :)

@cosmii02 
I've created a new, empty document for describing how to install the CUDA and ROCm drivers. It is `docs/installation/030_INSTALL_CUDA_AND_ROCM.md`, and part of the draft PR at #2564 . You can copy the header and follow the format used in the other documentation files.

If you write the ROCm part, I can write the CUDA part. I'm also happy for you to write both sections!

Let me know if you have any issues.

**Comment by lstein** [comment]
No worries. I used your container text and added pointers to the bare-metal installers. I'd greatly appreciate it if you could review the 030_INSTALL_CUDA_AND_ROCM.md file in PR #2564 and let me know if there are any mistakes or areas of improvement.

**Pull request merged**
