### PR TITLE
improve UI of textual inversion frontend

### PR DESCRIPTION
**Pull request by lstein**
- File selection box now accepts directories that don't exist yet.
- Fixed crash when resume is selected and no files available to resume from.

### CODE REVIEW

**Comment by hipsterusername** [comment]
Are there docs to test this yet, or would you like to merge and test in main?

**Comment by lstein** [comment]
> Are there docs to test this yet, or would you like to merge and test in main?

I'll write up the docs and add to the PR, then let you know when it is ready for testing.

**Comment by lstein** [comment]
@hipsterusername I've added documentation and made a few bug fixes to the textual inversion support. Please review when you have the chance.

**Review by hipsterusername — APPROVED** [review]
great interface!

**Pull request merged**
