### PR TITLE
perf: remove TypeAdapter if has use validate_assignment.

### PR DESCRIPTION
**Pull request by vvanglro**
Simple test example:
```py
from datetime import date, datetime
from timeit import timeit

from pydantic import TypeAdapter


def parse_obj(annot, value):
    ta = TypeAdapter(annot)

    result1 = timeit(lambda: ta.validate_python(value), number=10000)
    result2 = timeit(lambda: TypeAdapter(annot).validate_python(value), number=10000)

    print(f'{annot.__name__:<8} {result2 / result1:.2f}')


if __name__ == '__main__':
    for t, v in (
        (int, "0"),
        (float, '0.5'),
        (str, b"123"),
        (bool, 'true'),
        (date, '2024-01-01'),
        (datetime, '2024-01-01T00:00:00'),
    ):
        parse_obj(t, v)
```
output:
```sh
int      131.77
float    107.20
str      109.12
bool     128.88
date     283.73
datetime 272.90
```

Refer to: https://docs.pydantic.dev/latest/concepts/performance/#typeadapter-instantiated-once

### CODE REVIEW

**Review by psychedelicious — COMMENTED** [review]
Is there a measurable impact on the application's performance with this change? We don't call `parse_args()` very often - just at startup I believe.

It's hard to say no to faster startup, but I'm curious if there this does anything in practice besides add a few lines of code.

**Comment by vvanglro** [comment]
> Is there a measurable impact on the application's performance with this change? We don't call `parse_args()` very often - just at startup I believe.
> 
> It's hard to say no to faster startup, but I'm curious if there this does anything in practice besides add a few lines of code.

If the TypeAdapter has to be instantiated every time it is used, there will be a performance impact, and as stated in the documentation, it is possible to modify the number of times the test script is run to see this change.

For now, it's just a startup call, so it's not a big performance hit. But I think this is a usage specification, so if you want to use TypeAdapter in a function, you can just introduce it into the function.

**Comment by psychedelicious** [comment]
I understand that that the change is objectively going to be a performance improvement, but I'm asking about the magnitude of benefit.

**Review by psychedelicious — CHANGES_REQUESTED** [review]
I don't think `TypeAdapter` is even necessary here.

This model uses `validate_assignment=True`, so setting the CLI args is already automatically validated by pydantic. The `TypeAdapters` are extraneous.

**Comment by vvanglro** [comment]
> I understand that that the change is objectively going to be a performance improvement, but I'm asking about the magnitude of benefit.

Depends on how many times the TypeAdapter is called in the code. Take 100 times as an example. Here are the gain multipliers for different types
```sh
int      0.15
float    15.17
str      19.41
bool     18.27
date     30.53
datetime 45.37
```

**Comment by vvanglro** [comment]
> I don't think `TypeAdapter` is even necessary here.
> 
> This model uses `validate_assignment=True`, so setting the CLI args is already automatically validated by pydantic. The `TypeAdapters` are extraneous.

I'm sorry, but I have not investigated the use of this model in the project and cannot give a conclusion.

**Comment by psychedelicious** [comment]
> Depends on how many times the TypeAdapter is called in the code. Take 100 times as an example. Here are the gain multipliers for different types

Sorry, to be clear, I'm asking if the change has a measurable impact on this project. It's OK if you haven't profiled it, was just curious.

> I'm sorry, but I have not investigated the use of this model in the project and cannot give a conclusion.

I believe it is not needed, because calling `setattr` on a pydantic model with `validate_assignment=True` will get runtime type checking.

If you can explain why it _is_ needed, then we can accept this PR as a minor performance enhancement.

Otherwise, the actual change that is needed is to remove the usage of `TypeAdapter` entirely bc it isn't doing anything. Thanks to your PR that this deeper issue was recognized.

**Comment by vvanglro** [comment]
> I believe it is not needed, because calling `setattr` on a pydantic model with `validate_assignment=True` will get runtime type checking.

I tested the behavior of validate_assignment.

> Otherwise, the actual change that is needed is to remove the usage of `TypeAdapter` entirely bc it isn't doing anything. Thanks to your PR that this deeper issue was recognized.


Yes, I agree.

**Review by psychedelicious — APPROVED** [review]
Thanks for fixing the deeper issue here

**Pull request merged**
