### PR TITLE
Fix test-invoke-pip.yml

### PR DESCRIPTION
**Pull request by mauwii**
I Finaly managed to make a windows runner generate images :godmode: Unfortunatelly it is only working with the CPU Version since they are somehow to low-spec to even install the 2+GB CUDA Packages relieable (it works sometimes, where I guess it depends on the runner you "win" ...). Changes include:

test-invoke-pip:
- add workflow_dispatch to enable manual execution
- disable windows-cuda since the 2GB pip packages just work sometimes
- add macos-nightly but disable for now
- set PIP_USE_PEP517 to enable it in all pip related steps
- enable caching pip packages in setup-python action
- add installation of optional test dependencies
- add pytest step
- set INVOKE_OUTDIR and huggingface-cache-dir via python commands
- fix huggingface-models cache and load after pytests succeeded
- remove `--full-precision` since detected automatically
  - if there would come gpu runners available they would be used ootb
- rename step `Run the tests` to `run invoke`
- set runner specific outdir in `run invoke`
- fix Archive results step and also combine all results into one archive

.gitignore:
- add `configs/models.yaml.orig`
- add `junit/`

model_manager.py:
- read the file(s) in chunks since otherwise the windowsrunner almost always fails in calculating the hash

### CODE REVIEW

**Review by ebr — CHANGES_REQUESTED** [review]
FYI, once again, there will be some conflicts with https://github.com/invoke-ai/InvokeAI/pull/2448, so once again I would ask to please hold this PR until the installer one is merged.

scripts renamed, e.g.: https://github.com/invoke-ai/InvokeAI/pull/2448/files#diff-4d030697b69f24398b98cfd8f0aedc9ed35b864073d452b1c9c7b063d633708fR115

gitignore conflict: https://github.com/invoke-ai/InvokeAI/pull/2448/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947R75, + `configs` are being moved anyway

`skip_normalize` default is properly set here: https://github.com/invoke-ai/InvokeAI/pull/2448/files#diff-ebf3d607fb377ab6e44bacb6022f8912c1409ef461d4e40269bbab047078cf09R292

**Comment by mauwii** [comment]
> `skip_normalize` default is properly set here: https://github.com/invoke-ai/InvokeAI/pull/2448/files#diff-ebf3d607fb377ab6e44bacb6022f8912c1409ef461d4e40269bbab047078cf09R292

I did not want to set a default there since I thought there is a reason that it has not been enabled/disabled per default 🙈

And I just opened the PR since I was working on this over the last couple days and thought it could be useful to finally be able to confirm that that a PR would work on Windows as well, but I don't have any problems if this will be merged after #2448

**Comment by mauwii** [comment]
@ebr: I see that you requested changes, but I cannot see which changes you requested :-/

**Comment by mauwii** [comment]
after doing a misstake by rebaseing this PR, I will create a fresh PR once #2448 is merged

**Pull request closed without merging**
