### PR TITLE
Outpainting WebUI

### PR DESCRIPTION
**Pull request by SieR-VR**
Still working in progress, but I wanted to share my working progress with contributors.

- [x] Default canvas implementation (moving, zooming)
- [x] Drawing implementation
- [x] Inpainting function
- [ ] Outpainting function
- [ ] Accept Kyle's feedback (new)
  - [x] Mouse cursor based zoom
  - [x] Spacebar + drag movement
  - [ ] Undo/Redo
  - [ ] Retry for inpainting
  - [ ] Brush outline
  - [ ] Automatically remove mask
  - [ ] Using transparent grid instead of true transparent
  - [ ] More color guide other than alpha
  - [ ] Blurring edge
  - [ ] Easier saving image

~~Painting area highlight~~
~~Connect to outpainting python backend~~
~~Function work~~

(strikethrough is deprecated goal)

And question, my implementation uses default html5 canvas. Are you planning to use css render/other canvas library?
I'm not sure with my method.

### CODE REVIEW

**Comment by lstein** [comment]
Thanks for working on this! I had to rebuild the frontend using `yarn build` before the changes took effect, but now I'm getting the following screen when I try the `outpainting` tab. There doesn't seem to be a way to import an image, nor is there an obvious canvas. Is this expected at this stage?

I did try importing an image to `img2img`, but it didn't change the outpainting screen.

Screenshot from 2022-10-16 11-19-50

**Comment by SieR-VR** [comment]
Yes this expected. Can I use this native html canvas?

**Comment by lstein** [comment]
@Kyle0654 and @psychedelicious are working together on inpainting and outpainting support. I'll defer to them on this issue.

**Comment by psychedelicious** [comment]
https://github.com/invoke-ai/InvokeAI/pull/1126/commits/98d9d06886e1da1f1b5d1b09d76187e5d63d3187#diff-672fed13456cecc095659413af283c7203d2bf7943938f20aaee896db6bceb7aR85-R88

Can you please add a `isSpacebarHeld` boolean to determine if we pan the canvas vs draw? So, if I hold spacebar and mouseMove, it moves the canvas.

Trackpad users and touchpad users may not be able to use the `e.button` (I cannot, do not own a mouse). This is also consistent with image editors.

I started doing this a while ago but never got to it. Ty

**Comment by Kyle0654** [comment]
Some feedback:
* Zoom on mousewheel feels like it should zoom toward the mouse. I.e. pin the canvas at the mouse cursor and zoom in/out around that point, rather than the center of the canvas.
* I agree, spacebar + drag would be good for pan. I tried left and mouse button to pan as well, and didn't expect middle mouse button.
* Undo/redo would be great.
* A brush shape/size outline where the cursor is would be really helpful.
* It ran fine when I invoked, but I had to switch to outpaint and back to inpaint to see the new image.
* Being able to change the background color (or use the standard "transparent" grid) would be helpful - I was inpainting something pretty close to the background color and it was tough.
* In the future, it may be helpful to consider having two layers. An alpha layer for "paint this area" and a separate layer for painting "base color" (which can help guide inpainting in the direction you want).
* Blurring edges can be super helpful, especially with outpainting. It can also help to do another inpaint over outpainting edges. I can show you the algorithm I came up with if you'd like (or just bake it into a node).

**Comment by psychedelicious** [comment]
Hmm, a good chunk of @Kyle0654 's feedback I had already solved in my work on inpainting: https://github.com/psychedelicious/stable-diffusion/tree/wip-webui-inpainting

I just built a fresh bundle for that branch, can you please have take a quick look at that branch Kyle? It only has inpainting working. You'll need to click the gear icon and then Reset Web UI to reset the state of the UI, then refresh the page.

In the current state, @SieR-VR , there are some major performance issues. The canvas appears to be constantly rerendering. And I'm a bit concerned that a number of issues I had already solved have been re-introduced, related to both performance and functionality. I added a lot of comments in InpaintingCanvas.tsx that explain the decisions. 

I'll hold off on more comments as I understand it's a WIP but just wanted to mention this.

**Comment by SieR-VR** [comment]
Closed incidantally while merge branch

**Comment by lstein** [comment]
@SieR-VR I want to give you the heads up that after some discussion about it, I've encouraged @psychedelicious to complete his initial inpainting implementation so that we have something cued up for a 2.1 release that I hope to get out soon. Both he and @Kyle0654 are enthusiastic about your implementation, but my guess is that it won't be ready for release for some time to come. We would aim to get your implementation into 2.2.

Please let me know your thoughts on this.

**Comment by SieR-VR** [comment]
I agree. Acceping Kyle's review requires many time, so I should have many time for implement it

**Comment by lstein** [comment]
Great. I'm happy you're OK with this. Let me know of any questions or concerns.

**Comment by SieR-VR** [comment]
Close due duplicate #1355

**Pull request closed without merging**
