### PR TITLE
Face Restoration Modules and Real ESRGAN Implementation Refactor

### PR DESCRIPTION
**Pull request by blessedcoolant**
Refactored the implementation of Face Restoration Modules and Real ESRGAN. Here's a quick rundown of the changes.

## Structure Changes

- `ldm.gfpgan` folder renamed to `ldm.restoration`
- `ldm/gfpgan/gfpgan_tools.py` fully removed. GFPGAN now runs through `ldm/restoration/gfpgan/gfpgan.py` and ESRGAN runs through `ldm/restoration/realesrgan/realesrgan.py`. This was done to organize the folder structure as we may add more restorers and upscalers in the future.

---

## Implementation

All Face Restoration Modules and ESRGAN are now new classes that control the functionality of the processes respectively. They are completely independent of `generate`.

You can now call GFPGAN, CodeFormerRestoration and ESRGAN classes with their respective arguments to initialize them. Then you can run either by performing the `process` method that takes the `image`, `strength` and `seed` (optional) as inputs.

---

## Dream Script Changes

- Two new switches added: `--restore` and `--esrgan` .. They will individually tell the user to enable Face Restoration Modules and ESRGAN respectively.
- If enabled, the dream script will check for the models and files. If there's an error, the app will exit outputting the errors.
- `--gfpgan_bg_upsampler` argument removed. It is obsolete.
- `--gfpgan_bg_tile` renamed to `--esrgan_bg_tile` because that is what it is used for.

To enable Face Restoration users need to pass `--restore`. They can additionally set the folder for GFPGAN using `--gfpgan_dir`.
To enable Upscaling users need to pass `--esrgan` only.

---

## Generate Changes

- `generate` now takes new arguments - `gfpgan`, 'codeformer` and `esrgan` - set to `None` by default.
- If they are not provided, Face Restoration and Upscaling will be disabled.
- They can be provided by initializing GFPGAN and ESRGAN using the new classes mentioned above. The initialization is done PRIOR to calling `generate`.

---

## Side Effect Fixes

- Fixed the Embiggen Script to work with the new changes.
- Fixed the web server.py to work with the new changes.

---

## Note

- Added placeholders for embiggen in the `server.py`  as they're not officially supported yet and the generation was broken without them. Found this while making the changes I needed to do for this PR.

---

## NOTE

Think it's good to go now.

### CODE REVIEW

**Comment by blessedcoolant** [comment]
@lstein Here you go. I tested this but I think I'd like you to test it too.

**Comment by lstein** [comment]
That was fast! I've got to knock off for the evening, but I'll test first thing tomorrow morning. I'm really happy to see the post processors getting normalized.

I'm particularly interested in seeing what you did with embiggen, because it takes so many image generation arguments. I have two thoughts about this:

1. Just use the arguments the user supplies at embiggen time.
2. Use the arguments the user supplies, but default missing arguments to ones used to generate the initial image. If the initial image wasn't generated by SD, then fallback to (1).

I'm probably using embiggen wrong, by the way. It tends to give me ghostlike miniature images scattered around where tiles were placed.

**Comment by blessedcoolant** [comment]
I actually didnt touch the Embiggen script beyond just replacing the inits for ESRGAN. Felt like any other changes to it were outside the scope of this PR.

No issues. Take your time. Let me know if you spot any bugs or if you need any functionality changes with this.

**Comment by lstein** [comment]
Just a heads up that @Kyle0654 is ready to merge in his dependency-injector rewrite. The basic architecture has changed, and I don't know how this will affect your post-processing PR.

**Comment by blessedcoolant** [comment]
> Just a heads up that @Kyle0654 is ready to merge in his dependency-injector rewrite. The basic architecture has changed, and I don't know how this will affect your post-processing PR.

I can make changes as needed once that is live. Which I will have to make. It's a massive code change.

**Review by lstein — CHANGES_REQUESTED** [review]
Why are face restoration and upscaling disabled by default? I would rather have the check for GFPGAN and ESRGAN occur automatically at startup time and a warning message issued if the libraries are not installed/configured.

I'd like to reverse the logic, if OK, and have the switches be --no_restore and --no_esrgan. Let me know if this is OK to do.

Otherwise it seems to be performing as advertised. What I'd like to do is to rebase this into my pre-processor PR and tweak the two sets of code to work together. Let me know if this is an OK strategy.

**Comment by blessedcoolant** [comment]
> Why are face restoration and upscaling disabled by default? I would rather have the check for GFPGAN and ESRGAN occur automatically at startup time and a warning message issued if the libraries are not installed/configured.

Honestly I don't know why I did it that way. The other way around is better.

> I'd like to reverse the logic, if OK, and have the switches be --no_restore and --no_esrgan. Let me know if this is OK to do.

Yes please. I'd appreciate that.

> Otherwise it seems to be performing as advertised. What I'd like to do is to rebase this into my pre-processor PR and tweak the two sets of code to work together. Let me know if this is an OK strategy.

Perfect. That should be good.

**Comment by lstein** [comment]
One minor thing. In the new directory structure, the gfpgan and esrgan modules are called ldm.restoration.gfpgan.gfpgan and ldm.restoration.esrgan.esrgan . Do you really need to put each of them in its own directory? The doubled names looks weird.

I'd also prefer for them to live under the ldm.dream namespace, so do you mind if I move them to ldm.dream.restoration?

**Comment by blessedcoolant** [comment]
> One minor thing. In the new directory structure, the gfpgan and esrgan modules are called ldm.restoration.gfpgan.gfpgan and ldm.restoration.esrgan.esrgan . Do you really need to put each of them in its own directory? The doubled names looks weird.
> 
> I'd also prefer for them to live under the ldm.dream namespace, so do you mind if I move them to ldm.dream.restoration?

I put them in their own directory so any future work done to them can go into the same directory rather than populating the main directory.

If you think they're better off in ldm.dream.restoration, feel free to go ahead and move them.

**Comment by mh-dm** [comment]
> I'd like to reverse the logic, if OK, and have the switches be --no_restore and --no_esrgan. Let me know if this is OK to do.

If it's okay to change the default from --x to --no_x then I think it would be even better to just remove the switch. On start check if the optional feature is not installed/model not downloaded then print `X Disabled` like we currently print `>> ESRGAN Disabled`. The other time the --x flag matters is if the feature is slow to load at startup, in which case move the load to when it's first used.

**Comment by mh-dm** [comment]
Not sure if this PR or the fixes that come after but now I'm getting:
```
scripts/dream.py
* Initializing, be patient...

Traceback (most recent call last):
  File "stable-diffusion/scripts/dream.py", line 453, in <module>
    main()
  File "stable-diffusion/scripts/dream.py", line 53, in main
    gfpgan, codeformer = restoration.load_face_restore_models()
  File "stable-diffusion/ldm/dream/restoration/base.py", line 9, in load_face_restore_models
    gfpgan = self.load_gfpgan()
  File "stable-diffusion/ldm/dream/restoration/base.py", line 23, in load_gfpgan
    return GFPGAN(self.gfpgan_dir, self.gfpgan_model_path)
  File "stable-diffusion/ldm/dream/restoration/gfpgan.py", line 20, in __init__
    raise Exception(
Exception: GFPGAN model not found at path ./src/gfpgan/experiments/pretrained_models/GFPGANv1.3.pth
```

**Pull request merged**
